### ISSUE TITLE
Log injection using winston and its metadata format doesn't associate logs with spans in APM

### ISSUE THREAD

**Issue by dls314** [DataDog/dd-trace-js#1018]
**Describe the bug**

When the winston plugin is used for automatic injection of trace IDs, and the winston format includes the metadata format, logs are written with a dd attribute in their metadata, but they are not associated with spans in APM.

**Environment**

* **Operation system:** AWS Lambda
* **Node version:** nodejs10.x
* **Tracer version:** as included by serverless-plugin-datadog 1.0.0 <-- 0.22.1 most likely?
* **Agent version:** I'm unsure

**Describe the bug more**

My winston configuration looks like this
```
const loggerOptions: winston.LoggerOptions = {
  format: winston.format.combine(
    winston.format.metadata(),
    winston.format.errors({ stack: true }),
    winston.format.timestamp(),
    winston.format.json()
  ),
  level: loggerEnvironment.logLevel,
  transports: [
    new winston.transports.Console({
      handleExceptions: true
    })
  ],
  exitOnError: false
};
```

I'm using the serverless plugin and log injection, and the logs do include the trace information in them as follows (with exclusions) from CloudWatch

```
{
    "level": "info",
    "message": "Handling CloudFormation custom resource event",
    "metadata": {
        "RequestType": "Create",
        "ServiceToken": "arn:aws:lambda:us-east-1:012345678912:function:ex-svc-motd-cfn-resource-providers-dev-provider:$LATEST",
        "ResponseURL": "https://cloudformation-custom-resource-response-useast1.s3.amazonaws.com/much-more-stuff-elided-from-here",
        "StackId": "arn:aws:cloudformation:us-east-1:012345678912:stack/example-certificate-combined/b395c580-c082-11ea-a0f7-0a029b5a039d",
        "RequestId": "1fec030a-9bb9-4b19-9a68-e4cd77aa4400",
        "LogicalResourceId": "IssuedCertificate",
        "ResourceType": "Custom::IssuedCertificate",
        "ResourceProperties": {
            "ServiceToken": "arn:aws:lambda:us-east-1:012345678912:function:ex-svc-motd-cfn-resource-providers-dev-provider:$LATEST",
            "CertificateArn": "arn:aws:acm:us-east-1:012345678912:certificate/7a0c2695-5492-4adc-b1eb-286306d81119"
        },
        "dd": {
            "trace_id": "5152745135117593972",
            "span_id": "3928950851547084294",
            "service": "ex-svc-motd-cfn-resource-providers",
            "version": "0.7.33",
            "env": "dev"
        }
    },
    "timestamp": "2020-07-07T18:56:14.879Z"
}
```

However, when I look at the related spans in APM, these logs are not related to the spans.

Is this expected? 
What is required to make the association in APM?

**Comment by rochdev** [comment]
It looks like the `winston.format.metadata` formatter moves all of the log fields to a new `metadata` field which is not supported by default. We could patch it to automatically move the `dd` field back to the root, but I'm not sure it would make sense since the very reason you are probably using this formatter is to avoid that. Alternatively, you would have to remap the field in your log pipeline.

What do you think would make the most sense for your use case?

**Comment by dls314** [comment]
I tried disabling `winston.format.metadata` and the logs are associated to the related spans in APM when I do that, but the resulting logs are much harder to use for all other purposes as the metadata is not collected.

You mentioned...

> Alternatively, you would have to remap the field in your log pipeline.

I haven't used Logs pipeline filters yet, but once I can figure out the details, would bringing the whole 'dd' property up to the root of the log be the remapping that you had in mind?

**Comment by rochdev** [comment]
> Ah, I see I can remap the defaults perhaps. Like this?

Yes, that should definitely work.

Since `metadata` is a built-in formatter, I wonder if it would make sense to offer an option to patch it. Not sure about doing that out of the box though since it would alter the format. Do you think it would cause any issue? What is the use case for this formatter, is it just to make log entried clearer?

**Comment by dls314** [comment]
It does work, and as a work around it's definitely acceptable. I don't mind closing this issue.

The use case for the formatter for me is making the logs easier to read (mostly for people) as the metadata is separated into its own property, leaving only the level, message, and timestamp at the top level.

It has a side effect of leaving the info and message sorted to the front of the JSON object, which really helps readability.

This is the log w/o the metadata formatter:

```
{
    "RequestType": "Create",
    "ServiceToken": "arn:aws:lambda:us-east-1:012345678901:function:ex-svc-motd-cfn-resource-providers-dev-provider:$LATEST",
    "ResponseURL": "https://cloudformation-custom-resource-response-useast1.s3.amazonaws.com/**ELIDED**",
    "StackId": "arn:aws:cloudformation:us-east-1:012345678901:stack/example-certificate-combined/bf467d30-c1e9-11ea-9e64-0e765a9edd1f",
    "RequestId": "33f76512-330d-41eb-a4e5-74d857a849a4",
    "LogicalResourceId": "CertificateDNSRecord",
    "ResourceType": "Custom::CertificateDNSRecord",
    "ResourceProperties": {
        "ServiceToken": "arn:aws:lambda:us-east-1:012345678901:function:ex-svc-motd-cfn-resource-providers-dev-provider:$LATEST",
        "DomainName": "debug-certificate-provider.api.e3devcloud.com",
        "CertificateArn": "arn:aws:acm:us-east-1:012345678901:certificate/ec7f485a-7bda-48dc-a6c1-94e595b4badc"
    },
    "level": "info",
    "message": "Handling CloudFormation custom resource event",
    "dd": {
        "trace_id": "5967260091974472744",
        "span_id": "6494908503802706205",
        "service": "ex-svc-motd-cfn-resource-providers",
        "version": "0.7.33",
        "env": "dev"
    },
    "timestamp": "2020-07-09T13:44:32.519Z"
}
```

This is the same log with the metadata formatter

```
{
    "level": "info",
    "message": "Handling CloudFormation custom resource event",
    "metadata": {
        "RequestType": "Create",
        "ServiceToken": "arn:aws:lambda:us-east-1:012345678901:function:ex-svc-motd-cfn-resource-providers-dev-provider:$LATEST",
        "ResponseURL": "https://cloudformation-custom-resource-response-useast1.s3.amazonaws.com/**ELIDED**",
        "StackId": "arn:aws:cloudformation:us-east-1:012345678901:stack/example-certificate-combined/82705ac0-c1ee-11ea-98ca-0ab389d40b93",
        "RequestId": "90b4233c-9de8-4e82-bb07-0b5976be6187",
        "LogicalResourceId": "CertificateDNSRecord",
        "ResourceType": "Custom::CertificateDNSRecord",
        "ResourceProperties": {
            "ServiceToken": "arn:aws:lambda:us-east-1:012345678901:function:ex-svc-motd-cfn-resource-providers-dev-provider:$LATEST",
            "DomainName": "debug-certificate-provider.api.e3devcloud.com",
            "CertificateArn": "arn:aws:acm:us-east-1:012345678901:certificate/770df4fa-4ea5-4212-a210-c12f7e6e9637"
        },
        "dd": {
            "trace_id": "7407183195691138093",
            "span_id": "163252506852684960",
            "service": "ex-svc-motd-cfn-resource-providers",
            "version": "0.7.33",
            "env": "dev"
        }
    },
    "timestamp": "2020-07-09T14:15:06.119Z"
}
```

**Comment by dls314** [comment]
Since the work-around in Log pipelines configuration worked great, I'll close this issue.
