### ISSUE TITLE
[bug] Aborted postgres transactions held open

### ISSUE THREAD

**Issue by kuritz** [DataDog/dd-trace-js#1034]
**Describe the bug**
When the tracer is enabled, and we have a statement fail in a postgres transaction created by sequelize, it is not rolled back as expected. Instead at that point we see no further code execution by node except by the tracer itself. On our DB we can see the transaction is being held open and the connection blocked with a `idle in transaction (aborted)` state, indefinitely. We are using `sequelize@3.35.1` and `pg@6.4.2` and use `node:10.20.1-stretch` as the base image for our docker build. 

In addition to removing the tracer altogether, explicitly disabling the `pg` plugin by setting:
```
tracer.init({
  enabled: true
});
tracer.use('pg', {
  enabled: false
});
```
also corrects the observed behavior of sequelize being unable to rollback aborted transactions. We turned on debug logging for the tracer and do not see any errors or anything else suspicious. The tracer goes on recording other activity that happens at regular intervals. The tracer logs the following only:
- Added encoded trace to buffer
- Request to the agent
- Response from the agent
- Inject into carrier
- Encoding trace

**Environment**
```
const tracerEnabled = config.get('distributedTracing.enabled');
tracer.init({
  enabled: tracerEnabled,
  logInjection: true,
  analytics: true,
});

tracer.use('graphql', {
  enabled: tracerEnabled,
  analytics: true,
});

tracer.use('pg', {
  enabled: tracerEnabled,
  analytics: true,
});
```

* **Operation system:**
Debian Stretch (docker)
* **Node version:**
10.20.1
* **Tracer version:**
0.23.2
* **Agent version:**
latest (docker)

**Comment by devsnek** [comment]
@kuritz would you be able to provide a simple reproduction script?

**Comment by kuritz** [comment]
hey @devsnek, thanks for the quick reply. i'll see if we can reproduce in a simple example we can share.

**Comment by kuritz** [comment]
I was able to reproduce here: https://github.com/farmersdog/dd-trace-test

Thanks again @devsnek !
