### ISSUE TITLE
Module '"net"' has no exported member 'LookupFunction'

### ISSUE THREAD

**Issue by kingjerod** [DataDog/dd-trace-js#1040]
**Describe the bug**
If I try to do this:
`import tracer from "dd-trace";`

and compile with Typescript, I get this error:
`Module '"net"' has no exported member 'LookupFunction'`

it's coming from 
`node_modules/dd-trace/index.d.ts:2:10`

If I just use `require("dd-trace")` then it's fine.

* **Environment**
Docker image node:10.14.1

* **Operation system:**
Whatever OS the official Docker image uses

* **Node version:**
10.14.1

* **Tracer version:**
0.23.2

* **Agent version:**
Don't need the agent, just compile with TS

**Comment by rochdev** [comment]
Can you share a reproduction snippet? This works for me locally and is also tested in the build. I wonder if it could be a specific configuration triggering this?

**Comment by kingjerod** [comment]
Hmm tried making a new Docker env with what I have and it's working fine. Must be something specific to the combination of node modules. Even tried installing the same @node/types. It doesn't just happen on my local box but also on our CI build server. Not a blocker but strange.
