### ISSUE TITLE
GraphQL Plugin: Option to Ignore GraphQL Playground Introspection Requests

### ISSUE THREAD

**Issue by jon-whit** [DataDog/dd-trace-js#1046]
Using the `dd-trace` GraphQL plugin to auto-instrument a GraphQL API is really nice. A lot of GraphQL implementations make use of the [GraphQL Playground](https://github.com/prisma-labs/graphql-playground) to provide a UI to interact with and document the GraphQL API. The GraphQL Playground periodically issues Introspection requests to fetch the GraphQL schema so that it can show it in the UI docs.

I've noticed, due to the high volume of traces generated for the introspection query, that it is really hard to filter and inspect traces that are not introspection requests. It'd be nice if there was an option to ignore introspection requests.

**Comment by rochdev** [comment]
While there is no explicit configuration option right now, span hooks were recently added which should allow you to filter these out. For example:

```js
tracer.use('graphql', {
  hooks: {
    execute: (span, args, res) => {
      const isIntrospection = true // the information to actually detect should be on "args"

      if (isIntrospection) {
        span.setTag('manual.keep')
      }
    }
  }
})
```

**Comment by jon-whit** [comment]
@rochdev cool. Just to clarify, should that be `span.setTag('manual.keep')`?  I want to discard introspection traces. Wouldn't it be something more like `'manual.discard'`?

**Comment by rochdev** [comment]
My bad, you can replace that to `manual.drop`. I'll edit the snippet.
