### ISSUE TITLE
grpc client request is missing

### ISSUE THREAD

**Issue by kyoungduck** [DataDog/dd-trace-js#1063]
**Describe the bug**

When I use grpc client which is created by [https://www.npmjs.com/package/grpc-tools](https://www.npmjs.com/package/grpc-tools), I can't see grpc client request in datadog trace.
Buf if I use the client which use [https://www.npmjs.com/package/@grpc/proto-loader](https://www.npmjs.com/package/@grpc/proto-loader), I can see the grpc request.

Is there any option to catch the grpc request which send by the generated js file?

I use dd-tracer like this.
```
import { UserSvcClient } from "./common/auth/rpc/v1/user_grpc_pb";
import { credentials } from "grpc";
import express from "express";
import trace from "dd-trace";
import { UserReq } from "./common/auth/rpc/v1/user_pb";

trace
  .init({
    hostname: "localhost",
    port: 8126,
    service: "realty-test-server",
    env: "dev-kr",
  })
  .use("http")
  .use("http2")
  .use("express")
  .use("connect")
  .use("dns")
  .use("fs")
  .use("promise")
  .use("promise-js")
  .use("net")

  .use("grpc");

const app = express();
app.get("/", (req, res, next) => {
  const userClient = new UserSvcClient(
    "host",
    credentials.createInsecure(),
    {
      "grpc.keepalive_time_ms": 10000,
      "grpc.keepalive_timeout_ms": 5000,
      "grpc.keepalive_permit_without_calls": 1,
      "grpc.http2.max_pings_without_data": 0,
      "grpc.http2.min_time_between_pings_ms": 10000,
      "grpc.http2.min_ping_interval_without_data_ms": 5000,
    }
  );

  const userReq = new UserReq();
  userReq.setAuthToken("aafsdfasdf2445dsfvbh5k645");

  userClient.getUser(userReq, (err, user) => {
    console.log(user.toObject());

    res.json(user.toObject().user as any);
  });
});

app.listen(3000, () => {
  console.log("server is running");
});
```

**Environment**

* **Operation system: OSX, linux**
* **Node version: 12.13**
* **Tracer version: 0.24.0**
* **Agent version: 7.21.1**

**Comment by rochdev** [comment]
In your snippet, I see that there are several modules that are imported before the tracer is initialized. This can cause all sorts of issues, especially with integrations. Can you try to initialize the tracer before any other module is imported as described [here](https://docs.datadoghq.com/tracing/setup/nodejs/#typescript)?

**Comment by kyoungduck** [comment]
@rochdev THANKS!!!! I solve this problem
