### ISSUE TITLE
dd-trace is consuming ~30+Mb of heap space - Is there a way to mock this in tests

### ISSUE THREAD

**Issue by ckshobha** [DataDog/dd-trace-js#1069]
dd-trace is consuming 30Mb of heap space for each test that invoke the dd-tracer.
All my tests that test a function which is involving another API using request-promise  basically uses nock to mock out the request-promise. But before that tracer is used to track the stats.
Here is the snippet of code that I use before request-promise 

```
async function callDownstreamEndpoint({tags, tracer, opts}){
   ....
   const resp = await sendRequest( {tags, tracer, opts});
   ....
}

async function sendRequest({tags, tracer, opts}){
  .....
  const response = await tracer.trace(metricName, async (span) => {
      span.addTags({ tags: tags);
      return rp(opts);    // This call is mocked.
  });
  ....
};
```

Test.js
Two flavor of test
1. Mock the request promise using jest mockImplementation
Say I want to test callDownstreamEndpoint() this is what I do in test
const ddTracer = require('dd-trace');
jest.mock('request-promise');
tracer = ddTracer.init({ enabled: false });

test('test endpoint 1', async() => {
rp.mockImplementation(() => ({ statusCode: 200, body: { xyz:  'test' } }));
const resp = callDownstreamEndpoint({tags, tracer, opts}})
});

2. Mock the outgoing request with nock
```
const ddTracer = require('dd-trace');
tracer = ddTracer.init({ enabled: false });

test('test endpoint 1', async() => {
  app.set('tracer', tracer); // Where tracr is set and App reads it.
  .....
  nock('zyx.com').post(
      `/user`
    );
  request(app)
        .post(`/endpoint1`)
        .send(body)
        .expect(200));
....
});
```

Any tests that use tracer is basically consuming like ~30+MB of heap per test. When I run like 14 such test case heap memory eventually explodes with error pasted below.  
Just to isolate the issue that  this is indeed because of dd-trace, tested by removing the dd-trace and the heap consumption is normal.  
 **Is there any known issue on dd-trace for initializing this for dd-trace? ** . Any help appreciated. 
Also is there a way to mock the tracer in test?

Error seen:
```
<--- Last few GCs --->

[33606:0x102848000]   108092 ms: Mark-sweep 1351.9 (1447.1) -> 1331.4 (1442.0) MB, 904.8 / 1.2 ms  (average mu = 0.263, current mu = 0.259) allocation failure scavenge might not succeed
[33606:0x102848000]   109187 ms: Mark-sweep 1343.6 (1442.5) -> 1336.8 (1446.0) MB, 875.3 / 0.5 ms  (average mu = 0.239, current mu = 0.201) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3d53c055be3d]
    1: StubFrame [pc: 0x3d53c05582b0]
Security context: 0x34bb1071e6e9 <JSObject>
    2: allocUnsafe [0x34bbcd6da339] [buffer.js:~290] [pc=0x3d53c1416cf5](this=0x34bb2bb823e1 <JSFunction Buffer (sfi = 0x34bbcd6d08f1)>,size=3)
    3: getStrPrefixes(aka getStrPrefixes) [0x34bb416f3b51] [/node_modules/dd-trace/packages/dd-trace/src/encode/tokens.js:~5] [pc=0x3d53c17a6c15]...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003d051 node::Abort() [~/.nvm/versions/node/v10.19.0/bin/node]
 2: 0x10003d25b node::OnFatalError(char const*, char const*) [~/.nvm/versions/node/v10.19.0/bin/node]
 3: 0x1001b90e5 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [~/.nvm/versions/node/v10.19.0/bin/node]
 4: 0x100587042 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [~/.nvm/versions/node/v10.19.0/bin/node]
 5: 0x100589b15 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [~/.nvm/versions/node/v10.19.0/bin/node]
 6: 0x1005859bf v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [~/.nvm/versions/node/v10.19.0/bin/node]
 7: 0x100583b94 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [~/.nvm/versions/node/v10.19.0/bin/node]
 8: 0x10059042c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [~/.nvm/versions/node/v10.19.0/bin/node]
 9: 0x1005904af v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [~/.nvm/versions/node/v10.19.0/bin/node]
10: 0x10055fdf4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [~/.nvm/versions/node/v10.19.0/bin/node]
11: 0x1007e80d4 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [~/.nvm/versions/node/v10.19.0/bin/node]
12: 0x3d53c055be3d 
```

Environment
jest: 26.4.2
express: 4.17.1
nock: 12.0.2
dd-trace: 0.25.1

Operation system:
Mac: 10.15.6 
Also seen on AWS running Linux

Node version:
10.19.0

Tracer version:
0.25.1

Agent version: 
v7.21.1

**Comment by rochdev** [comment]
The tracer is designed to be initialized only once per process and stay initialized for the lifetime of the process. This may not be the case when using a test runner since they usually alter the behaviour of Node's module system (this is especially true with Jest). I would recommend not using the tracer and Jest at the same time, and disable the tracer using the `DD_TRACE_ENABLED=false` environment variable.

**Comment by stephendj** [comment]
using `jest.mock('dd-trace');` seems to be working for me, and yea as @rochdev i used both mocking and I also set `DD_TRACE_ENABLED=false` for tests

**Comment by rochdev** [comment]
Closing since the tracer should always be [mocked](https://jestjs.io/docs/en/manual-mocks) in tests, or at least disabled. Please reopen if this doesn't work for your use case.
