### ISSUE TITLE
Mongo/DocDB Insert, update and admin commands not recorded with useUnifiedTopology: true 

### ISSUE THREAD

**Issue by jprosevear** [DataDog/dd-trace-js#1078]
**Describe the bug**
Connect to DocumentDB with useUnifiedTopology: true , traces will show *-mongodb spans but only for find operations.  insert, update, admin ops all appear to be missing.    useUnifiedTopology: false shows the spans.

**Environment**
AWS/EC2

* **Operation system:**
$ uname -a
Linux ip-172-30-0-45.us-west-2.compute.internal 4.14.173-137.229.amzn2.x86_64 #1 SMP Wed Apr 1 18:06:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* **Node version:**
v14.2.0

* **Tracer version:**
0.24.0

* **Agent version:**
Agent 6.21.1

**Comment by jprosevear** [comment]
I saw number #1048 but this is different in that some queries show up, others do not.

**Comment by nagypeterjob** [comment]
Same thing for us since we set `useUnifiedTopology: true`. `findAndModify` and `insert` queries are not traced.

**Tracer version:** 0.26.1
**Agent version:** 7.19.2
**Cluster Agent version:** 1.5.2

**Comment by rochdev** [comment]
I'm currently working on this and it will be fixed in next release. Basically most of the code skips the `Server` class that we're instrumenting when using unified topology.

**Comment by jprosevear** [comment]
Confirmed working.
