### ISSUE TITLE
Unable to get access to Plugin

### ISSUE THREAD

**Issue by DavitSo** [DataDog/dd-trace-js#1090]
I'm trying to use Tracer::use function in following way
myFunciton(package: string) {
  tracer.use(package);
}

Its typescript code.
As a result I got following error
 Argument of type 'string' is not assignable to parameter of type '"q" | "amqp10" | "amqplib" | "aws-sdk" | "bluebird" | "bunyan" | "cassandra-driver" | "connect" | "couchbase" | "dns" | "elasticsearch" | "expres
s" | "fastify" | "fs" | "generic-pool" | ... 27 more ... | "winston"'.

So what you will recommend to get rid of this error?
Thanks.

**Comment by rochdev** [comment]
Can you clarify which plugin you are trying to configure? All plugins are enabled by default, so `tracer.use('express')` would have no effect for example. You only need to use it when disabling plugins or to configure them, for example `tracer.use('express', { service: 'some-name' })`.

**Comment by DavitSo** [comment]
Thanks for response. I wana use it as you mentioned but with general function
like
use(name: string, enable: boolean) : void {
  tracer.use(name, {enabled: enable});
}

**Comment by DavitSo** [comment]
But I got error as I mentioned.
What would you suggest? 
Thanks

**Comment by rochdev** [comment]
Ah sorry I think I misunderstood what you are trying to do. If the problem is just the typing mismatch, then you would have to set the actual list of values you will be using, which should be a subset of what is supported by the tracer.

For example, if you will only be using `express` and `mysql` you would do something like this:

```ts
use(name: "express" | "mysql", enable: boolean) : void {
  tracer.use(name, {enabled: enable});
}
```

**Comment by DavitSo** [comment]
ok, thanks i will do some workaround 
Will be nice to export/import
  type '"q" | "amqp10" | "amqplib" | "aws-sdk" | "bluebird" | "bunyan" | "cassandra-driver" | "connect" | "couchbase" | "dns" | "elasticsearch" | "expres
s" | "fastify" | "fs" | "generic-pool" | ... 27 more ... | "winston"'
