### ISSUE TITLE
Fails with node 12.18.2+

### ISSUE THREAD

**Issue by sasha-nechaiev** [DataDog/dd-trace-js#1103]
**Describe the bug**
Fails when running with node v12.18.2+
```
SyntaxError: Error parsing /app/node_modules/dd-trace/package.json: Unexpected token , in JSON at position 5129
```

works fine with v12.18.2

* **Code:**
```
import tracer from 'dd-trace'
tracer.init()
```

**Environment**
Mac, tried on ubuntu, same behaviour
* **Operation system:**
MacOS
* **Node version:**
12.18.4
* **Tracer version:**
0.26.1
* **Agent version:**
-

**Comment by rochdev** [comment]
Can you share the content of the file?

**Comment by sasha-nechaiev** [comment]
@rochdev updated the description with code. Looks quite simple. Don't you have this issue?

**Comment by rochdev** [comment]
I do not, and it seems like your `package.json` got corrupted somehow (maybe by some kind of build system?). That's why I would like to see its content.

**Comment by sasha-nechaiev** [comment]
> I do not, and it seems like your `package.json` got corrupted somehow (maybe by some kind of build system?). That's why I would like to see its content.

thanks @rochdev. I tested separately with minimum packages, and it works. My bad
