### ISSUE TITLE
Graphql plugin do not track apm data

### ISSUE THREAD

**Issue by dusan-dragon** [DataDog/dd-trace-js#1106]
**Describe the bug**
When you have multiple plugins enabled and also graphql plugin and you override service name and set it to same name in all plugins, then `graphql.execute` apm tracking stops working...

```
tracer.init({
analytics: true,
service: process.env.DD_SERVICE_NAME,
runtimeMetrics: true,
})

tracer.use('graphql', {
analytics: true,
service: process.env.DD_SERVICE_NAME,
})

tracer.use('http', {
analytics: true,
service: process.env.DD_SERVICE_NAME,
})

tracer.use('net', { enabled: false })
tracer.use('fs', { enabled: false })
tracer.use('dns', { enabled: false })
```
Where trace is export from dd-trace npm package.

You can find reproducible example here: https://github.com/dusan-dragon/dd-test
Note I also reported this via ticket system, so far proposed solution is:
```
const { MEASURED } = require('dd-trace/ext/tags')

tracer.use('graphql', {
  hooks: {
    execute: (span) => {
      span.setTag(MEASURED, true)
    }
  }
})
```

It is not clear to me why it is solution and why it is not required if we do no specify `service` in the plugin initialisation.

**Environment**
I tested this locally on mac os, but this behaviour is same in aws linux amis

* **Operation system: Linux**
* **Node version: 12**
* **Tracer version: 0.26.0**
* **Agent version: 7.22**

**Comment by rochdev** [comment]
Stats are aggregated by service/resource/env, but only for the root span of a service by default. This means that if you rename the service name for the `graphql` plugin to the same name as the root service, they end up being considered the same service, of which `graphql.execute` is not the root. At that point, the agent will stop generating stats for these spans and their corresponding resources, which by extension will stop appearing in the UI. Using the `MEASURED` tag allows you to re-enable stats for any arbitrary span for which you want them without having to rely on the additional service.

**Comment by dusan-dragon** [comment]
The weird part is that if you take a look at screenshots in the repository I provided is that even if I set the name to match of root service I still get 1 entry recorded there. So looks like it is sending some data to DD but not showing them in UI.

Also this is not mentioned in official documentation. I think it would be beneficial to mention it there.

**Comment by rochdev** [comment]
> The weird part is that if you take a look at screenshots in the repository I provided is that even if I set the name to match of root service I still get 1 entry recorded there

Can you clarify what is not working in the screenshot? It looks like the resources are appearing as expected.

> Also this is not mentioned in official documentation. I think it would be beneficial to mention it there.

The main reason it's not documented is that the changes we are making to the service name are still in flux, so for now we generally recommend to not change the service names on the plugins, at least not without contacting us.

**Comment by dusan-dragon** [comment]
> Can you clarify what is not working in the screenshot? It looks like the resources are appearing as expected.

Take a look in Non working example screenshot in Endpoint section. Why is there 1 entry? Based on your explanation of the problem there should be 0 entries right? Because gql is non root span so it should not be counted in resources

> The main reason it's not documented is that the changes we are making to the service name are still in flux, so for now we generally recommend to not change the service names on the plugins, at least not without contacting us.

I found exactly 0 (zero) recommendations of not changing it in your documentation (website or github)

**Comment by rochdev** [comment]
> Take a look in Non working example screenshot in Endpoint section. Why is there 1 entry? Based on your explanation of the problem there should be 0 entries right? Because gql is non root span so it should not be counted in resources

That query is an introspection query, which happens outside of requests, so it ends up being its own root since Express is never involved.

> I found exactly 0 (zero) recommendations of not changing it in your documentation (website or github)

What I meant is that there are many options on the tracer, and their behaviour must be well understood before configuring them since it can have an impact on the functionality of APM, or in case of the service name, of Datadog as a whole.

I will close this since it sounds like you were able to resolve your original issue by setting the `MEASURED` tag in a span hook. I do understand your confusion however and we are actively working on improving how we determine which stats to generate by default and the default service naming. If you would like to provide feedback and get more assistance for APM, I would recommend reaching out to [support](https://www.datadoghq.com/support/).

**Comment by dusan-dragon** [comment]
Hi I just tested the proposed solution and it does not work 😞
