### ISSUE TITLE
dd-trace prevents the process from exiting

### ISSUE THREAD

**Issue by vecerek** [DataDog/dd-trace-js#1114]
**Describe the bug**

`dd-trace` prevents the process from exiting. Opening this issue as per https://github.com/DataDog/dd-trace-js/issues/708#issuecomment-706351579.

Run the following code:
```js
const tracer = require("dd-trace").init({
  debug: true,
  service: "my-service",
});

process.exitCode = 0;
```

The process is expected to exit with an exit code of `0`. Instead, the process does not exit at all.

**Environment**

* **Operation system:** Mac OS X, Alpine Linux
* **Node version:** v12.16.2, v14.11.0 (possibly other versions as well)
* **Tracer version:** 0.26.0+ (possibly previous versions as well)
* **Agent version:** v6, v7, also when there's no agent running at all

**Comment by rochdev** [comment]
We've rewritten the encoder in 0.27.0 and that seems to have solved the issue which I can no longer replicate. Can you try with 0.27.0?

**Comment by vecerek** [comment]
I cannot reproduce the issue with 0.27.0, either. Thank you, Roch 🙂
