### ISSUE TITLE
UnhandledPromiseRejectionWarning in datadog-plugin-fs

### ISSUE THREAD

**Issue by jwallet** [DataDog/dd-trace-js#1115]
**Describe the bug**
We keep getting errors from datadog-plugin-fs on our datadog dashboard `[DEP0018] DeprecationWarning`, looks like you have set many promises without handling the reject/catch.

Datadog referred to this line  https://github.com/DataDog/dd-trace-js/blob/40e5617bb948bc0e14c71a4f57290242b0291a7b/packages/datadog-plugin-fs/src/index.js#L376

> [DEP0018] DeprecationWarning
> UnhandledPromiseRejectionWarning: TypeError: Cannot convert a Symbol value to a string
> UnhandledPromiseRejectionWarning: Unhandled promise rejection.

looks like this pull request #986 fixed the cause of errors about Symbol that cannot be converted to string in `0.22`

**Environment**
* **Operation system:**
* **Node version:**
14
* **Tracer version:**
0.16
* **Agent version:**

**Comment by rochdev** [comment]
Can you confirm if the issue is still present in the latest version? It sounds from the description of the issue that it was actually fixed a few versions ago?

**Comment by jwallet** [comment]
yes it's fixed.
