### ISSUE TITLE
Is it possible to get end to end traces for aws serverless lambda, for all possible triggers otherthan AWS Gateway?  

### ISSUE THREAD

**Issue by bala1074** [DataDog/dd-trace-js#1129]
Is it possible to get end to end traces for aws serverless lambda, for all possible triggers otherthan AWS Gateway?  

I tested with aws x-ray, it is supporting traces for AWS Gateway and Lambda correlation.

But I was stuck at other possible lambda triggers. 

Does datadog agent supports CloudwatchEvents, Log Subscriptions, DynamoDb Streams, S3 file triggers ..etc., triggers to lambda.

I need to derive correlation for all possible lambda triggers.
trigger(API Gateway or Streams or Events..) --------------> Lmabda ---------------> DynamoDB

**Comment by rochdev** [comment]
I would recommend asking in https://github.com/DataDog/datadog-lambda-js since that's the library handling correlation within Lambda.

**Comment by bala1074** [comment]
Sure @rochdev https://github.com/DataDog/datadog-lambda-js/issues/119
