### ISSUE TITLE
No longer sending Heap spans, or Async Resources

### ISSUE THREAD

**Issue by BannerBomb** [DataDog/dd-trace-js#1136]
**Describe the bug**
After I updated this module to 0.27.0 the datadog Node Runtime Metrics is no longer receiving Async Resources or Heap spans.
![image](https://user-images.githubusercontent.com/11788894/97066404-34764f80-1583-11eb-9e3a-1feb49cde723.png). The exact moment they were stopped being logged matches with the same time that the module was updated and I restarted my application. We run datadog and the node application in docker and the way I initialize the tracer is
```js
require('dd-trace').init({
	hostname: 'datadog',
	runtimeMetrics: true
});
```

the hostname is `datadog` which is the hostname I gave the datadog-agent container.
Reverting back to 0.26.1 seems to have fixed the issue. 
On 0.27.0 Looking at the console logs during initialization of the tracer, the `! DATADOG TRACER CONFIGURATION` message seems to get printed later on after the rest of the process is finished starting up.
But on 0.26.1 it is printed before anything else is started. I did make sure that when initializing the tracer that it was the very first thing to be run before any of my other code.

**Environment**

* **Operation system:** Debian GNU/Linux 9 (stretch) is the os that is running in the docker container for my application. The main os that is running all the containers is Ubuntu 18.04.3 LTS.
* **Node version:** v14.13.1
* **Tracer version:** v0.27.0 (Previous version before this issue was v0.26.1)
* **Agent version:** v7.23.0

**Comment by rochdev** [comment]
These metrics have been removed starting with 0.27.0. I have added more details about this breaking change in the [release notes](https://github.com/DataDog/dd-trace-js/releases/tag/v0.27.0).

Did you have a specific use case for these metrics? We could potentially bring them back behind a configuration option if they were useful to you, although I would recommend considering the performance implications of having these metrics turned on.

**Comment by BannerBomb** [comment]
Ah, I didn't see the breaking change notes. No I didn't have a specific use-case for it. It just seemed weird that it just stopped logging them in which I forgot to check the repos release notes. Sorry for wasting you time with this issue.
