### ISSUE TITLE
Question: How to get span tags?

### ISSUE THREAD

**Issue by gcavalcante8808** [DataDog/dd-trace-js#1144]
Hi Folks,

How do I get/list the tags from a span?

I want to verify if some specific tags were inserted on a span given a determined flux during unittests, but looking at https://datadoghq.dev/dd-trace-js/interfaces/span.html#tracer or using console.dir, I cannot find a method to retrieve it.

Thanks in advance.

**Comment by bengl** [comment]
Hello @gcavalcante8808!

This isn't part of the public API at the moment (partly because the structure that the tags are stored in is an implementation detail), so _this may change in the future at any time_, but you can access the tags via the `_tags` property of a span's context. For a given `span`, the tags are stored in the object at `span.context()._tags`.

**Comment by gcavalcante8808** [comment]
Hey Bryan,

Thanks for the quick response. I got it!

There is any plan for a ‘getTags’ method on span?

I'm willing to make a PR for it if needed.

Thanks again!

**Comment by rochdev** [comment]
For unit tests, can you mock the tracer instead? One of the reasons for not exposing the tags is that as @bengl mentioned how they are stored is an implementation detail, and it may not be possible in some cases to retrieve the original tag as-is. There was also the assumption that it shouldn't be needed to retrieve tags.

**Comment by gcavalcante8808** [comment]
A mock is a option for sure, but if a getTags method was available, there
is no need of a mock at all.

But a mock is better option than rely on a "private"/internal method for
sure.

**Comment by gcavalcante8808** [comment]
Hi Folks, In the end of the day, I just used an Spy + DI and it worked flawlessly for me without the need to change or worry about implementation details. Thanks for the tips!

**Comment by mmahalwy** [comment]
@gcavalcante8808 can you share what you did for spy?
