### ISSUE TITLE
No way to disable same-origin in-browser traces

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [DataDog/dd-trace-js#1151]
We bundle `dd-tracer` with a JS component we supply to our clients when integrating with their sites. Some of these clients do not wish to send traces for same-origin fetch requests, and would like us to restrict our telemetry to include only fetch requests to our own backend. 

It would be convenient to be able to simply pass a bool to the config to disable all same origin traces, and only send traces for domains in the `distributedTracingOriginWhitelist`

**Comment by rochdev** [comment]
Where is the tracer installed? It sounds like your use case is for the browser, or do they have this same requirement for Node services?

**Comment by 01100010011001010110010101110000** [comment]
Our use case is just in a browser

**Comment by rochdev** [comment]
Tracing for HTTP requests has actually moved from APM to RUM. The functionality is deprecated in the tracer and is now available in the [Browser SDK](https://github.com/DataDog/browser-sdk).

**Comment by 01100010011001010110010101110000** [comment]
> Tracing for browser HTTP requests has actually moved from APM to RUM. The functionality is deprecated in the tracer and is now available in the [Browser SDK](https://github.com/DataDog/browser-sdk).

Gotcha, thank you!
