### ISSUE TITLE
rxjs support

### ISSUE THREAD

**Issue by DavitSo** [DataDog/dd-trace-js#1171]
Hi All
I have question related supporting of tracing in rxjs.
Maybe there is some docs? Or plans to add plugin?
Thanks.

**Comment by rochdev** [comment]
Generally speaking, tracing is more useful for IO, for example incoming and outgoing requests from the service, and less for internals which is usually better served by profiling. Could you describe you use case for tracing RxJS?

**Comment by DavitSo** [comment]
Thanks for quick response , nothing special ))
I'm using Observable, and wander if there any examples(good practices)

**Comment by rochdev** [comment]
It's been a while since I used RxJS but I can try to provide an example. Can you share an example of some code that you are trying to trace?

**Comment by DavitSo** [comment]
const temp = new Observable(subscirber => { .....; return someObject});
temp.subscribe(someObject => {
   doSomething;
})

**Comment by DavitSo** [comment]
sorry for bad example. I want to do end to end tracing

**Comment by rochdev** [comment]
End to end tracing is already supported and happens automatically out of the box. Still not sure I understand the use case of the above example. Are you trying to trace some asynchronous operation that has an observer? And if yes, can the asynchronous operation itself be traced instead?

Basically, RxJS simply provides a way to define a flow of operations, similar to promises or events. We never trace these directly and always the underlying operation instead.

**Comment by DavitSo** [comment]
ok thanks
