### ISSUE TITLE
The options callback to tracer.wrap is called only once

### ISSUE THREAD

**Issue by ab-pm** [DataDog/dd-trace-js#1181]
While this functionality is not exactly documented in the text, the [`tracer.wrap` method](https://datadoghq.dev/dd-trace-js/interfaces/tracer.html#wrap) has the following overload:

    wrap<T>(name: string, options: (...args: any[]) => TraceOptions & SpanOptions, fn: T): T

This seems pretty useful, allowing the wrapper to create tags directly from the arguments of the wrapped function. At least that seems to be the expected behaviour, wouldn't it?

The problem is with the code
https://github.com/DataDog/dd-trace-js/blob/30ba0dc28ed46200df09183aeab4126008c2ea44/packages/dd-trace/src/tracer.js#L67-L73
where `options` is a closure over the parameter of the `wrap` function, and **re-assigns it**. So on the first call of the returned function, it works just fine, but on any following call the options object that the first call has created will be used, not creating new tags from new arguments.

I'm not quite certain what the purpose of the overload is. Should it just lazily initialise the options? Then why does it take arguments?

Please either fix the code to behave as per my expectation, or add documentation about the actual behaviour.

**Comment by rochdev** [comment]
@bengl was that the expected behaviour?
