### ISSUE TITLE
Vulnerable axios version

### ISSUE THREAD

**Issue by alvarocantador** [DataDog/dd-trace-js#1185]
**Describe the bug**

New vulnerability found in axios: https://www.npmjs.com/advisories/1594
As it is using the version 0.19.2 it can block pipelines with audit checks.
Would be good to update it to the version 0.21.1.

Thanks in advance!

**Environment**

* **Operation system:**
* **Node version:**
* **Tracer version:**
* **Agent version:**

**Comment by rochdev** [comment]
Fixed in #1184 and will be in next release.
