### ISSUE TITLE
Google cloud pubsub integration: instrument publish operations from CronJob

### ISSUE THREAD

**Issue by mnahkies** [DataDog/dd-trace-js#1204]
We often publish events to Google cloud pubsub topics from cron jobs. When we do this, there is no parent/root scope for visibility on APM (compared to publishing a message off the back of a REST request or receiving a message for example).

For the moment I've wrapped one of our publishers like so:
```
  return tracer.trace(
    'cronjob.publish_event',
    { resource: topic },
    async () => {
      // do publish to topic
    },
  )
```

Which seems to work, but I wonder if it would be better for a publish operation to automatically start a `pubsub.publish` span/scope, if there is no root scope active.

**Comment by rochdev** [comment]
Can you provide more details about how this would look like? I'm not sure I understand the suggestion since there are already `publish` spans for each message published.

**Comment by mnahkies** [comment]
It's quite possible that I'm doing something wrong, so I'll try to explain the use-case a bit more. Consider a script like this:

```
import tracer from 'dd-trace';
tracer.init();

import {
    PubSub,
} from '@google-cloud/pubsub';


const pubsub = new PubSub();

async function doWork() {
    pubsub.topic("my-topic").publish(Buffer.from(JSON.stringify({ now: Date.now() })))
}


setInterval(doWork, 10 * 1000)
```

As far as I've seen, this won't show up in the APM monitoring for that service as having done anything, because it's starting a chain of events that isn't in response to a web request or receiving a message, etc.
- Traces tab: "No matching traces found"

By wrapping the `doWork` function in a `tracer.trace('cronjob.publish_event', {resource: 'my-topic'}, () => doWork())` then I do see things in the APM:

- operation "cronjob.publish_event" becomes present, split out by resource with topic names
- traces tab includes traces

One thing that doesn't seem to be quite right is that when I look at an individual trace, it stops at the `pubsub.publish` span, and doesn't show all the receiving spans. Not sure if this is by design or if I've done something wrong in the `tracer.trace` call. If I look at a consumers trace, I can see all other consumers, and that root publish event span.

I'm wondering if it would be a sensible default to have the publish span become the root operation if it occurs when no parent/existing scope/span is active.

(apologies if I've used the wrong terminology for the individual pieces)

**Comment by rochdev** [comment]
This should work without the additional span, but it's possible the integration is not working properly because things are not imported in the right order. You can find how to prevent hoisting when using TypeScript to make sure the tracer is initialized first in our [setup docs](https://docs.datadoghq.com/tracing/setup_overview/setup/nodejs/?tab=containers#typescript-and-bundlers). Hopefully that is the issue at hand and it will resolve the issue completely.

**Comment by mnahkies** [comment]
I believe we have implemented the initialization correctly. Our initialization looks like this in the transpiled javascript code:

Application entry point:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.run = void 0;
require("./datadog");

/* application code starts */
const x = require('x')
...
```
datadog.js
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const dd_trace_1 = require("dd-trace");
dd_trace_1.default.init({ /* options * / });
exports.default = dd_trace_1.default;
```

**Comment by rochdev** [comment]
The above does indeed look correct, so it looks like it might be an issue with the auto-instrumentation. Is this something you can replicate easily by extracting the code for a single message from the CRON job?

**Comment by bengl** [comment]
@mnahkies It's been a year, so I'm going to go ahead and close this. Please feel free to comment or re-open if you're still facing this issue.
