### ISSUE TITLE
0.30.1 Did not send trace messages to the datadog agent

### ISSUE THREAD

**Issue by BenHewins** [DataDog/dd-trace-js#1209]
**Describe the bug**

We upgraded from `0.29.2` to `0.30.1`, and after doing so no longer received *any* traces from the client. This resulted in some metrics in Datadog having no data, nor did any of the APM views. Reverting to `0.29.2` resolved the issue.

In the agent logs, we saw some messages like this, which could be related:
```
2021-01-12 15:52:35 UTC | TRACE | WARN | (pkg/trace/info/stats.go:111 in LogStats) | [lang:nodejs lang_version:v12.20.1 interpreter:v8 tracer_version:0.30.1 endpoint_version:v0.4] -> spans_malformed(resource_empty:6). Enable debug logging for more details.
```

**Environment**

* **Operation system:**  node:12-slim
* **Node version:** node:12-slim
* **Tracer version:** 0.30.1
* **Agent version:** datadog/agent:7

**Comment by bengl** [comment]
Hello @BenHewins (and everyone else who thumbs-upped this issue)!

This issue is resolved in `0.30.2`. Please give that a try, and if that does not work, we can reopen this issue.
