### ISSUE TITLE
Support AWS SDK v3

### ISSUE THREAD

**Issue by jsumners** [DataDog/dd-trace-js#1221]
The AWS SDK v3 release went stable in December. It would be interesting to see support for it. Though, I'm not sure how easy such a feat would be. It's no longer a single package.

https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.0.0

https://aws.amazon.com/blogs/developer/modular-aws-sdk-for-javascript-is-now-generally-available/

**Comment by rochdev** [comment]
We're actively working on it! The main issue is distributed tracing which is not trivial with the new API, but otherwise things are looking good so far.

**Comment by jsumners** [comment]
Awesome! Glad to hear it is being worked on. I just learned about the general availability this morning. So I was doing a little due diligence on feasibility of usage.

**Comment by astorm** [comment]
@rochdev (or anyone really) Is there any update on instrumentation for V3 of the AWS javascript SDKs, or are you'all still in a "actively working on it" phase?  No worries either way, just trying to get a feel for whether on not we can expect this soon or if it's best to assume it won't be coming out and sticking to the V2 APIs.

**Comment by rochdev** [comment]
@astorm We've had a few setbacks that have slowed down the work on this, but it's still one of the next features we want to ship. Right now we're focusing on 1.0 which might change a little bit how the trace data is structured, but this is definitely a priority for APM as well as Serverless afterwards. The conservative answer would be this year, but we're aiming for Q3.

**Comment by bigkraig** [comment]
@rochdev any news on this?

**Comment by rochdev** [comment]
@bigkraig My credibility for a timeline is pretty much non-existant at this point in this thread, but I can at least say that we're actively working on it right now.

**Comment by ShukiPesso** [comment]
@rochdev any news on this?

**Comment by rochdev** [comment]
We've switched our focus to some other work that will impact aws-sdk v2 so we've put the aws-sdk v3 work on hold for the time being. We do plan to resume that work during this quarter.

**Comment by dforsl** [comment]
Hi, any news on how this one is coming along?

**Comment by wregis** [comment]
[On the docs](https://docs.datadoghq.com/tracing/trace_collection/compatibility/java/) there is this column "support type" wich is full or beta for most of cases. Would it be this hard to deliver a partial support to at least the most used clients (I'm not sure wich ones first, maybe s3, dynamodb, lambda, ec2, athena, kinesis, ses, sns, mq...)?

The lack of support is not holding me from using, but it would be great to have some analytics on this.

**Comment by Treparme** [comment]
I was wondering if there is an update on this? We are working on v3 and would love to see distributed tracing for our producer-consumer pattern (currently no tracing/correlation of the logs on the consuming part) 
Thank you!!

**Comment by tlhunter** [comment]
This task is one of our goals for the current Q4 and will hopefully be ready by the end of the year.

**Comment by blytheaw** [comment]
This is what we want for Christmas 2022. Thanks!

**Comment by automartin5000** [comment]
Maybe before the end of the Chinese New Year? 😅

**Comment by rochdev** [comment]
@automartin5000 Sorry for the delay, definitely my fault 😅 I got sick before the holidays and then I was out for the holidays so I ended up a bit behind on schedule, but as soon as I'm caught up with everything I missed for the past few weeks I'm resuming the work on this.

**Comment by matray** [comment]
Incredible 🥳

**Comment by smcroskey** [comment]
Awesome thank you @rochdev!!  Just curiously, what's the release cadence/process for this library, or when do we expect this to be included in a release?  Anxious to start leveraging this ASAP :)

**Comment by rochdev** [comment]
@smcroskey We don't really have a specific cadence, but we usually release every few days at most, so you can expect a release soon!

**Comment by automartin5000** [comment]
@rochdev Thanks again for getting this done 💪

**Comment by astuyve** [comment]
AWS SDK V3 support is now available in [3.14.0](https://github.com/DataDog/dd-trace-js/releases/tag/v3.14.0) and [2.27.0](https://github.com/DataDog/dd-trace-js/releases/tag/v2.27.0)

**Comment by blytheaw** [comment]
> AWS SDK V3 support is now available in [3.14.0](https://github.com/DataDog/dd-trace-js/releases/tag/v3.14.0) and [2.27.0](https://github.com/DataDog/dd-trace-js/releases/tag/v2.27.0)

@astuyve Where can we track when this is released in the Lambda layer?

**Comment by astuyve** [comment]
Hi @blytheaw - I merged it on [friday](https://github.com/DataDog/datadog-lambda-js/pull/353), it'll go out tomorrow.

Thanks!

**Comment by astuyve** [comment]
This is now released in [6.87.0 and Layer version 87](https://github.com/DataDog/datadog-lambda-js/releases/tag/v6.87.0)

**Comment by automartin5000** [comment]
@astuyve @rochdev I just deployed a version of our code with the new Lambda layer and our traces for AWS SDK calls are still showing `http.request` instead of `dynamodb.command` or whatever. I do note that we seem to not be seeing service to service traces either for our Node serverless functions, so I'm not sure if that's related. But I wanted to check if it's a misconfiguration, if that's expected, or if it's a bug. Thanks!

**Comment by jsumners** [comment]
> @astuyve @rochdev I just deployed a version of our code with the new Lambda layer and our traces for AWS SDK calls are still showing `http.request` instead of `dynamodb.command` or whatever. I do note that we seem to not be seeing service to service traces either for our Node serverless functions, so I'm not sure if that's related. But I wanted to check if it's a misconfiguration, if that's expected, or if it's a bug. Thanks!

Maybe open a new issue on the appropriate repo and leave this one for the original topic?

**Comment by automartin5000** [comment]
> > @astuyve @rochdev I just deployed a version of our code with the new Lambda layer and our traces for AWS SDK calls are still showing `http.request` instead of `dynamodb.command` or whatever. I do note that we seem to not be seeing service to service traces either for our Node serverless functions, so I'm not sure if that's related. But I wanted to check if it's a misconfiguration, if that's expected, or if it's a bug. Thanks!
> 
> Maybe open a new issue on the appropriate repo and leave this one for the original topic?

Well if the PR didn’t add support for AWS SDK v3, then I’d say it is relevant to this issue and maybe it should be reopened. Otherwise, if it’s something specific to me, then I’m happy to open a new issue. That’s what I’m trying to figure out.

**Comment by teyckmans** [comment]
@automartin5000 just had the same, doesn't work until you mark each individual aws sdk v3 client library you use as external before it works.

I'm on node18 where aws sdk v3 is part of the default layer. 

Might not be completely the same for you but at least that did the trick for me.

**Comment by automartin5000** [comment]
@teyckmans Success! That it did it, thanks! 

I'm still seeing `http.request`, `tcp.connect`, and `dns.lookup` nested below that though. Are you (or anyone else) seeing that as well? I guess my only concern with it is adding noise to traces and the service map (for example, making it harder to differentiate between an AWS service call and some other API request).

**Comment by teyckmans** [comment]
You can disable those by setting the DD_TRACE_DISABLED_PLUGINS environment variable to "http,http2,dns,net" 

The environment variable is mentioned here: https://docs.datadoghq.com/tracing/trace_collection/library_config/nodejs/ 

The plugin names map to 'datadog-plugin-xxx' packages in this repo (https://github.com/DataDog/dd-trace-js/tree/master/packages) 

not 100% about the net plugin might also be connect.

**Comment by blytheaw** [comment]
I would appreciate some further clarity here. Is the implication that this only works if you use the AWS SDK v3 that is included in the Node 18 Lambda runtime by default? We use Node 16 and AWS does not include the v3 SDK in their Node 16 runtime. Therefore, we have to bundle AWS SDK v3 clients with our functions. So is there no path for this tracing to work in this way for Node16?

**Comment by automartin5000** [comment]
> You can disable those by setting the DD_TRACE_DISABLED_PLUGINS environment variable to "http,http2,dns,net"
> 
If I completely disable the `http` plugin, we’d lose _all_ tracing of API calls 🙃

**Comment by teyckmans** [comment]
> If I completely disable the `http` plugin, we’d lose tracing of _all_ API calls 🙃

Well, if that is the case, then you will have to live with 1 level of 'noise' I guess.

**Comment by automartin5000** [comment]
@rochdev @astuyve So now that I have it working, I'm noticing that traces are showing `{$serviceName}-aws-{$awsServiceName}` instead of just `aws.${awsServiceName}` like our other non-JS clients. Is that by design?

**Comment by astuyve** [comment]
Hi - I replied to @automartin5000 in another thread, I did not have problems similar to above and included my [reproduction](https://github.com/DataDog/datadog-lambda-js/issues/364#issuecomment-1464193369) in the ticket.

The provided SDK is fine, and marking each client external should solve this use case.
