### ISSUE TITLE
Spans from unrelated requests fused together

### ISSUE THREAD

**Issue by tlhunter** [DataDog/dd-trace-js#1239]
**Describe the bug**

Our APM traces seem to be getting combined into the wrong requests. This issue started after I upgraded to version `dd-trace@0.30.6`, it doesn't seem like it was happening with `dd-trace@0.26.0`. This is with the `hapi@16.7.0` framework.

Here's the queries displayed in that request. The three queries that run 4 times are each executed once at the start of the request.
![image](https://user-images.githubusercontent.com/551402/107417394-64157d00-6aca-11eb-9ead-b3d6266be328.png)

Here's the timeline view which suggests something is amiss:
![image](https://user-images.githubusercontent.com/551402/107417626-a474fb00-6aca-11eb-9217-7140caddbdae.png)

**Environment**

* **Operation system:** Linux
* **Node version:** v12.14.1
* **Tracer version:** 0.30.6
* **Agent version:**

**Comment by rochdev** [comment]
We changed the default scope manager in 0.30.6, so it's likely that this is the issue. Can you try with 0.30.5, or otherwise if it's easier can you try with the `DD_TRACE_SCOPE=async_local_storage` environment variable?

Also, does this happen on any request or only on specific requests?

**Comment by tlhunter** [comment]
I'm going to deploy a version with 0.30.5 and will let you know. This does affect other routes as well.

**Comment by tlhunter** [comment]
@rochdev it is still happening quite a bit with this version. Here's a screenshot of one that seems to contain hundreds of requests if I keep scrolling down. Each one of these pink dots represents a new request:

![Screenshot_20210212_164459](https://user-images.githubusercontent.com/551402/107836373-c59b4d00-6d51-11eb-93c1-e40001f8f7b7.png)

**Comment by tlhunter** [comment]
Note that this service was just upgraded to Node.js v14.15.4 and is still exhibiting the same behavior.

**Comment by rochdev** [comment]
Can you provide a reproduction case? Otherwise, do you know the exact version when it started happening? There were quite a bit of changes between 0.26 and 0.36 so it's a bit difficult to narrow down what change may have caused this without a reproduction.

**Comment by rochdev** [comment]
@tlhunter Do you still have the issue with the latest version?

**Comment by tlhunter** [comment]
@rochdev just deployed our app with `dd-trace@0.32.0` and we're still getting the same issue:

![screenshot-20210428140111](https://user-images.githubusercontent.com/551402/116472242-7af68080-a82a-11eb-974b-25b1a37ce12d.png)

Could it be that some metadata that we're attaching is causing this issue? Values like these are present:

```
account_id | high cardinality hex string
admin | boolean
env | low cardinality string
mode | low cardinality string
request_id | 1619643462113:e82eab6e26ce:1:ko1v8wce:62338
version | low cardinality string
```

**Comment by rochdev** [comment]
> Could it be that some metadata that we're attaching is causing this issue?

It's unlikely if it was working before. Are you able to pinpoint exactly in which version the issue started? Otherwise are you able to provide a reproduction?

**Comment by tlhunter** [comment]
Sadly I don't have the bandwidth to do either. Also, I'll no longer have access to the project in about a week. I could send a private message with the output of `npm ls` in case a package is conflicting, like perhaps something introduces a known issue with `async_hooks`.

**Comment by tlhunter** [comment]
@rochdev sent you a DM via Slack Datadog Public

**Comment by Qard** [comment]
@rochdev @tlhunter has this been resolved? If so, we should close this.

**Comment by rochdev** [comment]
@Qard Sounds like this could be related to the issue we discussed offline this week about an unexpected span ending up as a parent of all request spans.

**Comment by Qard** [comment]
It reads more to me like one request leaking into another, not all requests rooted from a higher level span, unless I'm misreading something.

**Comment by tlhunter** [comment]
@Qard I am no longer with the company where I had encountered this issue.

Ironically, I suspect I'll soon go from reporting this issue to working on it, haha.

**Comment by Qard** [comment]
So I've heard. 🎉

**Comment by tlhunter** [comment]
No idea if this was resolved but it's certainly no longer affecting me.
