### ISSUE TITLE
Enable/disable tracer at runtime

### ISSUE THREAD

**Issue by jacque006** [DataDog/dd-trace-js#1258]
Is there a way to enable/disable the tracer at runtime? For example:

`tracer.js` (from example)
```javascript
import tracer from "dd-trace";

// initialized in a different file to avoid hoisting.
tracer.init({
	analytics: true,
	runtimeMetrics: true,
	logInjection: true,
});

export default tracer;
```

`someOtherFile.js`
```javascript
import tracer from "./tracer";

...

tracer.disable();
// or
tracer.enable();
```

If not are there any plans to support this in the future?

Our use case is we are trying to analyze a larger background async process but want to keep span analysis costs reasonable so we only want to turn on the tracer for a specific duration of time without restarting the NodeJS process.

**Comment by rochdev** [comment]
Right now this is not supported but we do plan to support dynamically configuring the tracer at runtime in the next few months.

@andrewardito Is there any other way to reduce costs for this use case without stopping tracing completely?

**Comment by andrewardito** [comment]
Hey @jacque006 ! Would love to understand more about your use case for only wanting traces for a specified period of time.  We've done a lot recently to allow fine-grained control over ingested and indexed volumes (documentation [here](https://docs.datadoghq.com/tracing/trace_retention_and_ingestion/)).  

Would you mind opening a support ticket so we can get some extra information from you and possibly arrange a call to discuss? Feel free to paste your ticket number here as well so I can track it.

**Comment by jacque006** [comment]
@andrewardito the link you posted for ingested and indexed volumes looks like it could work for what we need to do. I will give that a try first.

I'll be out the rest of this week, but happy to chat/open a ticket next week if you'd still like more info.

**Comment by andrewardito** [comment]
@jacque006 great to hear! I'll leave it up to you - if the current approach and linked doc doesn't allow you to customize as much as you'd want, please reach out and we'll set up a call to make sure we're considering your use case as we move forwards.

**Comment by jacque006** [comment]
@andrewardito I've set up some more fine grained indexing rules that I believe cover my use case here, so feel to close this issue unless you want to use it to track progress on the `dynamically configuring the tracer at runtime` feature you're working on.

I have some additional questions about setting up APM span exclusions, mainly around not tracing k8s http health checks on pods but will do that in a support thread. Thanks @andrewardito & @rochdev for the quick and detailed responses!

**Comment by rochdev** [comment]
Closing since while dynamic config will land soon, enabling/disabling features will not be included. More context about this decision can be found in #1800.

**Comment by btiernay** [comment]
@rochdev 👋 Do you mind giving some clarity as to why this rejected as a feature? I see a lot value in being able to disable at runtime for various reasons, including:
- Incidents: quickly fix impact on critical flows due to a bug in DD or otherwise too high overhead from implementation 
- Profiling: quickly A/B test to establish baseline performance.

**Comment by rochdev** [comment]
@btiernay Simply put, some of what we have to do in order for dd-trace to work is irreversible, so it cannot cleanly be disabled at runtime. The reverse is also true, where in order to enable it some things need to be patched or enabled when the application itself starts, and so we can't enable the library at runtime because at that point it's too late.
