### ISSUE TITLE
Upgrading from 0.19.0 to 0.31.0 degrades CPU performance significantly

### ISSUE THREAD

**Issue by Lovivan** [DataDog/dd-trace-js#1262]
**Describe the bug**
We are tracing multiple node js Kubernetes microservices at this point. We started tracing with library version 0.19.0 but recently we wanted to make use of more recent features including nodejs runtime metrics but therefore we have to upgrade our dd-trace npm package version. We have done some tests and upgraded to 0.31.0 but we saw significantly more CPU usage compared to the 0.19.0 we were using with runtime metrics still disabled.

In the following picture, you see the in the red line the CPU graph with the latest version compared to the green line representing the old library version.

![image](https://user-images.githubusercontent.com/31881480/110438836-1125ea00-80b7-11eb-9113-4a21c569eb31.png)

**Environment**

* **Operation system:** based on docker image node:12.10.0-alpine
* **Node version:** 12.10.0
* **Tracer version:** 0.31.0
* **Agent version:**

**Comment by rochdev** [comment]
There were changes made to our scope manager since then to try and work around limitations in `async_hooks` that prevented proper context propagation with async/await. However, we have also built a new scope manager entirely but it is used only in latter versions of Node. Can you try to update Node to latest 12? (12.21.0 as of this writing)

**Comment by Lovivan** [comment]
@rochdev i'll do some local testing tonight and see the difference. I'll build some new docker image based on the latest node version 12.21.0 and come back to you

**Comment by Lovivan** [comment]
@rochdev tried to reproduce it locally but the load is not representative enough to trigger the same effect as shown in my picture. I'll have to do these tests again in the same or similar environment which will take a bit more time

**Comment by rochdev** [comment]
@Lovivan Were you able to validate if updating Node resolves the issue?

**Comment by Lovivan** [comment]
@rochdev i am waiting for the right moment to claim our acceptance environment to do representative testing. We currently reverted to the old version. I hope that I will be able to test this next week and get back to you

**Comment by rochdev** [comment]
Since we've seen similar issues that were resolved by updating Node and `dd-trace`, I'm going to assume that you will get the same result and close the issue. Please feel free to re-open if that's not the case.
