### ISSUE TITLE
SNS to SQS distributed tracing

### ISSUE THREAD

**Issue by Czechh** [DataDog/dd-trace-js#1280]
The tracer currently supports distributed tracing for SQS, as we inject the Datadog info on `sendMessage` and also extract the trace info if present on `receiveMessage`. A regular pattern is to publish to SNS first to have a fan out to multiple SQS queues via topic subscriptions.

I wanted to reach out to before submitting a PR for injecting the trace into the `MessageAttributes` in SNS `publish`, so the the trace data can get all the way from the production of the SNS event, to the SQS consumers.

**Comment by bengl** [comment]
Hello @Czechh! Yes, a PR implementing this would be welcome, for sure.

**Comment by dls314** [comment]
Is there any chance that this got done and is part of https://github.com/DataDog/serverless-plugin-datadog/releases/tag/v3.7.0 ?

**Comment by rochdev** [comment]
@astuyve Was this included in #1776?

**Comment by astuyve** [comment]
Hi @rochdev, @dls314 - yes! This is already completed in #1776. It's a bit overcomplicated, but the short answer is yes, that functionality was released in v.3.7.0 of the serverless datadog plugin (for nodejs and python specifically).

**Comment by dls314** [comment]
I'm trying to track down an ultimate cause of https://github.com/DataDog/serverless-plugin-datadog/issues/232

**Comment by astuyve** [comment]
Yes, writing you a comment now.

**Comment by rochdev** [comment]
Closing this issue as the functionality has been released.

**Comment by dcfranca** [comment]
I see that it is supported on Python and NodeJS, is it supported in Go?

I have an application doing the same

I'm wrapping the SNS client in DD AWS Trace
```
	sess = awstrace.WrapSession(sess)

	ing.snsClient = sns.New(sess)
```

Then, passing the context:
```
	if _, err := ing.snsClient.PublishWithContext(ctx, &sns.PublishInput{
		MessageAttributes: attr,
		Message:           aws.String(string(bytes)),
		TopicArn:          aws.String(ing.SNSTopicArn),
	}); err != nil {
		ing.logger.Error("failed to send event,", err)
		return http.StatusInternalServerError, pkgerrors.Wrap(err, "failed to publish message")
	}
```

And then wrapping the SQS client, and receiving the context
```
	sess = awstrace.WrapSession(sess)
	sqsClient := sqs.New(sess)
```

```
			output, err := sqsClient.ReceiveMessageWithContext(ctx, &sqs.ReceiveMessageInput{
				QueueUrl:        aws.String(d.env.QueueURL),
				WaitTimeSeconds: aws.Int64(defaultWaitTimeSecs),
			})

```

However, the trace stops at publishing to SNS, doesn't follow the e2e process

Is it possible to implement it in Go?
