### ISSUE TITLE
Question: how to add tags based on request context?

### ISSUE THREAD

**Issue by dandean** [DataDog/dd-trace-js#1303]
Is there a way to, while using auto-instrumentation, add tags to the current request trace based on information found in the request context?

**Comment by rochdev** [comment]
You can use [span hooks](https://datadoghq.dev/dd-trace-js/#span-hooks) to add tags to the request span right before the request is finished.

For example:

```js
tracer.use('http', {
  hooks: {
    request: (span, req res) => {
      span.setTag('customer.id', req.query.id)
    }
  }
})
```

**Comment by dandean** [comment]
@rochdev – thank you!
