### ISSUE TITLE
DD trace does not inject with pino prettyPrint

### ISSUE THREAD

**Issue by edrich-xendit** [DataDog/dd-trace-js#1328]
Without prettyPrint activated, dd traces are injected correctly. When I activate prettyPrint, the dd traces are no longer showing up.

**Environment**

* **Logger:**
* pino
* **Operation system:**
* Mac OSX  
* **Node version:**
* v12.21
* **Tracer version:**
* v0.20.0
* **Agent version:**

**Comment by simon-id** [comment]
Thank you for the bug report, I am working on landing a fix for it.
May I know wich version of Pino/Fastify you're using ?

**Comment by rochdev** [comment]
@edrich-xendit Can you try with the latest version of the tracer as well? There have been a lot of changes since 0.20, including some to log injection.

**Comment by rochdev** [comment]
Never mind my above comment, it looks like we were able to reproduce.
