### ISSUE TITLE
gRPC client not instrumented if used without protobuf serialization

### ISSUE THREAD

**Issue by joshua-barnett** [DataDog/dd-trace-js#1376]
**Describe the bug**
If you do not use `protobuf` as your means of serialization and client setup, your client requests will not create spans.

This is due to the gRPC plugin [only patching `makeClientConstructor`](https://github.com/DataDog/dd-trace-js/blob/38327b4d91d499bad28a97393c0aef972dcfa5da/packages/datadog-plugin-grpc/src/client.js#L238) of gRPC's [`src/client.js` module](https://github.com/grpc/grpc-node/blob/grpc%401.24.x/packages/grpc-native-core/src/client.js#L979).

If you simply use the `Client` class exported by the `grpc` module to construct your client (e.g. `new grpc.Client(...args)`) you will find that this client isn't instrumented.

A workaround for now is to use the `grpc.makeGenericClientConstructor` method exposed by the `grpc` module (as it is simply an alias of `makeClientConstructor`).

```javascript
const Client = grpc.makeGenericClientConstructor(...serviceDefArgs);
const client = new Client(...clientArgs);
```

The above example results in a properly instrumented client.

**Environment**
- _Not applicable_

**Comment by rochdev** [comment]
It looks like this would require a rewrite of the integration since as you mentioned it currently relies on pre-existing method definitions. It's definitely something that will need to be done since the `Client` class is exposed publicly, but it might take a bit of time to get to it given the scope. In the meantime is there any downside to using `makeGenericClientConstructor`? Otherwise I'd definitely recommend to use that for now.

**Comment by rochdev** [comment]
Can you share an example of using the `Client` class directly? It seems to only support low-level calls with a custom serializer and deserializer, and I can't find any example usage for that.

**Comment by joshua-barnett** [comment]
By the way @rochdev, I also discovered that it also means calls made to any client instance's `makeUnaryRequest` method will also not be traced.

As only the methods defined upfront will be wrapped by the plugin.

**Comment by joshua-barnett** [comment]
@rochdev here's a rough example of a client and server using JSON as custom serialization.

https://gist.github.com/joshua-barnett/b944aed624fcfea231ba9f492841fb3d

This appears to be a supported use case of gRPC given this article in their documentation.

https://grpc.io/blog/grpc-with-json/

**Comment by rochdev** [comment]
So basically when instantiating a client manually you would only use `make*Request`? I assumed it had a way to register new methods similar to when using Protobuf, but if that's not the case then we could simply instrument these methods which should be straightforward.

**Comment by rochdev** [comment]
By the way, do you have a similar requirement on the server side of things or does the existing instrumentation also work for JSON there?

**Comment by joshua-barnett** [comment]
> So basically when instantiating a client manually you would only use `make*Request`? I assumed it had a way to register new methods similar to when using Protobuf, but if that's not the case then we could simply instrument these methods which should be straightforward.

With `makeUnaryRequest` you provide the `path` as a parameter so that's effectively how you use it without registering the method with the client beforehand.

> By the way, do you have a similar requirement on the server side of things or does the existing instrumentation also work for JSON there?

I've not had any issues with tracing on the server-side, I've been using the `Server` class directly, you have to specify the method names and paths on instantiation (which is probably why there's no issue there).

Thanks for looking into this its much appreciated.

As a stop gap I've just been providing the method name in the metadata of the request and a single `Exec` method which means the breakdowns in the Datadog UI isn't very good.
