### ISSUE TITLE
Log extra parameters in Sequelize add-on

### ISSUE THREAD

**Issue by gstamac** [DataDog/dd-trace-js#1383]
Currently only query text (and some connection params) is logged in Sequelize add-on. When we use bind to send parameters of a raw query directly to the DB we don't see the values of these parameters. So we get a query text with question marks instead of paramemeter values in the log. It would be nice to add those as a tag to the span. I can create a MR if that's ok.

**Comment by rochdev** [comment]
Would definitely be a welcome addition! It should be possible to configure which tags are allowed to make sure no security risk is introduced. Right now individual drivers are instrumented and not Sequelize, so this should be implemented per driver if possible, or if you think it would be better to have information specific to Sequelize, then a new integration would be needed but that's definitely more work. Let me know which approach you think is best and I can provide some guidance if needed.

**Comment by gstamac** [comment]
Yes, you're right. I was thinking about pg add-on. I'll prepare the PR as soon as I have some time.

**Comment by gstamac** [comment]
This is what I came up with https://github.com/DataDog/dd-trace-js/pull/1456

**Comment by tlhunter** [comment]
I'm going to close this out since the associated PR has a workaround attached. Feel free to reopen if I'm off!
