### ISSUE TITLE
Data corruption / injection

### ISSUE THREAD

**Issue by ColinSullivan1** [DataDog/dd-trace-js#1387]
**Describe the bug**

Hello from the [NATS.io](https://nats.io) team!  Hey, I wanted to give you a heads up - some of our users have been reporting issues related to data corruption when using your library - it looks like some dd trace related data is being injected into our protocol parsing.

See:  https://github.com/nats-io/nats.js/issues/429

(Edit)
See Also:  https://github.com/DataDog/dd-trace-js/issues/1311

CC @aricart

**Comment by aricart** [comment]
To be more accurate on partial TCP frames it looks like Buffers are being reused without truncating the length of them so additional data is found on a received frame that is unexpected by our protocol.

**Comment by rochdev** [comment]
@aricart You mention in https://github.com/nats-io/nats.js/issues/429 that removing **or upgrading** dd-trace fixes the issue. Is it isolated to older versions?

**Comment by aricart** [comment]
From Jonathans original issue looks like new libs are ok.

**Comment by rochdev** [comment]
Going to close this since it should be resolved in latest versions according to https://github.com/DataDog/dd-trace-js/issues/1311#issuecomment-823593394. Please feel free to reopen if that's not the case or if this is actually a different issue.

**Comment by ColinSullivan1** [comment]
Thanks @rochdev.
