### ISSUE TITLE
MaxListenersExceededWarning on tracer version 0.34.0

### ISSUE THREAD

**Issue by lawrenceong** [DataDog/dd-trace-js#1395]
**Describe the bug**

Getting a `MaxListenersExceededWarning` on tracer version `0.34.0`

```
DATADOG TRACER CONFIGURATION - {"date":"2021-05-30T23:26:16.020Z","os_name":"Linux","os_version":"5.4.89+","architecture":"x64","version":"0.34.0","lang":"nodejs","lang_version":"14.17.0","env":"qa","enabled":true,"service":"admin","agent_url":"http://10.40.0.14:8126","debug":false,"analytics_enabled":false,"sample_rate":1,"sampling_rules":[],"tags":{"service":"admin","env":"qa"},"log_injection_enabled":true,"runtime_metrics_enabled":false,"integrations_loaded":["fs","http","net","dns","express@4.17.1","winston@3.1.0","https","bluebird@3.7.2","knex@0.21.19","http2","@grpc/grpc-js@1.3.2","@google-cloud/pubsub@2.12.0"]}
(node:18) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
```

Was previously addressed as part of #1203 but the code was reverted.

**Environment**

* **Operation system:** MacOs/Linux
* **Node version:** 14.17.0
* **Tracer version:** 0.34.0
* **Agent version:** 7.27.0

**Workaround**

Put this at the very top of the startup script (next to the tracer initialisation):

```
require('events').EventEmitter.defaultMaxListeners = 1024;
```

**Comment by rochdev** [comment]
The PR you mentioned fixed this for an event listener that no longer exists, so this would be a different issue. Did the problem just appear after you upgraded to 0.34? What version were you previously using?

**Comment by lawrenceong** [comment]
@rochdev 0.34 is the first version we are using.  We haven't used any other version.

**Comment by lawrenceong** [comment]
@rochdev could you please clarify what you mean by event listener that no longer exists?

**Comment by lawrenceong** [comment]
I've just tested this again and it is still happening.  All I've done is hit a health endpoint again and again and eventually, the message will appear.  Will try and create a stripped down version of the app with just the health endpoint and test.

**Comment by rochdev** [comment]
> could you please clarify what you mean by event listener that no longer exists?

What I mean is that the event emitter that we fixed was from the new dynamic configuration feature, which has since been dropped as we need to make some changes to the core of the tracer before implementing it properly, so the event emitter that was fixed no longer exists. This means that the issue you are seeing is unrelated to that change and is another bug.

> Will try and create a stripped down version of the app with just the health endpoint and test.

Please let me know when that's done and I will look into it.

**Comment by lawrenceong** [comment]
@rochdev Unfortunately, I've been unable to replicate the issue in a stripped down version of the app.  The newer version of the app contains updated libraries with the hard coded increase removed and is no longer generating this message, so I'm going to close this ticket.  Thank you all the help.
