### ISSUE TITLE
New Integration: ShareDB

### ISSUE THREAD

**Issue by dwinrick-lever** [DataDog/dd-trace-js#1408]
Hello,

I'm reaching out from Lever.co, where we make extensive use of https://github.com/share/sharedb

Recently, we have our own custom instrumentation to make DataDog work with sharedb, but I think it would be preferred if it was just part of this core project. Custom integration is required, since many messages/spans are sent/created over a single long-lived connection.

I'm happy to create a PR for this feature (proposed name: `packages/datadog-plugin-sharedb`).

Just checking that DataDog is open to adding this plugin!

**Comment by rochdev** [comment]
We would definitely be open to this plugin! Generally speaking we want to support as much as possible out of the box, so if you are willing to open a PR we would definitely welcome it.

**Comment by dwinrick-lever** [comment]
Yay, thank you! I will close this we'll get on it.
