### ISSUE TITLE
Improve docs around require() and initialization order

### ISSUE THREAD

**Issue by dbsanfte** [DataDog/dd-trace-js#141]
Hiya,

It wasn't immediately apparent that dd-trace only works properly if you:

1) require() it
2) require() everything else it's supposed to instrument
3) make sure you require('dd-trace').init(); before you require() anything else instrumentable

It doesn't work if using module import statements. This had me pulling my hair out. 

Better docs for dummies like me please :)

**Comment by rochdev** [comment]
This is actually documented as a note in [Getting Started](https://docs.datadoghq.com/tracing/setup/javascript/#installation).

This has been a problem for a few users however so I agree that it's probably not clear enough.

What change do you think could be made to improve visibility? Would replacing the note by an actual code comment in the snippet help?

**Comment by rochdev** [comment]
I added a code comment in the documentation snippet, and also a warning in the debug log in https://github.com/DataDog/dd-trace-js/pull/148 which will be part of the next release.

I am closing this issue, but please feel free to reopen if you think these are not enough to properly guide new users.
