### ISSUE TITLE
dd-trace tries to instrument local javascript files that are require()'d if they name-match 

### ISSUE THREAD

**Issue by dbsanfte** [DataDog/dd-trace-js#142]
Looks like dd-trace will try to instrument local javascript files if they name-match supported modules.

For instance, we had a `require('./mongodb');` in one of our projects, as it had unfortunately named its DAL with the same name as the mongodb module. dd-trace tried to instrument it and broke things pretty badly.

Might want to look at being more strict around which require()'d things dd-trace tries to instrument, if possible.

**Comment by rochdev** [comment]
I will add validation of the instrumented module API in the instrumenter. This will prevent a module that doesn't match the expected API from breaking the app. It should resolve this issue, and will also prevent any changes in the actual npm module from breaking the app as well.
