### ISSUE TITLE
Excluding traces/spans with errors from APM indices 

### ISSUE THREAD

**Issue by betomoretti** [DataDog/dd-trace-js#1420]
Hi 👋,  

I would like to know if someone was able to exclude (or reject?) specific spans and/or traces. 
We are using APM for our services and one of them has elastic search as a dependency. Based on some necessities, we do some checks that end up in elastic search responding 401 errors. This expected and fine for us. But Datadog ends up showing this as Non-Http errors because of `Datadog Intelligent Retention Filter` (I think). Sometimes, we could end up with up to 4k of these errors in just one hour. This leads us to the necessity of trying to exclude these traces.
I tried two things:
- Hooks: I thought that I could hook to the span using [this](https://datadoghq.dev/dd-trace-js/interfaces/plugins.elasticsearch.html#hooks) but I don't know what could I do there to reject this span.
- Retention filter: I thought that I could use a retention filter at 0% (which I thought could avoid indexing the span at all).  But I couldn't but this before the `Datadog Intelligent Retention Filter` so I guess that it's indexing it anyways.  

I'm a bit blocked here and I would appreciate some help.

P.S: It could be that I'm not explaining that well the issue. Feel free to ask.

**Comment by rochdev** [comment]
> Hooks: I thought that I could hook to the span using this but I don't know what could I do there to reject this span.

You won't be able to reject the span using a hook, but if the error is expected you could remove the error from the hook to avoid retention.

For example:

```js
tracer.use('elasticsearch', {
  hooks: {
    request (span, params) {
      if (!isError(params)) { // detect the case that should not be an error somehow
        span.setTag('error', false)
      }
    }
  }
})
```

Please let me know if that works for your use case. In any case, I would recommend opening a support ticket since I may not be aware of how to fix this from the UI, and I expect it should be possible without altering the instrumentation.

**Comment by betomoretti** [comment]
Hey, thanks for the quick response. I tried that but I have some typescript issues:
```
Object literal may only specify known properties, and 'request' does not exist in type '{ query?: (span?: Span, params?: TransportRequestParams) => any; }'
```

[Here](https://datadoghq.dev/dd-trace-js/interfaces/plugins.elasticsearch.html#hooks) you can see that only `query` is allowed.

**Comment by rochdev** [comment]
@betomoretti Sorry, that was a typo on my end, it's actually `query` and not `request`.

**Comment by betomoretti** [comment]
```
tracer.use('elasticsearch', {
  hooks: {
    request (span, params) {
      if (!isError(params)) { // detect the case that should not be an error somehow
        span.setTag('error', false)
      }
    }
  }
})
```

Okay then, coming back to this code block, it's what I've actually tried when I mentioned:
> Hooks: I thought that I could hook to the span using this but I don't know what could I do there to reject this span

but nothing in params indicates an error(although it finishes as an error).

**Comment by rochdev** [comment]
Rejecting might require more context than what's currently available. Do you know exactly what you would need to make the decision? Anything that could be added as another parameter to the hook?

**Comment by betomoretti** [comment]
I think I need two things for rejecting the trace:
- The path. This indicates the elastic search request that we are doing for detecting an special use case which ends up in errors.
- The error. Something that tells me that the trace for that path is going to end up as an error. 
The last is what I'm struggling because at the time that the `query` hook is being called there's no error information.

**Comment by rochdev** [comment]
It looks like queries return `error` and `result`. The `result` object has a `statusCode` property. Would adding the `result` object to the hook be enough for your use case? Is the path on the `params` object?

**Comment by betomoretti** [comment]
FYI I contacted support and they pointed me out [this](url). 
I think that I'm going to try that.


> It looks like queries return error and result. The result object has a statusCode property. Would adding the result object to the hook be enough for your use case? Is the path on the params object?


```
    tracer.use(`elasticsearch`, {
        hooks: {
            query: (span, params) => {
                logger.debug('params', params);
                logger.debug('tags', span.getBaggageItem('elasticsearch'));
            }
        }
    });
```

I configured this code and I cannot see the result object in params. Am I missing something?

**Comment by rochdev** [comment]
What I meant is that right now the result is not passed to the hook, and I am wondering if adding that to the `elasticsearch` plugin in dd-trace so that it would be passed to your hook would help you solve your use case.

The link you shared from support seems to be broken.

**Comment by betomoretti** [comment]
Sorry, [this is the linkg](https://docs.datadoghq.com/tracing/setup_overview/configure_data_security/?tab=mongodb#exclude-resources-from-being-collected). 

> What I meant is that right now the result is not passed to the hook, and I am wondering if adding that to the elasticsearch plugin in dd-trace so that it would be passed to your hook would help you solve your use case.

Yeah, I think that would work :)

**Comment by tlhunter** [comment]
Looks like this issue has been worked out. I'll close it but feel free to reopen if I'm wrong.
