### ISSUE TITLE
Different http handler for incoming and outgoing request

### ISSUE THREAD

**Issue by hong823** [DataDog/dd-trace-js#1434]
`http` module currently has both incoming and outgoing request set using the same handler `http.request` (Span name).

![Screen Shot 2021-06-17 at 2 32 11 PM](https://user-images.githubusercontent.com/5250790/122463400-2f836780-cf7b-11eb-9eaf-0a11f9607fe5.png)

Client: https://github.com/DataDog/dd-trace-js/blob/64206ba2fb233fdee73e53f169ee300491c999d7/packages/datadog-plugin-http/src/client.js#L55

Server: https://github.com/DataDog/dd-trace-js/blob/7b27059fe3b9de6788c0517a2b499ff6b78da5ff/packages/datadog-plugin-http2/src/server.js#L37

I understand there's a `span.kind` that could differentiate them in the tag

```  
{
    "trace_id": "<removed>",
    "span_id": "<removed>",
    "parent_id": "<removed>",
    "name": "http.request",
    "resource": "GET <removed>",
    "error": 0,
    "meta": {
      "service": "my-service",
      "span.kind": "client",
      "http.method": "GET",
      "http.url": "<removed>",
      "http.status_code": "200",
      "language": "javascript"
    },
    "metrics": {
      "_sample_rate": 1,
      "_sampling_priority_v1": 1
    },
    "start": <removed>,
    "duration": <removed>,
    "service": "my-service",
    "type": "http"
  }
```
It would be nice to have it differently or at least have an option to overwrite the handler, so it will be more meaningful in the flame graph.

For example:
Client: http.request.client
Server: http.request.server

**Comment by rochdev** [comment]
This is definitely a change we want to make, and the main hold off so far has been that it's a breaking change since the operation name is also used when generating the corresponding metrics. I can say however that for sure this change will happen, it's just a matter of when.

**Comment by rochdev** [comment]
What framework are you using? Generally speaking you should rarely see `http.request` for a server in the first place since we use the name of the framework for any supported library, for example `express.request` or `fastify.request`.

**Comment by hong823** [comment]
@rochdev I agreed, this is definitely not an easy change since others might be using it for dashboard, monitor, etc. Splitting them up into different handlers might also be helpful on differentiate client/server metrics without having to use custom metrics.

We're using NestJS framework, mainly using for server-side rendering (SSR) of pages. 

We have other project uses express framework and those show up separately as `express.request`.
![Screen Shot 2021-06-17 at 5 38 15 PM](https://user-images.githubusercontent.com/5250790/122480705-f35c0100-cf92-11eb-9d73-25938553df94.png)

**Comment by tlhunter** [comment]
This issue is super old and I'm pretty sure we've made vast improvements to differentiate incoming and outgoing http spans. I'll close it for now but feel free to reopen if the current version of the tracer doesn't work as expected.
