### ISSUE TITLE
dd-trace v0.34.0+ breaks on nodejs 12

### ISSUE THREAD

**Issue by peterfraedrich** [DataDog/dd-trace-js#1435]
**Describe the bug**

When using dd-trace v0.34.0 and above on nodejs 12, socket.io connections cause the tracer to throw an exception. This is because `req.connection.encrypted` is deprecated in node 13 and the dd-trace agent has been updated to keep in line with this change, however this change breaks backwards compatibility for versions < node 13.

This change was made with https://github.com/DataDog/dd-trace-js/pull/1372 

```
message: "Cannot read property 'encrypted' of undefined",
  stack: "TypeError: Cannot read property 'encrypted' of undefined\n" +
    '    at extractURL (/root/dev/.../node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:412:33)\n' +
    '    at addRequestTags (/root/dev/.../node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:347:15)\n' +
    '    at finish (/root/dev/.../node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:232:3)\n' +
    '    at Response.res._datadog_end (/root/dev/.../node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:268:5)\n' +
    '    at internals.Response.Payload.internals.Payload.onend (_stream_readable.js:679:10)\n' +
    '    at Object.onceWrapper (events.js:417:28)\n' +
    '    at internals.Response.Payload.internals.Payload.emit (events.js:311:20)\n' +
    '    at internals.Response.Payload.internals.Payload.EventEmitter.emit (domain.js:505:15)\n' +
    '    at endReadableNT (_stream_readable.js:1204:12)\n' +
    '    at /root/dev/.../node_modules/async-listener/glue.js:188:31\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:84:21)',
```

**Environment**

* **Operation system:** Ubuntu 20.04 LTS
* **Node version:** 12.16.1
* **Tracer version:** 0.34.0+
* **Agent version:** n/a

**Comment by rochdev** [comment]
It looks like `req.socket` was introduced in Node 0.3.0, and we run our tests all the way back to Node 8, so I'm not sure what could cause that property to be missing. Is this something that is easy to reproduce or specific to a single application?

**Comment by peterfraedrich** [comment]
@rochdev its possible its an artifact of our application's architecture, but without extensive testing and attempting to re-create it on a different app I'm not sure. Our app is using `hapi-io` to route socket.io requests to `hapi`, so its very possible its an artifact of how `hapi-io` is creating the virtual endpoints and the subsequent requests to them.

**Comment by rochdev** [comment]
From the `hapi-io` documentation: `Each time an event is received, a fake HTTP request is created and injected into the hapi server.`. That definitely sounds like a recipe for disaster 😅. It does mean however that I should be able to reproduce this in a test.

**Comment by peterfraedrich** [comment]
It might be worth it to open an issue with `hapi-io` as well to see if they can implement the full http request spec instead of [what I assume is] a bare-minimum one.

**Comment by rochdev** [comment]
Unfortunately, I doubt this would be possible since the API is actually pretty big and includes tons of nested objects, streams, etc. The approach they likely took is to set anything that Hapi needs and nothing else, which is reasonable for what they're trying to do.

On our end, I added a comment to our tests so that no properties are assumed to be present on request objects, along with a fix for `req.socket` specifically.
