### ISSUE TITLE
Start trace with given traceId and parentId

### ISSUE THREAD

**Issue by LukasAV** [DataDog/dd-trace-js#1441]
Hi,
I looked around the forum and the documentation for quite a while now but could not get starting a trace with a given trace id.

I am currently doing something like this:

```
const childOf = tracer.extract('text_map', attributes);
const span = tracer.startSpan('newSpan', { childOf });
tracer.scope().activate(span, f);  // f is a given function to include in the trace and produce sub-traces function
```

Calling `tracer.scope().active().context().toTraceId()` inside `f` returns the injected traceId, but when opening the trace no trace named 'newSpan' can be found, however the logs from `f` seem to be linked.

I also read in an issue that `tracer.startSpan` is deprecated, but I could not find a way to do this with `tracer.tracer()`.

Any idea what I am missing?

**Comment by rochdev** [comment]
Without seeing the values of `attributes` and `f` it's a bit difficult to say since the above looks correct. The only thing I can think of at a glance if anything would be causing `span.finish()` to never be called, especially since it's never called in the above snippet. However, it's worth noting that as you mentioned `tracer.trace()` handles all of this for you so you don't have to.

Using `tracer.trace()` for the above example would look like this:

```js
const childOf = tracer.extract('text_map', attributes);

// Using tracer.trace() will ensure that the span is finished after `f` is done.
// It will also activate the new span and handle any error and add it to the span.
// This assumes that `f` is either synchronous or returns a promise.
tracer.trace('newSpan', { childOf }, () => f())
```

Let me know if that helps!

**Comment by LukasAV** [comment]
Thanks for your quick reply, I had not found `childOf` in the [TraceOptions](https://datadoghq.dev/dd-trace-js/interfaces/traceoptions.html) so I did not know this was possible. The proposed code seems to work so far and the trace as well as all sub-traces are added to the specified traceId.

The only span still separate is the original `amqp.receive` trace which actually receives the attributes to use for the new trace and is currently active when starting the new span like above. Is there a possibility to add this span to the received traceId, too?

**Comment by rochdev** [comment]
Yes, by setting it as the `childOf`, but it looks like you're already using another span as the parent? What is `attributes`?

**Comment by LukasAV** [comment]
So we are starting the trace in service A and then send data along with the `attributes` object via AMQP to service B, where a `amqp.receive` trace is automatically generated. Once the data is received we can access the `attributes` and start a ‘newSpan’ with the traceId sent from service A. This results in two traces: One with everything from service A and ‘newSpan’ with its sub-traces from service B, and one trace with the automatically generated ‘amqp.receive’ trace. So the question is how to set the traceId for this ‘amqp.receive’ trace.

I am only referring to `attributes` as the object generated in service A using `tracer.inject()`, which results in an object like `{‘x-datadog-trace-id’:1, ‘x-datadog-parent-id’: 2, …}`

**Comment by rochdev** [comment]
If `newSpan` is started while the `amqp.receive` span is currently active, `tracer.trace()` should automatically set it as the parent without needing any manual extraction, so it should be enough to simply not call `tracer.extract` and not pass any `childOf` to `tracer.trace()`.

**Comment by LukasAV** [comment]
That is not exactly what I am trying to achieve. This is the view I want to achieve:

```
|-Span service A, sending trace details along with the data----------------------------------|
    |-amqp.receive in service B, created automatically-------------------------------------|
        |-newSpan in service B, reading the received data and extracing trace details---|
```

The amqp.receive span however starts a new trace as it is not aware of the trace details that were received. Only newSpan can then set the recieved traceId. This results in the amqp.receive span being alone in the new trace it started and the rest of the spans in service B being in the trace started by service A as intended.

I suppose what I am trying to achieve is currently not possible, so I made sure newSpan covers the everything from amqp.receive and just ignore that span.

**Comment by rochdev** [comment]
> The amqp.receive span however starts a new trace as it is not aware of the trace details that were received.

It should be aware since our auto-instrumentation supports distributed tracing. So the `amqp.receive` span should automatically be a child of the the `amqp.send` span from service A, and then `newSpan` simply needs to set the `amqp.receive` span as its `childOf` to continue the hierarchy.

**Comment by LukasAV** [comment]
The AMQP message content follows a specific format, so the trace data probably does not arrive in the format that dd-trace expects, thus the traceId is not injected automatically. However, I do not know the exact implementation of service A.

For now, I simply made sure that `newSpan` covers the same duration which the original `amqp.receive` covers, which provides all information needed. Thank you very much for your help.

**Comment by rochdev** [comment]
Makes sense. If you have your own distributed tracing implementation and the auto-instrumentation span is redundant you can also disable it with `tracer.use('rhea', false)`.
