### ISSUE TITLE
Yarn Plug'n'Play Support

### ISSUE THREAD

**Issue by andrewBsk** [DataDog/dd-trace-js#1446]
Add support for Yarn's PnP.
https://yarnpkg.com/features/pnp

**Comment by nickperkins** [comment]
Certainly need support for Yarn PnP. Any idea when this might get on the roadmap?

**Comment by drphelps** [comment]
This should already be possible if you [set up PnP](https://yarnpkg.com/features/pnp#initializing-pnp) so that Node knows how to resolve modules. You can either require the pnp.cjs file in the script, `NODE_OPTIONS='--require ./pnp.cjs --require dd-trace/init' next start` or a custom module 
```
const path = require('path');
const pnp = require(path.resolve(__dirname, '../../.pnp.cjs'));

// set up PnP module resolution
pnp.setup();

const tracer = require('dd-trace').init();
```

**Comment by tlhunter** [comment]
This is a pretty old issue and it looks like @drphelps came up with a workaround. I'll close it for now but if it's still relevant feel free to reopen.
