### ISSUE TITLE
Bundling with esbuild

### ISSUE THREAD

**Issue by amurdock** [DataDog/dd-trace-js#1480]
The dynamic imports defined within `packages/datadog-plugin-aws-sdk/src/helpers.js` break bundles generated using `esbuild`. Would it be possible to remove `getService` and replace with something along the following lines?

```
const services = {
  cloudwatchlogs: new require("./services/cloudwatchlogs")(),
  dynamodb: new require("./services/dynamodb")(),
  kinesis: new require("./services/kinesis")(),
  lambda: new require("./services/lambda")(),
  s3: new require("./services/s3")(),
  redshift: new require("./services/redshift")(),
  sns: new require("./services/sns")(),
  sqs: new require("./services/sqs")()
}
```

**Comment by rochdev** [comment]
What version of the dd-trace are you using? It should already be like the above in the latest version.

**Comment by amurdock** [comment]
`0.34.0` ... what a noob ... sorry for the bother.
