### ISSUE TITLE
Knex: show different DB instances as separate services

### ISSUE THREAD

**Issue by gszpak** [DataDog/dd-trace-js#1481]
Hi, this issue is very similar to https://github.com/DataDog/dd-trace-js/issues/977 and https://github.com/DataDog/dd-trace-js/issues/317.

I have a monolithic service that uses knex to connect to different PG instances. From what I noticed, the DD service name is created based on the driver name (eg `app-postgres`, `app-mysql`). Could you add support to set service name per host / database, like in https://github.com/DataDog/dd-trace-js/pull/1110?

**Comment by rochdev** [comment]
Since you are using Postgres it should be possible to use the approach that was added in the PR, for example:

```js
tracer.use('pg', {
  service: params => `${params.host}-${params.database}`
})
```

**Comment by gszpak** [comment]
I'll try it out - thank you!

**Comment by tlhunter** [comment]
I'm going to close this since it sounds like Roch's reply worked.
