### ISSUE TITLE
Distributed Tracing for Grpc

### ISSUE THREAD

**Issue by Bibob7** [DataDog/dd-trace-js#1488]
I have two NodeJs services. One is acting as BFF and provides a REST api for fronten. This NodeJs BFF is talking via grpc to another NodeJs backend service.

For the backend service I can see the grpc traces, but I can't see distributed traces from frontend REST call to the backend service via grpc. 

Are there plans to implement distributed tracing for grpc. I know already from the PHP extension, that we need to push some metadata like trace.if from client to receiver site.

**Comment by rochdev** [comment]
Distributed tracing is supported for the gRPC integration. Assuming by frontend you mean the browser and that RUM is installed in the frontend application, in your example you should be seeing the HTTP span from the frontend (XHR and Fetch are instrumented by RUM), then the spans for the BFF, and the spans for the backend all in a single distributed trace. Which part of the trace exactly is disconnected or missing?

**Comment by Bibob7** [comment]
The last part is missing, so I don‘t see the connection between the grocery client and receiver.

**Comment by rochdev** [comment]
Is this something you can minimally reproduce with code you could share? It sounds like a bug since distributed tracing is supported and supposed to work out of the box.

**Comment by Bibob7** [comment]
I have a controller class that will also register the route based on the annotations for an express app.
Inside of this controller I call a service that is handling the grpc call.

Controller class:
```
@Route('related-searches')
export class RelatedSearchesController extends Controller {
    @Get('/')
    public async getResults(
        @Query('search_term') term: string,
        @Query() limit: number
    ): Promise<RelatedSearchResponse> {
        const service = RelatedSearchesService.createDefault();
        try {
            const relatedSearchesResponse = await service.getBySearchTerm(term, limit);
            return {
                relatedSearches: relatedSearchesResponse.getRelatedSearchesList(),
            };
        } catch (error) {
            this.setStatus(translateIntoHttpStatusCode(error.code));
            throw new Error(error.message);
        }
    }
}
```

Grpc Service class:
```
export class RelatedSearchesService
    extends GrpcService<RelatedSearchesServiceClient>
    implements RelatedSearchesServiceInterface {
    async getBySearchTerm(term: string, limit: number): Promise<GetByTermResponse> {
        const getByTermRequest = new GetByTermRequest();
        getByTermRequest.setSearchTerm(term);
        getByTermRequest.setLimit(limit);

        const metadata = this.createCallMetadata();

        return new Promise((resolve, reject) => {
            this.client.getByTerm(getByTermRequest, metadata, (error, response) => {
                if (error || !response) {
                    reject(error);
                    return;
                }

                resolve(response);
            });
        });
    }

    static createDefault(): RelatedSearchesServiceInterface {
        const address = `${process.env.RELATED_SEARCHES_API_HOST ?? DEV_API_HOST}:${
           process.env.RELATED_SEARCHES_API_PORT ?? DEV_API_PORT
        }`;

        return new RelatedSearchesService(RelatedSearchesServiceClient(address, credentials.createInsecure()));
    }
}
```

For the BFF service, I can only see: ![Bildschirmfoto 2021-07-13 um 08 30 48](https://user-images.githubusercontent.com/4511770/125402379-a3673300-e3b4-11eb-886b-f8e580ec425b.png)

And for the backend service, I only see:
![Bildschirmfoto 2021-07-13 um 08 32 33](https://user-images.githubusercontent.com/4511770/125402594-e0cbc080-e3b4-11eb-93b6-3b54c19a1b37.png)

**Comment by rochdev** [comment]
I don't see any outgoing gRPC request from the BFF side, is there any? It's the `grpc` client integration that is responsible for propagation, as well as `http2` if HTTP2 is used as well. If these integrations are not working for any reason in the BFF then propagation won't work.

**Comment by Bibob7** [comment]
This part is the outgoing grpc request:

```
this.client.getByTerm(getByTermRequest, metadata, (error, response) => {
                if (error || !response) {
                    reject(error);
                    return;
                }

                resolve(response);
            });
```

The client generated via protoc.
if this is not correct, how you would do it?

**Comment by Bibob7** [comment]
By the way, I'm using:

@grpc/grpc-js: 1.3.5
@dd-tace-js: 1.0.0

**Comment by rochdev** [comment]
It's possible that statically generated clients are not supported right now and we don't currently have tests for that. I'll try to reproduce.

**Comment by rochdev** [comment]
I can't seem to reproduce. Is the tracer initialized before any other module is imported? Otherwise it's possible that the integration doesn't work or has issues.

**Comment by Bibob7** [comment]
@rochdev: Id did not initialize the tracer at the top. This was the issue. Thanks for you help! :)
