### ISSUE TITLE
Question: Middleware tracing with apollo-server-fastify

### ISSUE THREAD

**Issue by thehideki81** [DataDog/dd-trace-js#1490]
We are using this with apollo-server-fastify, and middleware tracing doesn't seem to work out of the box.

The actual `fastify.request` trace is being traced as expected, but not the middlewares. Currently we have circumvented the issue by wrapping our middleware functions with tracer.trace() implementation.

Is there a "proper" way of getting the middlewares to work with apollo-server-fastify?

Here is a simplified example code of us instantiating the server:

```
import fastify from 'fastify'

import { ApolloServer } from 'apollo-server-fastify'

import { jwtMiddleware, loggerMiddleware, errorHandler } from './middlewares'
import { apolloConfig } from './config'

const app = fastify()

const apollo = new ApolloServer(apolloConfig)

app.register(apollo.createHandler())
// These are not traced automatically, they have a tracer.trace() wrapper inside the function...
app.addHook('onRequest', jwtMiddleware)
app.addHook('onResponse', loggerMiddleware)
app.setErrorHandler(errorHandler)

app.listen(port, '0.0.0.0', () =>
  console.log(`API listening`)
))
```

EDIT: note, this is not a working code example, just a stripped down example from our codebase.

**Comment by thehideki81** [comment]
Had to edit the issue a bit, sorry. Now should be descriptive of our problem.

**Comment by thehideki81** [comment]
Middleware example with our wrapper. Just wondering if it is possible to get this working out-of-the-box without having to create these wrappers manually for every middleware.

```
const jwtMiddleware = async (request) {
    return tracer.trace('middleware-jwt', () => {
       // Here we do our middleware stuff.
    })
}
```

**Comment by rochdev** [comment]
Plugins and hooks are not currently instrumented by the tracer, so support for that would need to be added in the automatic instrumentation. What is your use case for having spans specifically for them? Wouldn't there already be spans for any slow operations executing in the context of a plugin/hook?

**Comment by thehideki81** [comment]
We need to trace errors from our middlewares. Basically we have a graphql server which works fine with datadog, and fastify in front of it. The fastify request is being traced, the graphql is being traced, but for example if our JWT middleware service throws an error, it doesn't get traced unless we manually add the tracer inside the middleware.

---

I may have misunderstood this, https://datadoghq.dev/dd-trace-js/interfaces/plugins.fastify.html
 
middleware
middleware: undefined | false | true

"Whether to enable instrumention of .middleware spans"

---

I thought that this would enable instrumentation of fastify middleware plugins automatically.

**Comment by rochdev** [comment]
Looks like that's an issue with our docs. Middleware instrumentation is only supported for a few frameworks that have an Express-like middleware system. It could definitely be added though, but I would probably be explicit that it's plugins and hooks, and not necessarily go with the "middleware" terminology.

**Comment by rochdev** [comment]
Does the error at least go on the request span? It's supposed to automatically be captured, at least the last occurrence.

**Comment by thehideki81** [comment]
No. No errors are logged at all if I throw inside the middleware without the custom trace wrapper.

**Comment by thehideki81** [comment]
And also, only logged error is `error: true` If I throw an error and return 500 from the request.

**Comment by thehideki81** [comment]
If the errors would be automatically caught to the main parent trace, it would be enough for us, but currently nothing is caught unless we wrap it ourselves.

**Comment by rochdev** [comment]
> If the errors would be automatically caught to the main parent trace, it would be enough for us, but currently nothing is caught unless we wrap it ourselves.

Ok, so I'd say let's focus on that for now since this should be the case, meaning there is a bug. I'll have to look into it.

**Comment by thehideki81** [comment]
Any update on this @rochdev ?

**Comment by rochdev** [comment]
@thehideki81 Not yet, but I'll look into it early next week.

**Comment by rochdev** [comment]
@thehideki81 What version of Fastify are you using? I opened #1533 to fix the issue but I wasn't able to make it work with versions before `3.9.2`, at least not for actual exceptions.

**Comment by thehideki81** [comment]
Sadly we are running fastify 2.x due to our dependency chain.

**Comment by rochdev** [comment]
How do you handle exceptions thrown in hooks without killing the process? Or do you only use `done(err)` to fail the hook?

**Comment by thehideki81** [comment]
Damn. Did not mention we are running on older fastify.

I would not put too much effort into supporting our use case, if you made it work with the 3.x.

We will anyway need to de-debt our app at some point, and it might not be feasible to focus on supporting legacy major versions after LTS.

**Comment by thehideki81** [comment]
But good to know the issue will be fixed when we finally update :D.

All the best and thanks

**Comment by thehideki81** [comment]
> How do you handle exceptions thrown in hooks without killing the process? Or do you only use `done(err)` to fail the hook?

We tried both, callback done() and throws. Currently throwing because of code consistency.

**Comment by rochdev** [comment]
Throwing in hooks that use async/await is supported will be supported on all versions when the PR lands, only throwing synchronously is not supported, so hopefully it should work for your use case. If you are throwing synchronously anywhere, please let me know how to handle that and I will add support as well (I tried adding an `onError` hook and `setErrorHandler` and the process still crashes before 3.9.2).

**Comment by thehideki81** [comment]
we are only using async hooks, so it should be enough for us.

**Comment by thehideki81** [comment]
Hooks we currently use:
- onRequest, onResponse

And also a custom setErrorHandler.

Currently all of these three are wrapped in a custom tracer wrap.

PS. we are now updating to Fastify 3.
