### ISSUE TITLE
tracing on injected requests (eg, shot) throws exception

### ISSUE THREAD

**Issue by mikeatkins** [DataDog/dd-trace-js#1509]
**Describe the bug**
The recent change in this PR:  https://github.com/DataDog/dd-trace-js/pull/1372 breaks "fake" requests such as those created with [hapijs/shot](https://github.com/hapijs/shot) cause dd-trace to throw an exception. I have raised this issue with hapijs folks as well (https://github.com/hapijs/hapi/issues/4268), however, I think there is a valid argument to be made that we should not be attempting to trace requests that are injected (i.e., not real http requests), or at least if we are then at the very least there should be better handling around `request.socket.encrypted` (the underlying issue here is that `request.socket` is undefined for shot requests).

**Environment**
all
* **Operation system:**
all
* **Node version:**
all
* **Tracer version:**
\>= 0.34.0
* **Agent version:**

**Comment by rochdev** [comment]
Do you still have the issue with the latest version of the tracer? This is supposed to have been fixed by #1442 in 0.36.1.

**Comment by mikeatkins** [comment]
perfect, I had not noticed that. Sorry for the noise. I think this can be closed.
