### ISSUE TITLE
Tracing with jest-environment-jsdom fails finding getVmContext function

### ISSUE THREAD

**Issue by nhoughto** [DataDog/dd-trace-js#1510]
**Describe the bug**
I'm testing our Datadog CI visibility with some Jest tests, tracing via `jest-environment-node` works ok, but fails when using `jest-environment-jsdom` with the errors:

```
TypeError: this.getVmContext is not a function

      at DatadogJestEnvironment.handleTestEventWithTrace [as handleTestEvent] (../../../../../node_modules/dd-trace/packages/datadog-plugin-jest/src/index.js:108:26)
```

Jest Environment is configured as per docs like this:
```
//from https://docs.datadoghq.com/continuous_integration/setup_tests/javascript/?tab=jest
require('dd-trace').init({
  flushInterval: 300000  // To guarantee test span delivery
})

module.exports = require('jest-environment-jsdom');
```

If I comment out the `require()..init()..` all the tests pass, so seems like a bug with this jest integration and jsdom?

**Environment**

* **Operation system:** macOS 10.15.7
* **Node version:** 12.18
* **Tracer version:** 1.0.0
* **Agent version:** `7`

**Comment by juan-fernandez** [comment]
hi @nhoughto. Thanks for reporting this bug. 

Could you provide me with the versions you're using of: 
`jest`, `jest-circus`, `jest-environment-jsdom` and `jest-environment-node` (if you haven't installed the last two separately, they should be at the same version as `jest`)

**Comment by nhoughto** [comment]
Yep you are right, i was missing an explicit version range for `jest-environment..` so was using mismatched versions 🤦 
thanks for the tip
