### ISSUE TITLE
Pino v7 shipping soon

### ISSUE THREAD

**Issue by jsumners** [DataDog/dd-trace-js#1516]
We released the first release candidate today -- https://github.com/pinojs/pino/releases/tag/v7.0.0-rc.1

I'm not sure how this affects your integration. Just giving you a heads up.

**Comment by mcollina** [comment]
Something that would be extremely amazing would be to support our new transport system to push the logs through that. It's based on the worker_threads and it should be significantly faster than using the main event loop.

**Comment by rochdev** [comment]
@mcollina Do you have an example of how the new transport system works? It's definitely something we should add if log injection doesn't currently work with it.

**Comment by mcollina** [comment]
I'm not sure how you are currently sending the logs to your servers.  Check out https://github.com/pinojs/pino/blob/master/examples/transport.js#L18, which will run https://github.com/pinojs/pino-elasticsearch in a separate process instead of the main event loop. This approach has the benefit of being able to send the logs _synchronously_ when the user does `process.exit(0)` manually on the main thread.

**Comment by rochdev** [comment]
We don't actually use Pino to send logs, but rather we support setting an existing Pino instance as the logger for dd-trace, and we also patch Pino to inject the tracing context into the logs. My understanding is that both should work without any explicit support for the new transport system.

**Comment by jsumners** [comment]
> My understanding is that both should work without any explicit support for the new transport system.

Correct. Though, a test to make sure an application using Pino for logging and DataDog for tracing will work with transports would be a good idea.

**Comment by mcollina** [comment]
> We don't actually use Pino to send logs, but rather we support setting an existing Pino instance as the logger for dd-trace, and we also patch Pino to inject the tracing context into the logs. My understanding is that both should work without any explicit support for the new transport system.

Sure thing. What I was trying to convey is that you might want to leverage the multihtread transport system to send out those logs instead of the current in-thread mechanism.

**Comment by rochdev** [comment]
Official support for 7.x has now been released (we were missing support for the new exports added in 6.8.0).
