### ISSUE TITLE
[Next]: Module not found: Can't resolve 'async_hooks'

### ISSUE THREAD

**Issue by Meemaw** [DataDog/dd-trace-js#1527]
**Describe the bug**
Trying to upgrade to recent versions of `dd-trace-js` that dropped the browser support, we're observing these errors in a NextJS project with custom `express` server:

```
error - ../node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:3:0
Module not found: Can't resolve 'async_hooks'
```

Also tried bumping node to `v16.1.0` to see if that changes anything, but still getting the same error.

**Environment**

* **Operation system:** Darwin MacBook-Pro-7 18.7.0 Darwin Kernel Version 18.7.0: Mon Mar  8 22:11:48 PST 2021; root:xnu-4903.278.65~1/RELEASE_X86_64 x86_64
* **Node version:** v14.15.4
* **Tracer version:** v1.1.0
* **Agent version:** /
* **Next version:** 10.2.2

**Comment by rochdev** [comment]
`async_hooks` is a Node module so it's expected that it's not available in the browser, and it should always be available in Node since it's built-in. Is this error in the browser? If yes then APM doesn't support the browser and [RUM](https://github.com/DataDog/browser-sdk) should be used instead.

**Comment by Meemaw** [comment]
This is the error on server.

**Comment by rochdev** [comment]
Can you provide a reproduction? To my knowledge it's impossible for a Node built-in module to not be available.

**Comment by Meemaw** [comment]
Fixed. `dd-trace` somehow got imported even though it was behind a `if(process.env.IS_SERVER)` check which `NextJS` should tree shake away in client bundle...

Btw, does the `next` plugin need to be initialised manually? Having deployed the latest version I still don't see the new traces that the plugin should be doing, e.g. `handleRequest` and so on.

**Comment by rochdev** [comment]
> does the next plugin need to be initialised manually?

It doesn't but the tracer has to be initialized before Next itself otherwise the instrumentation will not work. The easiest way to make sure of that is to use `NODE_OPTIONS='--require dd-trace/init'` instead of initializing the tracer programmatically.
