### ISSUE TITLE
Why don't we mark 5XX status code as errors in http module

### ISSUE THREAD

**Issue by seanyu4296** [DataDog/dd-trace-js#1563]
https://github.com/DataDog/dd-trace-js/blob/cb042ad2d3fb09dd25b4db0a58659082362de8e0/packages/datadog-plugin-http/test/client.spec.js#L527

Wondering why we dont mark 5XX status code as errors in http module ?

Because generally 500 errors are server errors right? btw the above test also does not hold true because it only excludes 500 not all 5xx but it states all "5xx errors are not errors by default"
https://github.com/DataDog/dd-trace-js/blob/cb042ad2d3fb09dd25b4db0a58659082362de8e0/packages/datadog-plugin-http/src/client.js#L286

**Comment by rochdev** [comment]
We flag 5xx as errors on servers and 4xx as errors on clients by default to follow the semantics of these errors. For example, if a client receives a 5xx, then it's the server that it was calling that had an error, not the client. But if a 4xx error is received, it means the error originated from the client.

You can override this behaviour with the `validateStatus` option:

```js
tracer.use('http', {
  client: {
    validateStatus: code => code < 400
  }
})
```

**Comment by seanyu4296** [comment]
Got it. That does make sense as a default. Thanks @rochdev for the help
