### ISSUE TITLE
dd-trace-js overrides the default handle function/object on the Layer class in Express

### ISSUE THREAD

**Issue by shayonj** [DataDog/dd-trace-js#1603]
**Describe the bug**
In our application, we load `dd-trace-js` as the first thing. On application boot, we also traverse through the express router stack for some more custom instrumentation. The reason we do that is to get a list of all registered endpoints. 

However, because dd-trace-js overrides/wraps the `handle` https://github.com/DataDog/dd-trace-js/blob/0f3983bf0c27a9d0ab0b2d2421a14860ce6fe08a/packages/datadog-plugin-router/src/index.js#L51, its no longer possible to read into `handle. stack` on a `Layer`. Instead as a workaround we need to read on `handle._datadog_orig.stack`

Following is an example of a Layer object

```javascript
Layer {
  handle: [Function: wrapCallHandle] {
    _datadog_orig: [Function: router] {
      params: {},
      _params: [],
      caseSensitive: undefined,
      mergeParams: undefined,
      strict: undefined,
      stack: [Array],
      _name: 'router'
    }
  },
  name: 'router',
  params: undefined,
  path: undefined,
  keys: [],
  regexp: /^\/?(?=\/|$)/i { fast_star: false, fast_slash: true },
  route: undefined,
  _datadog_matchers: [ { path: '/', test: [Function: test] } ]
}
```

What would be expected is to not have `_datadog_orig` represent the original handle function as a nested attribute. Example 

```javascript
Layer {
  handle: [Function: router] {
    params: {},
    _params: [],
    caseSensitive: undefined,
    mergeParams: undefined,
    strict: undefined,
    stack: [Array],
    _name: 'router'
  },
  name: 'router',
  params: undefined,
  path: undefined,
  keys: [],
  regexp: /^\/?(?=\/|$)/i { fast_star: false, fast_slash: true },
  route: undefined,
  _datadog_matchers: [ { path: '/', test: [Function: test] } ]
}
```

**Environment**

* **Operation system: Max OS 11.5.2**
* **Node version: 1v14.17.5**

**Comment by shayonj** [comment]
I am happy to attempt at a potential solution if the behaviour is unintended. I see some comments around, so want to verify first 👍🏾

**Comment by rochdev** [comment]
The behaviour is unintentional, but we are working on a new shimmer that will make fixing (and preventing) problems like this easier going forward. It should land on `master` in the next few days, so it's probably best to wait for that first.

**Comment by shayonj** [comment]
Thats great! thanks @rochdev
