### ISSUE TITLE
Cannot disable some integrations with DD_TRACE_DISABLED_PLUGINS

### ISSUE THREAD

**Issue by joshua-barnett** [DataDog/dd-trace-js#1604]
**Describe the bug**
I've set my `DD_TRACE_DISABLED_PLUGINS` variable to the value of `aws-sdk@2.747.0,@elastic/elasticsearch@6.8.0,dns,express`.

However, in the logs of my application I can see these integrations are still being loaded whereas other ones like `dns` and `express` are absent as expected.

Why are the `aws-sdk@2.747.0` and `@elastic/elasticsearch@6.8.0` integrations not disabled?

I've also tried without the version suffixes.

**Log**
```
DATADOG TRACER CONFIGURATION
{
    "date": "2021-09-06T08:18:37.211Z",
    "os_name": "Linux",
    "os_version": "5.4.0-1045-aws",
    "architecture": "x64",
    "version": "0.35.0",
    "lang": "nodejs",
    "lang_version": "10.22.0",
    "env": "staging",
    "enabled": true,
    "service": "project",
    "debug": false,
    "analytics_enabled": false,
    "sample_rate": 1,
    "sampling_rules": [],
    "tags": {
        "service": "project",
        "env": "staging",
        "version": "0.55.0"
    },
    "dd_version": "0.55.0",
    "log_injection_enabled": false,
    "runtime_metrics_enabled": false,
    "integrations_loaded": [
        "http",
        "https",
        "aws-sdk@2.747.0",
        "@elastic/elasticsearch@6.8.0"
    ]
}
```

**Environment**

* **Operation system: Linux**
* **Node version: 10.22.0**
* **Tracer version: 0.35.0**
* **Agent version: 1.10.0**

**Comment by rochdev** [comment]
The environment variable takes the plugin names and not the module names. I guess it would make sense to support both to avoid confusion, but in the meantime you should be able to achieve the above with `DD_TRACE_DISABLED_PLUGINS='aws-sdk,elasticsearch,dns,express'`.

What is the use case for disabling these plugins? In general this environment variable should only be used when debugging an issue with an integration.

**Comment by joshua-barnett** [comment]
@rochdev thanks I'll give that a go, I was going by the names in the `integrations_loaded` array.
