### ISSUE TITLE
trace to queue 

### ISSUE THREAD

**Issue by ngonzalezromero** [DataDog/dd-trace-js#1607]
**Describe the bug**
Hi !!

I'm getting "trace to queue" message when I'm trying to send traces from a nodejs's lambda to datadog
`
             2021-09-13T19:11:58.940Z	371e927d-3f26-5376-b285-cbc49b9cd283	DEBUG	Adding trace to queue: [
            {
                "trace_id": "0445d90f1166dce2",
                "span_id": "0445d90f1166dce2",
                "parent_id": "0000000000000000",
                "name": "own-service",
                "resource": "own-service",
                "error": 0,
                "meta": {
                    "service": "own-service",
                    "runtime-id": "13341220-1c4b-4589-ab21-f9d0078b921d",
                    "language": "javascript"
                },
                "metrics": {
                    "_dd.agent_psr": 1,
                    "_sample_rate": 1,
                    "_dd.measured": 1,
                    "_sampling_priority_v1": 1
                },
                "start": 1631560318212035300,
                "duration": 727077637,
                "service": "own-service"
            }
            ]
`

The trace is showed in the APM/Traced section, but  in  Log explorer /Trace Tab section, the link  is missing

<img width="1006" alt="Screen Shot 2021-09-13 at 16 34 00" src="https://user-images.githubusercontent.com/8051738/133145731-1f459adb-2366-4627-b5e1-4ea302c6a8e7.png">

**Environment**
AWS Lambda
* **Operation system:**
* NA
* **Node version:**
* 14
* **Tracer version:**
*1.3.0
* **Agent version:**
1.3.o

**Comment by ngonzalezromero** [comment]
related issue https://github.com/DataDog/dd-trace-js/issues/1081

**Comment by rochdev** [comment]
Can you open a [support](https://www.datadoghq.com/support/) ticket? We will need to look into your account to look at the data being reported to better understand what is causing the issue.

**Comment by bengl** [comment]
I'm going to close this issue, since it's from September and it has (hopefully) been moved to Datadog support. If not, please open a support issue.
