### ISSUE TITLE
msgpack-lite used by dd-trace-js is using a lot of processor's resources

### ISSUE THREAD

**Issue by agindre** [DataDog/dd-trace-js#161]
Hi guys,

I used dd-trace on my server for two weeks. I used it to get the stats from a [parse server](https://github.com/parse-community/parse-server) (it's an express app with extra libs) launched in cluster mode with pm2.
During this period, I noticed that my nodejs processes were using much processor's resources than before. It went to the roof, up to 100% per core for some requests.

After I launched every nodejs process with --prof to get the profiling, I get this result:
` ticks parent  name`
 ` 113187    7.6%  UNKNOWN`
`  13640   12.1%    LazyCompile: *write buffer.js:889:40`
`  13639  100.0%      LazyCompile: *string /home/ubuntu/parse-server/node_modules/msgpack-lite/lib/write-type.js:110:20`
`  10863   79.6%        LazyCompile: *<anonymous> /home/ubuntu/parse-server/node_modules/msgpack-lite/lib/write-type.js:237:26`
`  10863  100.0%          Builtin: ArrayForEach`
`  10863  100.0%            LazyCompile: *obj_to_map /home/ubuntu/parse-server/node_modules/msgpack-lite/lib/write-type.js:230:22`
This is just a sample of the output, I got several line like this one ending up to msgpack-lite. 
[here is the report](https://github.com/DataDog/dd-trace-js/files/2132205/report.txt)

For what I understood from this report it is the processor which is spending too many ticks in the msgpack-lite, I found from the package-lock.json that dd-trace-js was the only one using it. So I removed dd-trace-js from my code and everything went back to normal.

I don't know what happened but it will be great if there is a way for us to fix this issue in order to use datadog APM :) 

Cheers,

**Comment by rochdev** [comment]
Which version of `dd-trace-js` are you using? There have been a few memory leaks issues in the past weeks which would cause an ever growing trace to stay in memory and get reprocessed by `msgpack-lite` in each request. This should be resolved in 0.3.1.

How many requests per second is this service receiving/sending? This library has not yet been optimized, so it shouldn't be used for anything more than a few hundred req/sec.

**Comment by agindre** [comment]
Hi @rochdev,

Thanks for your reply.
I'm using the version 0.3.1.
The system is dealing with 31 req/sec.

**Comment by rochdev** [comment]
This is way below what this library should be able to handle. Do you know how many spans are created for every trace?

It would be helpful to see the debug logs. You can get those by using the `debug` property when initializing the tracer.

```js
tracer.init({ debug: true })
```

Depending on how sensitive these are, you can either send them here, in a direct message on the public Slack, or through support.

**Comment by agindre** [comment]
Hi @rochdev 

Unfortunately, I used the lib in production. It's difficult for me to reproduce in an iso prod environment and I don't want to enable the debug mode in prod. On the other hand, I can enable the debug mode for one of the node of my cluster. It won't give you an exact vision of what's happening but you will see a fraction of the requests. 

Tell me if it could work for you.

Cheers,

**Comment by rochdev** [comment]
@agindre That would work. As long as I can see a few of the generated traces, it should give me an idea of what is going on.

**Comment by rochdev** [comment]
@agindre Were you able to get a few logs? Also, can you try with `0.4.0`? It has quite a few changes to the core that could have fixed the problem. If you use manual instrumentation, please note that this version contains [breaking changes](https://github.com/DataDog/dd-trace-js/releases/tag/v0.4.0).

**Comment by agindre** [comment]
Hi @rochdev,

Sorry for my late answer. No I didn't but I will try it with the last version end of this week.
