### ISSUE TITLE
Does graphql support include express-graphql?

### ISSUE THREAD

**Issue by dbsanfte** [DataDog/dd-trace-js#162]
https://github.com/graphql/express-graphql

Do you guys support this lib as well?

I ask because anyone running express under the hood is probably using express-graphql if they're using graphql. And you guys support express. :)

**Comment by rochdev** [comment]
It should be supported since it's using `graphql` to parse and execute the document. Basically any library that uses `graphql` should be supported.

I will leave this opened for now since maybe the documentation could be clearer for implicit support of popular dependent modules.

**Comment by dbsanfte** [comment]
Okay I'll give it a shot. Thanks!

**Comment by rochdev** [comment]
Documentation has been updated to include `express-graphql` and Apollo Server
