### ISSUE TITLE
Add support for multiple Mongo services if connecting to multiple clusters from the same node.js app

### ISSUE THREAD

**Issue by venku122** [DataDog/dd-trace-js#1664]
We are using Mongoose and we are adding two different databases/clusters.
Before we would instrument our mongoDB connection using dd-trace like this
ddTrace.use('mongodb-core', { analytics: true });
The issue with this is now we have two different connections but they are both using mongodb-core as the driver to connect to Mongo.
Ideally I'd like to name the service for each connection
So instead of
```
// current behavior
api-mongodb

// new behavior
api-mongodb-db1
api-mongodb-db2
```

From the conversation on Slack:
> @rochdev Unfortunately this is not possible today. Do you know where the connection name is available from the API? We could either add a `splitByInstance` option or a span hook so that you can alter any span tag, but in both cases the connection name needs to be available.

>I have the connection name available at the model level in Mongoose. Is there a way to add/edit the spans already?
Also for us, this is a per-collection connection.
So N collections are on connection 1 and M collections are on connection 2.
Could we add a filter at the datadog end to split queries up into 2 services after they have been received?

> @rochdev I don't think this can be done since it would rely on the service name, which cannot be changed right now. The way things currently work, this needs to happen on the tracer side. Unfortunately, without a span hook for mongodb, this is not something you can do yourself. If the connection name is available on the model, I'm assuming it's also available at the point we instrument, so it shouldn't be too difficult to add an option to use it in the service name.

**Comment by apank** [comment]
@venku122 - not sure if you're still dealing with this issue - I have a few suggestions;

> Could we add a filter at the datadog end to split queries up into 2 services after they have been received?

Depending on the output of the logs having some identifier that differentiates the db's you can use the [Service Remapper](https://docs.datadoghq.com/logs/log_configuration/processors/?tab=ui#service-remapper)


Another possible work around would be to update your [DD Agent's YAML](https://docs.datadoghq.com/integrations/mongo/?tab=standalone) to connect to MongoDB directly. This way you can pass a service name per connection. If you are using this Atlas then you would want to follow this [guide](https://docs.datadoghq.com/integrations/mongodb_atlas/).

**Comment by tlhunter** [comment]
This issue is pretty old and it looks like @apank might have provided a workaround. I'll close it for now but if you still need help then please reopen.
