### ISSUE TITLE
app-graphql service missing since update to dd-trace 1.3.0

### ISSUE THREAD

**Issue by ephemer** [DataDog/dd-trace-js#1679]
## Describe the bug

We were using a pre-1.0 release of `dd-trace` and recently updated to `1.3.0` Since the update, our `-graphql` service no longer appears in the APM services list. The standard express and database services are still available, and the `/graphql` route is logged via express, even with GraphQL spans broken down correctly, but there is no top-level service any more, meaning we our monitoring can no longer be sorted / filtered per mutation / query. This hugely reduces the value of datadog for us overall.

(I am aware there are newer versions of dd-trace, and am not opposed to updating, but that's what we're currently using).

Here is our setup:

```
const tracer = require("dd-trace").init({
    // otherwise the datadog *agent*'s hostname is used, which
    // doesn't correlate properly between logs and traces (we use fargate on ecs):
    reportHostname: true,
    analytics: false,
    logInjection: true,
    tags: datadogTags,
    enabled: isProduction,
});

tracer.use("express", {
    headers: [ /* ... relevant headers ... */],
    hooks: {
        request: (span, req) => {
            // ... set span tags based on req ...
        },
    },
});


const regexOfDisallowedVariables = /(email)|(password)/i;

tracer.use("graphql", {
    variables: (variables) => {
        const variablesToReturn = {};
        Object.entries(variables || {}).filter(([key, value]) => {
            if (regexOfDisallowedVariables.test(key)) {
                variablesToReturn[key] = "******";
            } else {
                variablesToReturn[key] = value;
            }
        });

        return variablesToReturn;
    },
    hooks: {
        execute: (span, { contextValue }) => {
            const { user, requestCountry } = contextValue;
            // set tags based on user / country
        },
    },
});
```

Maybe some of the variable names are incorrect, leading to a silent error; maybe the API has changed completely. I found documentation for the various configuration `dd-trace` settings hard to find, and the documentation for the plugins (e.g. `graphql`) also seemed sparse. I would greatly appreciate any input on this to get us back on track.

## Environment

**Operation system:** Alpine Linux / macOS

**Node version:** 14.x / 16.x
**Tracer version:** 1.3.0
**Agent version:** `datadog/agent:latest`

**Comment by rochdev** [comment]
This is expected as we are moving away from using the service name to separate operations within the same service. You should see a dropdown list in the top left of the UI where `express.request` will be selected by default but you can change it to `graphql.execute` to view GraphQL queries for that service. If the queries are more relevant for you than the Express request, you can change which one is the [primary operation](https://docs.datadoghq.com/tracing/guide/configuring-primary-operation/) as well.

**Comment by ephemer** [comment]
@rochdev thanks a lot for your response here. I can confirm that the graphql requests are visible like they were by changing the request type.

Unfortunately this is not ideal for us: we have both graphql routes and non-graphql routes. The separation into express and graphql made perfect sense. It's not a deal break for us but it is a big step back to have to switch between them manually, and to not see both side-by-side in the overview

**Comment by rochdev** [comment]
@ephemer If for your use case it makes more sense to separate them into completely different services, the previous behaviour can be restored with the following configuration:

```
tracer.use('graphql', {
  service: 'some-service-graphql' // any service name you would like for that service
})
```

**Comment by ephemer** [comment]
@rochdev I will give that a try, that's fantastic, thanks!

**Comment by ephemer** [comment]
That's working as expected so I'll close this issue now. Thanks a lot for your help!
