### ISSUE TITLE
Logs crowded with TimeoutOverflowWarning messages

### ISSUE THREAD

**Issue by DmytroMysak** [DataDog/dd-trace-js#1685]
**Describe the bug**

A lot of errors in console like: "(node:311712) TimeoutOverflowWarning: 678934156894683900 does not fit into a 32-bit signed integer."
![image](https://user-images.githubusercontent.com/22196591/141772865-efa5353d-9ed9-43ab-9543-fa16a129e7e4.png)

Installed dd-trace, after the ~30s got all over my logs this error. Profiling enabled.

**Environment**

* **Operation system:** Ubuntu LTS
* **Node version:** node.js 14.15
* **Tracer version:** "dd-trace": "1.5.1"
* **Agent version:** datadoghq/cluster-agent:1.15.1

**Comment by pbstriker38** [comment]
Setting `DD_PROFILING_ENABLED` to false for local development fixed this for us.

**Comment by DmytroMysak** [comment]
I have the same error in kubernates
