### ISSUE TITLE
Tracer does not load http integrations on startup

### ISSUE THREAD

**Issue by tamanjoku** [DataDog/dd-trace-js#1699]
**Describe the bug**
My tracer does not seem to load up the http integration, but loads the express integration, and as such my hook does not work. Here is the log of my tracer config:

DATADOG TRACER CONFIGURATION - {"date":"2021-11-23T13:31:40.059Z","os_name":"Darwin","os_version":"19.6.0","architecture":"x64","version":"1.5.1","lang":"nodejs","lang_version":"14.17.2","env":"local","enabled":true,"service":"delphi","agent_url":"http://127.0.0.1:8126","debug":false,"sample_rate":1,"sampling_rules":[],"tags":{"cluster_name":"local","cluster":"local","service":"delphi","env":"local","version":"1.0.0","runtime-id":"36eea7c4-747a-42b1-a5dc-07a0c20b4f88"},"dd_version":"1.0.0","log_injection_enabled":true,"runtime_metrics_enabled":false,"profiling_enabled":false,"integrations_loaded":["express@4.16.4","redis@3.1.2"]}

And here is my code sample:

```
const tracer = require('dd-trace').init({
    logInjection: true,
    service: process.env.DD_SERVICE,
    env: process.env.DD_ENV,
    version: process.env.DD_VERSION,
    hostname: process.env.DD_AGENT_HOST,
    tags: {
        'cluster_name': process.env.DD_CLUSTER_NAME,
        'cluster': process.env.DD_CLUSTER_NAME,
    }
});

tracer.use('http', {
    server: {
        hooks: {
            request: (span, req) => {
                if (req.url && req.url.includes('messages')) {

                    ...

                }
            }
        }
    }
});
```

**Environment**

* **Operation system: MacOS**
* **Node version: 14.17.2**
* **Tracer version: 1.5.1**
* **Agent version: v7**

**Comment by rochdev** [comment]
This looks like a load order issue. Is the tracer initialized before any other module is imported? Can you share your initialization code?

Also, did you try adding the hook on `express` instead of `http`? (although if there is a load order issue it's possible the configuration will be ignored)

**Comment by bengl** [comment]
@tamanjoku Are you still affected by this? If so, we can reopen, but for now I'm going to close it. If you're still affected by it, plz let us know if you can share the spot where this code is loaded, and if you could try adding the hook on `express` instead of `http`.
