### ISSUE TITLE
Heads up: Fastify v4 release preparation has started

### ISSUE THREAD

**Issue by jsumners** [DataDog/dd-trace-js#1701]
See https://github.com/fastify/fastify/issues/3482

I anticipate a release near the new year. I do not know how this module will be affected, if at all, but the changes can be inspected at https://github.com/fastify/fastify/compare/main...next

cc: @mcollina

**Comment by rochdev** [comment]
Thanks for the heads up! Is there any beta release that I could test?

**Comment by jsumners** [comment]
Just the `next` branch at the moment. I'm sure we will issue RCs soon.

**Comment by rochdev** [comment]
Fastify 4 new exports were not being instrumented but this was fixed in #1833 and released in 2.2.0.
