### ISSUE TITLE
Graphql Plugin - Mutation not traced & throw errors

### ISSUE THREAD

**Issue by quentin-** [DataDog/dd-trace-js#174]
👋,

I think it's because of a typo here "mutations" instead of "mutation":
https://github.com/DataDog/dd-trace-js/blob/master/src/plugins/graphql.js#L257

While debugging this I also discovered that this does not work as intended:
https://github.com/DataDog/dd-trace-js/blob/master/src/plugins/graphql.js#L15-L17

This might use the patched schema, because the object is never deeply copied.
I could reproduce this like so:

1. start graphql server
2. run mutation, works fine (does not wrap anything since there's a typo)
3. run query, schema is mutated
4. run mutation, throw errors: contextValue in undefined in #resolveField

**Comment by rochdev** [comment]
I cannot reproduce the error with the provided steps. Can you provide a code snippet to reproduce?

**Comment by quentin-** [comment]
```js
it('should not mutate the schema', (done) => {
  const query        = `query MyQuery { hello(name: "world") }`
  const subscription = `subscription onSomething { ... } `

  graphql.graphql(schema, query).catch(done)

  expect(schema._datadog_patched).to.equal(undefined)
  // ^ _datadog_patched is true right now

  graphql.graphql(schema, subscription).catch(done) 
  // ^ this errors since schema is patched and subscription is not supported operation
})
```

**Comment by rochdev** [comment]
Thanks a lot! I'll work on a fix as soon as possible.

**Comment by rochdev** [comment]
I cannot reproduce with this exact snippet added to the test suite (only difference is I commented out the `_datadog_patched` test).

**Comment by quentin-** [comment]
I opened this PR with a test case https://github.com/DataDog/dd-trace-js/pull/179

**Comment by rochdev** [comment]
I thought you meant it was throwing an exception, sorry about that. Working on a fix.
