### ISSUE TITLE
Support custom jest environment

### ISSUE THREAD

**Issue by oleg-rdk** [DataDog/dd-trace-js#1747]
I'm currently trying to set up `dd-trace-js` and e2e tests based on puppeteer.

I'm extending the Puppeteer environment like is shown in the docs of the integration pkg - https://github.com/smooth-code/jest-puppeteer/tree/master#extend-puppeteerenvironment

but the whole thing doesn't work. I tried to debug it and found out that eventually [`handleTestEventWithTrace`](https://github.com/DataDog/dd-trace-js/blob/82e1a7fd9c3e0c9a1f17507811e52fb17d21dc0a/packages/datadog-plugin-jest/src/jest-environment.js#L74) is not called at all during the execution of the tests. Thus, I guess dd-trace just doesn't patch the needed environment.

`jest` 26.6.3
`jest-puppeteer` 5.0.2
`jest-environment-node` 26.6.2 (required by `jest` and `jest-puppeteer`
node 14.18.0

happy to provide more details if needed

**Comment by oleg-rdk** [comment]
@juan-fernandez thank you for the response!
`dd-trace` is v1.6.0. I also used `jest-circus` runner so that might a reason. 

Anyway, I had to proceed with just uploading JUnit report to DataDog since it covered my most critical needs. Thus the issue is not that blocking for me. But also I'm ready to help you to debug it if you are interested in it

**Comment by juan-fernandez** [comment]
hey @oleg-rdk . Thanks for the info 😄 

Is it possible for you to share your current `testEnvironment` file? At least the part where `jest-environment-puppeteer` and `dd-trace` are required. 

Also, is updating `dd-trace` an option? We have done a major rewrite of the plugins and this might've solved some issues.

**Comment by oleg-rdk** [comment]
here is environment file:
```
const { setup, teardown } = require('jest-environment-puppeteer/lib/global');

// replacing require('dd-trace/ci/jest/env') from docs for custom init config
const tracer = require('dd-trace/packages/dd-trace');
tracer.init({
    startupLogs: true,
    logLevel: 'debug',
    flushInterval: 1000,
    debug: true,
});

tracer.use('jest', true);
tracer.use('fs', false);

const PuppeteerEnvironment = require('jest-environment-puppeteer/lib/PuppeteerEnvironment').default;

class CustomPuppeteerEnvironment extends PuppeteerEnvironment {
    constructor(config, context) {
        super(config, context);
    }

    async handleTestEvent(event) {
        // recoding screen, taking screenshots
    }
}

module.exports = CustomPuppeteerEnvironment;
module.exports.setup = setup;
module.exports.teardown = teardown;
```

> Also, is updating dd-trace an option?

yeah I just tried it, but after that I stopped seeing logs from `dd-trace` (just a startup one). Probably some config has changed.

**Comment by oleg-rdk** [comment]
ohh :facepalm: 
you are right. It's me ~not knowing ES6~ missing simple things. Sorry for disturbing you!
And thank you so much!
