### ISSUE TITLE
MySQL Pooled queries have the wrong parent

### ISSUE THREAD

**Issue by fragglebob** [DataDog/dd-trace-js#175]
I noticed in DataDog that none of my traces had database calls, except for the first query, which seemed to have them all belong to it.

After loads of debugging I worked out its down to the current span in the query being the span that creates the connection.

My solution for now was to stop using `pool.query` and use `pool.getConnection`, however I had to bind the callback to get the correct span for the query.

```js
pool.getConnection(tracer.bind((err, conneciton) => {
    connection.query(sql, values, cb)
}))
```

The problem happens in `pool.acquireConnection`, when it enters `onOperationComplete` the span is changed to that original one.

**Comment by rochdev** [comment]
I cannot reproduce this issue specifically since the provided snippet gives me the correct span. I was however able to cause a similar issue related to the internal queue of the `mysql` module.

@fragglebob If I open a PR, would you be able to try it out directly?

**Comment by fragglebob** [comment]
The snippet I shared produces the correct span. It's the way I've got round the issue for now.

Sure, I can give it a go tomorrow.

**Comment by rochdev** [comment]
I meant that even without `tracer.bind()` it still works for me, even if I run multiple queries.

Here's the PR: https://github.com/DataDog/dd-trace-js/pull/178

**Comment by fragglebob** [comment]
I get ya now.

I think it might have been from using a combination of express, graphql and mysql together. I will give it a go tomorrow. 👍 

If I get some time I will figure out how to cause it in a smaller example.

**Comment by fragglebob** [comment]
Yep, that fixes it completely.
