### ISSUE TITLE
[plugins-web]: support traceparent header

### ISSUE THREAD

**Issue by zekth** [DataDog/dd-trace-js#1789]
Currently `dd-trace-js` supports `b3` and `datadog` http headers, it would be great to support `traceparent` one. Which is inherited from the w3c rfc: https://www.w3.org/TR/trace-context/#examples-of-http-traceparent-headers

Right now i've started a hacky solution to replace the `express` middleware which kind of look like so:

```ts
    let httpTraceId:string, httpSpanId: string
    const traceparent: string = req.headers["traceparent"] as string
    if (traceparent) {
      const r = new RegExp(/^\d{2}-([A-Fa-f0-9]{32})-([A-Fa-f0-9]{16})-\d{2}$/)
      const matches = traceparent.match(r)

      if (matches) {
        httpTraceId = matches[1]
        httpSpanId = matches[2]
      }
    }

    const txtMap = {
      ['x-datadog-trace-id']: httpSpanId,
      ['x-datadog-parent-id']: httpTraceId,
      ['x-datadog-sampling-priority']: 1
    }

    const extracted = tracer.extract('text_map', txtMap)

    const s = tracer.startSpan("xpress.request", { childOf: extracted })
```

The issue i'm currently facing is the `traceparent` header is using `base16` and `datadog` is using `base10` with the use of `id` from : https://github.com/DataDog/dd-trace-js/blob/f68c28f94c964a6bebf7ccac65a0bb817f03bd9d/packages/dd-trace/src/id.js

Would it be possible to expose this API or add the header parsing in the lib itself?

If need i can work on this feature.

**Comment by rochdev** [comment]
> Would it be possible to expose this API or add the header parsing in the lib itself?

Exposing an API to provide a custom propagator is definitely a good idea and something we should eventually add to the library. However, since W3C Trace Context is an official standard we should definitely have built-in support for that as well.

> If need i can work on this feature.

We definitely welcome community contributions. We use 64-bit trace IDs internally and not 128-bit like the standard does, but the specification has guidelines on how to handle that with padding.

**Comment by zekth** [comment]
Is the plan of supporting `traceparent` headers in one PR and exposing the custom propagator in another looks like a good plan for you?

I'll be able to start working on this in a few days.

**Comment by rochdev** [comment]
> Is the plan of supporting traceparent headers in one PR and exposing the custom propagator in another looks like a good plan for you?

Definitely!
