### ISSUE TITLE
source-map-resolve is deprecated

### ISSUE THREAD

**Issue by jfirebaugh** [DataDog/dd-trace-js#1808]
Installing the dd-trace npm package prints the following:

```
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
```

This is due to the dependency [here](https://github.com/DataDog/dd-trace-js/blob/1e491665c85ccd3d62d4e82e411f82a950aacdf2/package.json#L88). I'm not familiar with how dd-trace-js uses this module, but is is possible to find a replacement?

**Comment by rochdev** [comment]
Source map support is actually used by the profiler. We are currently switching to the built-in source map support from `pprof`, not sure if it has the same issue but it doesn't look like it.

cc @Qard

**Comment by Qard** [comment]
Yeah, that will be going away soon.

**Comment by bcomnes** [comment]
It doesn't even seem like its being used anywhere in the code. Is it some kind of peer dependency?

**Comment by OKULLO** [comment]
Having same issue here....How do i make it go away
