### ISSUE TITLE
2.1.0 - Context creation failed: Cannot read property 'requestInject' of undefined"

### ISSUE THREAD

**Issue by OZhurbenko** [DataDog/dd-trace-js#1823]
**Describe the bug**
Started getting this error today after pulling the latest release:

```
"TypeError: Context creation failed: Cannot read property 'requestInject' of undefined",
                "    at Object.requestInject (/myapp/node_modules/dd-trace/packages/datadog-plugin-aws-sdk/src/helpers.js:83:17)",
```
                

Looks like there used to be a null check [HERE](https://github.com/DataDog/dd-trace-js/commit/51f7ddb3a5afcfd056e4d3f84e0cf49ea7638f8e#diff-ccafd385f71a839fbbb84973c703d4cdf62229978b57860d625dcebeccb6ff97L81-R83) and now it's gone 🤷‍♂️ 

* **Operation system:**
Ubuntu
* **Node version:**
14.x
* **Tracer version:**
2.1.0
* **Agent version:**

**Comment by astuyve** [comment]
Thanks for the report @OZhurbenko - we should have a fix out for it shortly.
