### ISSUE TITLE
Add `appsec?: boolean` to TracerOptions interface

### ISSUE THREAD

**Issue by ratrock** [DataDog/dd-trace-js#1829]
**Describe the bug**
Initializing appsec in TypeScript with `tracer.init({ appsec: true });` according to the [instructions](https://docs.datadoghq.com/security_platform/application_security/getting_started/nodejs/?tab=intypescriptcode) produces a TypeScript error:
`Argument of type '{ appsec: boolean; }' is not assignable to parameter of type 'TracerOptions'.`

**Environment**

* **Operation system:** Linux Mint 20.2
* **Node version:** 14.16.1
* **Tracer version:** 2.1.1
* **Agent version:** Heroku buildpack

**Comment by simon-id** [comment]
@rochdev I'm guessing I have to update this file accordingly ? https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts

**Comment by rochdev** [comment]
@simon-id Yes that's the one, with a corresponding test in `docs/test.ts`.

**Comment by ben-fuller1** [comment]
+1

**Comment by simon-id** [comment]
Fixed in version `2.2.0` of `dd-trace`. Please update and report back if you're still having issues 👍
