### ISSUE TITLE
Bug: Tracer ignores configured sampling rate

### ISSUE THREAD

**Issue by atreidesend** [DataDog/dd-trace-js#183]
It looks like the tracer constructed in `opentracing/tracer.js` is ignoring the configured sample rate and using a hardcoded value of 1
```
this._sampler = new Sampler(1)
```
Unless I'm missing something this samples *everything*, regardless of config. Happy to put together a quick PR to patch -> it could probably use something as simple `config.sampleRate || 1`

**Comment by rochdev** [comment]
Thank you for reporting this oversight! Since we are planning a release in a few hours, I will make the PR to make sure I can get it to go in that release.
