### ISSUE TITLE
DD-Trace: Jest throws TypeError: Cannot destructure property 'root' of 'path.parse(...)' as it is undefined.

### ISSUE THREAD

**Issue by sathishvenkataraman** [DataDog/dd-trace-js#1843]
**Describe the bug**
Bug description
i have a node.js application and using jest for unit testing.. i use the following to use dd-trace lib.. const tracer = require('dd-trace').init();

app works good, however when i try to run unit test via jest, just this init line alone cause the following error:

jest --coverage --verbose

FAIL plugins/tests/Apputils.test.js ● Test suite failed to run

TypeError: Cannot destructure property 'root' of 'path.parse(...)' as it is undefined.

  3 | const AWS = require("aws-sdk");
> 4 | const tracer = require('dd-trace').init();
    |                ^
  5 | var StatsD = require('hot-shots');
  6 | var dogstatsd = new StatsD();

  at findUp (node_modules/dd-trace/packages/dd-trace/src/pkg.js:25:11)
  at findPkg (node_modules/dd-trace/packages/dd-trace/src/pkg.js:14:20)
  at Object.<anonymous> (node_modules/dd-trace/packages/dd-trace/src/pkg.js:37:18)
  at Object.<anonymous> (node_modules/dd-trace/packages/dd-trace/src/config.js:7:13)
  at Object.<anonymous> (node_modules/dd-trace/packages/dd-trace/src/proxy.js:6:16)
  at Object.<anonymous> (node_modules/dd-trace/packages/dd-trace/index.js:4:23)
  at Object.<anonymous> (node_modules/dd-trace/index.js:3:18)
Any idea to get this working?

if I remove this line, all works well.. const tracer = require('dd-trace').init();

**Windows**

* **Operation system: Windows 10**
* **Node version: 14.x**
* **Tracer version:2.2.0**
* **Agent version: Agent 7.33.0 - Commit: e6cfcb9d38 - Serialization version: v5.0.4 - Go version: go1.16.7**

**Comment by bmeck** [comment]
what version of jest are you using? My guess is something jest is doing to mock node's `path` module might be confusing things.

**Comment by juan-fernandez** [comment]
hi @sathishvenkataraman ! Thanks for reporting this issue. I'd like to clarify a couple of things: 

1. Are you mocking `path` somewhere in your codebase? This is likely, as @bmeck suggested, because `path.parse` shouldn't return `undefined`.
2. Are you attempting to use CI Visibility (https://docs.datadoghq.com/continuous_integration/setup_tests/javascript/?tab=jest)? Or are you just testing code that happens to use `dd-trace` ? 
3. Apart from `jest` version, could you provide us with your `jest` config file? Feel free to remove fields you don't want to share.

**Comment by rochdev** [comment]
If it causes issues, even if it's not supposed to happen, should we still handle `path.parse` being undefined? It's better for the functionality to be broken in the tracer than causing possible crashes when the module is mocked for example.

**Comment by juan-fernandez** [comment]
@sathishvenkataraman I'm closing the issue since it should be fixed with #1973. Let me know if that's not the case though!
