### ISSUE TITLE
Does not work with Fastify

### ISSUE THREAD

**Issue by gajus** [DataDog/dd-trace-js#1859]
**Describe the bug**

Previously thought it is an issue with Express and Fastify being used together (https://github.com/DataDog/dd-trace-js/issues/1858). However, now I have re-written the second service to use Fastify as well and the issue continues.

When dd-trace is enabled:

```js
/* eslint-disable node/no-process-env */

import tracer from 'dd-trace';

tracer.init({
  env: process.env.ENVIRONMENT,
  hostname: process.env.DD_AGENT_HOST,
  runtimeMetrics: true,
  service: process.env.SERVICE_NAME,
});

tracer.use('fastify', {
  blocklist: ['/ready', '/live'],
});
```

Then CPU usage jumps from ~10m to ~1000M

```
NAME                                                  CPU(cores)   MEMORY(bytes)
contra-api-5cf5f8cbbd-74tqj                           1000m        364Mi
contra-api-5cf5f8cbbd-7scwm                           1000m        362Mi
contra-api-5cf5f8cbbd-8knzf                           1000m        866Mi
contra-api-5cf5f8cbbd-d9c6p                           1005m        311Mi
contra-api-5cf5f8cbbd-ff8xj                           999m         837Mi
contra-api-5cf5f8cbbd-hcjxb                           1001m        449Mi
contra-api-5cf5f8cbbd-hzlw7                           326m         356Mi
contra-api-5cf5f8cbbd-nbjk2                           1000m        451Mi
contra-api-5cf5f8cbbd-s5p95                           1000m        339Mi
```

Related to this issue: https://github.com/DataDog/dd-trace-js/issues/969

I have found that disabling network plugins does not eliminate the issue, i.e.

```js
tracer.use('fastify', false);
tracer.use('dns', false);
tracer.use('net', false);
```

Produces the same:

```
contra-api-cf589c6b7-9x55g                            989m         848Mi
contra-api-cf589c6b7-gt6ld                            996m         654Mi
contra-api-cf589c6b7-j4vdn                            988m         363Mi
contra-api-cf589c6b7-kn9n8                            951m         1010Mi
contra-api-cf589c6b7-pgzcl                            502m         569Mi
contra-api-cf589c6b7-qlgsb                            999m         1111Mi
contra-api-cf589c6b7-rk887                            999m         1187Mi
contra-api-cf589c6b7-v7vwv                            519m         787Mi
contra-api-cf589c6b7-zght9                            63m          191M
```

Therefore, not 100% sure if this is related to Fastify, but we have dd-agent running on another node.js application that is not Fastify and this issue does not surface.

**Environment**

* **Operation system:** Linux
* **Node version:** 16.13
* **Tracer version:** 2.2.0
* **Agent version:** 2.33

**Comment by rochdev** [comment]
@gajus Now that both are written with Fastify, do you now get Fastify traces or are those still missing? Or at the very least is the 1 service that worked with Express still working with Fastify?

Also, for this kind of performance issue, I'd recommend opening a [support ticket](https://www.datadoghq.com/support/) so that we can gather more information about your application.

**Comment by gajus** [comment]
> do you now get Fastify traces or are those still missing?

yes

> is the 1 service that worked with Express still working with Fastify?

yes

> I'd recommend opening a [support ticket](https://www.datadoghq.com/support/) so that we can gather more information about your application.

done

**Comment by gajus** [comment]
FYI there is a high correlation between the response size and failure.

A small JSON response handles 100 requests / second (100 bytes) without too much a problem.

A 4KB response starts chocking after 10 requests / second.

**Comment by gajus** [comment]
After investigating, I've found that the culprit is our logger.

For context, our setup looks as follows:

```js
const app = createFastify({
  connectionTimeout: 150_000,
  genReqId: () => {
    return uuid();
  },
  logger: createFastifyLogger(Logger),
  trustProxy: true,
});

app.addHook('preHandler', (request, reply, done) => {
  Logger.adopt(
    () => {
      done();
    },
    {
      reqId: request.id,
    }
  );
});
```

The `Logger.adopt` creates a new async context in `preHandler` that ensures that anything that is logged in relation to the request has the assigned `reqId`, even if not using Fastify logger instance.

However, it turns out that Fastify is passing the entire req/res object to the logger context. We were [filtering out](https://github.com/gajus/roarr-fastify/blob/db9884a2aae3a19de7395a84f03f52bcb125bbd7/src/factories/createFastifyLogger.ts#L11-L53) this data using a Roarr middleware and this worked fine until dd-trace was added. Something about dd-trace added to the mix is causing the CPU go through the roof. In our case, we were able to fix the issue by [modifying Roarr logger](https://github.com/gajus/roarr/commit/2df6c4cd167eeeb61b21eaf3b20d8c2dacd14b6b) to prioritize middlewares before trying to remove circular references from the logger context.

It is unclear what about dd-trace causes CPU hog with the earlier setup, but this addressed our performance issue.

**Comment by rochdev** [comment]
@gajus Did you try updating dd-trace to the latest version? This should have been fixed in the release a few days ago.

**Comment by rochdev** [comment]
Basically we were adding a `req._datadog` property that was causing some loggers to have issues, but we have now switched to an internal `WeakMap` instead.

**Comment by gajus** [comment]
This indeed would explain the issue. We are already doing Okay based on the latest Roarr modifications, but I will upgrade dd-trace.
