### ISSUE TITLE
Can dd-trace-js used to trace NextJs serverless node function?

### ISSUE THREAD

**Issue by bzhaotheiconic** [DataDog/dd-trace-js#1867]
Hi DD team,

Is there a way that we can setup dd-trace for NextJs api other than relying on (aka serverless functions) a custom express server

![Screen Shot 2022-02-24 at 7 20 36 pm](https://user-images.githubusercontent.com/97488935/155485940-650a5851-fd05-4804-b490-5dbdfaced828.png)

I have found a article touching on this topic 
https://jake.tl/notes/2021-04-04-nextjs-preload-hack
But I can't be certain this is a safe way. Any suggestion?

**Comment by rochdev** [comment]
This depends on what is loading NestJS in the first place. Generally speaking, if you are calling either `node` or `next` directly from the command line, you can use `NODE_OPTIONS='-r dd-trace/init'. If you are deploying your app in some serverless environment that controls the process, most of these have a way to preload code or alter Node environment variables.

Can you share more information about your specific environment?
