### ISSUE TITLE
ioredis instrumentation error on v2.2.1

### ISSUE THREAD

**Issue by pbstriker38** [DataDog/dd-trace-js#1879]
```shell
TypeError: Cannot read property 'span' of undefined
    at /node_modules/dd-trace/packages/datadog-plugin-redis/src/index.js:68:38
    at Subscription._handler (/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:13:9)
    at Channel.publish (diagnostics_channel.js:54:9)
    at finish (/node_modules/dd-trace/packages/datadog-instrumentations/src/ioredis.js:48:14)
    at /node_modules/dd-trace/packages/datadog-instrumentations/src/ioredis.js:27:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Environment**

* **Operation system:** OSX
* **Node version:** 14.17.5
* **Tracer version:** 2.2.1
* **Agent version:** none. `DD_TRACE_ENABLED` is set to false locally
* **ioredis version:** 4.27.2

**Comment by pbstriker38** [comment]
v2.2.0 works as expected

**Comment by rochdev** [comment]
This shouldn't be possible assuming that context propagation is working properly. Are you using a promise library like Bluebird or Q or are you relying only on native promises?

**Comment by rochdev** [comment]
I'm trying to reproduce but I get the expected behaviour and I'm seeing native promises internally. Is this something you're able to reproduce with a snippet you could share?

**Comment by pbstriker38** [comment]
we are not using any promise library

**Comment by pbstriker38** [comment]
I'm seeing this with winston as well
```shell
TypeError: Cannot read property 'span' of undefined
    at /node_modules/dd-trace/packages/dd-trace/src/plugins/log_plugin.js:39:46
    at Subscription._handler (/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:13:9)
    at Channel.publish (diagnostics_channel.js:54:9)
    at DerivedLogger.<anonymous> (/node_modules/dd-trace/packages/datadog-instrumentations/src/winston.js:17:15)
    at DerivedLogger.<computed> [as error] (/node_modules/winston/lib/winston/create-logger.js:81:14)
    at process.exit_handler.uncaughtExceptionHandler (/app/utils/exit_handler.js:85:12)
    at process.emit (events.js:412:35)
    at process.emit (domain.js:470:12)
    at process._fatalException (internal/process/execution.js:167:25)
    at triggerUncaughtException (<anonymous>)
```

**Comment by pbstriker38** [comment]
We jumped from dd-trace 1.7.0, so maybe there is some configuration issue ??

**Comment by rochdev** [comment]
We are in the process of rewriting all of our plugins with a new plugin system. This is ongoing so not related to a specific version but most of it so far happened since 2.x.

Basically the instrumentation is now decoupled from the plugin and publishes events that plugins subscribe to. We don't check if the store exists in the plugin before accessing it because it's supposed to be safe, assuming that context propagation through `async_hooks` works properly. We could just add a check to the object access, but then it's possible there is a bug somewhere that we'd just be hiding, which could cause other issues.

Is this something you are able to isolate? Can you share a reproduction snippet?

**Comment by pbstriker38** [comment]
ok. I think I traced it down.

```
DD_TRACE_ENABLED="false"
DD_LOGS_INJECTION="true"
```

**Comment by pbstriker38** [comment]
Even if we have DD disabled. Setting the log injection to true causes the errors

**Comment by rochdev** [comment]
It looks like the plugin manager is initialized even when dd-trace is disabled, which could definitely cause that. Working on a fix now. In the meantime, it should be possible to skip the plugin manager with `tracer.init({ plugins: false })`.

**Comment by pbstriker38** [comment]
yeah, also Had to comment out `tracer.use("ioredis", { service: "redis-cluster" });`

We can wrap all of our `tracer.use` in a check of `DD_TRACE_ENABLED` for now

**Comment by mmbfreitas** [comment]
+ 1

**Comment by beam36** [comment]
I got a similar error on ECS Fargate and I don't have DD_TRACE_ENABLED set (default should be true)

```
uncaughtException: Cannot read property 'span' of undefined
TypeError: Cannot read property 'span' of undefined
at /app/node_modules/dd-trace/packages/dd-trace/src/plugins/log_plugin.js:39:46
at Subscription._handler (/app/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:13:9)
at Channel.publish (/app/node_modules/diagnostics_channel/index.js:81:9)
at DerivedLogger.<anonymous> (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/winston.js:17:15)
at DerivedLogger.<computed> [as info] (/app/node_modules/winston/lib/winston/create-logger.js:81:14)
at Server.onListening (/app/index.js:48:7)
at Server.emit (events.js:314:20)
at Server.emit (/app/node_modules/dd-trace/packages/datadog-plugin-http/src/server.js:22:19)
at emitListeningNT (net.js:1350:10)
at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

**Comment by a88zach** [comment]
I am seeing the same issue with DD_TRACE_ENABLED not set on version 2.2.1.  

`TypeError: Cannot read properties of undefined (reading 'span')`

Using fastify with pino

**Comment by rochdev** [comment]
Been looking into this issue and it looks like there are actually 2 bugs:

1) There is a bug in the log injection where it tries to access the span even outside of a tracing context. I'm working on a fix right now and should have a PR soon. This should fix all the errors in this thread except the original one with `ioredis`.

2) For `ioredis`, I don't see how this could happen because for native promises it's Node that's in charge of tracking the asynchronous context, so it should never be undefined. @pbstriker38 I'm trying to see if the way we use `async_hooks` could cause an issue like that, but in the meantime, can you provide a reproduction? So far I've been unable to reproduce no matter what I do.

**Comment by pbstriker38** [comment]
I have a couple ways to reproduce it within our app. I'm not sure how to reproduce it outside of the context of our app though.

```shell
DD_TRACE_ENABLED=false
```

```js
const ddTrace = require("dd-trace");
const tracer = ddTrace.init();
tracer.use("ioredis", { service: "redis-cluster" });
```

And then I also realized that a comment in our dotenv file was actually making it into the ENV value

```bash
DD_TRACE_ENABLED=false # Disable DataDog
```
Which resulted in `process.env.DD_TRACE_ENABLED === 'false # Disable DataDog'`


To be clear, these errors are happening during our test suite. Once I fixed these issue's I then ran into some weirdness around [testdouble.js](https://github.com/testdouble/testdouble.js/) usage in our test suite. dd-trace seems to be removing the mocks that testdouble is creating, which then causes the tests to fail. Only way to fix this one was to completely remove dd-trace.

**Comment by rochdev** [comment]
@pbstriker38 Unfortunately I tried just that, and even tried to misuse the libraries and the tracer on purpose, and was unable to reproduce. I wonder if the test suite overrides the global `Promise` as this would definitely cause this sort of weirdness if it replaces it with a custom implementation that doesn't propagate the async context properly. I'll try to explicitly bind the resolve/reject handlers and hopefully it will fix the issue.

**Comment by rochdev** [comment]
Just released 2.3.0 with log injection fixed and promises explicitly bound to the correct tracing context.

@pbstriker38 Do you still have any issue with 2.3.0?

**Comment by pbstriker38** [comment]
Other then the testdouble.js issue, it's working.

**Comment by rochdev** [comment]
@pbstriker38 We're reworking our require hooks right now so it might work better in the future but it's hard to tell as anything that alters `require` or the module system in general is prone to conflicts. If you have a specific problem or can reproduce easily I would recommend opening a new issue so we can look into it and maybe add a test for that framework.
