### ISSUE TITLE
MongoDB `withTransaction` retries are recorded as errors

### ISSUE THREAD

**Issue by rohit-gohri** [DataDog/dd-trace-js#1888]
**Describe the bug**
We are using mongodb's [`withTransaction`](https://mongodb.github.io/node-mongodb-native/3.6/api/ClientSession.html#withTransaction) api to automatically retry writes in case of conflicts and we have a lot of conflicts due to parallel processing of a lot of data.

This api retries the method when an error occurs:

> retrying either the commit operation or entire transaction as needed (and when the error permits)

This has led to our APM being filled with these errors like `MongoError: WriteConflict` and `MongoError:Transaction 1 has been aborted.`, around 8.79M of them 😱 

This makes it difficult to find actual errors that might be happening and causing actual issues. Is there anything we can do to filter/handle these?

**Environment**

* **Operation system:** Linux
* **Node version:** 16
* **Tracer version:** 1.4.0
* **Agent version:**
* MongoDB Version: 3.6.9
* Mongoose Version : 5.13.6

**Comment by rochdev** [comment]
Unfortunately it's not really possible right now to alter this behaviour. Do you get a lot of these errors for every trace, or just a few and there are a lot of traces? Also, what would you expect to see instead? Should these spans exist but not be marked as errors, or would you expect a span for the whole transaction for example?

I would also recommend opening a [support](https://www.datadoghq.com/support/) ticket so that we can take a look at your account to better understand what the traces look like and what we could do to mitigate the issue.

**Comment by rohit-gohri** [comment]
> Do you get a lot of these errors for every trace, or just a few and there are a lot of traces?

I get a lot of errors for every trace. In the spans list for the trace there are multiple `findAndModify` queries and all of them except the last one are marked as errors.

> Also, what would you expect to see instead? 

Good question. The reason I noticed this is because of [Error Tracking feature]
(https://app.datadoghq.eu/apm/error-tracking), these errors are visible there but not actionable. They are expected to happen even, so I guess this is more a UX problem then a library one? We should be able to ignore a certain set of errors?

> Should these spans exist but not be marked as errors?

I think this would be the best option.

> I would also recommend opening a [support](https://www.datadoghq.com/support/) ticket

Opened support ticket 701701

**Comment by rochdev** [comment]
> They are expected to happen even, so I guess this is more a UX problem then a library one?

I definitely agree that this should be done in the UI and not in the library, because otherwise we're removing the error completely instead of still sending it but providing the ability to ignore it. Unfortunately this is not possible today however so this is something we'd have to fix at the library level.

You mentioned `withTransaction`. Does that mean that using `findAndModify` without a transaction would be an actual error, but not within `withTransaction`? Can you show a code example of how this is used with the retry logic? I wonder if maybe we could add an additional span to wrap the errors so that the top-level span for MongoDB is not erroring.

**Comment by rohit-gohri** [comment]
`withTransaction` is provided by the node mongodb driver so the retries are handled there, the source code is [here](https://github.com/mongodb/node-mongodb-native/blob/main/src/sessions.ts#L464-L470).

> Does that mean that using findAndModify without a transaction would be an actual error, but not within withTransaction

So, we create a `session` and start the transaction on that session.  And we pass the session to all the queries that we want to be a part of the transaction. The `withTransaction` catches the errors and retries the query/whole callback depending on the error (Write Conflict/Transaction aborted), and commits the transaction when the whole callback is completed successfully.

This is a simpler code sample
```ts
// Model is a mongoose model
const getUpdates = (doc, update) => ({ status: update.status });
const filter = { externalId: 'existing-doc-id' };
const update = { status : "next" };
const session = await Model.db.startSession();
await session.withTransaction(async () => {
	const existingDoc = await Model.findOne(filter).session(session);
	const updates = await getUpdates(
	  existingDoc,
	  update,
	);
	
	const finalDoc = await Model.findByIdAndUpdate(
	  existingDoc._id,
	  {
	    $set: updates,
	  },
	  {
	    new: true,
	    session,
	  },
	);
});
```

And this is how the spans look:

![image](https://user-images.githubusercontent.com/31949290/156489447-5062e96f-84ab-42c1-98a6-8c855d0643d4.png)

**Comment by rochdev** [comment]
From the above I think we could add a `mongodb.transaction` span that would be the parent of all of these individual operations. Then if any single operation fails it shouldn't appear in the error reporting. The downside of this approach is that these individual spans would no longer be at the top level of the service, so stats wouldn't be calculated for them and they wouldn't appear in the service page.

Do you think that would be an acceptable trade-off? Is there any information we can get about this transaction that would be relevant to set as the resource name of such span?

**Comment by rohit-gohri** [comment]
> Do you think that would be an acceptable trade-off?

That would be pretty great I think, we would also get a high level overview of transactions being done in the service with this.

> Is there any information we can get about this transaction that would be relevant to set as the resource name of such span?

I'm not sure, the session is created at the DB level so we can't use the collection name.  Each session does have an id, but that is probably not a good resource name.

**Comment by rochdev** [comment]
> Each session does have an id, but that is probably not a good resource name.

Yes it should be something that can group similar transactions together. The main issue if that we really need something to use as the resource name, otherwise it wouldn't quite make sense to create the span. Is there anything happening maybe during the transaction that could be the resource name?

**Comment by rohit-gohri** [comment]
We could use the function name that is passed to `withTransaction` but that could be an arrow fn with no name. 

> Is there anything happening maybe during the transaction that could be the resource name?

Lots of queries/updates to the DB and all are linked using the `session`. A join of all those queries (could get really large)? Then it will change if we add/remove any query from the transaction, kind of making it unique.

**Comment by rohit-gohri** [comment]
Is there a way we could do this in userland? (create a parent span)

**Comment by rochdev** [comment]
> Is there a way we could do this in userland? (create a parent span)

I didn't consider that but it would definitely be an option. You could just wrap `withTransaction` with something like this:

```js
await session.withTransaction(tracer.wrap('mongodb.transaction', async () => {
  return somePromise
}));
```
