### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by havenchyk** [DataDog/dd-trace-js#1899]
**Describe the bug**
During running jest tests I got

```
TypeError: Cannot read property 'split' of undefined

      at Spec.onException (node_modules/dd-trace/packages/datadog-plugin-jest/src/jest-jasmine2.js:100:39)
      at process.emit.sharedData.processEmitHook.installedValue [as emit] (../node_modules/@cspotcode/source-map-support/source-map-support.js:613:40)
```

**Environment**

* **Operation system:** Ubuntu
* **Node version:** 14.18.2
* **Tracer version:** 2.3.1
* **Agent version:** probably 7.34.0 ([docker](https://console.cloud.google.com/gcr/images/datadoghq/global/agent@sha256:2ef4ef739b3809872bc8bb959b19c0fc665d239cae306c7adec95e63deb4ab3c/details?tab=info))

**Comment by juan-fernandez** [comment]
hey @havenchyk ! Thanks for reporting this. It seems we didn't cover the case were the error stack is missing. This PR should fix this: https://github.com/DataDog/dd-trace-js/pull/1901. In any case, I'd like to know how this can happen so that I can add a unit test to protect ourselves in the future. Can you tell me more about how this error happened? Was it during a failed test? What happened in this failed test?

**Comment by havenchyk** [comment]
@juan-fernandez thanks for the quick response! 


1. this fail is flaky, it happens from time to time (maybe it's a flaky test, idk)
2. here is a test

```
it("tracks failures", async () => {
      const errorSession = OT.initSessionError("apiKey", "errorSessionId", {
        connect: true,
      });

      await expect(
        openTokHelper.connectSession(errorSession, "errorToken"),
      ).rejects.toBeTruthy();

      expect(trackError).toHaveBeenCalledWith(
        { error: { message: "error", name: "error name" } },
        {
          label: Errors.OT_CONNECT_SESSION,
          sessionId: errorSession.sessionId,
        },
      );
    });
```

**Comment by chris-hinds** [comment]
Hi @juan-fernandez has there been any updates on this? I see that you have a draft PR open with a potential fix.

**Comment by chris-hinds** [comment]
Thanks @juan-fernandez

**Comment by chris-hinds** [comment]
@juan-fernandez when are we likely to see this in an updated package?

**Comment by juan-fernandez** [comment]
hey @chris-hinds ! There are a couple of things we want to get merged before releasing, but it should happen during this week. I'll let you know 😄
