### ISSUE TITLE
Making a Axios Request with a httpsAgent Breaks Tracing

### ISSUE THREAD

**Issue by devinlynch** [DataDog/dd-trace-js#1900]
**Describe the bug**
We are seeing an issue where traces will not be sent to the Datadog Agent for endpoints that perform an Axios request while setting "httpsAgent" on the request config.  We have an endpoint which makes an external call through a proxy and this endpoint is not being traced in Datadog.   We are using a library called tunnel (https://www.npmjs.com/package/tunnel) to configure the proxy.  

I have pushed an example app which reproduces the issue here: https://github.com/devinlynch/node-datadog-proxy-issue.   One endpoint (http://localhost:3000/ ) makes a web request to Google through an API proxy, and the other (http://localhost:3000/noProxy) makes a web request to Google without an API proxy.   You will notice that the "/" endpoint will not be traced in Datadog.   Upon enabling debug logging, it looks like traces are not being sent and therefore I am assuming it is something to do with the span not getting completed.

This seems to be an issue with the http DD plugin.   When we disable the "http" plugin, traces for the endpoint go to Datadog.

Code: https://github.com/devinlynch/node-datadog-proxy-issue/blob/main/index.js

**Environment**
Local

* **Operation system:**
Mac

* **Node version:**
v14.19.0

* **Tracer version:**
2.2.1

* **Agent version:**
latest

**Comment by edeesis** [comment]
Affects 1.1.2 as well from my testing.
