### ISSUE TITLE
Logs/traces correlation missing since v2.2.1

### ISSUE THREAD

**Issue by eldonzo** [DataDog/dd-trace-js#1908]
Hi, I recently updated the library from version 2.0.0 to the latest 2.3.1 and I noticed on Datadog that the correlation between logs and traces is missing since the update.

I tried all the previous releases in between and I found it works with 2.2.0 and seems to be broken starting from 2.2.1.

I'm using Bunyan for logging (wrapped inside a custom class, I don't know if could be relevant).

The environment is AWS t3a.medium instance with Linux and node 12.20.2, the agent version is 7.30.0

**Comment by bengl** [comment]
@eldonzo The log library instrumentation code was rewritten in 2.2.1, so it's certainly possible that something was introduced there.

I've used this file here to attempt to reproduce:

```
process.env.DD_LOGS_INJECTION = 'true'
require('dd-trace/init')
const { execSync } = require('child_process')
const bunyan = require('bunyan')
const http = require('http')
const log = bunyan.createLogger({name: "myapp"})

const server = http.createServer((req, res) => {
  log.info({ some: 'data' })
  res.end()
}).listen(0, () => {
  console.log(`http://localhost:${server.address().port}/`)
})
```

Hitting that server with `curl` or a web browser produces logs with the `dd` property and the trace data inside it. like this: 

```
{"dd":{"trace_id":"7565679098164090293","span_id":"7565679098164090293","service":"test","version":"1.0.0"},"name":"myapp","hostname":"bengl-computer","pid":209767,"level":30,"some":"data","msg":"","time":"2022-03-14T18:48:56.121Z","v":0}
```

Do you see the `dd` property in your JSON output? If not, could you provide a full-but-minimal reproduction case?

**Comment by eldonzo** [comment]
@bengl I think I found the issue trying to write a simple reproduction case: I was including bunyan before dd-trace, and that worked nice before 2.2.1, while now it seems it's required for dd-trace to be included before bunyan initialization in order to work.

That's not a problem, I can change the inclusion order, so we can consider this case closed, thanks 🙂

**Comment by shun-yamazaki** [comment]
@bengl 
I've rewritten your reproduce code a bit and the problem has reproduced.(Initializing winston before dd-trace)
Since my application uses winston instead of bunyan, I replaced bunyan in the reproduction code with winston, but the result was the same for bunyan.

```js
process.env.DD_LOGS_INJECTION = 'true'
const winston = require('winston')
require('dd-trace/init')
const { execSync } = require('child_process')
const http = require('http')
const log = winston.createLogger({name: "myapp"})

const server = http.createServer((req, res) => {
  log.info({ some: 'data' })
  res.end()
}).listen(0, () => {
  console.log(`http://localhost:${server.address().port}/`)
})
```

As reported above, the correlation between logs and traces is missing from 2.2.1 to 2.3.1, but it reappeared in 2.4.0.
I looked at the release notes but didn't know which changes were affecting them.

Is it not supposed to initialize logger before dd-trace?
I'm wondering if my application code should be modified to initialize dd-trace before logger.

**Comment by rochdev** [comment]
The tracer definitely needs to be initialized before the logger is imported. We're reworking the plugin system right now, and since we don't explicitly support importing instrumented libraries before the tracer, the result is undefined and can change seemingly randomly between versions.

**Comment by shun-yamazaki** [comment]
@rochdev 
Thanks. I will consider changing my application.

**Comment by BridgeAR** [comment]
<s>Reopening. This is definitely an issue.</s>

I will actually create a new issue for the lazy logger init @ab-pm. Please always open new issues :) That helps to separate the topics.
