### ISSUE TITLE
blocklist with NestJS does not work

### ISSUE THREAD

**Issue by cabrinoob** [DataDog/dd-trace-js#1928]
I'am using dd-trace 2.4.0 to instrument a NestJS 8 service in typescript. I'd like to ignore the /api/ping resource of it, and to do this I'am using the blocklist config param but it does not work.

I tried the same on a classic NodeJS service (in javascript)

To reproduce this behavior, you can create a new NestJS project with a simple @Get route on /api/ping that returns "pong" for instance, and then, add a **tracer.ts** file like this : 

```
import tracer from 'dd-trace';

tracer.init({
    runtimeMetrics: true,
    logInjection: true,
});

tracer.use('express', {
    blocklist: ['/api/ping']
});

export default tracer;
```
then, in the **main.ts** file I import the tracer like this : 

```
import './tracer';
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(3000);
}
bootstrap();

```
As you can see, the tracer is the first module imported. I tried to replace **tracer.use('express')** by **tracer.use('http')** but with no effect : "/api/ping" resource continues to be captured by the APM.

![image](https://user-images.githubusercontent.com/5182775/159943459-2057afe4-2e1a-4a7b-aefc-9d608269291b.png)

Thank you for your help

**Comment by chklauser** [comment]
I'm not using NestJS, but express directly and I'm observing the same behavior with versions 2.4.0 and 2.4.2. Neither `blocklist` nor `allowlist` seem to have any effect.

**Comment by rochdev** [comment]
Are you getting only metrics or are you also seeing traces for these endpoints?

**Comment by chklauser** [comment]
I'm seeing traces for the blocked endpoints (not just in the agent; they also get exported to datadog itself)

I created [a small reproduction repository](https://github.com/chklauser/repro-dd-trace-js-express-esm) with just `trace-dd 2.4.2` and `express 4.17.3`. 

I would expect requests to `/health` be ignored (based on the express plugin blocklist), but they get traced. Even when I set allowlist to something nonsensical, I still get traces for all requests.

**Comment by rochdev** [comment]
@chklauser There is a bug right now where there can be conflicts between the `http` and `express` plugins. Does it work if you configure the `blocklist` option on `http` instead of `express`? I tried it locally and it seems to resolve it for me at least with the reproduction you provided.

**Comment by cabrinoob** [comment]
I also tried with `http` as mentioned in my original post, but I still have the pb. The version of NestJS I'am currently using is embedding Express v4.17.1 (don't know if it helps)

**Comment by rochdev** [comment]
@cabrinoob Can you try with the latest version of dd-trace? We have rewritten these plugins with a new plugin system which might fix configuration issues.

**Comment by cabrinoob** [comment]
Ok, I'll try. thank you
