### ISSUE TITLE
graphql plugin of dd-trace consumes lots of cpu

### ISSUE THREAD

**Issue by mohit61** [DataDog/dd-trace-js#1943]
**Graphql plugin consumes lots of cpu**

 I am using graphql plugin of dd-trace, and on cpu profiling found out that its consuming atleast 10% of cpu, 8.1% of cpu is consumed by the `visit` function of graphql which is being triggered by the plugin, is there any solution to fix this? 

* **Operation system: MacOS**
* **Node version: 14.15.1**
* **Tracer version: 1.6.0**

**Comment by rochdev** [comment]
Can you share the profile and the code that has the added overhead? If it's not something you can share publicly, I would recommend opening a [support](https://www.datadoghq.com/support/) ticket.

**Comment by tlhunter** [comment]
It looks like this issue is stale so I'll close it for now. @mohit61 feel free to reopen and share the information Roch requested if it's still relevent!
