### ISSUE TITLE
dd-trace produces errors when testing a React ErrorBoundary with jest

### ISSUE THREAD

**Issue by sokki** [DataDog/dd-trace-js#1945]
**Describe the bug**

Example: https://github.com/sokki/dd-trace-error-boundary or http://gitpod.io/#https://github.com/sokki/dd-trace-error-boundary

[ErrorBoundaries](https://reactjs.org/docs/error-boundaries.html) are supposed to catch errors in child components (`yarn test`).
When we add dd-trace (`yarn test:dd`), errors get logged to the console. That is an issue for us since we make our tests fail when we detect a `console.error`.

I was able to track this down to this code in `packages/datadog-plugin-jest/src/jest-environment.js`:
```
      await new Promise((resolve) => {
        tracer._exporter._writer.flush(resolve)
      })
```

Delaying teardown like this seems to mess with jest' teardown. I was able to fix this by running the flush after jest' teardown. But I'm not sure if this has unwanted side-effects:
```
return teardown
        .apply(this, arguments)
        .then(() => new Promise((resolve) => tracer._exporter._writer.flush(resolve)))
```

**Environment**

* **Operation system:** macOS + Linux
* **Node version:** 10-16
* **Tracer version:** 2.4.0
* **Agent version:** None

**Comment by juan-fernandez** [comment]
@sokki thanks for this! #1965 has just been merged and will soon be released :)
