### ISSUE TITLE
using docblock `@jest-environment jsdom` skips dd-trace

### ISSUE THREAD

**Issue by sokki** [DataDog/dd-trace-js#1946]
**Describe the bug**

Example: https://github.com/sokki/dd-trace-jest-environment-docblock or http://gitpod.io/#https://github.com/sokki/dd-trace-jest-environment-docblock

When following the [guide to trace jest tests](https://docs.datadoghq.com/continuous_integration/setup_tests/javascript/?tab=jest#instrument-your-tests), tests that specify an environment via [docblock](https://jestjs.io/docs/configuration#testenvironment-string) are not traced by dd-trace. Since it skips these tests silently it took us a while to figure out why some tests are missing in DataDog. It would be nice if this would be mentioned in the docs.

We solved it by injecting dd-trace via `node -r dd-trace/ci/jest/env  ./node_modules/.bin/jest`. 

**Environment**

* **Operation system:** any
* **Node version:** any
* **Tracer version:** 2.4.0
* **Agent version:** none

**Comment by juan-fernandez** [comment]
that's a great catch. Does this not work if you specify a path to the custom environment including the initialisation of `dd-trace`? 

They suggest this in the docs:
```
/**
 * @jest-environment ./src/test/my-custom-environment
 */
```

In any case, a documentation section makes sense for sure

**Comment by sokki** [comment]
Yes, that works as well. But it would leak implementation details of the concern 'ci test visibility' into every spec file, which I want to avoid.

Injection via node options seems to work well and also fits better in our setup. As a nice side effect it brings flexibility for dd-trace to plug into any part of jest.

**Comment by juan-fernandez** [comment]
> Yes, that works as well. But it would leak implementation details of the concern 'ci test visibility' into every spec file, which I want to avoid.

yeah, agreed. I was just curious about whether it worked. It's definitely not the way to go. 

> Injection via node options seems to work well and also fits better in our setup. As a nice side effect it brings flexibility for dd-trace to plug into any part of jest.

That's great, because we'll most likely update the documentation soon to recommend just this way of instrumenting. We actually mention it in https://github.com/DataDog/dd-trace-js/pull/1948

**Comment by juan-fernandez** [comment]
hey @sokki, we now recommend using `NODE_OPTIONS=-r dd-trace/ci/init`: https://docs.datadoghq.com/continuous_integration/setup_tests/javascript/?tabs=onpremisesciproviderdatadogagent#instrument-your-tests, which should also solve your issues. 

I'm closing this issue, but feel free to reopen if I'm wrong 😄
