### ISSUE TITLE
http plugin mark all `http.request` spans as error

### ISSUE THREAD

**Issue by Grmiade** [DataDog/dd-trace-js#1953]
**Describe the bug**
When our service receives an http response with a 200 status code. The span is marked as an error.
We have this issue since we upgraded to the 2.4.1 version, for all services and each `http.request` spans.

<img width="1050" alt="Screenshot 2022-03-31 at 10 20 19" src="https://user-images.githubusercontent.com/11244106/161010680-dc2f771b-2f94-436c-8b65-5b5a9c4dc336.png">

**Environment**
* **Node version:** 17.8.0
* **Tracer version:** 2.4.1

**Comment by jakst** [comment]
We're also seeing this from the v2.4.1 upgrade (we came from v2.2.0)

**Comment by rochdev** [comment]
We did made a few changes to the `http` integration in that version, but I can't find anything obvious that would cause this and was unable to reproduce this locally. Can you share a reproduction snippet?

**Comment by iainmcgin** [comment]
We (Gusto) were just impacted by this too - upgrading from 2.4.0 to 2.4.1 in our graphql gateway service resulted in all outgoing POST requests from our graphql gateway service as errors. After rolling back to 2.4.0, the errors subsided. GET requests were unaffected.

<img width="782" alt="Screen Shot 2022-03-31 at 11 45 19 AM" src="https://user-images.githubusercontent.com/309153/161127502-b298919d-213a-4c62-82f2-97060ec6ae04.png">

**Comment by iainmcgin** [comment]
Our graphql gateway is built using apollo-server, and the requests occur within the context of a [RemoteGraphQLDataSource](https://cs.github.com/apollographql/federation/blob/3651a853e3a81b7e2ad2cec8e1bcd1f7a59acb2e/gateway-js/src/datasources/RemoteGraphQLDataSource.ts#L21). I don't think we've customized the fetcher, and it looks like the default implementation uses [make-fetch-happen](https://www.npmjs.com/package/make-fetch-happen), and from our lock file, looks like v8.0.14. I hope that helps!

**Comment by Grmiade** [comment]
@rochdev It seems the problem comes from the [instrumentation](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-instrumentations/src/http/client.js#L89).
The `close` event is always called during a successful request. So this [line](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-http/src/client.js#L71) will be executed since no third parameter is provided [here](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-instrumentations/src/http/client.js#L90). What do you think?

See https://nodejs.org/api/http.html#:~:text=In%20a%20successful,%27close%27
> In a successful request, the following events will be emitted in the following order:
> - 'socket'
> - 'response'
>   - 'data' any number of times, on the res object ('data' will not be emitted at all if the response body is empty, for instance, in most redirects)
>   - 'end' on the res object
> - 'close'

**Comment by mb21** [comment]
We also have this after upgrading from 2.2.0 to 2.4.1 and we're using node-fetch 2.6.7 on node.js 16.13.

**Comment by rochdev** [comment]
@Grmiade That's definitely it. I'll figure out a test and release a fix as soon as possible.

**Comment by tommoor** [comment]
I'm still seeing this problem with the latest version `3.9.3` – is it possible something regressed here? 🤔
