### ISSUE TITLE
How does v1.0+ enable analytics for all like below v1.0 does?

### ISSUE THREAD

**Issue by ayokota** [DataDog/dd-trace-js#1957]
Hello, I am upgrading from v0.19, and the way I initializing the tracer is

tracer.init({
analytics: true, **<---------------------- this**
env: process.env.STAGE,
logInjection: true,
plugins: true,
runtimeMetrics: true,
service: 'service',
});

after upgrading to v2.4 (or anything above 1.0), this option is gone, and no where to be found. How does one enable analytics globally like the way it is below v0.19?

**Comment by rochdev** [comment]
This is no longer needed and the same metrics you had before should still work even without the option. What metrics specifically are missing?

**Comment by ayokota** [comment]
@rochdev thanks for replying! I wasn't sure what this `analytics: true` do exactly. Sounds like it's safe to interpret it as "new version enables this by default?"

**Comment by rochdev** [comment]
Yes, assuming you were only using the global setting on `tracer.init()` then the default behaviour is now that the new equivalent feature is enabled by default.

**Comment by ayokota** [comment]
great thank you!!
