### ISSUE TITLE
Plugin for Opensearch

### ISSUE THREAD

**Issue by ronald-sz** [DataDog/dd-trace-js#1966]
Hi, 

it would be great to have a plugin for Opensearch: https://github.com/opensearch-project/OpenSearch

Is this something which is already planned?

Best,
Ronald

**Comment by khanayan123** [comment]
No not currently, it's not something we're likely to get to any time soon.

**Comment by ronald-sz** [comment]
Thanks for reopening this. 

I think support for Opensearch is important as AWS moved from Elasticsearch to Opensearch. Therefore every user of AWS Opensearch Service (formerly Elasticsearch Service) will not be able to benefit from the current dd-trace Elasticsearch plugin. 

I also guess, as the Opensearch client is a fork of the Elasticsearch client, it should be relatively easy to create an Opensearch plugin based on the existing Elasticsearch plugin.

**Comment by zomgbre** [comment]
+1 for Opensearch!!!!

**Comment by gleb9gurbatov** [comment]
+1 for OpenSearch, we really need it ^-^
