### ISSUE TITLE
[NextJS] tracing in react component does not work

### ISSUE THREAD

**Issue by mklebe** [DataDog/dd-trace-js#1980]
**Describe the bug**
*Background*: I am using NextJS with SSR. I observed a high initial server response time. When digging deeper into the APM I found that the for some requests the server side processing, takes a lot of time:
![image](https://user-images.githubusercontent.com/8981536/162191151-83256b91-5057-4c7d-95ef-cc72a7751e65.png)
To dig deeper into it I would love to figure out which component is expensive.

What I did so far:
* adding NODE_OPTIONS='-r dd-trace/init' to the start script in the package.json
* added trace marker in the rendered react component

Expected behaviour:
* no error

Actual behaviour:
error - ../node_modules/@datadog/pprof/node_modules/source-map/lib/read-wasm.js:20:0
Module not found: Can't resolve 'fs'

Import trace for requested module:
../node_modules/@datadog/pprof/node_modules/source-map/lib/source-map-consumer.js
../node_modules/@datadog/pprof/node_modules/source-map/source-map.js
../node_modules/@datadog/pprof/out/src/sourcemapper/sourcemapper.js
../node_modules/@datadog/pprof/out/src/index.js
../node_modules/dd-trace/packages/dd-trace/src/profiling/profilers/cpu.js
../node_modules/dd-trace/packages/dd-trace/src/profiling/index.js
../node_modules/dd-trace/packages/dd-trace/src/profiler.js
../node_modules/dd-trace/packages/dd-trace/src/proxy.js
../node_modules/dd-trace/packages/dd-trace/index.js
../node_modules/dd-trace/index.js
./src/pages/l/[cattype]/[...catid].tsx

https://nextjs.org/docs/messages/module-not-found

**Environment**

* **Operation system:**
* Linux 5.4.0-107-generic
* **Node version:**
* v16.13.1
* **Tracer version:**
* 1.6.0.
* **Agent version:**

**Comment by rochdev** [comment]
Are you loading dd-trace in the browser? The `fs` module would only be available in Node and not in the browser (which we don't support).

**Comment by mklebe** [comment]
This occurs both, on the server and in the client. Not working in the client is something I absolutely understand, on the server it'd be great to work.

**Comment by mklebe** [comment]
`import React from 'react';
import tracer from 'dd-trace';

const Page: React.FunctionComponent = () => {
  tracer.trace('rendered server and client side', () => {
    console.log('Sample code');
  });
  return (<h1>My headline</h1>);
};

export default Page;`

**Comment by rochdev** [comment]
How do I run the above? It also doesn't look at all like something that would run on the server as it's a React component.

**Comment by mklebe** [comment]
This runs in a NextJS application as a page. And the document the server responds with contains the HTML 'My Headline'. The stack trace I posted, I got from the console I started the server from. So I would assume the code is executed on the server.

It seems to me to have to do something with the react tree. Because a sample code like this runs without error:
`
import tracer from 'dd-trace';
import React from 'react';

const Page: React.FunctionComponent = () => <h1>My headline</h1>;

export const getServerSideProps = () => {
  tracer.trace('runs.server.side.only', () => {
    console.log('sample code');
  });

  return {
    props: {},
  };
};

export default Page;
`

**Comment by mklebe** [comment]
Can be closed, this is not caused be Datadog. The react component is rendered both, on server and on the client. But due to code elimination everything not available on the client is left out. The reference to 'fs' is left out as well. This is pointed out in this issue [#vercel/nex](https://github.com/vercel/next.js/issues/7755#issue-464463866).

The webpack config adjustments supressed the error regarding the reference to 'fs' but opened up new reference errors:
* Module not found: Can't resolve 'graphql/language/visitor'
* Module not found: Can't resolve 'graphql/language/printer'
* Module not found: Can't resolve 'graphql/utilities'
* Module not found: Can't resolve 'dns'
* Module not found: Can't resolve 'dgram'
* Module not found: Can't resolve 'net'
* Module not found: Can't resolve 'v8'
* Module not found: Can't resolve 'child_process'
* Module not found: Can't resolve 'module'
* Module not found: Can't resolve 'async_hooks'

So: closed, doesn't work for my use case :-(

**Comment by rochdev** [comment]
Does that prevent you from using dd-trace on the server side as well? If that's the case then it's definitely something we should address.
