### ISSUE TITLE
Supporting multiple messages in SQS

### ISSUE THREAD

**Issue by stephen-harris** [DataDog/dd-trace-js#1986]
Currently if you have a AWS lambda consumer of an SQS queue, the aws-sdk plug-in uses the [first message](https://github.com/DataDog/dd-trace-js/blob/fe6e1e1394e6d9d3e70e285a11daf587e66f4ee9/packages/datadog-plugin-aws-sdk/src/services/sqs.js#L53) to set the trace ID.

If there are multiple messages in the event, each with their own trace ID, these get ignored and instead they appear under the trace associated with the first message.

In the lambda function code I've tried overriding the trace ID inside the loop of event records:

```
const consumer = async (event) => {
  console.log(event.Records.length + " records")
  
  for (const record of event.Records) {
    const childOf = tracer.extract('text_map', record.messageAttributes._datadog.stringValue)
    const span = tracer.startSpan('sqs.receive', { childOf })
    await tracer.scope().activate(span)
    console.log(record.messageAttributes._datadog.stringValue)
    ...
    span.finish();
  }
};
```
This kind of works: the spans for each message get corrected under the trace ID associated with the messag. But there's a massive gap where I'd expect the SQS span to be (except for the first message's trace), and - more importantly - all the _logging_ is tied to the trace of the first message.

What's the recommended way of tracing multiple messages within a Lambda consuming from SQS? Would I need to disable auto injection of trace ID into the logs and manage that myself?

**Comment by rochdev** [comment]
> What's the recommended way of tracing multiple messages within a Lambda consuming from SQS? Would I need to disable auto injection of trace ID into the logs and manage that myself?

That would be the recommended approach since batches are not supported by auto-instrumentation. However, I would recommend using `tracer.trace()` instead since it will make that easier as it automatically handles errors and finishing the span after the promise is resolved.

```js
for (const record of event.Records) {
  const childOf = tracer.extract('text_map', record.messageAttributes._datadog.stringValue)
  await tracer.trace('sqs.receive', { childOf }, span => {
    // the message handler should run here
    // if it returns a promise, the span will be finished when it resolves
    ...
  })
  console.log(record.messageAttributes._datadog.stringValue)
}
```

**Comment by stephen-harris** [comment]
Thanks @rochdev - that's a much neater approach. For anyone else who finds this, you will need to parse the string into JSON before passing it to `extract`:

```
const childOf = tracer.extract('text_map', JSON.parse(record.messageAttributes._datadog.stringValue))
```

There are two:

- There's still a gap where the SQS span should be (except for the first message's trace) - which is fine
- The log messages now have the correct trace ID but despite this in DataDog the logs appear under the first message's trace. It appears DataDog is associating the first trace with the lambda _invocation_ and then pulling in logs associated with that invocation. Using DD's free search though you can still pull in logs for a particular trace ID
