### ISSUE TITLE
Issue with the fastify instrumentation

### ISSUE THREAD

**Issue by fxalgrain** [DataDog/dd-trace-js#2047]
**Expected behaviour**
Importing dd-trace should have no side effect 
For exemple, GET /_ready should short

**Actual behaviour**
When importing dd-trace, GET /_ready will not return a response, and client is waiting forever (or will time out)

**Steps to reproduce**

_plugin.ts_
```ts
const plugin: FastifyPluginAsync = async fastify => {
  fastify.addHook("onRequest", async (request: FastifyRequest) => {
    request.httpContext = {};
  });
};

export const httpContextPlugin = fp(plugin, { fastify: ">=3.15.0", name: "http-context-plugin" });
```
When I register this plugin via `await fastify.register(httpContextPlugin);`, I get the timeout issue.

**Environment**

* **Operation system:**
* **Node.js version:** 16.4.2
* **Tracer version:** 2.7.0
* **Agent version:** unknown 
* **Relevant library versions:**
fasitfy: 3.27.2
fastify-plugin: 3.0.1

**Comment by bengl** [comment]
Hi @fxalgrain and thanks for the report! As far as I can tell, this should be fixed by #2049. If you're able to test branches in your setup, feel free to give it a try. Otherwise, it will likely make its way to a release in the next couple of days.

**Comment by fxalgrain** [comment]
HI @bengl

I can confirm you that this PR fix my issue.  Thanks you!

We will wait the next release to update our application

**Comment by bengl** [comment]
v2.7.1 has been released which includes this fix.
