### ISSUE TITLE
Koa: `koa.request` traces are not visible after upgrading to 2.7.0

### ISSUE THREAD

**Issue by jinroh** [DataDog/dd-trace-js#2048]
**Expected behaviour**
I would have expected that upgrading from 2.5.0 to 2.7.0 as minor to not have direct impact on our ingested traces.

**Actual behaviour**
After upgrading, the `koa.request` are not visible anymore and `koa.middlewares` traces start showing up.
The changelog does not warn about the changes made on koa by #2033 

**Steps to reproduce**
Upgrade from 2.5.0 to 2.7.0

**Environment**

* **Operation system:**
* **Node.js version:** 12.22.1
* **Tracer version:**: 2.7.0
* **Agent version:** 7.35.1
* **Relevant library versions:** koa-router 7.4.0

Are we missing some changes that needs to be done to upgrade to 2.7.0 and keep the `koa.request` traces ?

**Comment by bengl** [comment]
@jinroh Hello! Thanks for reporting this.

I've tried the following example with both 2.5.0 and 2.7.0, and in either case, the traces produced have `koa.request` as the top level span in the trace, so I can't reproduce the issue you're seeing.

```js
'use strict';
require('dd-trace').init();
const Koa = require('koa');
const Router = require('koa-router');

const app = new Koa();
const router = new Router();

router.get('/', (ctx, next) => {
  ctx.body = 'Hello, World';
});

app.use(router.routes());

app.listen(3000);
```

Could you provide a small app that reproduces the issue?

**Comment by jinroh** [comment]
I think I found the culprit. Just add disable the `http` tracing:

```js
'use strict';
const ddtracer = require('dd-trace').init()
ddtracer.use('http', { enabled: false })
ddtracer.use('koa', {
  hooks: {
    request: (span, req) => {
      console.log('you there ?')
    }
  }
})

const Koa = require('koa');
const Router = require('koa-router');

const app = new Koa();
const router = new Router();

router.get('/', (ctx, next) => {
  ctx.body = 'Hello, World';
});

app.use(router.routes());

app.listen(3000);
```

**Comment by jinroh** [comment]
I think I found the culprit. Just add disable the `http` tracing:

```js
'use strict';
const ddtracer = require('dd-trace').init()
ddtracer.use('http', { enabled: false })
ddtracer.use('koa', {
  hooks: {
    request: (span, req) => {
      console.log('you there ?')
    }
  }
})

const Koa = require('koa');
const Router = require('koa-router');

const app = new Koa();
const router = new Router();

router.get('/', (ctx, next) => {
  ctx.body = 'Hello, World';
});

app.use(router.routes());

app.listen(3000);
```

**Comment by bengl** [comment]
@jinroh Great, thanks! I'll have a look at this now.

**Comment by bengl** [comment]
@jinroh The `koa.request` spans depend on the `http` plugin being enabled. Can you try with the `http` plugin enabled? We'll work on making the documentation and changelog clearer on this.

**Comment by jinroh** [comment]
For us it's a breaking change because we had te deactivate http tracing from the beginning[1]. There are many possible solution, but would it be possible to separate HTTP "client request" tracing from "server request" tracing ? It would probably make things clearer also in terms of API too.

--
[1] This is an unrelated issue, but the http tracing does not only instrument, but also modify the headers of our client requests; which for us was not acceptable.

**Comment by bengl** [comment]
Yes. You can configure them separately via the `client` and `server` properties of the config for the plugin. You can disable just the client instrumentation if you want (https://datadoghq.dev/dd-trace-js/interfaces/plugins.http.html#client). Alternatively, you can disable propagation, which is what modifies the headers (https://datadoghq.dev/dd-trace-js/interfaces/plugins.http.html#propagationblocklist).

For example, to completely disable HTTP client instrumentation, you can do:

```js
tracer.use('http', { client: false });
```

**Comment by jinroh** [comment]
@bengl Oh sorry I missed that. Thanks for the tip ;)

**Comment by jinroh** [comment]
Sorry I closed the issue a bit too quickly. After upgrading and setting deactivating the HTTP client instrumentation, I now receive the `koa.request` traces. 

However I have another regression now: all requests are marked with the same resource name with the top level router. I think you should be able to reproduce with this kind of env:

```
const ddtracer = require('dd-trace').init()
ddtracer.use('http', { client: false })
ddtracer.use('koa', {
  hooks: {
    request: (span, req) => {
      console.log('you there ?')
    }
  }
})

const Koa = require('koa');
const Router = require('koa-router');

const app = new Koa();
const router1 = new Router();
const router2 = new Router();

router2.get('/plop', (ctx, next) => {
  ctx.body = 'Hello, World';
});

router1.use(router2.routes())

app.use(router.routes());

app.listen(3000);
```

**Comment by rochdev** [comment]
@jinroh Just tried the above and I see the correct route.

**Comment by fr-xiaobin-xu** [comment]
> @jinroh The `koa.request` spans depend on the `http` plugin being enabled. Can you try with the `http` plugin enabled? We'll work on making the documentation and changelog clearer on this.

Hi @jinroh , do you mean that if user wants to use koa plugin, users must also use http plugin? My dd-trace version is "dd-trace": "0.22.1", I've met a strange issue:
trace init() option: plugin: false
trace use() plugins: graphql mysql redis koa (I've not used http plugin)
In my local env, datadog apm service will display all four plugins service. In koa service, the operation name for traces is "koa.request" and all works well. Besides, there is also "service:abc" in trace init() option, which will let datadog apm service list a service that having traces "koa.middleware"
However, in another test env, graphql/mysql/redis can be displayed. But koa service and the above service "abc" is not listed. It seems that this env doesn't recognize koa related request.
I've also try this:
const koaLogger = datadog.wrap('koa.test', logger);
...
app.use(koaLogger);

koa service still isn't displayed. Do you know the possible reason? Thanks!
