### ISSUE TITLE
KafkaJS: Consumer not reading headers into current context after upgrading to `2.7.0`

### ISSUE THREAD

**Issue by itsAmr** [DataDog/dd-trace-js#2051]
**Expected behaviour**

After consuming a message with datadog headers, the active tracer scope `tracer.scope().active()?.context()` should be populated with the correct trace information.

On `2.6.0`:

```
await consumer.run({
  eachMessage: async ({ topic, partition, message }) => {
    console.log(message.headers);
    console.log(`In the consumer - trace id is: \x1b[31m ${tracer.scope().active()?.context().toTraceId()} \x1b[0m`)
  }
})
```

![Screen Shot 2022-05-11 at 8 02 38 PM](https://user-images.githubusercontent.com/10677996/167966486-6c661a4f-13a4-45b6-a574-1fe6982a400d.png)

**Actual behaviour**

On `2.7.0`:

![Screen Shot 2022-05-11 at 8 03 21 PM](https://user-images.githubusercontent.com/10677996/167966553-6bc14ce0-34e9-4d4e-839c-7da3e998a4ad.png)

**Steps to reproduce**

producer:
```
const tracer = require('dd-trace').init(); // instrument producer.send method with dd headers.

// initialize Kafka producer
const kafka = new Kafka({
  clientId: '...',
  brokers: ['localhost:9092'],
})

const producer = kafka.producer();

await producer.send({
  topic: 'test-topic',
  messages: [
    { key: "1", value: msg },
  ],
})
```

consumer:
```
const tracer = require('dd-trace').init(); // instrument consumer.run method with dd headers. 

const kafka = new Kafka({
    clientId: '...',
    brokers: ['localhost:9092'],
})

const consumer = kafka.consumer({ groupId: '...' });

await consumer.subscribe({ topic: 'test-topic', fromBeginning: true })
await consumer.connect()

await consumer.run({
  eachMessage: async ({ topic, partition, message }) => {
    console.log(message.headers);
    console.log(`In the consumer - trace id is: \x1b[31m ${tracer.scope().active()?.context().toTraceId()} \x1b[0m`)
  },
});
```

**Environment**

* **Operation system:** macOS Monterey
* **Node.js version:** 17.8.0
* **Tracer version:** 2.7.0
* **Agent version:**
* **Relevant library versions:**

**Comment by bengl** [comment]
I've tried with your example, adding the `require('kafkajs')` line _after_ initializing the tracer in both the consumer and producer, and everything works correctly for me.

Can you verify that You're doing your `requite('kafkajs')` _after_ doing the `require('dd-trace').init()`?

**Comment by itsAmr** [comment]
Hey @bengl you are correct, kafkajs was imported _before_ initializing dd-trace.

Behaviour changed from previous minor version but documentation clearly states
> The Node.js tracing library needs to be imported and initialized before any other module.

So closing this issue, my mistake. Thanks Bryan!

**Comment by bengl** [comment]
No worries!
