### ISSUE TITLE
TracerOptions type declaration is missing tracing property

### ISSUE THREAD

**Issue by ab-pm** [DataDog/dd-trace-js#2063]
The `tracing` option that can be passed to `Tracer.init()` since #1780, is missing from the `TracerOptions` interface in dd-trace@2.7.1

**Comment by rochdev** [comment]
Going to close this since this option was never exposed programmatically and only through an environment variable.

**Comment by ab-pm** [comment]
Oh, you're right, I confused the `options` with the `config` that was built from them.

However, is there really no longer a way with 2.0 to disable tracing programmatically? Would calling `ddTracer.init()` inside an `if` statement work? I've only seen in [the migration guide](https://github.com/DataDog/dd-trace-js/blob/master/MIGRATING.md#configuration) *that* the options were removed, but not why (or why using environment variables would be more beneficial)

**Comment by rochdev** [comment]
> However, is there really no longer a way with 2.0 to disable tracing programmatically?

Correct.

> Would calling ddTracer.init() inside an if statement work?

That would work, although the condition would still need something to be given to the process like an environment variable.

> I've only seen in [the migration guide](https://github.com/DataDog/dd-trace-js/blob/master/MIGRATING.md#configuration) that the options were removed, but not why (or why using environment variables would be more beneficial)

You can find most of the context in #1800.
