### ISSUE TITLE
DoS vulnerability introduced through: dd-trace@2.7.1 › multer@1.4.4 › busboy@0.2.14 › dicer@0.2.5

### ISSUE THREAD

**Issue by mishabruml** [DataDog/dd-trace-js#2067]
https://snyk.io/test/npm/dd-trace/2.7.1
 dd-trace@2.7.1

**Comment by nicolaslt** [comment]
The dependency has been added in [#984](https://github.com/DataDog/dd-trace-js/pull/984), it looks like it might just be a `devDependencies` that has been mistakenly added to `dependencies`?

The only references to `multer` in the codebase are `package.json`, a license file and a test file.

I'll open a PR to propose moving it to `devDependencies`

**Comment by sam-beautypie** [comment]
Multer has been moved: https://github.com/DataDog/dd-trace-js/pull/2076

**Comment by aliwatters** [comment]
Is anyone working on a 2.7.2 release with this change?

We have many services failing `npm audit` due to this at the moment.

**Comment by rochdev** [comment]
@aliwatters We're preparing a release right now. In the meantime, this is a false alarm that can safely be ignored as we are not using `multer` anywhere.

**Comment by rochdev** [comment]
For anyone using an older version, this was put in our dependencies by mistake and we were not using the library at all, so the vulnerability didn't affect dd-trace.

**Comment by AlexBrohshtut** [comment]
Hello @rochdev, @bengl 
I see the [v0.36.4](https://github.com/DataDog/dd-trace-js/releases/tag/v0.36.4) tag with this fix, however, it is not available on [npm](https://www.npmjs.com/package/dd-trace?activeTab=versions). When do you plan to release it?

**Comment by AlexBrohshtut** [comment]
> [`v2.8.0` (release)](https://github.com/DataDog/dd-trace-js/releases/tag/v2.8.0) its in the latest release

Yes, but what about node8-10?

**Comment by rochdev** [comment]
@AlexBrohshtut It's released now in 0.36.5.

**Comment by RichardEustace** [comment]
Hi, 
Is there going to be a patch version of v1.7.x? Is this covered by the Maintenance mode? 

https://docs.datadoghq.com/tracing/setup_overview/compatibility_requirements/nodejs/#maintenance
