### ISSUE TITLE
The example of GraphQL configurations is unavailable 

### ISSUE THREAD

**Issue by sunsern-k** [DataDog/dd-trace-js#2068]
**Expected behaviour**
I'm looking for some examples of Datadog's trace configurations of GraphQL from https://github.com/DataDog/dd-trace-js/blob/master/docs/interfaces/plugins.graphql.html. However, this link is not available. 

**Actual behaviour**
Try to access this https://github.com/DataDog/dd-trace-js/blob/master/docs/interfaces/plugins.graphql.html but it is not available. 

**Steps to reproduce**
Access this document: https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md and click GraphQL which is point to this link: https://github.com/DataDog/dd-trace-js/blob/master/docs/interfaces/plugins.graphql.html and the error is returned

**Comment by rochdev** [comment]
This file is the source for this page: https://datadoghq.dev/dd-trace-js/

Unfortunately it can't be used directly from GitHub but all the links should work in the generated page.

**Comment by sunsern-k** [comment]
Hi @rochdev,

Thank you very much for pointing this out. I'm good with the given link. 

Sunsern

**Comment by zelongc** [comment]
I had a hard time reading the looking for/ reading graphql related plugin. Also that document (https://datadoghq.dev/dd-trace-js/interfaces/plugins.graphql.html) does nothing more than ts type definition.
Is there any plan to add examples...etc for each use case?

**Comment by rochdev** [comment]
@zelongc Do you have something specific in mind? Where do you think would make the most sense for the examples? Should we put them in the API doc, on the website, or in a folder in the repo? Also, what examples are you looking for specifically? We usually recommend to use dd-trace with all the defaults so it shouldn't be common to need extensive configuration.

**Comment by sunsern-k** [comment]
I just spotted a type from the `source`, not sure it can be tracked in the same ticket here. 


> Whether to include the source of the operation within the query as a tag on every span. This may contain sensitive 
> information and **sould** (sunser-k: should it be `should`?) only be enabled if sensitive data is always sent as variables 
> and not in the query text.
