### ISSUE TITLE
Socket hang up error crashing app

### ISSUE THREAD

**Issue by ashish-kadam-myglamm** [DataDog/dd-trace-js#2075]
Hello team, 

Our production app keeps crashing intermittently and the error that we see in the logs has something to do with dd-trace, can you please suggest us something here?
We are on the dd-trace 0.31.1 version and nodejs: 10

This is the error from the logs:
`{"date":"Wed May 25 2022 07:09:08 GMT+0000 (Coordinated Universal Time)","dd":{"env":"prod","service":"prod-service-ms","span_id":"3511004031915050165","trace_id":"7944874997170426354","version":"0.0.0"},"error":{"code":"ECONNRESET"},"exception":true,"level":"error","message":"uncaughtException: socket hang up\nError: socket hang up\n at createHangUpError (_http_client.js:332:15)\n at Socket.socketOnEnd (_http_client.js:435:23)\n at scope.activate (/home/node/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19)\n at Scope._activate (/home/node/app/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:54:14)\n at Scope.activate (/home/node/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)\n at Socket.bound (/home/node/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20)\n at Socket.emit (events.js:203:15)\n at endReadableNT (_stream_readable.js:1145:12)\n at process._tickCallback (internal/process/next_tick.js:63:19)","os":{"loadavg":[0.0654296875,0.17138671875,0.2138671875],"uptime":604999},"process":{"argv":["/usr/local/bin/node","/home/node/app/app.js"],"cwd":"/home/node/app","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"external":21857306,"heapTotal":198500352,"heapUsed":116523224,"rss":275202048},"pid":19,"uid":1000,"version":"v10.24.1"},"stack":"Error: socket hang up\n at createHangUpError (_http_client.js:332:15)\n at Socket.socketOnEnd (_http_client.js:435:23)\n at scope.activate (/home/node/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19)\n at Scope._activate (/home/node/app/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:54:14)\n at Scope.activate (/home/node/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)\n at Socket.bound (/home/node/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20)\n at Socket.emit (events.js:203:15)\n at endReadableNT (_stream_readable.js:1145:12)\n at process._tickCallback (internal/process/next_tick.js:63:19)","trace":[{"column":15,"file":"_http_client.js","function":"createHangUpError","line":332,"method":null,"native":false},{"column":23,"file":"_http_client.js","function":"Socket.socketOnEnd","line":435,"method":"socketOnEnd","native":false},{"column":19,"file":"/home/node/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js","function":"scope.activate","line":54,"method":"activate","native":false},{"column":14,"file":"/home/node/app/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js","function":"Scope._activate","line":54,"method":"_activate","native":false},{"column":19,"file":"/home/node/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js","function":"Scope.activate","line":12,"method":"activate","native":false},{"column":20,"file":"/home/node/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js","function":"Socket.bound","line":53,"method":"bound","native":false},{"column":15,"file":"events.js","function":"Socket.emit","line":203,"method":"emit","native":false},{"column":12,"file":"_stream_readable.js","function":"endReadableNT","line":1145,"method":null,"native":false},{"column":19,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":63,"method":"_tickCallback","native":false}]}`

**Comment by rochdev** [comment]
Does it only happen when dd-trace is enabled? The library tends to show up in most stack traces since it instruments many things, but that doesn't necessarily mean it's the source of the error. If it does only show up with dd-trace, then is this something that you can reproduce in isolation?

**Comment by ashish-kadam-myglamm** [comment]
hey you are right, we removed dd-trace just to check as you rightly mentioned it does show up, but is not the source of the issue, it is some other uncaught exception.
