### ISSUE TITLE
Koa: poluted http.route tag when using middlewares

### ISSUE THREAD

**Issue by jinroh** [DataDog/dd-trace-js#2092]
**Actual behaviour**
After upgrading to 2.7.0 an application using koa and koa-router (tested on both koa-router 7.X and 8.X), the root span tag `http.route` is not properly set.

**Expected behaviour**
No regression.

**Steps to reproduce**
```js
'use strict'
const ddtracer = require('dd-trace').init()
ddtracer.use('http', { client: false })
ddtracer.use('koa', {
  hooks: {
    request: (span, req) => {
      console.log(span._spanContext._tags)
      console.assert(span._spanContext._tags['http.route'] === '/foobar') // Assertion failed => tag is '(.*)'
    }
  }
})

const Koa = require('koa')
const Router = require('koa-router')
const app = new Koa()
const router = new Router()
router.use((ctx, next) => next())
router.get('/foobar', (ctx) => {
  ctx.body = 'Hello, World'
})
app.use(router.routes())
app.listen(3000)
```

^ with this example tested with both koa-router 7 and 8, the http.route tag is `(.*)`.

**Environment**

* **Operation system:**
* **Node.js version:** 12.22.1
* **Tracer version:** 2.8.0 and 2.7.0
* **Agent version:**
* **Relevant library versions:** koa-router 7.X and 8.X

**Comment by rochdev** [comment]
We refactored the plugin recently and it seems that we now check routes in the wrong order. I'm working on a fix right now.

**Comment by sunnywhy** [comment]
not only `koa`, I believe `express` has the same problem. 2.8.0 I always get `/` as the http.route. I changed it back to version 2.4.2 and it works well.

**Comment by rochdev** [comment]
@sunnywhy I tried the same snippet as above but using Express instead of Koa and I'm seeing the correct route. Can you share a reproduction snippet for Express?

**Comment by sunnywhy** [comment]
@rochdev, I used the same snippet as above for `express`, however, I also have an aws API Gateway, so the flow is client -> API gateway -> backend API endpoints(this is the project with dd-trace). It doesn't work in this case, however, a downgrade to 2.4.2 works well.
