### ISSUE TITLE
logs correlation not happening in DataDog after application instrumentation using dd-trace

### ISSUE THREAD

**Issue by ankitatasolvi** [DataDog/dd-trace-js#2106]
Hi,

I have a Nodejs application which is writing logs to DataDog, but even after instrumentation with dd-trace package, logs are not getting correlated without DataDog Agent. 
If I use the DataDog Agent Correlation is working fine.
I have done following setup for instrumentation and using winstons' Http transport for writing logs to DataDog:
const tracer = require('dd-trace').init({
  logInjection: true,
  env:'dev'
});

Is there something I am missing in my configuration?

**Comment by bengl** [comment]
Yes. The Datadog Agent is required to use `dd-trace`, including log correlation. See the documentation here: https://docs.datadoghq.com/tracing/setup_overview/

I'll close this, but please feel free to ask if you require additional information.

**Comment by ankitatasolvi** [comment]
Thanks @bengl , but as per documentation https://docs.datadoghq.com/logs/log_collection/nodejs/?tab=winston30
it's possible to have Agentless logging.

**Comment by bengl** [comment]
@ankitatasolvi Yes, you can have agentless logging by using an HTTP transport for winston sending logs to Datadog's log intake, but you won't be able to get _correlation_ without tracing (i.e. `dd-trace`), and tracing requires a Datadog Agent.

**Comment by ankitatasolvi** [comment]
Thanks @bengl, is it possible to host DataDog Agent on Azure App service for a nodejs application hosted on same app service?

**Comment by bengl** [comment]
@ankitatasolvi I'm not sure about Azure App Service. I know some folks are running it on _separate_ services.

At this point, it's best to contact [Datadog support](https://help.datadoghq.com), who will be better able to work through your use case.
