### ISSUE TITLE
How to set a custom trace_id when starting a new trace?

### ISSUE THREAD

**Issue by acSpock** [DataDog/dd-trace-js#2115]
Apologies this is not an issue, but more of a how to.

We run a job processing system that is two parts; an HTTP layer that accepts jobs requests and then queues them in a redis cluster. The second part is a cluster of worker nodes to process the queue. The HTTP layer and job processing layer are nodejs apps. 

I'm storing the original trace_id that was generated at the HTTP layer in the job process data and i'd like to start a new trace in the worker node using the original tracer_id so I can trace across all job processing events.

In opentrace api there's a couple api's available but the documentation isn't clear on what `carrier` & `format` are.

For example in my fastify controller: 

```
HTTP Service

import { tracer }  from '../../tracer';

  fastify.post(
    '/create-job',
    {},
    async (req, reply) => {

      const traceId = tracer.scope().active()?.context().toTraceId(); //grabs the traceId
      
      cache.createJob({...otherdata, traceId})
   
      reply.send('ok');
    },
  );

```

In another long running processing service

```
import { tracer }  from '../../tracer';

// some queue listener code...
on('new_job', process);

function process(jobData){
   const {traceId, ...otherData} = jobData;

   tracer.trace() <--- have to manually trace but how do I use the trace id or span context from my http service
}

```

There's also trace.inject and extract but it is now clear how they can be used; even after looking through the dd-trace code.

**Comment by rochdev** [comment]
The carrier is any object holding metadata that will be sent to the called service. For example, the carrier for an HTTP request would be the headers object. On the sending side, you would call `tracer.inject(span, 'text_map', headers)` and on the receiving side you would call `const childOf = tracer.extract('text_map', headers)` which could then be passed to the tracer with `tracer.trace('some.name', { childOf }, () => { ... })`.

If I understand the above code properly, it would look something like this for your use case:

```js
fastify.post(
  '/create-job',
  {},
  async (req, reply) => {
    const jobData = { ...otherdata }

    tracer.inject(span, 'text_map', jobData)

    cache.createJob(jobData)

    reply.send('ok')
  }
)

function process(jobData){
  const childOf = tracer.extract('text_map', jobData)

  tracer.trace('job.process', { childOf }, () => {
    // actual processing here
  })
}
```

**Comment by acSpock** [comment]
@rochdev Thanks for the response; appreciate it. Perhaps I should clarify what I meant by long running process. 

The function:

```
function process(jobData){
}
```

is running in a separate node app running in another process, perhaps, in another region in GCP. So extracting anything within the tracer will probably return undefined.

**Comment by rochdev** [comment]
The tracing context will be added to the job data similar to what you were doing in the original post, meaning that if the job data is sent to the next service then it will receive the data and the tracer will be able to extract it on the other end.

**Comment by acSpock** [comment]
Gotcha, thanks. I'll give this a try!
