### ISSUE TITLE
Could I get trace ID in code when i using datadog?

### ISSUE THREAD

**Issue by VeejaLiu** [DataDog/dd-trace-js#2116]
Is there a way for me to get the current traceid in the code so that I can easily query the log in combination with other systems.

Another question is, can I use datadog to set or get custom fields in my code?

**Comment by acSpock** [comment]
export your global tracer object and call:

```
const traceId = tracer.scope().active()?.context().toTraceId(); or .toSpanId()
```

**Comment by VeejaLiu** [comment]
Thank you very much.
