### ISSUE TITLE
Cannot use Jest injectGlobals: false

### ISSUE THREAD

**Issue by brandenbyers** [DataDog/dd-trace-js#2125]
**Expected behaviour**
Tests should run for Datadog CI using `dd-trace/ci/jest/env` when jest.config.js includes `injectGlobals` set to `false`.

**Actual behaviour**
Using a custom `testEnvironment` as instructed in the Datadog CI documentation and a jest.config.js with `injectGlobals` set to `false`, attempting to run using `dd-trace/ci/jest/env` results in the following error:

```
● Test suite failed to run

    No target object provided.

      at assertMethod (node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:108:11)
      at wrapMethod (node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:35:3)
      at Object.wrap (node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:65:7)
      at DatadogEnvironment.handleTestEvent (node_modules/dd-trace/packages/datadog-instrumentations/src/jest.js:71:17)
``` 

If I remove the line and/or set `injectGlobals` to `true`, everything works as expected. It was not immediately obvious what the issue was. I would prefer to continue to avoid globals and continue to import as follows: `import { expect, test, beforeAll } from '@jest/globals'`

**Steps to reproduce**

jest.config.js
```
/* eslint-disable no-undef */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: '<rootDir>/testEnvironment.js',
  transform: {
    '^.+\\.ts?$': 'ts-jest',
  },
  injectGlobals: false,
  transformIgnorePatterns: ['<rootDir>/node_modules/'],
}
```

testEnvironment.js
```
if (process.env.DD_ENV === 'ci') {
  require('dd-trace/ci/jest/env')
}

module.exports = require('jest-environment-node').default
```

example.test.ts
```
import { expect, test } from '@jest/globals'

test('example', async () => {
  expect(true).toEqual(true)
})
```

And then run tests using `DD_ENV=ci npm test` or similar.

**Environment**

* **Operation system:** macOS 12.3.1
* **Node.js version:** 16.15.0
* **Tracer version:** 2.9.1
* **Agent version:** agent-github-action@v1.3
* **Relevant library versions:** Jest 28

**Comment by juan-fernandez** [comment]
#2143 should fix this issue. I still have to add some unit tests but it's looking good 👍
