### ISSUE TITLE
DD_TRACE_DISABLED_PLUGINS ignored after upgrading dd-trace

### ISSUE THREAD

**Issue by nicolas-vivot** [DataDog/dd-trace-js#2129]
**Expected behaviour**
DD_TRACE_DISABLED_PLUGINS with a provided list of plugins should disable tracing for these plugins.

**Actual behaviour**
DD_TRACE_DISABLED_PLUGINS seems to be ignored after upgrading the dd-trace npm package from version 1.1.2 to 2.9.0

**Tracer initialization code**

> const tracer = require('dd-trace').init();
> const opentracing = require('opentracing');
> opentracing.initGlobalTracer(tracer);
> 
> export default tracer;

**Environment variables (docker)**

DD_TRACE_DISABLED_PLUGINS: 

> dns,net,fs,mongodb,mongodb-core

**Additional information**
Before the upgrade, none of the dns, net or mongodb plugins were traced. After the upgrade these plugins are traced again by the library despite the deactivation via the environment variable.

We also upgraded some of our npm dependencies, including the mongodb one. But that does not explain the behavior since the plugin name is defined by the dd-trace library right ?

**Question**
Is the DD_TRACE_DISABLED_PLUGINS environment variable not supported anymore ? Do i need to initialize the trace in a different way to disabe plugins ?

**Comment by rochdev** [comment]
> Is the DD_TRACE_DISABLED_PLUGINS environment variable not supported anymore ? Do i need to initialize the trace in a different way to disabe plugins ?

This environment variable is still supported, so this is definitely a bug. It doesn't seem to be handled at all by the new plugin system which would be an oversight. We'll add back support as soon as possible.
