### ISSUE TITLE
Koa route is not correct

### ISSUE THREAD

**Issue by eddycharly** [DataDog/dd-trace-js#2131]
Koa route is incorrectly reported.
For a given route `/bank-transaction`, the reported route becomes `/bank-transaction/bank-transaction/bank-transaction/bank-transaction` (repeated once per middleware).

**Comment by rochdev** [comment]
While the issue is not exactly the same as #2120, I think it should still be solved by #2123 when it lands. If you can provide a reproduction snippet I can try it out with the fix to see if it resolves your issue as well. Alternatively you can try installing dd-trace from the branch.

**Comment by rochdev** [comment]
Can you try with 2.10.0? This will validate if the change mentioned above fixed the issue.

**Comment by jinroh** [comment]
We have this issue running the 2.10.0. I can try to find a way to reproduce.

**Comment by jinroh** [comment]
Seems to happened with "inline" middlewares:

```js
'use strict'
const ddtracer = require('dd-trace').init()
ddtracer.use('koa', {
  hooks: {
    request: (span, req) => {
      console.assert(span._spanContext._tags['http.route'] === '/plop') // Assertion failed => tag is '/plop/plop'
    }
  }
})

const Koa = require('koa')
const Router = require('koa-router')
const app = new Koa()
const router = new Router()
router.get(
  '/plop',
  (ctx, next) => next(), // <- culprit
  (ctx) => {
    ctx.body = 'bar'
  }
)
app.use(router.routes())
app.listen(3000)
```

**Comment by theJC** [comment]
Just upgraded to 2.10.0 and am seeing this issue as well

**Comment by theJC** [comment]
@rochdev -- is it worth my time trying to create a sample to exhibit our scenario, or do you think @jinroh's example is sufficient and you have the ability to track down the culprit?
