### ISSUE TITLE
Socket hang up in Lambda

### ISSUE THREAD

**Issue by alper** [DataDog/dd-trace-js#2135]
Hi,

We are seeing the following error message:

```
Error - socket hang up
Jun 16, 2022 11:09 AM
Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at Socket.socketCloseListener (_http_client.js:449:25)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:475:12)
    at TCP.<anonymous> (net.js:686:12)
    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)
```

From our other tool we can see that there are attempts to post to the agent which fail and then there are retries a bit later which are fine.

![CleanShot 2022-06-20 at 16 40 33](https://user-images.githubusercontent.com/72429/174626743-66c2dde5-2cb0-4893-b6f6-203a642a0053.png)

Even though the thing may work eventually, these errors propagate in other parts of our system and generally seem undesirable. Can we figure out why this could be happening?

**Comment by alper** [comment]
I can see some other situations where the exact same thing happened: https://github.com/DataDog/dd-trace-js/issues?q=is%3Aissue+socket+hang+

**Comment by alper** [comment]
It seems that this error happened because we were using the Serverless macro. So you're probably right that it is not relevant.

**Comment by rochdev** [comment]
Closing since it seems the issue wasn't with dd-trace. Please feel free to re-open if this is still being an issue.
