### ISSUE TITLE
dd-trace crash with Tedious

### ISSUE THREAD

**Issue by lostfields** [DataDog/dd-trace-js#2145]
**Expected behaviour**
Expecting that tedious queries should run as normal when requiring dd-trace

**Actual behaviour**
When using mssql (tedious) with dd-trace that isn't initialized it fails with error message `request.apply is not a function`

**Steps to reproduce**
Install dd-trace@^2.4 or newer when using Windows as development environment. Require `dd-trace` but don't run `tracer.init()`. Run some mssql queries and it will fail with 

```
TypeError: request.apply is not a function
    at Connection.makeRequest (<project>\node_modules\dd-trace\packages\datadog-instrumentations\src\tedious.js:16:22)
```

It will fail with mssql@^8 as well, but you will be presented with a `operation timed out for an unknown reason` instead, but deep down in the stack you will see there is a `request.apply is not a function` as well.

![image (5)](https://user-images.githubusercontent.com/4351799/175006397-1b122aa4-07ff-4819-8997-bc4e6e39d3de.png)

**Environment**

* **Operation system: Windows 11
* **Node.js version: v16.14.0
* **Tracer version: ^2.4
* **Relevant library versions: mssql@^6

**Comment by sabrenner** [comment]
Thanks for pointing this out. We'll be working on a fix ASAP, and will tag this issue in the PR once it comes out!

**Comment by tgensol** [comment]
<img width="931" alt="Capture d’écran 2023-04-01 à 18 31 13" src="https://user-images.githubusercontent.com/7864896/229303027-f2634a00-0798-4e52-a630-659bbcd72ab8.png">

We are having lots of crash with the 3.16
