### ISSUE TITLE
Mocha integration: beforeAll and first beforeEach hooks are not traced

### ISSUE THREAD

**Issue by ostrovanka** [DataDog/dd-trace-js#2157]
**Expected behaviour**
Mocha hooks should be traced (have active span). Test level hooks belong to appropriate test span.

**Actual behaviour**
BeforeAll and first beforeEach hooks doesn't have active span. BeforeEach hooks starting from the 2nd one belong to span of the previous test.

**Steps to reproduce**
Short test to illustrate this behaviour:
```
const {createLogger, transports, format} = require("winston");
const tracer = require('dd-trace');

const loggerWinston = createLogger({
    level: 'info',
    format: format.json(),
    transports: [new transports.Console(), new transports.File({
        filename: `./my.log`,
    })],
});

describe('DD Logs Suit', function () {
    before(async () =>{
        const span = tracer.scope().active();
        console.log(`Before all span: ${span?.context().toTraceId()}`)
        loggerWinston.info("Before all")
    })

    after(async () =>{
        const span = tracer.scope().active();
        console.log(`After all span: ${span?.context().toTraceId()}`)
        loggerWinston.info("After all")
    })

    beforeEach(async () =>{
        const span = tracer.scope().active();
        console.log(`Before each span: ${span?.context().toTraceId()}`)
        loggerWinston.info("Before each")
    })

    afterEach(async () =>{
        const span = tracer.scope().active();
        console.log(`After each span: ${span?.context().toTraceId()}`)
        loggerWinston.info("After each")
    })
    it('Test 1', async function () {
        const span = tracer.scope().active();
        console.log(`Test span: ${span?.context().toTraceId()}`)
        loggerWinston.info({message: "Winston Logger"})
    })

    it('Test 2', async function () {
        const span = tracer.scope().active();
        console.log(`Test span: ${span?.context().toTraceId()}`)
        loggerWinston.info({message: "Winston Logger"})
    })
})
```
Output would be something like this:
```
  DD Logs Suit
Before all span: undefined
...
Before each span: undefined
...
Test span: 7007257701732416091
...
    ✔ Test 1
After each span: 7007257701732416091
...
Before each span: 7007257701732416091  //Wrong span!! should belong to the span of the next test, but is assigned to the already finished test
...
Test span: 298910298997552109
...
    ✔ Test 2
After each span: 298910298997552109
...
After all span: 298910298997552109
```

**Environment**

* **Operation system:** mac os Big sure 11.2.3
* **Node.js version:**  v14.16.0
* **Tracer version:** 2.7.1
* **Agent version:** 7
* **Relevant library versions:** winston 3.3.3, mocha 10.0.0 (same with 8.4.0)

**Comment by juan-fernandez** [comment]
hi @ostrovanka ! Thanks for reporting this issue and providing a reproducible case. 

I have a question: what would you expect as the active span in `before` and `after` hooks? These hooks are not associated to a test but to a suite, so there doesn't seem to be a good candidate currently. Just for your information, we're currently working on test suite level visibility, so this question will have an answer soon, but I'm curious what you think.

**Comment by ostrovanka** [comment]
hi @juan-fernandez tricky question about before and after, valid for any test reporting tool. 
Ideally those should be in a separate spans but only if there is a new 'entity' on DD board side to display those hooks on Test tab.
Other way (which I saw in some reporting tools) is to add `before` and `after` hooks data to each of the tests in the respective suite. although this violates the real flow of things, it makes sense to me as when I view test logs I'd like to see everything that is related to this test execution and before/after hooks definitely relate to this.

one question - can I hope for a quick fix for this issue? (especially the wrong span for `beforeEach` and `afterEach` hooks)

**Comment by juan-fernandez** [comment]
> hi @juan-fernandez tricky question about before and after, valid for any test reporting tool. Ideally those should be in a separate spans but only if there is a new 'entity' on DD board side to display those hooks on Test tab. Other way (which I saw in some reporting tools) is to add `before` and `after` hooks data to each of the tests in the respective suite. although this violates the real flow of things, it makes sense to me as when I view test logs I'd like to see everything that is related to this test execution and before/after hooks definitely relate to this.
> 
> one question - can I hope for a quick fix for this issue? (especially the wrong span for `beforeEach` and `afterEach` hooks)

thanks for the input @ostrovanka. This is interesting feedback. 

As for the quick fix: I've been working on a solution. Things are looking good. I'd expect a PR early next week 😄

**Comment by ostrovanka** [comment]
Hi @juan-fernandez , I tried updated dd-trace with your fixes. Unfortunately, now I am seeing an error in the hooks:

`     done() called multiple times in hook <DD Logs Suit "before all" hook in "DD Logs Suit"> of file /Users/aostr/Documents/Projects/yum/dd-test/test-dd.js; in addition, done() received error: TypeError: Cannot read property 'title' of undefined
    at getTestSpanMetadata (/usr/local/lib/node_modules/dd-trace/packages/datadog-plugin-mocha/src/index.js:28:32)
    at MochaPlugin.startTestSpan (/usr/local/lib/node_modules/dd-trace/packages/datadog-plugin-mocha/src/index.js:99:46)
    at /usr/local/lib/node_modules/dd-trace/packages/datadog-plugin-mocha/src/index.js:53:25
    at Subscription._handler (/usr/local/lib/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:12:9)
    at Channel.publish (/usr/local/lib/node_modules/dd-trace/node_modules/diagnostics_channel/index.js:81:9)
    at /usr/local/lib/node_modules/dd-trace/packages/datadog-instrumentations/src/mocha.js:49:21
    at exports.AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at Runner.<anonymous> (/usr/local/lib/node_modules/dd-trace/packages/datadog-instrumentations/src/mocha.js:48:21)
    at Runner.emit (events.js:315:20)
    at next (/Users/aostr/Documents/Projects/yum/dd-test/node_modules/mocha/lib/runner.js:778:10)
    at Runner.runTests (/Users/aostr/Documents/Projects/yum/dd-test/node_modules/mocha/lib/runner.js:842:3)
    at Runner.runTests (/usr/local/lib/node_modules/dd-trace/packages/datadog-instrumentations/src/mocha.js:133:21)
    at /Users/aostr/Documents/Projects/yum/dd-test/node_modules/mocha/lib/runner.js:919:10
    at next (/Users/aostr/Documents/Projects/yum/dd-test/node_modules/mocha/lib/runner.js:486:14)
    at cbHookRun (/Users/aostr/Documents/Projects/yum/dd-test/node_modules/mocha/lib/runner.js:551:7)
    at done (/Users/aostr/Documents/Projects/yum/dd-test/node_modules/mocha/lib/runnable.js:310:5)
    at /Users/aostr/Documents/Projects/yum/dd-test/node_modules/mocha/lib/runnable.js:371:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  uncaught: true
}
`

Note: I am using the same test as I listed in this ticket above.

Could you please take a look at this?

**Comment by juan-fernandez** [comment]
> Hi @juan-fernandez , I tried updated dd-trace with your fixes. Unfortunately, now I am not seeing spans attached to any of the hook or test:
> 
> ```
>   DD Logs Suit
> Before all span: undefined
> {"level":"info","message":"Before all"}
> Before each span: undefined
> {"level":"info","message":"Before each"}
> Test span: undefined
> {"level":"info","message":"Winston Logger"}
>     ✓ Test 1
> After each span: undefined
> {"level":"info","message":"After each"}
> Before each span: undefined
> {"level":"info","message":"Before each"}
> Test span: undefined
> {"level":"info","message":"Winston Logger"}
>     ✓ Test 2
> After each span: undefined
> {"level":"info","message":"After each"}
> After all span: undefined
> {"level":"info","message":"After all"}
> ```
> 
> Note: I am using the same test as I listed in this ticket above.
> 
> Could you please take a look at this?

hey @ostrovanka , thanks for following up. That's weird, as I created a test just to test this behavior. I'll have a look

**Comment by juan-fernandez** [comment]
> const {createLogger, transports, format} = require("winston");

just tested the latest `master` with your test suite: 

```
$ NODE_OPTIONS='-r dd-trace/ci/init' mocha


  DD Logs Suit
Before all span: undefined
{"level":"info","message":"Before all"}
Before each span: 2055767271143206699
{"level":"info","message":"Before each"}
Test span: 2055767271143206699
{"level":"info","message":"Winston Logger"}
    ✔ Test 1
After each span: 2055767271143206699
{"level":"info","message":"After each"}
Before each span: 2360112477197216194
{"level":"info","message":"Before each"}
Test span: 2360112477197216194
{"level":"info","message":"Winston Logger"}
    ✔ Test 2
After each span: 2360112477197216194
{"level":"info","message":"After each"}
After all span: undefined
{"level":"info","message":"After all"}


  2 passing (7ms)

```

are you using the latest `master`? 
```
yarn add --dev https://github.com/DataDog/dd-trace-js/tarball/master  
```

The `after all span` and `before all span` are left `undefined` on purpose, as they don't belong to any test

**Comment by ostrovanka** [comment]
@juan-fernandez worked now, thanks! I was using `mocha --require dd-trace/ci/init` instead of `NODE_OPTIONS='-r dd-trace/ci/init'`

**Comment by ostrovanka** [comment]
hi @juan-fernandez , while using new version of dd-trace with the fixes you provided I've found one more issue, decided not to create new ticket and just notify you here:

in `datadog-instrumentations/mocha` module:
'hook end' event:
```
    this.on('hook end', (hook) => {
      const test = hook.ctx.currentTest
      if (test && hook.parent._afterEach.includes(hook)) { // only if it's an afterEach
        const isLastAfterEach = hook.parent._afterEach.indexOf(hook) === hook.parent._afterEach.length - 1
        if (isLastAfterEach) {
          const asyncResource = getTestAsyncResource(test)
          asyncResource.runInAsyncScope(() => {
            testFinishCh.publish('pass')
          })
        }
      }
    })
```
this implementation gives false-positive results, if test itself has failed but it's afterEach hook has passed.

I tried this dummy fix and it worked for me (probably there are more elegant ways):

```
    this.on('hook end', (hook) => {
      const test = hook.ctx.currentTest
      if (test && hook.parent._afterEach.includes(hook)) { // only if it's an afterEach
        const isLastAfterEach = hook.parent._afterEach.indexOf(hook) === hook.parent._afterEach.length - 1
        if (isLastAfterEach) {
          let status;
          if (test.pending) {
            status = 'skip'
          } else if (test.state !== 'failed' && !test.timedOut) {
            status = 'pass'
          } else {
            status = 'fail'
          }
          const asyncResource = getTestAsyncResource(test)
          asyncResource.runInAsyncScope(() => {
            testFinishCh.publish(status)
          })
        }
      }
    })
```

**Comment by juan-fernandez** [comment]
> hi @juan-fernandez , while using new version of dd-trace with the fixes you provided I've found one more issue, decided not to create new ticket and just notify you here:
> 
> in `datadog-instrumentations/mocha` module: 'hook end' event:
> 
> ```
>     this.on('hook end', (hook) => {
>       const test = hook.ctx.currentTest
>       if (test && hook.parent._afterEach.includes(hook)) { // only if it's an afterEach
>         const isLastAfterEach = hook.parent._afterEach.indexOf(hook) === hook.parent._afterEach.length - 1
>         if (isLastAfterEach) {
>           const asyncResource = getTestAsyncResource(test)
>           asyncResource.runInAsyncScope(() => {
>             testFinishCh.publish('pass')
>           })
>         }
>       }
>     })
> ```
> 
> this implementation gives false-positive results, if test itself has failed but it's afterEach hook has passed.
> 
> I tried this dummy fix and it worked for me (probably there are more elegant ways):
> 
> ```
>     this.on('hook end', (hook) => {
>       const test = hook.ctx.currentTest
>       if (test && hook.parent._afterEach.includes(hook)) { // only if it's an afterEach
>         const isLastAfterEach = hook.parent._afterEach.indexOf(hook) === hook.parent._afterEach.length - 1
>         if (isLastAfterEach) {
>           let status;
>           if (test.pending) {
>             status = 'skip'
>           } else if (test.state !== 'failed' && !test.timedOut) {
>             status = 'pass'
>           } else {
>             status = 'fail'
>           }
>           const asyncResource = getTestAsyncResource(test)
>           asyncResource.runInAsyncScope(() => {
>             testFinishCh.publish(status)
>           })
>         }
>       }
>     })
> ```

great catch, @ostrovanka ! Thanks for this. I'll push a fix right away. It'll look very similar (if not the same) as your suggestion 😄
