### ISSUE TITLE
Custom res.end() is called twice

### ISSUE THREAD

**Issue by yriklin** [DataDog/dd-trace-js#2161]
We wrap res.end() in a middleware for graphql operations in the following way:
```
const originalResEndFunction = res.end.bind(res);
res.end = (requestReturnedValue) => {
    originalResEndFunction(requestReturnedValue);
    subscribedCallback({ req, res, requestReturnedValue }, ...args);
};
```
res.end(result) is called from another module we use: express-graphql.

Starting from dd-trace version 2.4.1 our wrapped res.end() is called a second time.
This call was added in version 2.4.1 in the following section:
```
this.addSub('apm:http:server:request:async-end', ({ req }) => {
    const context = web.getContext(req)
    web.wrapRes(context, context.req, context.res, context.res.end)()
})
```
File: packages/datadog-plugin-http/src/server.js
PR: Migrate HTTP from old to new plugin system: https://github.com/DataDog/dd-trace-js/pull/1804/files.

Commenting this code section seems to solve the problem.

**Comment by ruettenm** [comment]
Hi,

today I analyzed an issue in our app that we have our access logging log entries twice in datadog.

We implemented our access logging by overwriting the `res.end` method of express.

In the end I found out that `dd-trace` is calling the `res.end` method in addition to express.

Could you please react in short term and let us know how to fix this issue. Thanks!


Best regards
Matthias

**Comment by ruettenm** [comment]
I also tested version `2.4.0` (like suggested from @yriklin) and with this version the issue disappears.

The latest version `2.11.0` is also broken.

**Comment by ruettenm** [comment]
Thanks @rochdev !!
