### ISSUE TITLE
Issue trying to filter out some MongoDB spans

### ISSUE THREAD

**Issue by clement-heliot** [DataDog/dd-trace-js#2163]
**Expected behaviour**
I expect the `ismaster admin.$cmd` span to not be produced when configuring the tracer like this:

```javascript
tracer.use('mongodb-core', { measured: { 'ismaster admin.$cmd': false } })
```

**Actual behaviour**
 The span `ismaster admin.$cmd` is produced.

<img width="1562" alt="Screenshot 2022-06-28 at 15 18 54" src="https://user-images.githubusercontent.com/101628187/176188825-7272ce73-da1f-4393-a045-c37c6ec2d317.png">

<img width="257" alt="Screenshot 2022-06-28 at 15 08 10" src="https://user-images.githubusercontent.com/101628187/176186372-b9e21adf-9e84-4cad-afe3-8faede2089dd.png">

Is it the right way to filter out these kind of spans?

**Tracer version:** 2.9.1

Cheers :)

**Comment by jeansouza** [comment]
@clement-heliot I'm facing the same problem, did you manage to solve it?
