### ISSUE TITLE
Package install fails in 2.10.0 on Windows 10 during node-gyp for @datadog/pprof-nodejs

### ISSUE THREAD

**Issue by dls314** [DataDog/dd-trace-js#2186]
**Expected behaviour**
Upgrading to 2.10.0 from 2.9.1 should work

**Actual behaviour**
During package install on Windows 10, the transitive dependency on @datadog/pprof-nodejs through @datadog/native-metrics doesn't build under node-gyp.

**Steps to reproduce**
Update to "dd-trace": "2.10.0" and try to install packages on Windows 10, eventually receive an error message from NPM with information like this:

```shell
error {prefix-path-omitted}\node_modules\@datadog\pprof\bindings\sample.cc(70): error C2039: 'front_inserter': is not a member of 'std' [{prefix-path-omitted}\node_modules\@datadog\pprof\build\dd_pprof.vcxproj]
```

**Environment**

* **Operation system:** Windows 10
* **Node.js version:** v14.19.3
* **Tracer version:** 2.10.0
* **Agent version:** ?
* **Relevant library versions:**
   * Python 3.10.4
   * MS Build Tools VS2017 (15.9.28307.2019)
   * node-gyp -v v8.4.1

**Comment by dls314** [comment]
The repository, here: https://github.com/DataDog/pprof-nodejs does not have issues enabled, so there is not a better avenue for targeted support than here in dd-trace-js (sorry).

The build error is likely due to a missing inclusion like: `#include <iterator>` in https://github.com/DataDog/pprof-nodejs/blob/main/bindings/sample.cc

**Comment by Qard** [comment]
Strange...it shouldn't be building at all on Windows, there's prebuilds. 🤔

**Comment by dls314** [comment]
I can see the `datadog-pprof-0.5.1\package\prebuilds\win32-x64\node-83.node` in the package, and that should be what is selected on my system -- I think, I'm not familiar enough with node-gyp or node-gyp-build to be sure.

Know of any way I can get more information on how the prebuild isn't selected during package install?

**Comment by dls314** [comment]
The fixes in pprof have propagated at some point, and I was able to install dd-trace 2.14.0 without issue (likely earlier, but this is the first I've tested against).

Thanks!
