### ISSUE TITLE
Make it possible to use dd-trace-js together with a Typescript ESM loader

### ISSUE THREAD

**Issue by fardjad** [DataDog/dd-trace-js#2190]
Thanks to (experimental) support for loaders in Node.js, it's relatively easy to run Typescript without a pre-compilation step in ESM projects. That simplifies the build process and improves the developer experience.

However, it's still hard to get the ESM loader used by dd-trace-js (import-in-the-middle) to play nice with a Typescript ESM loader such as [ts-node](https://github.com/TypeStrong/ts-node).

I reported an issue [here](https://github.com/DataDog/import-in-the-middle/issues/13) about two weeks ago, but I did not receive any acknowledgment/feedback/input from Datadog whatsoever. As we are planning to migrate our Node.js repositories to ESM, and we would like to keep the possibility of running our TS projects without a build step, I thought it's best to raise this here again in a more generic manner.

**Comment by rochdev** [comment]
I opened https://github.com/DataDog/import-in-the-middle/pull/16 to try and merge your test project and the extension fix as a single PR, but I wasn't able to make it work. Do you know what could cause the error [here](https://github.com/DataDog/import-in-the-middle/runs/7398964944?check_suite_focus=true)? I'm not familiar at all with `ts-node` so I'm not sure what's going on.

**Comment by fardjad** [comment]
I think I don't have access to see the error logs, but I rebased your branch in my fork and updated [the PR](https://github.com/DataDog/import-in-the-middle/pull/14). I think it should be working now. `ts-node/esm` is still not chain-friendly because it sets `shortCircuit: true` property, until that is changed (which IMHO, should not matter much for this project), we can create our own custom chain loader. I also had to rename `say-hi.ts` to `say-hi.mts` because esm mode is enabled.

**Comment by rochdev** [comment]
Perfect, thanks for the quick fix. Do you know why it's a problem if `ts-node/esm` uses `shortCircuit` since it comes last anyway?

**Comment by fardjad** [comment]
No problem! Well it should actually come before IITM (it is also the case in the custom chain loader even though it might be a bit hard to spot at first glance). The reason is, IITM expects JS code (i.e. transpiled TS).

**Comment by fardjad** [comment]
No problem! 

According to the [official Node.js docs](https://nodejs.org/api/esm.html#esm_loaders), if we do `--loader loader1 --loader loader2`, it actually calls **loader2** first and then **loader2** **MUST** call **loader1** unless it returns `shortCircuit: true`.

After refreshing my memory on how loaders work, I realized that my previous comment was not accurate and while it's related but it doesn't have much to do with `shortCircuit`. When we pass multiple `--loader` arguments to node, the default resolve/load function will always be the one [provided by node](https://github.com/nodejs/node/blob/main/lib/internal/modules/esm/loader.js#L151). Keeping that in mind, when we do `--loader iitm --loader ts-node/esm`, the following happens when loading a Typescript file:

1. **ts-node/esm::resolve** resolves the specifier and automatically resolves **JS** extensions to their corresponding **TS** extensions, and that's why we need TS extensions support in IITM.
2. **ts-node/esm::load** gets called, and then it hands over control to Node, which in turn calls **iitm::load**
3. We end up with an endless recursion. **iitm::load** invokes **ts-node/esm::load** and **ts-node/esm:load** passes control back to the default load function provided by Node, which in turn calls the next loader (i.e. iitm) and it goes on and on.

**Comment by rochdev** [comment]
Sounds like this could be handled better in iitm. In any case, now that the new plugin system landed in dd-trace, it's very likely we'll end up with a custom internal loader instead which shouldn't have this type of issue in the following months.
