### ISSUE TITLE
100% graphQL error rate on 2.11.0

### ISSUE THREAD

**Issue by kuritz** [DataDog/dd-trace-js#2203]
**Expected behaviour**
Only requests that truly error should cause the tracer to record an error on the related span.

**Actual behaviour**
100% of our graphql traces recorded errors. Diving into individual traces, it looked like mostly `graphql.resolve` spans as where the `error: true` field originated from. Everything was operating normally during this time period, it is unclear why errors were being reported by the tracer.

<img width="725" alt="Screen Shot 2022-07-20 at 5 16 12 PM" src="https://user-images.githubusercontent.com/15093505/180083650-0f8a4906-f16b-4fb1-adf7-17218aae5188.png">

**Steps to reproduce**
We upgraded from 2.9.1 to 2.11.0 without changing any other code. The spike started at the time we deployed the commit with version 2.11.0 of the tracer and subsided after we reverted that commit.

**Environment**

* **Operation system:** debian bullseye (docker)
* **Node.js version:** 14.19.3
* **Tracer version:** 2.11.0
* **Agent version:**  7.37.1
* **Relevant library versions:** 
```
"express": "^4.17.2"
"graphql": "^15.7.2"
```

**Notes:**

We tried upgrading to 2.11.0 hoping it might resolve the bug we are experiencing on 2.9.1 noted in https://github.com/DataDog/dd-trace-js/issues/2204

**Comment by ostrowr** [comment]
Replicating on our end as well. Additionally, setting the `error` tag to `null` in the `execute` hook doesn't seem to resolve – I've been stepping through the code but haven't yet found where `addError` is called.

**Comment by jamesicon** [comment]
We are also seeing this same issue with our graphql setup and dd-tracer.
