### ISSUE TITLE
Blocklist configuration for http client plugin does not work

### ISSUE THREAD

**Issue by Quramy** [DataDog/dd-trace-js#2208]
**Expected behaviour**

I read https://datadoghq.dev/dd-trace-js/interfaces/plugins.http.html#blocklist and it saids

> List of URLs that should not be instrumented.

However,  it seems that `blocklist` of http.client plugin implementation  only effects whether to inject tracing headers or not.  It seems that the plugin send span of an HTTP request matched in `blocklist` to agent.

https://github.com/DataDog/dd-trace-js/blob/5326afb5828cef3295c4c3d29503e2b4007f5a90/packages/datadog-plugin-http/src/client.js#L37-L51

Is API document wrong ? 🤔 

And I want to reject to instrument for some requests ( they can be detected via URL domain or path). Is there alternative way?

**Actual behaviour**

**Steps to reproduce**

**Environment**

* **Operation system:**: Docker (based from node:16.14.2-buster)
* **Node.js version:**: 16.14.2
* **Tracer version:** : 2.11.0
* **Agent version:**
* **Relevant library versions:**

**Comment by rochdev** [comment]
This was removed because of issues with the previous plugin system which has since been replaced. It should be possible to restore this feature at this point. I'll have to take a look at how to handle propagation of the sampling decision for these spans.

**Comment by clement-heliot** [comment]
This might be related: https://github.com/DataDog/dd-trace-js/issues/2225

**Comment by rochdev** [comment]
@clement-heliot Thanks for the additional context in #2225. It wasn't clear to me what the use case was for this was, although it seems pretty clear now that it's basically the same reason that we drop our own requests to avoid seeing observability related requests. The main concern was wether we should just drop the span itself, or also any other spans following from that span, but for this use case it's definitely the latter. We should be able to add this back now.

**Comment by Quramy** [comment]
>  this use case it's definitely the latter.

👍 

yes. I want to reject nested spans in an http-client span which matches the `blocklist`.

**Comment by dko-slapdash** [comment]
@rochdev Just spent 1h or so with an interactive debugger trying to figure out, why `blocklist` is ignored, finally figured out, and then found this thread. :-) What was another confusion is that feature is mentioned as functioning in the official docs: https://docs.datadoghq.com/tracing/guide/ignoring_apm_resources/?tab=datadogyaml#tracer-configuration-options

Would be super-cool to have this feature back. Thanks!
