### ISSUE TITLE
http module configuration breaks server APM reporting

### ISSUE THREAD

**Issue by clement-heliot** [DataDog/dd-trace-js#2225]
:wave: I have a case where configuring the `http` module breaks the APM reporting of the server. The service http-client is still being reported correctly.

**Expected behaviour**
I would expect configuring the `http` module this way would not break the APM server reporting.

**Actual behaviour**
APM server reporting is broken and stop reporting.

**Steps to reproduce**
```javascript
tracer.use('http', {
    server: {
      blocklist: ['/ping'],
    },
    client: {
      blocklist: [
        'https://back.sqreen.io/sqreen/v1/app-beat',
        'https://ingestion.sqreen.com/batches',
        'https://events.launchdarkly.com/bulk',
      ],
    },
  })
```

**Environment**

* **Tracer version:** 2.10.0

**Comment by rochdev** [comment]
When you say "stop reporting" do you mean that you're no longer getting traces at all, only when you use a blocklist configuration?

**Comment by clement-heliot** [comment]
@rochdev Yep, the APM Service page stopped being updated. Say the service name was saturne, saturne APM page wasn't receiving anything. However saturne-http-client was working as expected. When I rolled back the changes and removed the configuration, saturne APM page worked again.

**Comment by rochdev** [comment]
Is this something you are able to easily isolate in a reproduction snippet? Also, was there anything else in that change, for example changing the version of dd-trace?

**Comment by clement-heliot** [comment]
@rochdev Nope, basically I changed 

```javascript
tracer.use('http', { blocklist: ['/ping'] })
  ```
  
to 

  ```javascript
tracer.use('http', {
    server: {
      blocklist: ['/ping'],
    },
    client: {
      blocklist: [
        'https://back.sqreen.io/sqreen/v1/app-beat',
        'https://ingestion.sqreen.com/batches',
        'https://events.launchdarkly.com/bulk',
      ],
    },
  })
  ```
  
  made only those changes, no dd-trace version change were involved.

**Comment by tlhunter** [comment]
@clement-heliot can you confirm if you're still facing this issue with a current tracer version?

**Comment by tlhunter** [comment]
I'll close this for now but we can reopen it if it's still an issue.
