### ISSUE TITLE
log initialization

### ISSUE THREAD

**Issue by gajus** [DataDog/dd-trace-js#223]
Use a logger to document what the agent is doing, which plugins are being enabled, what modules are being patched.

I humbly recommend https://github.com/gajus/roarr for all the reasons described in https://github.com/gajus/roarr#motivation.

Case in point: I have loaded `dd-trace` using:

```js
import tracer from 'dd-trace';

// eslint-disable-next-line no-process-env
if (process.env.DD_AGENT_SERVICE_HOST && process.env.DD_AGENT_SERVICE_PORT) {
  tracer.init({
    // eslint-disable-next-line no-process-env
    hostname: process.env.DD_AGENT_SERVICE_HOST,
    // eslint-disable-next-line no-process-env
    port: process.env.DD_AGENT_SERVICE_PORT
  });
}

```

and I have no clue whats the reason "pg" or "express" data is not being logged; only "http" is being tracked.

**Comment by gajus** [comment]
Never mind, it looks like you have a `{debug: true}` configuration.

https://docs.datadoghq.com/tracing/setup/nodejs/#debug-mode

It would be handy to have all of this in README.md.

**Comment by gajus** [comment]
Either way, looks like enabling debug does not log anything of value with regards to plugin loading issues.

**Comment by rochdev** [comment]
You can also set your own logger by using the [logger option](https://datadog.github.io/dd-trace-js/#custom-logging)

Please let me know if you think anything is missing from the debug logs! We went with a minimal approach to start and only logged the components that are the most difficult to debug.

Currently which plugin is loaded is not included, but I agree it would be very helpful.

Are you importing `express` and `pg` before initializing the tracer? This is usually the only reason a plugin would not be loaded. Also note that hoisting can happen when transpiling with Babel.

**Comment by rochdev** [comment]
Actually the version could also be a cause, and this should be logged as well if there is a version mismatch.

**Comment by gajus** [comment]
> Either way, looks like enabling debug does not log anything of value with regards to plugin loading issues.

There is `DD_TRACE_DEBUG` setting.

https://github.com/DataDog/dd-trace-js/blob/master/src/config.js#L11-L20

**Comment by gajus** [comment]
> Actually the version could also be a cause, and this should be logged as well if there is a version mismatch.

That is the case indeed. Yes, this should be logged.

**Comment by andrewsouthard1** [comment]
@gajus We've since added default startup logs in addition to debug logging: https://docs.datadoghq.com/tracing/troubleshooting/tracer_startup_logs/?tab=java#startup-logs please reach out if you have any other questions!
