### ISSUE TITLE
cpu-profiler data doesn't show up in the profiler view on datadog.com

### ISSUE THREAD

**Issue by vanstinator** [DataDog/dd-trace-js#2238]
**Expected behaviour**
The patch notes for 2.12.0 mention that the cpu-profiler support has shipped. https://github.com/DataDog/dd-trace-js/pull/2044

After enabling `DD_PROFILING_ENABLED` for an app I'd expect to see cpu profile data on the APM "Profiles" tab on datadog.com

**Actual behaviour**
I'm still only seeing `Wall Time` and `Heap Usage` profile data. The cpu bits in the UI still mention that the nodejs tracer doesn't support cpu profiling. 

I expect this is _probably_ intentional if there's UI work that needs to ship, but the patch notes and PR don't mention anything at all, so if there's extra steps to take as a developer to enable this experimental feature can we get docs for that? Otherwise it might be worth leaving a note on the patch notes indicating that the feature doesn't actually provide any value to end-users just yet.

**Steps to reproduce**
Should repro on any starter app with dd-trace enabled.

**Environment**

* **Operation system:**debian
* **Node.js version:**16.16.0
* **Tracer version:**2.12.0
* **Agent version:**7.37.1
* **Relevant library versions:**

**Comment by rochdev** [comment]
I think the feature is behind a configuration option, @Qard can probably provide more information.

**Comment by Qard** [comment]
The feature is entering private beta. It's not all there yet. It will get a proper announcement when it's ready for users.

**Comment by vanstinator** [comment]
Is this still in private beta? (I'm almost certain the answer must be yes, but I'm enthusiastic about this feature after using it with the `go` profiling tools).

I'm putting together a project spec internally where we're going to target CPU utilization on some of our hottest services with a goal of reducing overall infrastructure costs, and hotspot support would be nice (even if not totally necessary).

Happy to bug my rep about early access to this feature, if necessary/possible.
