### ISSUE TITLE
node-gyp error - binding.gyp not found

### ISSUE THREAD

**Issue by amberasaurus** [DataDog/dd-trace-js#2239]
Attempting to install the latest version (2.12.0) of dd-trace is giving the following error: 
`npm ERR! gyp: binding.gyp not found (cwd: #####/node_modules/@datadog/native-metrics) while trying to load binding.gyp
npm ERR! gyp ERR! configure error`

My system info is:
Node: 16.13.1
OS: macOS Big Sur 11.6.8

I've attempted:
- Deleting node_modules and package-lock file
- Re-installing node-gyp
- Re-installing node itself
- Installing an older version of dd-trace: 1.5.1

If I remove dd-trace from my package.json file, I can install other packages, etc. successfully. 

Any help on this issue would be much appreciated. Thank you!

**Comment by rochdev** [comment]
I tried installing dd-trace in a new empty project with both npm and yarn and it works properly for me. Can you provide reproduction steps outside of an existing project?

**Comment by amberasaurus** [comment]
Sure, I ran these commands and received the same error (accepting all the defaults for npm init):
`mkdir npm-test
npm init
npm install dd-trace --save`

This may be due to how my machine is configured, etc. so if its not reproducible outside of my machine, I am fine with closing this.

**Comment by arutrub** [comment]
Hello - we seem to be running into the same issue. I am wondering if it has something to do with this recent PR in @datadog/native-metrics merged ~23 hours ago?
https://github.com/DataDog/dd-native-metrics-js/pull/23

**Comment by amberasaurus** [comment]
@arutrub I think you may be right, I manually installed this version of native-metrics and it seems to have resolved my issue: 
"@datadog/native-metrics": "1.2.0"

Still doing some more testing, but let me know if this helps you as well!

**Comment by arutrub** [comment]
@amberasaurus thank you for the information!
The below is a potential workaround that seemed to work for me for the time being.
Tested locally using the following snippet as part of my package.json file and confirmed I can build successfully using version **2.11.0**:
```json
  "dependencies": {
    "dd-trace": "2.11.0",
    ...
},
  "devDependencies": {
    ...
},
  "overrides": {
    "dd-trace": {
      "@datadog/native-metrics": "1.4.0"
    }
  }
```

**Comment by rfsbsb** [comment]
Facing the same issue with node 16.13, macos 12.5, pyenv with python 3.10

**Comment by rochdev** [comment]
The new version doesn't have a `binding.gyp` because it provides prebuilds for all supported platforms. There is no way for `npm` to know there should be a `binding.gyp` file if there isn't one, so I'm really not sure how to reproduce the issue.

**Comment by rochdev** [comment]
Tried the above an I'm getting the following result:

```
15:12:55 ❯ npm init
15:13:10 ❯ npm install dd-trace --save 

added 71 packages, and audited 72 packages in 688ms

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

And then dd-trace is installed properly. This is on Node 16.13.1 on macOS 12.3.1.

**Comment by rochdev** [comment]
The only way I can reproduce is running `npm run rebuild` while in the project itself, since that is the command we use for building locally while in development. Could something be running this command explicitly in all dependencies? My understanding is that `npm rebuild` will actually run `npm build` in dependencies, so the `rebuild` script should never be run from dependents.

**Comment by nelsojaco** [comment]
Saw the same error today on node 16.14.2, macOS 12.3.1. 
Overriding @datadog/native-metrics as suggested above worked for me.

**Comment by rochdev** [comment]
I tried to make it fail in Docker with this Dockerfile:

```js
FROM node:16

WORKDIR /usr/src/app

RUN npm init -y
RUN npm install --save dd-trace
```

And it works properly. Can anyone make it fail in Docker to remove any environment specific factors?

**Comment by bengl** [comment]
@amberasaurus @rfsbsb @arutrub Can any of you provide the npm version that this is happening with?

**Comment by rfsbsb** [comment]
Using the trick provide by @arutrub I was able to install it.
My env:
Node 16.13
NPM 8.1.2
Pyenv with python 3.10

**Comment by rochdev** [comment]
@rfsbsb This workaround would mean that you are stuck with this version however since we do not plan to restore the file since a build should never happen. Do you have more steps we could take to reproduce the issue or is there anything specific to your environment?

**Comment by rfsbsbprodigy** [comment]
So, we have a fixed version for `dd-trace` at 2.5.0, but that will still use the latest 1.x version of `@datadog/native-metrics` which seem to have stopped working after version 1.4.0 for us.
```
  "dependencies": {
    "dd-trace": "2.5.0"
  },
```
We are building it in a Typescript env with `ES2019` as target and `["ES2019", "ESNext"]` set as `lib`

As for other dependencies that makes uses of `node-gyp` we have 2:
- `@datadog/native-appsec` (which is a dependency of this module)
- `nan` (which is probably a dependency of other module we are using)

Nothing exotic on building or other packages we're using

**Comment by rochdev** [comment]
@rfsbsbprodigy Is this something you are able to reproduce in Docker?

**Comment by rfsbsb** [comment]
I tried building it on Docker using `node-build` as base and it failed due to python version.

**Comment by rfsbsb** [comment]
After a few more tests, it looks like we have an issue of cached version on our internal registry. If I use the default npm registry I works, but as soon as I switch to our internal it fails. I'll perform a few more tests and keep you posted.

**Comment by mkaufmaner** [comment]
> After a few more tests, it looks like we have an issue of cached version on our internal registry. If I use the default npm registry I works, but as soon as I switch to our internal it fails. I'll perform a few more tests and keep you posted.

@rfsbsb Were you able to resolve this problem with your internal registry? We are experiencing similar problems.

**Comment by rochdev** [comment]
After investigating the issue further, it seems that there is bug in npm reported in https://github.com/npm/cli/issues/5234. It's unclear whether the bug was triggered by removing the `binding.gyp` or removing the install script, but one of these changes combined with npm >=7 and a registry proxy results in an error when updating `dd-trace`. This doesn't seem to happen when installing the latest version dd-trace with no prior installation.

Hopefully this will be fixed by npm soon, but in the meantime it's possible to unblock the installation with `npm install --ignore-scripts --save dd-trace`. In my tests, it seems that once this command runs successfully, further updates no longer need to use `--ignore-scripts`.

**Comment by rochdev** [comment]
For environments where it's easier to change an environment variable than the command, the same workaround can also be used with `NPM_CONFIG_IGNORE_SCRIPTS=true`.

**Comment by mkaufmaner** [comment]
@rochdev Any update on getting the following PR's merged and packages released? The only other option we see is for us to fork the dd-trace library and publish it internally overriding the DataDog library.

https://github.com/DataDog/dd-native-metrics-js/pull/31
https://github.com/DataDog/pprof-nodejs/pull/49

**Comment by rfsbsb** [comment]
I know this has been closed, I just want to loop back and say that the 1.4.2 worked just fine. Thanks for the nimble response to this!

**Comment by rochdev** [comment]
@amberasaurus @mkaufmaner Did 2.12.2 resolve the issue for you?

**Comment by mkaufmaner** [comment]
> @amberasaurus @mkaufmaner Did 2.12.2 resolve the issue for you?

@rochdev Yes, it did. Thank you.
