### ISSUE TITLE
Doesn't work with the latest PG module

### ISSUE THREAD

**Issue by chaserelock** [DataDog/dd-trace-js#224]
We've upgraded our PG module from 6.3 -> 7.4
We no longer see information for postgres in our services tab for our environment

**Comment by rochdev** [comment]
`pg` 7.x is not supported at the moment, but it will be as soon as support for testing multiple module versions lands.

Related to https://github.com/DataDog/dd-trace-js/pull/144

**Comment by rochdev** [comment]
Fixed in #250 and released in v0.6.0
