### ISSUE TITLE
Graphql plugin doesn't detail queries & mutations

### ISSUE THREAD

**Issue by cyril94440** [DataDog/dd-trace-js#2255]
Hi there,

I have a pretty basic setup with Apollo graphql on a node.js v12 backend.

dd-trace is initialized with the following code :

```
import tracer from 'dd-trace';

tracer.init({
	logInjection: true,
	profiling: true,
	runtimeMetrics: true
});

tracer.use('amqplib');
tracer.use('graphql');
tracer.use('aws-sdk');

export default tracer;
```

in the datadog APM service section, when I take a look at the ressources of my graphql service, I only get two of them:
- GET
- POST

And I then have to open each and every span to see what query or mutation has been called. 
What am I doing wrong that prevents me from having all queries and mutations listed as separate ressources so that I can have query-specific statistics like with a REST API?

Thank you very much

**Comment by rochdev** [comment]
There should be a dropdown at the top left of the UI with the operation name in it, for example something like `operation:express.request`. If you switch the dropdown to `graphql.execute` you should be able to view GraphQL resources.

**Comment by cyril94440** [comment]
<img width="1755" alt="Capture d’écran 2022-08-05 à 12 10 09" src="https://user-images.githubusercontent.com/2829562/183055638-7e1a9194-e918-4ca9-b02e-ae1dfade51e7.png">

@rochdev Yaaay! Thank you so much!!

**Comment by tbell511** [comment]
I'm having a similar issue.

```
// tracer.ts
import tracer from "dd-trace";
tracer.init();
tracer.use('graphql');
export default tracer;
```

But don't see `graphql.execute` as an option 🤔 

<img width="486" alt="image" src="https://user-images.githubusercontent.com/25237806/213573511-6035f9ec-a809-4b03-a02e-e4963a98c8d3.png">

**Comment by rochdev** [comment]
The fact that `web.request` is displayed instead of the actual framework would indicate a load order issue. Is dd-trace the very first import in your app? One way to ensure that it is would be to use `NODE_OPTIONS='-r dd-trace/init'`.

**Comment by brunobrg** [comment]
@marco2216 I was having the same issue, and simply doing as @rochdev said - importing the tracer in the first line of my code - fixed the issue. graphql.execute and other graphql operations are now being traced
