### ISSUE TITLE
Supporting koa web framework

### ISSUE THREAD

**Issue by JohnLZeller** [DataDog/dd-trace-js#231]
In the [Tracing docs](https://docs.datadoghq.com/tracing/setup/nodejs/#web-frameworks) it says that support for `koa` web framework is "Coming soon". I would really love to bump this up in priority if that's possible :) Happy to test some stuff if needed. Thanks for your work!

**Comment by rochdev** [comment]
Thanks for you interest in the tracer! We are currently working on a few improvements to the core and our ability to test multiple versions of supported libraries, but Koa is the next planned new integration :)

Duplicate of #202

**Comment by JohnLZeller** [comment]
Great, thank you @rochdev!
