### ISSUE TITLE
ReactJs / React Native Support

### ISSUE THREAD

**Issue by sumeetsympatica** [DataDog/dd-trace-js#233]
The plugin works great with express based nodejs apps

However we would like to trace request latency from client to server and back 

When I use the module from a ReactJS app created using create-react-app I get this error:

```
./node_modules/require-in-the-middle/index.js
Module not found: Can't resolve 'module' in '...\node_modules\require-in-the-middle'
```

**Comment by rochdev** [comment]
The tracer currently only supports Node and doesn't work in the browser. Browser support is on our radar but there is no plan to support this short-term as we currently focus on improving Node tracing.

Related: #48

**Comment by sumeetsympatica** [comment]
Thank you for your fast reply. I will wait for the "horizon" to approach.

In case I am willing to auto instrument my code for tracing, could I in the meantime use your earlier project 'https://github.com/rochdev/datadog-tracer-js'?

Thanks, Sumeet

**Comment by rochdev** [comment]
That could be a workaround. Keep in mind that it's no longer maintained however.

**Comment by sumeetsympatica** [comment]
Hello,

I have been able to use dd-trace-js in my react js project by 
1) commenting out the instrumentation code like so 
```
// this._instrumenter.
```
2) modifying text_map.js like so
```
 const Int64 = require("node-int64")  
 carrier[traceKey] = new Int64(spanContext.traceId.toString()).toString()
 carrier[spanKey] = new Int64(spanContext.spanId.toString()).toString()
```
3) changing node/index.js to
```
const platform = {
  _config: {},
  name: () => 'nodejs',
  version: () => /*sumeet*/ /*process.version */ "v8.11.3" /*sumeet*/,
  engine: () => /*sumeet*/ /*process.jsEngine ||*/ 'v8'/*sumeet*/,
  configure (config) {
    this._config = config
``` to replicate how the nodejs module sends meta data

4) manually adding minimally neeed libraries to project package.json

**Comment by sumeetsympatica** [comment]
5) instrumenting window.fetch using code borrowd from react-tracing
```
let reactTracingFetch = function reactTracingFetch (url) {
      let options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {}
      let _options$method = options.method,
        method = _options$method === undefined ? "GET" : _options$method,
        _options$body = options.body,
        body = _options$body === undefined ? "" : _options$body

      let spanName = getName({url: url, method: method, body: body})

      let span = _this.startSpan(
        spanName,
        // $FlowFixMe
        _this._tracing_current_span)

      /* add tags for datadog*/
      span.addTags({"sym.url_client": url})
      span.addTags({"sym.url_method": method})
      // span.addTags({"sym.url_body": prettyPrint(body)})

      let headers = options.headers || {}
      _this.tracer.inject(span, TracerOpenTracing.FORMAT_HTTP_HEADERS, headers)

      console.log(span)

      function success (span, result) {
        this.finishSpan(span)
        // $FlowFixMe
        this._tracing_current_span = span.childOf
        return result
      }

      function failure (span, err) {
        this.finishSpan(span)
        // $FlowFixMe
        this._tracing_current_span = span.childOf
        throw err
      }

      return fetchImplementation(
        url,
        Object.assign(
          {},
          options,
          {headers: headers})
      )
        .then(success.bind(_this, span), failure.bind(_this, span))
    }

    return reactTracingFetch
  }
```

**Comment by sumeetsympatica** [comment]
6) the fetch is wrapped and custom x-data-doh headers are added to all outgoing queries

7) I have reverse proxied a remote datadog agent installed on an aws server using nginx proxy and sendinng appropriae cors headers

**Comment by sumeetsympatica** [comment]
HOWEVER, I am getting BAD REQUEST back from the nginx reverse proxy with nginx log line
```
2018/08/18 01:40:05 [error] 9571#0: *178 connect() failed (111: Connection refused) while connecting to upstream, client: 42.111.145.62, server: dddev.sympatica.health, request: "PUT /v0.3/traces HTTP/1.1", upstream: "http://[::1]:8126/v0.3/traces", host: "dddev.sympatica.health", referrer: "http://localhost:3001/dashboard"
```

the dd-debug trace is:
```
dd-trace debug: Request to the agent: {"protocol":"http:","hostname":"dddev.sympatica.health","port":"","path":"/v0.3/traces","method":"PUT","headers":{"Content-Type":"application/msgpack","Datadog-Meta-Lang":"nodejs","Datadog-Meta-Lang-Version":"v8.11.3","Datadog-Meta-Lang-Interpreter":"v8","Datadog-Meta-Tracer-Version":"0.5.4","X-Datadog-Trace-Count":"1"}} INFO sym-dd-trace-debug

bugsnag.js:1380 DatadogSpan {_parentTracer: DatadogTracer, _operationName: "client", _tags: {…}, _startTime: 1534536377426, _spanContext: DatadogSpanContext}

bugsnag.js:1822 PUT http://dddev.sympatica.health/v0.3/traces 400 (Bad Request)

bugsnag.js:1380 dd-trace debug: Encoding trace: [{"trace_id":1534536377427,"span_id":1534536377427,"parent_id":null,"name":"client","resource":"client","service":"node","error":0,"meta":{"env":"local","sym.url_client":"http://dddev.sympatica.health/v0.3/traces","sym.url_method":"PUT"},"start":1534536377426000000,"duration":245300049}] INFO sym-dd-trace-debug

bugsnag.js:1380 dd-trace debug: Adding encoded trace to buffer: 91 8a a8 74 72 61 63 65 5f 69 64 cb 42 76 54 97 ee 45 30 00 a7 73 70 61 6e 5f 69 64 cb 42 76 54 97 ee 45 30 00 a9 70 61 72 65 6e 74 5f 69 64 c0 a4 6e 61 6d 65 a6 63 6c 69 65 6e 74 a8 72 65 73 6f 75 72 63 65 a6 63 6c 69 65 6e 74 a7 73 65 72 76 69 63 65 a4 6e 6f 64 65 a5 65 72 72 6f 72 00 a4 6d 65 74 61 83 a3 65 6e 76 a5 6c 6f 63 61 6c ae 73 79 6d 2e 75 72 6c 5f 63 6c 69 65 6e 74 d9 29 68 74 74 70 3a 2f 2f 64 64 64 65 76 2e 73 79 6d 70 61 74 69 63 61 2e 68 65 61 6c 74 68 2f 76 30 2e 33 2f 74 72 61 63 65 73 ae 73 79 6d 2e 75 72 6c 5f 6d 65 74 68 6f 64 a3 50 55 54 a5 73 74 61 72 74 d3 15 4b c4 b4 77 64 38 00 a8 64 75 72 61 74 69 6f 6e d3 00 00 00 00 0e 9e fb 51 INFO sym-dd-trace-debug

bugsnag.js:1380 dd-trace ERROR: Error from the agent: 400 Bad Request ERROR sym-dd-trace-error

```

Any help would be appreciated ..

Thanks a lot,
Sumeet

**Comment by rochdev** [comment]
Just wanted to comment on all the points mentioned above for future reference when doing the actual implementation of this.

1. The instrumenter is probably the most difficult part, but parts of it should be extracted to platform to make it also work for the browser as it's the component responsible for loading all integrations, including React.

2. Why the change to `node-int64`? The encoder is using `msgpack-lite` which relies on a `int64-buffer` instance to properly encode/decode 64-bit integers.

3. This information should be available from a new "browser" platform.

4. Which libraries did you need to add?

5. Awesome!

6. What are the custom headers for?

7. This is one of the areas where I'm really not sure the best way to handle this. Maybe some kind of interceptor that allows adding authentication information to the outgoing request before it's sent out?

Also see the list at https://github.com/DataDog/dd-trace-js/issues/48

@sumeetsympatica Thanks for all the work you put into this!

**Comment by sumeetsympatica** [comment]
Hi,

Correction: change to node-int64 was not required... react does support that module. and msgpack-lite worked fine too...

I got it working with React. Will now see if it an also work with RN

And will upload my changes to github as fork once all is working

Happy to contribute :)

**Comment by incorvia** [comment]
@sumeetsympatica Did you ever get this running with RN?

**Comment by sumeetsympatica** [comment]
yes, i did.

I had to clone the repo, comment out auto hooking code and modify some lines and wrap fetch manually

I am travlling at the moment - will be happy to upload a zip of the modified code when i am back...

could you possibly remind me to do so post 4th march?

TIA

**Comment by incorvia** [comment]
Hey @sumeetsympatica  *nudge*, thanks!

**Comment by sumeetsympatica** [comment]
HI Kevin,

 

Thank you for reminding me

 

Could you share your email so I could send the Zip to your directly?

 

Thanks,

Sumeet

**Comment by nsilberman** [comment]
would be great to try it :) thanks @sumeetsympatica

**Comment by sumeetsympatica** [comment]
Have attached the entire modified code as also helper libs used

 

The image shows how the fetch is wrapped and then used for all htpp calls in the RN app

 

Do let me know if any points need clarififcation

 

Most code changes preceded by sumeet

**Comment by fbartho** [comment]
I'd be super interested in using this as well. We're leaning towards using Datadog for some backend instrumentation, and we have react-native apps as well.

@rochdev please let us know if this is on your roadmap.

**Comment by rochdev** [comment]
@fbartho We plan to eventually support browser instrumentation and the most popular frameworks, but it's not on our roadmap at the moment as we are still focusing on Node. I will update all browser related issues when we start working on browser support.

**Comment by rochdev** [comment]
@fbartho Make sure to contact support to make a feature request if you want this feature. The more users request this feature the faster it will be prioritized. We unfortunately don't use GitHub at the moment to prioritize features, so this is very important.

**Comment by arski** [comment]
@sumeetsympatica do you have a clone repo with all your changes where it works in React? I'd love to try it out too, can't wait for browser-js support! :)

**Comment by sumeetsympatica** [comment]
Please share your email and I will send you a zip

**Comment by rochdev** [comment]
@sumeetsympatica Any chance you can push your changes to a fork? This would help other users who would like to use your code or contribute to make this feature move forward.

**Comment by sumeetsympatica** [comment]
I attach it here as a zip – you are welcome to fork and push the code….

**Comment by UmangThapliyal** [comment]
Hello,
I was also trying to implement the datadog to get logs from my react app, I was not able to make it work can you help me in this?

**Comment by rochdev** [comment]
@UmangThapliyal It sounds like you are looking for logs and not tracing. If that's the case, you can use our [@datadog/browser-logs](https://docs.datadoghq.com/logs/log_collection/javascript/) module.

**Comment by rochdev** [comment]
Closing as all functionalities related to the browser, including frameworks like React, have moved to the [Browser SDK](https://github.com/DataDog/browser-sdk).
