### ISSUE TITLE
How can I add the GraphQL Query String / Summary of response to the span?

### ISSUE THREAD

**Issue by sumeetsympatica** [DataDog/dd-trace-js#234]
this would be great to be able to drill down into problematic queries

**Comment by sumeetsympatica** [comment]
I am using apollo-server v2

**Comment by rochdev** [comment]
You should see the GraphQL query already in the span in the `graphql.document` tag.

For the response this is currently not added by the integration. We do add the error if there is one however. What is your use case for viewing the response when the execution is successful?

**Comment by rochdev** [comment]
This other issue was reported in https://github.com/DataDog/dd-trace-js/issues/235. For now I unfortunately don't know of a workaround as I'm not very familiar with schema stitching. A simple check to avoid redefining might work but I'm not sure if it's correct for the use case. I'll try to implement a quick workaround and keep https://github.com/DataDog/dd-trace-js/issues/235 up-to-date.
