### ISSUE TITLE
_addDefaultMeta is not a function -- winston + express + dd-trace issue

### ISSUE THREAD

**Issue by joshribakoff-sm** [DataDog/dd-trace-js#2353]
**Expected behaviour**
Type error / don't crash at runtime.

**Actual behaviour**
No type error / crashes at runtime (can't replicate it anymore)
```
/Users/dromanenko1/code/groundwater/node_modules/winston/lib/winston/create-logger.js:80
        self._addDefaultMeta(info);
             ^
TypeError: self._addDefaultMeta is not a function
    at Server.DerivedLogger.<computed> (/Users/dromanenko1/code/groundwater/node_modules/winston/lib/winston/create-logger.js:80:14)
    at Server.emit (node:events:526:28)
    at Server.emit (/Users/dromanenko1/code/groundwater/node_modules/dd-trace/packages/datadog-instrumentations/src/http/server.js:61:17)
    at emitErrorNT (node:net:1357:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Steps to reproduce**

I am honestly not sure, but here are my notes from when we were reproducing it reliably.

We had this code:
```
// express
  const server = app.listen(PORT, () => {
    return logger.info(`Listening at ${HOST}:${PORT}`);
  });
```

The second argument of `listen` is typed as a function that returns `void`, in the Express types.

 In typescript, `void` is only a guarantee that the caller will not try to consume the return value,[ a function with a non void return value can still be assigned to `() => void` still](https://www.typescriptlang.org/docs/handbook/2/functions.html#return-type-void).

There seems to maybe be something about the [monkey patching being very unreliable in general in dd-trace](https://github.com/DataDog/dd-trace-js/issues/2277#issuecomment-1218324132)? It seems like Express was maybe monkey patched in a way where it does consume the return value, even though the return type of `void` means callers are not supposed to care about the return value. I am not sure, because suddenly we cannot replicate the problem anymore, and we did not change anything.

It seems like either https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-instrumentations/src/http/server.js#L39-L62 or https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-shimmer/src/shimmer.js under certain conditions is causing Winston logger to be called with the wrong value for `this` due to all of the use of `.apply()` and all the monkey patching.  Seemed like maybe by returning the Winston `Logger` interface in the callback passed to the 2nd of `express.listen()`, `dd-trace` took an instance of the Express server and passed it as the value of `this` to the Winston logger. Here is the Winston code where it will try to call the (non existent) method on `this` if it is bound https://github.com/winstonjs/winston/blob/7937f337dac50b4f134bbfa88f72bdd313ad0af5/lib/winston/create-logger.js#L71-L101

We're worried there is some sort of non determinism with this monkey patching...

**Environment**

* **Operation system:**
* **Node.js version:**
* **Tracer version:**
* **Agent version:**
* **Relevant library versions:**

**Comment by joshribakoff-sm** [comment]
You know what, we are working on switching from `npm` to `yarn PNP` and switching branches back and forth, and so it may be happening only when on our `pnp` branch but we incorrectly have `node_modules` folder still present (perhaps with differing versions of things).

Still my point stands that its an unfriendly developer experience

**Comment by Qard** [comment]
We don't patch the part of winston where that error is happening. I think it's likely you just got a corrupted node_modules folder in your conversion and something didn't line up given that you seem to be unable to reproduce the issue. I don't think this is actually an issue on our part. Our instrumentation for winston isn't even in that stack trace, only the instrumentation on the `server.listen(...)` appears.

**Comment by joshribakoff-sm** [comment]
That's fair, however I assumed it was *possible* it is related to `server.listen()` being monkey patched (which is in the stack trace). I am assuming (perhaps incorrectly) that Express itself does not utilize the return value (since the return type is void in their types), and therefore I assumed (perhaps incorrectly) it may be the monkey patching.

 I mostly just wanted the issue tracked in case anyone runs into a similar issue. It seems like we were not able to definitively rule out anything, but yes it does seem like it could be related to having corrupt dependencies

**Comment by Qard** [comment]
Express just defers to the Node.js core `http.Server` listen method, which does nothing with the return value, so definitely nothing there.

**Comment by joshribakoff-sm** [comment]
Yeah I noticed that, and I noticed that is also the method being monkey patched. I was deducing (perhaps incorrectly) since it discards the return value, it "had" to be the monkey patching (but its just speculation on my part)

**Comment by Qard** [comment]
It just passes it through to the caller, so if the other end doesn't do anything with it then it would just get discarded.
