### ISSUE TITLE
mocha this.skip() breaking the flow of mocha tests

### ISSUE THREAD

**Issue by kingatlas** [DataDog/dd-trace-js#2355]
**Code example:**

```javascript
describe("foo", () => {
    before(function () {
        this.skip(); // <-- this is breaking
    })
    it("should be skipped", () => {
        console.log("done")
    });
});
describe("another", () => {
    it("should always run", () => {
        console.log("done")
    });
});
```

**Expected behaviour**
- Calling `this.skip()` inside a `describe()` should just skip the whole block of tests and not fail. like:

```
> debug-dd-trace-mocha@1.0.0 test
> mocha test.js

  foo
    - should be skipped

  another
done
    ✔ should always run


  1 passing (6ms)
  1 pending
```

**Actual behaviour**
- Calling `this.skip()` inside a `describe()` is failing the test suite with:
```
> debug-dd-trace-mocha@1.0.0 traced-test
> NODE_OPTIONS='-r dd-trace/ci/init' mocha test.js

  foo
    - should be skipped
    1) "before all" hook in "foo"
```
- this is also not executing the second test suite.
- in a bigger test suite (can't share it here), the execution is even stuck after calling `this.skip()`.

**Steps to reproduce**
- clone this repo: https://github.com/kingatlas/dd-trace-mocha-debug
- run `npm install`
- run `npm run traced-test` to see that the second test suite is not executed and the skipped test is failing.
- run `npm test` to see the non-instrumented result.

**Environment**

* **Operation system:** Mac OS
* **Node.js version:** v16.13.2
* **Tracer version:** 3.2.0
* **Agent version:** N/A
* **Relevant library versions:** mocha 9.3.1 (also tried mocha 10.0.0)

**Comment by juan-fernandez** [comment]
hi @kingatlas ! Thanks for reporting this issue. It should be fixed in https://github.com/DataDog/dd-trace-js/pull/2363 😄

**Comment by juan-fernandez** [comment]
Also, just tested with `juan-fernandez/fix-mocha-skip` branch with https://github.com/kingatlas/dd-trace-mocha-debug and it seems to work as expected 😄 

Thanks for the reproducible case!

**Comment by kingatlas** [comment]
thanks for the quick fix @juan-fernandez , any idea on which version this would land ? (and when)

**Comment by juan-fernandez** [comment]
there's no fixed schedule but patch releases are done frequently. I'll let you know if I know of a specific date

**Comment by juan-fernandez** [comment]
@kingatlas https://github.com/DataDog/dd-trace-js/releases/tag/v3.3.0 and https://github.com/DataDog/dd-trace-js/releases/tag/v2.16.0 should include this fix 😄

**Comment by kingatlas** [comment]
Thank you @juan-fernandez , I've tested my example an it is working now.
However I'm still having troubles (stuck tests) with my real tests. Will try to find a simple scenario to reproduce it.
