### ISSUE TITLE
In Express in case of error the resource route is not shown

### ISSUE THREAD

**Issue by toniov** [DataDog/dd-trace-js#236]
Hi there!
I'm using the express plugin, and in case a request return an error code (>=500) the route is not shown in the DD APM:

![screen shot 2018-08-16 at 11 35 57_censored](https://user-images.githubusercontent.com/2839810/44185365-d2259700-a14e-11e8-9a93-7b62d78d75d7.jpg)

I could find out that this only happens when I send the  HTTP response outside the route middleware, for example, in an error-handling middleware:

```js
// this works properly
app.get('/bar/foo', function (req, res) {
  res.json(500, { bar: 'foo'});
});
```
```js
// this one not
app.get('/bar/foo', (req, res, next) => {
  next(new Error('foo'));
});
app.use((err, req, res, next) => {
  res.json(500, { bar: 'foo' });
});
```
Also tried using `res.status().json()` and `res.status().send()`, with same results.
It's possible it's related to [this](https://github.com/expressjs/express/issues/2093)?

Also, what is supposed to be shown in the `Error` part? It's always blank.

Details:
>Node version: 8.11.3
Express version: 4.16.3
dd-trace version: 0.5.4

**Comment by rochdev** [comment]
This happens because of an assumption that when `next()` is called, it means it's a middleware and not a route and thus the path is ignored. This is however not true for errors. I'll have a look.
