### ISSUE TITLE
dd-trace net instrumentation producing query on closed connection?

### ISSUE THREAD

**Issue by Saeger** [DataDog/dd-trace-js#2362]
Hi,

We're using MongoDB 4.4 selfhosted and we're facing a production of many of the stack trace below.
I am not really sure why this is happening, but it's performing several operation as:

operation: mongodb.query
resource: hello admin.$cmd

Which I believe it's to get to handshake and get to know the replicasets involved.

```
MongoNetworkError: connection <monitor> to 10.20.180.243:27017 closed
    at Connection.onClose (/engine/node_modules/mongodb/lib/cmap/connection.js:138:19)
    at Socket.<anonymous> (/engine/node_modules/mongodb/lib/cmap/connection.js:65:46)
    at Socket.emit (events.js:388:22)
    at Socket.emit (domain.js:470:12)
    at Socket.emit (/engine/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:61:25)
    at TCP.<anonymous> (net.js:673:12)
    at TCP.callbackTrampoline (internal/async_hooks.js:134:14)
```

**Environment**

* **Node.js version: 14**
* **Agent version: 3.2.0**
* **Relevant library versions: MongoDB 4.7.0 lib and MongoDB 4.4 engine**

**Comment by tlhunter** [comment]
@Saeger is this still an issue for you with recent versions of the libraries?

**Comment by Saeger** [comment]
Hej @tlhunter ,

I will double check this once again since we have bumped the version of dd-trace to latest 4.xx pretty recently. I will get back to you end of this week.

**Comment by Saeger** [comment]
Hi @tlhunter ,

I can confirm that latest versions doesn't seem to be affected by this issue. Currently I have only one microservice running dd-trace @  3.11.0 which have the issue, but all the others running on 4.20.0 doesn't.

I have opened a ticket internally to perform the update of the agent and see if it will address the connection closed problem.
