### ISSUE TITLE
DD_SERVICE_MAPPING not working

### ISSUE THREAD

**Issue by Baune8D** [DataDog/dd-trace-js#2400]
We have a Node.js microservice that connects to a RabbitMQ instance using the `amqplib` npm package. This makes the service also report in to Datadog with a `-amqp` suffix. We want to remap this using `DD_SERVICE_MAPPING` but it does not work.

**Expected behaviour**
Expect the service name to be remapped from `corp.socket-amqp` to `corp.socket` according to `DD_SERVICE_MAPPING`.

**Actual behaviour**
The service ignores `DD_SERVICE_MAPPING` and keeps reporting in using the `-amqp`  suffix.

**Steps to reproduce**
1. Set the following environment variable: `DD_SERVICE_MAPPING=amqp:corp.socket`
2. Start service with `node --require dd-trace/init src/index.js`

**Environment**

* **Operation system:** Alpine 3.16
* **Node.js version:** 16.17.0
* **Tracer version:** 3.3.1
* **Agent version:** 7.39.0
* **Relevant library versions:** `amqplib` 0.10.3

**Comment by rochdev** [comment]
The value being mapped should be the whole service name, so for example `DD_SERVICE_MAPPING=corp.socket-amqp:corp.socket`.

We're also working on removing the suffix entirely for AMQP. This was supposed to be done in 3.0 as we removed suffixes for all other non-database and non-cache spans but we missed this one and are actively working on getting the change out for this as well.

**Comment by Baune8D** [comment]
This is still not working for us with the updated `DD_SERVICE_MAPPING`, services still report in with the `amqp` suffix. But it is not a huge deal for us if its being removed automatically in future tracer version 🙂

**Comment by rochdev** [comment]
Looks like the first value is not the name of the service but instead the name of the plugin, sorry for the confusion. Does it work with `DD_SERVICE_MAPPING=amqplib:corp.socket`?

**Comment by Baune8D** [comment]
> Looks like the first value is not the name of the service but instead the name of the plugin, sorry for the confusion. Does it work with `DD_SERVICE_MAPPING=amqplib:corp.socket`?

That worked! Thanks!
