### ISSUE TITLE
Tracing stops working as long as a DynamoDB action is made.

### ISSUE THREAD

**Issue by quentinbarbault** [DataDog/dd-trace-js#2405]
Hello,

I am currently experiencing a weird problem with lambda, Datadog and dd-trace.
I have tracing with logInjection enabled. 

I manually add each span in my Logger class with winston.

It works great. I can retrieve every logs in Datadog for my lambda, linked to each trace.

Except, in one particular case, where the lambda interacts with DynamoDB via "aws-sdk/clients/dynamodb". Once it does, the whole trace disappears in Datadog for that particular lambda.

The really weird thing is that logs still are available, and correctly formatted with a "dd" object in them. Every identifier matches. 
If the missing lambda triggered another one, I can find logs for the missing one linked to the triggered one, thanks to distributed tracing.

So basically everything is there for Datadog. Except traces for the lambda that made a DynamoDB call.

Do you have any idea ?

Thank you for your help.

> import tracer from "dd-trace";
tracer.init();
export default tracer;

> format.printf(({ level, message }) => {
                    const log: Log = {
                        timestamp: new Date().toISOString(),
                        level: level,
                        domain: this.logContext ? this.logContext.domain : "",
                        requestId: this.logContext ? this.logContext.requestId : "",
                        message: message,
                    };
                    const span = tracer.default.scope().active();
                    if (span) {
                        tracer.default.inject(span.context(), formats.LOG, log);
                    }
                    return JSON.stringify(log);
                })
`

**Comment by rochdev** [comment]
Is this something you can reproduce with a snippet you can share?

**Comment by quentinbarbault** [comment]
Hi @rochdev,

It's part of a huge project. I'll try to recreate the issue on a smaller scale and will come back to you.
Maybe that will help me find the solution too.

Have a good day.

**Comment by quentinbarbault** [comment]
Hi @rochdev,

I managed to get my trace back on Datadog by disabling the aws-sdk module.

`tracer.init().use("aws-sdk", false);
`
I suppose this tells dd-trace to not care about any use of the aws-sdk module, including any import of DynamoDB.

`import DynamoDB, { DocumentClient } from "aws-sdk/clients/dynamodb";`

This does not tell me, however, why I would need to do such a thing. As I would like to see DynamoDB displayed as any other span on Datadog.

I'm using aws-sdk 2.1209.0 (I've seen reports of it not working on aws-sdk v3 yet) with the latest release of dd-trace.

Please note that my dynamo requests don't take much time. So no timeout involved. I'm having troubled finding why this could happened.

Would you have any idea ?
Thank you.

**Comment by rochdev** [comment]
This only tells us that the issue is in the `aws-sdk` plugin, which makes sense since the issue is with DynamoDB. However, we'd really need a reproduction since in our integration tests DynamoDB works properly, so there must be something else causing the plugin not to work properly.

**Comment by quentinbarbault** [comment]
I finally found the issue.

https://github.com/DataDog/datadog-lambda-js/releases

I had not upgraded the datadog nodeLayerVersion in my lambda in quite some time (maybe 3 months) and after searching some more in patch notes, I finally found it :

```
[v6.79.0](https://github.com/DataDog/datadog-lambda-js/releases/tag/v6.79.0)
What's Changed
Bump protobufjs from 6.11.2 to 6.11.3 by https://github.com/dependabot in https://github.com/DataDog/datadog-lambda-js/pull/288
feat: bump dd-trace-js to ^2.9.1 by @astuyve in https://github.com/DataDog/datadog-lambda-js/pull/290
** Fixes a bug where tracing aws-sdk calls will cause the tracer not to flush.
```

And this is the problem right there. When the aws-sdk was used, the trace simply disappeared.

I upgraded everything as it should and everything works as intented.

Thank you for your time.
