### ISSUE TITLE
Report Postgres Process ID as Span Tags

### ISSUE THREAD

**Issue by jcarvalho** [DataDog/dd-trace-js#2420]
In the Postgres plugin, would be great if we could add the Connection's Process ID as a Span Tag. This would make it a lot easier for us to correlate slow queries with Postgres Logs (particularly useful to debug Lock Timeouts).

I have a working implementation of this feature, would be happy to contribute a PR :slightly_smiling_face:

Example:
![image](https://user-images.githubusercontent.com/849596/193319995-0b2377ff-a9da-4470-b13c-084d90105fff.png)

**Comment by rochdev** [comment]
PRs are definitely welcome! Most of our integrations report mostly information based on our limited knowledge of all the different systems we support. We're definitely open to add more data when available and relevant.
