### ISSUE TITLE
Postgres spans stopped being collected after upgrade to v3.4.0

### ISSUE THREAD

**Issue by martinslota** [DataDog/dd-trace-js#2432]
We use the standard Postgres plugin and today we tried upgrading `dd-trace` from version `3.3.1` to version `3.4.0`.

**Expected behaviour**
`pg.query` spans should continue being collected.

**Actual behaviour**
`pg.query` spans stopped being collected.

**Steps to reproduce**
Upgrade to `dd-trace` version `3.4.0`.

**Environment**

* **Operation system:**
* **Node.js version: 18.5.0**
* **Tracer version: 3.3.1 and 3.4.0**
* **Agent version:**
* **Relevant library versions:**

**Comment by Will-Howard** [comment]
I just ran into a similar problem and your PR fixed it, thanks! My issue was that mongo and postgres spans were not being shown as sub-spans in the main request trace

Before using your fix:
<img width="844" alt="Screenshot 2022-10-09 at 10 17 30" src="https://user-images.githubusercontent.com/77623106/194748590-3e90bed9-3a87-4182-ad58-9bc6bf98148f.png">
After using your fix:
<img width="844" alt="Screenshot 2022-10-09 at 10 17 01" src="https://user-images.githubusercontent.com/77623106/194748601-1e9b7736-3b4a-488b-b175-15461a147d83.png">
