### ISSUE TITLE
Customisable runtime metrics config

### ISSUE THREAD

**Issue by csabapalfi** [DataDog/dd-trace-js#2440]
Runtime metrics are great but there's a large number of them.

Large scale deployments could benefit from customising the list of runtime metrics they want to collect to save on cost.

Is that maybe something that can already be achieved? Or Is that something that you'd be willing to accept a PR for?

**Comment by rochdev** [comment]
> to save on cost

Can you clarify this? Runtime metrics should be free, and if they aren't that would be a bug.

**Comment by csabapalfi** [comment]
Ah, ok. So these will not count towards Custom Metrics? Our team is checking with our Datadog CSM to confirm this as well.

If runtime metrics are confirmed to be free then there's very limited benfit or use-cases to implement the proposed feature and happy to close this issue.

**Comment by rochdev** [comment]
> So these will not count towards Custom Metrics?

Correct, these were made free since they are not considered custom and are included in APM, and also to allow us to add/remove them without any changes to billing.

**Comment by csabapalfi** [comment]
That's brilliant news. Thanks a lot!
