### ISSUE TITLE
Memory leak v3.5.0

### ISSUE THREAD

**Issue by theo-mesnil** [DataDog/dd-trace-js#2448]
**Expected behaviour**
No memory leak on server side

**Actual behaviour**
We have done a load test with vegeta to check if we got a memory leak and we got this results:
![Capture d’écran 2022-10-17 à 16 23 00](https://user-images.githubusercontent.com/50322149/196234753-ae9d1f04-ea9f-47c3-837a-7d21ab1051f3.png)

**Steps to reproduce**
- yarn dd-trace (v3.5.0)
- create a file for tracer
```js
import tracer from 'dd-trace'

tracer.init({ service: 'xxxx', profiling: true, runtimeMetrics: true })

export default tracer
```
- import tracer before all our server code

**Environment**

* **Node.js version:** 16.13.1
* **Tracer version:** 3.5.0

**Comment by rochdev** [comment]
Did it result in an out-of-memory exception? Also, did the problem appear after a dd-trace upgrade or did you just install the library?

**Comment by theo-mesnil** [comment]
Hi @rochdev :)

We did a load test before and after dd-trace on our code :

Before dd-trace, result of load testing:
![Capture d’écran 2022-10-11 à 15 48 06](https://user-images.githubusercontent.com/50322149/196385068-7dd2b9ae-d940-4dde-9b50-7acb2a0a83ef.png)

After dd-trace, result of load testing:
![Capture d’écran 2022-10-17 à 16 23 00](https://user-images.githubusercontent.com/50322149/196384330-d2a51063-2a6f-4f93-8e27-cc7add143111.png)

**Comment by Qard** [comment]
Looks like you're using profiling. Can you share what your heap profiler data looks like during that load test?

**Comment by rochdev** [comment]
@theo-mesnil Did you try disabling the profiler? Since you have runtime metrics enabled as well, I'd try to disable that too so that we can narrow down the issue to tracing. Also, we've seen reports of upgrading Node fixing memory leak issues, so might be worth a shot to try upgrading to the latest 16.x. And lastly, did the issue start after upgrading dd-trace or was it a fresh install?

**Comment by theo-mesnil** [comment]
@Qard @rochdev i'll keep you updated tomorrow after new load testing :)

**Comment by theo-mesnil** [comment]
We upgraded nodejs for our tests to v16.18.0.

With profiling we got a memory leak who take more time to get the crash:
![Capture d’écran 2022-11-02 à 17 07 06](https://user-images.githubusercontent.com/50322149/199542045-db0b9523-8446-44e6-bb36-d5777c980260.png)

When we removed the profiling we got the same result:
![Capture d’écran 2022-11-02 à 18 20 37](https://user-images.githubusercontent.com/50322149/199558039-446ef38d-ff19-40ce-935f-9b5126912a1b.png)

**Comment by rochdev** [comment]
@theo-mesnil What about runtime metrics and the last version of dd-trace that was not causing a leak?

**Comment by theo-mesnil** [comment]
@rochdev it's a fresh install for dd-trace, we got the last version 3.7.1 (same with 3.7.0)
I removed metrics and profiling and the result:

![Capture d’écran 2022-11-03 à 10 27 08](https://user-images.githubusercontent.com/50322149/199686418-8474833d-1c84-458d-9970-8582299744f3.png)

**Comment by rochdev** [comment]
I would recommend opening a [support](https://www.datadoghq.com/support/) issue so that we can collect more information about your environment and look into your account.

**Comment by theo-mesnil** [comment]
Thanks @rochdev i will open a support issue :)

**Comment by tlhunter** [comment]
@theo-mesnil were you able to open a support issue? If so I'll close this GH issue out.

**Comment by theo-mesnil** [comment]
Hi @tlhunter, yes thanks i need to make some test with them :)
