### ISSUE TITLE
Question regarding validateStatus http-plugin

### ISSUE THREAD

**Issue by steinarxff** [DataDog/dd-trace-js#2475]
Background; we want to filter out 404 as errors in some cases as they are used in application logic.

I think I've found how to do it.

But [documentation ](https://datadoghq.dev/dd-trace-js/interfaces/plugins.http.html#validatestatus) says the following;

Callback function to determine if there was an error. It should take a status code as its only parameter and return true for success or false for errors.
default: code => code < 400 || code >= 500

To me this looks like only 400-499 counts as errors. Status codes from and above 500 will return true and be viewed as success? 
Whats the reasoning behind this?

Am I missing something, or am I looking at the wrong place?

**Comment by rochdev** [comment]
From an HTTP client perspective, if the status code from the remote server is 500, it means there was an issue with the server and not the client. The client could handle this gracefully, or it could re-throw in which case it would also become an error, but the status code itself doesn't indicate an issue with the client.

**Comment by jkalberer** [comment]
@steinarxff how do you filter these? We have a dependency on an AWS library and want to filter the 404s as well.

**Comment by steinarxff** [comment]
@rochdev Thanks for the explanation. It does assume a lot of things that doesnt necessarily reflect the real world, but I can get behind the idea.

@jkalberer To my understanding you have to override the validateStatus function in the code which initiates the dd-tracer.

**Comment by tlhunter** [comment]
Looks like Roch was able to answer OP's question. If this isn't the case feel free to reopen.
