### ISSUE TITLE
Trace ID not injected in my (winston) custom logs from my NodeJS lambda function

### ISSUE THREAD

**Issue by ludocoding** [DataDog/dd-trace-js#2479]
**Expected behaviour**
The Datadog extension from my lambda functions should automatically inject trace ID into my logs (emitted from winston in NodeJS)

**Actual behaviour**
Only logs emitted from the Datadog extension have trace ID, not the log emitted from my application

**Steps to reproduce**
```
// tracer.ts

import tracer from 'dd-trace';

// initialized in a different file to avoid hoisting.
tracer.init({
  logInjection: true
});

export default tracer;
```

```
// lambda.ts

import './tracer';

import { createLogger, format, transports } from 'winston';

const logger = createLogger({
  level: 'info',
  exitOnError: false,
  format: format.json(),
  transports: [
    new transports.Console()
  ]
});

export async function handler(): Promise<any> {
  logger.log('info', 'Log from my lambda function!');

  return {
    text: "ok",
  };
}
```

**Environment**

* **Operation system:** Lambda functions from AWS
* **Node.js version:** 16
* **Tracer version:** 3.6.0
* **Relevant library versions:**

I am using a lambda in NodeJS with 2 Datadog layers
* **Datadog-Node16-x:** 84
* **Datadog-Extension:** 31

I am using the "Log Forward" strategy, so i have a lambda that collect the logs from other lambda functions in Cloudwatch, then send it to Datadog.

When i invoke my lambda, then i go to "Infrastructure > Serverless" and i open my lambda in the Datadog UI, i can see the invocations, and when i click on it, i see some logs that don't come from my application, but (i guess) from the layer (Datadog Extension), i have 5 of it at every invoke:
- REPORT
- LOGS
- EXTENSION
- START
- END 

But when i access the "Logs" tab of the lambda function (without going thought the invocation), i see more:
- REPORT
- LOGS
- EXTENSION
- START
-  my custom log 1
-  my custom log 2
- END 

When i check every logs emitted from de Datadog Extension, they do have a very clean trace in the "Trace" tab pulled from Xray.
But when i check my custom logs, i have a "No Trace associated with this Log" message.

I can't see what i missed, my logs are clean, but there is no correlation with the trace ID / context of the lambda invoke.
Also i don't see any RequestId, traceId or anything in my custom logs.

One curios thing i noticed is that the logs emitted from the Datadog Extension are not in JSON.

Note: I do have the `DD_LOGS_INJECTION` env var set to `true`

I just followed these documentations: 
- https://docs.datadoghq.com/tracing/other_telemetry/connect_logs_and_traces/nodejs
- https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/nodejs/?tab=awslambda

**Comment by tlhunter** [comment]
@ludocoding The dd-trace package is by default catered more towards traditional Node.js applications. For example, that log injection feature works for injecting logs into common HTTP frameworks.

For your Lambda project I think you'll like the [datadog-lambda-js](https://github.com/DataDog/datadog-lambda-js) package. It ultimately wraps dd-trace but also provides a bunch of Lambda niceties. This includes capturing the trace ID from the current Lambda invocation to be injected into the logs.

**Comment by ludocoding** [comment]
Hi @tlhunter,

Thanks for your answer.

There is a specific documentation for serverless here: https://docs.datadoghq.com/serverless/configuration/?tab=datadogcli#connect-logs-and-traces

It says "If you are using the Lambda extension to collect traces and logs, Datadog automatically adds the AWS Lambda request ID to the aws.lambda span under the request_id tag"

I am using this Lambda Extension and it doesn't do anything.

From what i have read datadog-lambda-js can be usefull if you want to create custom metrics, span and so on...

It can be interesting, but i would like to go step by step, and first enable the "basic" Trace feature.

Did you see this documentation?
I don't get what i miss.

**Comment by astuyve** [comment]
Hi @ludocoding - thanks so much for reaching out.

We do automatically inject trace context [here](https://github.com/DataDog/datadog-lambda-js/blob/main/src/trace/patch-console.ts#L34-L82).

Although I'd like to point out that if you're using the Datadog Lambda Extension, you don't need to configure the Datadog Forwarder - the extension can send logs itself.

That said this is definitely something I'd like to help you fix.
I'm going to take your example and try to reproduce - do you think you could close this issue and recreate it in https://github.com/datadog/dd-lambda-js?

Thanks!!

**Comment by astuyve** [comment]
Hi @ludocoding - based off of your example I've tried to reproduce this on my own.

Handler:
```js
"use strict";
const { createLogger, format, transports } = require("winston");

const logger = createLogger({
  level: "info",
  exitOnError: false,
  format: format.json(),
  transports: [new transports.Console()],
});

module.exports.hello = async (event) => {
  logger.log("info", "hello this is from my lambda function");
  return {
    statusCode: 200,
    body: JSON.stringify(
      {
        message: "Go Serverless v1.0! Your function executed successfully!",
        input: event,
      },
      null,
      2
    ),
  };
};

```

serverless.yml
```yml
service: logs-loss
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
custom:
  datadog:
    apiKey: <my key>

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          method: "get"
          path: /hello

plugins:
  - serverless-plugin-datadog
```
Note that I didn't create a `tracer` file because if you're using the datadog lambda layer, this is already done for you. You shouldn't need to set `logsInjection`, as that's the default behavior.

After a minute or so I was able to see the Lambda Logs in the Serverless page, as well as the APM view.
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/1598537/198712110-3c4ebd8b-cea1-4016-8f23-1dbebe16c0d9.png">
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/1598537/198712148-25e72894-4c4b-4615-ab4f-9e7ba9389de8.png">

I was also able to see the logs appear very quickly in the `logs` section by switching to the `live` view in the time-picker.

Could you share a bit more about your configuration and what you're seeing? If you're still experiencing this, opening a support ticket and sharing specifics may be the fastest way we can resolve this.

Thank you!

**Comment by ludocoding** [comment]
Hi @astuyve,

I have just discover the issue, it was just my `site` variable, `datadoghq.com` instead of `datadoghq.eu` (using the Datadog CDK construct)...

I didn't have any error, when you told me the log forwarder is optional i tried to understand why my logs didn't go to Datadog if i didn't use it, and figured out this mistake in my construction parameters...

So sorry for the lost of time!

**Comment by astuyve** [comment]
No problem at all, very happy to help. I'm glad you got things sorted out!
