### ISSUE TITLE
Doesn't support subscriptions

### ISSUE THREAD

**Issue by clayne11** [DataDog/dd-trace-js#248]
[This PR](https://github.com/DataDog/dd-trace-js/pull/180/files) added support for mutations but there's still no support for subscriptions. We need to add `subscription` to the types array.

```tsx
const types = ['query', 'mutation', 'subscription']
```

Without this change every subscription call is crashing my app. With the change made everything works as expected.

**Comment by rochdev** [comment]
What is the error you are getting? Unsupported types should simply be ignored and not crash the application, so this is definitely a bug. For example, if a new type is added in the future which we don't yet support, it should not crash.

**Comment by clayne11** [comment]
The issue is [these lines](https://github.com/DataDog/dd-trace-js/blob/de7d346419c76f9b233270c0818bb20863c0e94f/src/plugins/graphql.js#L15-L17):

```js
// top of graphql.js
const operation = getOperation(document)

if (!schema || !operation || typeof fieldResolver !== 'function') {
  return execute.apply(this, arguments)
}

// lower down
function getOperation (document) {
  if (!document || !Array.isArray(document.definitions)) {
    return
  }


  const types = ['query', 'mutation']
  const definition = document.definitions.find(def => types.indexOf(def.operation) !== -1)


  return definition
}
```

Since `subscription` isn't in the types then the `execute` function never gets called. If we want to ignore it we need to make sure that `execute` gets called, just that the tracking doesn't occur.
