### ISSUE TITLE
FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema"

### ISSUE THREAD

**Issue by duki994** [DataDog/dd-trace-js#2481]
A deprecation warning appears when instrumenting fastify code.

Here is relevant stack trace
`(node:13084) [FSTDEP012] FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in `fastify@5`. at Object.emit (/home/dusank/source/repos/h10-adtomic-proxy/node_modules/process-warning/index.js:52:13) at _Request.get (/home/dusank/source/repos/h10-adtomic-proxy/node_modules/fastify/lib/request.js:159:15) at Object.preparsingRawBody (/home/dusank/source/repos/h10-adtomic-proxy/node_modules/fastify-raw-body/plugin.js:59:32) at next (/home/dusank/source/repos/h10-adtomic-proxy/node_modules/fastify/lib/route.js:546:16) at preParsingHookRunner (/home/dusank/source/repos/h10-adtomic-proxy/node_modules/fastify/lib/route.js:569:3) at runPreParsing (/home/dusank/source/repos/h10-adtomic-proxy/node_modules/fastify/lib/route.js:520:5) at Object.routeHandler (/home/dusank/source/repos/h10-adtomic-proxy/node_modules/fastify/lib/route.js:469:7) at Object.wrapper [as handler] (/home/dusank/source/repos/h10-adtomic-proxy/node_modules/dd-trace/packages/datadog-instrumentations/src/find-my-way.js:15:22) at Router.callHandler (/home/dusank/source/repos/h10-adtomic-proxy/node_modules/find-my-way/index.js:413:14) at Router.lookup (/home/dusank/source/repos/h10-adtomic-proxy/node_modules/find-my-way/index.js:391:17)`

Seems like `find-my-way.js` is using `request.context` property which is deprecated in fastify

**Expected behaviour**
No deprecation warnings

**Actual behaviour**
FastifyDeprecation warning appears.

**Steps to reproduce**
Run any fastify app (4.9+ versions) with any Node 16 LTS/

**Environment**
* **Operating system: Linux Mint 20.3**
* **Node.js version: 16.17.0**
* **Tracer version: 3.6.0**

**Comment by rochdev** [comment]
It looks like the issue is in `find-my-way` and not in `dd-trace`, especially since we don't use `request.context`. Do you have the same issue without dd-trace?

**Comment by duki994** [comment]
Was issue in another library. 
Somehow it surfaced when dd-trace was instrumenting code.
