### ISSUE TITLE
Some Runtime metrics not reporting after upgrade to node v18

### ISSUE THREAD

**Issue by dearcodes** [DataDog/dd-trace-js#2482]
**Expected behavior**
Runtime metrics mentioned [here](https://docs.datadoghq.com/tracing/metrics/runtime_metrics/nodejs/?tab=environmentvariables#data-collected) should report 

**Actual behavior**
Most `node.runtime` metrics are no longer present
<img width="1700" alt="Screenshot 2022-10-31 at 12 38 56" src="https://user-images.githubusercontent.com/1930813/198999488-dc676ea1-a9c7-42f4-84e3-6058c5c77a07.png">

**Steps to reproduce**
Upgrade to node v18

**Environment**

* **Operation system:** Linux
* **Node.js version:** 18
* **Tracer version:** 1.50 (happens also if I upgrade to 3.6.0
* **Agent version:**
* **Relevant library versions:**

**Comment by rochdev** [comment]
Did you also update dd-trace? What version are you using? Basically, was there any other differences other than upgrading Node?
