### ISSUE TITLE
[NextJS] Add tracing functionality for render, renderHTML methods

### ISSUE THREAD

**Issue by mwisner** [DataDog/dd-trace-js#2525]
Hi,

With regards to the `nextjs` plugin, we are looking to add traces around the time nextjs spends rendering the page. 

It looks like the DD trace plugin: https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-instrumentations/src/next.js#L130-L152 

I was wondering if it would be possible to wrap `render` and `renderToHTML` as well? 

Or is there some other strategy that might be better?

**Comment by david-alpert-nl** [comment]
is there a reason this was closed as not planned without any explanation? perhaps related to NextJS 13's experimental (but still broken) move to support OpenTelemetry?
