### ISSUE TITLE
Integrate Event Loop Utilization (ELU) metric

### ISSUE THREAD

**Issue by mrkosima** [DataDog/dd-trace-js#2533]
Hello there!
I didn't find any docs or code related to the question, therefore I'm creating this issue.

Node.js provides a very useful metrics - Event Loop Utilization (ELU):
https://nodesource.com/blog/event-loop-utilization-nodejs
https://www.youtube.com/watch?v=WetXnEPraYM

We use custom metrics to track ELU.
Also it's integrated into our DD dashboards and helps a lot to observe the load of the node service ([Saturation from golden signals](https://sre.google/sre-book/monitoring-distributed-systems/#xref_monitoring_golden-signals)):

![image](https://user-images.githubusercontent.com/6384121/201884386-35f4377b-53a8-4048-ac38-fc3d77272402.png)

And it would be great to have the metrics "from the box" in dd-trace. 

Do you plan to support ELU for node monitoring?

**Comment by mrkosima** [comment]
Thanks for the reply, @rochdev.
You're right, DD provides some metrics for related monitoring, like:
- Event Loop Iterations Per Second
- Event Loop Delay Per Second

But the problem is that they are too abstract, correlating only with the previous state and do not provide details how healthy the service is.

In the case of ELU, it provides absolute values of the service state and an understanding of how the service configuration is optimised for the current load (e.g. number of instances).

**Comment by rochdev** [comment]
@mrkosima I'm not sure I understand the distinction. The event loop delay is reported per second, but it's still the absolute value for each second, which is then reported over time, which seems to be the same as your screenshot from above. The only difference that I can see is the unit used, but both units can be correlated to each other. Do you have an example where the ELU works and the metric we currently report doesn't? (ideally with screenshots of the difference)

**Comment by mrkosima** [comment]
hey @rochdev , thanks for the response.

We have many services running in prod, but let's look only on two of them.
Here's the chart for two different services that shows some spikes of Event Loop Delay:

<img width="800" alt="event loop delay" src="https://user-images.githubusercontent.com/6384121/208680956-feb0663d-5e0b-49ea-a7a5-5135175ca85a.png">

The purple line (_service_A_) shows an Event Loop Delay peak  at 16:30.
The blue one (_service_B_)  - around 21:00.

Two services have own CPU / Memory limits
And it's not clear about the causes of the delays, neither how bad those spikes.

This is the ELU charts for almost the same time span:
<img width="800" alt="ELU" src="https://user-images.githubusercontent.com/6384121/208681435-82afd05c-bffe-4e2d-87de-80ddecb9bbe3.png">

ELU chart shows that _service_A_ was utilising about 40% of Event Loop during the peak.
While the _service_B_ reached 100% ELU around 21:00. 

There might be several causes for issues with _service_A_,  we need to dive deeper to analyse the root cause.

But with _service_B_ it's visible that the service load is close to the capacity, so we need to scale up (horizontally or vertically) the service.

**Comment by rochdev** [comment]
Both values are mostly reporting on the same thing but in different ways, so I wouldn't really expect such a big difference as seen above, unless there is a very high event loop iteration count. This is something we'll have to look into, but at the end of the day it should also still be possible to have both metrics, they should just not be _that_ different.

**Comment by MikeKoval** [comment]
@mrkosima how do you set up your custom metric of ELU? i am looking for ELU also, current values are really a bit abstract and i am used to ELU when worked with Heroku.

**Comment by tlhunter** [comment]
Support for this was added in #2846 so I'll close this issue out. Please give it a try. If it doesn't work then please tag me and reopen this issue!
