### ISSUE TITLE
MongoDB no longer sanitizes resource_names

### ISSUE THREAD

**Issue by vanstinator** [DataDog/dd-trace-js#2536]
**Expected behaviour**
MongoDB traces should be sanitized. They were removed in https://github.com/DataDog/dd-trace-js/pull/2295

The justification was that the Agent can already do this.

**Actual behaviour**
The agent only sanitizes the tags, not the `resource_name`. This leads to all of the find queries for a given service appearing as separate resources making it much harder to aggregate and in our case blocking the majority of the traces
<img width="368" alt="image" src="https://user-images.githubusercontent.com/577219/202014438-5a5d373b-95d3-423b-a0f1-cdb5e5b710f4.png">

The [documentation for the agent](https://docs.datadoghq.com/tracing/configure_data_security/?tab=mongodb#agent-trace-obfuscation) suggests that this obfuscation behavior is intentional. If a GHI with the agent project would be helpful I can file there as well but it seems as if the dd-trace-js library should provide an opt-in to the old behavior.

The current behavior makes the data much less valuable in our case as the broad strokes of the obfuscated query shapes was much more useful for us.

**Steps to reproduce**

**Environment**

* **Operation system:**
* **Node.js version:** 18.X
* **Tracer version:** 3.7.1
* **Agent version:** v7.40.1
* **Relevant library versions:**
*

**Comment by vanstinator** [comment]
Would a configuration option for this behavior be acceptable? Or is there somewhere else I should be looking/asking for this?

**Comment by robsman** [comment]
For us, a config option would be great. Ideally similar to the agent config, allowing to exclude selected keys from sanitization.

**Comment by Qard** [comment]
This should be fixed soon by https://github.com/DataDog/dd-trace-js/pull/2631.
