### ISSUE TITLE
dd-trace crashes when formatting tags which don't extend from the Object.prototype

### ISSUE THREAD

**Issue by dmg3** [DataDog/dd-trace-js#2542]
**Expected behaviour**
When adding tags to a span, if an an object with no prototype is passed as a tag then it should accept the tag with out erroring. 

**Actual behaviour**
Currently the application crashes with an error when an object with no prototype is passed in:
```javascript
my_app/node_modules/dd-trace/packages/dd-trace/src/format.js:163
          if (!value.hasOwnProperty(prop)) continue
                     ^

TypeError: value.hasOwnProperty is not a function
```

**Steps to reproduce**
Create a simple object with no prototype, like this: 
```javascript
let myTags = Object.create(null);
myTags['key']='my value'
tracer.scope().active().addTags(myTags);  // Uncaught TypeError: myTags.hasOwnProperty is not a function

//Example output from console
console.log(myTags.hasOwnProperty('key')) // Uncaught TypeError: myTags.hasOwnProperty is not a function
console.log(Object.prototype.hasOwnProperty.call(myTags, 'key')) // true
```
myTags.hasOwnProperty is undefined - this causes an issue in [dd-trace format.js](https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/format.js#L178) because it attempts to call hasOwnProperty 

The following code appears to be equivalent and won't cause issues with the above tags object:
`!Object.prototype.hasOwnProperty.call(value, prop)`

**Environment**

* **Operation system:**
18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* **Node.js version:**
 v14.18.2
* **Tracer version:**
3.8.0
* **Agent version:**
7.35.2-jmx
* **Relevant library versions:**

    "dependencies": {
        "dd-trace": "^3.8.0"
    }

**Comment by andreeatirgovatustockX** [comment]
I have the same issue.

**Comment by Qard** [comment]
#2687 should fix this when it lands. :)

**Comment by dmg3** [comment]
> 

Awesome, thank you!
