### ISSUE TITLE
A request to move @airbnb/node-memwatch to devDependencies in package.json

### ISSUE THREAD

**Issue by ColinBradley** [DataDog/dd-trace-js#257]
Any chance of `@airbnb/node-memwatch` being moved into a `devDependency` in `package.json`? As it's just increasing CI times for us - especially sad as it is a dev dependency. It also causes errors that get ignored in some environments (not a real bother or your problem).
I have resorted to using the `--no-optional` flag for `npm install` and `npm prune` and that does avoid the problem. Using that flag feels a little heavy handed for just your package though.

Although this isn't your problem, the errors I get look like:

    ..\src\memwatch.cc(19): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory [...\node_modules\@airbnb\node-memwatch\build\memwatch.vcxproj]
    ..\src\heapdiff.cc(291): warning C4244: 'argument': conversion from 'unsigned __int64' to 'v8::SnapshotObjectId', possible loss of data [...\node_modules\@airbnb\node-memwatch\build\memwatch.vcxproj]
    ..\src\heapdiff.cc(303): warning C4244: 'argument': conversion from 'unsigned __int64' to 'v8::SnapshotObjectId', possible loss of data [...\node_modules\@airbnb\node-memwatch\build\memwatch.vcxproj]
    ..\node_modules\nan\nan_new.h(208): warning C4244: 'argument': conversion from 'unsigned __int64' to 'double', possible loss of data (compiling source file ..\src\heapdiff.cc) [...\node_modules\@airbnb\node-memwatch\build\memwatch.vcxproj]

I understand that you might not want dev package restores to fail, but increasing everyone else's bother isn't great either.

Anyway, just a humble request :)

**Comment by rochdev** [comment]
That was actually a mistake on my part. I moved it from `devDependencies` to `optionalDependencies` because it doesn't install on Node <8 but I forgot that `optionalDependencies` are not installed only in dev. I'll simply remove the dependency completely and install it as a build step.
