### ISSUE TITLE
Feature request (expressjs): allow to skip instrumentation in certain routes

### ISSUE THREAD

**Issue by aledbf** [DataDog/dd-trace-js#258]
Right now all the routes are instrumented but some like `/healthz` could be used in some probes (Kubernetes) that cause lots of (unnecessary) traces

**Comment by rochdev** [comment]
It's possible to ignore routes directly in the agent. See https://github.com/DataDog/datadog-agent/blob/master/pkg/config/config_template.yaml#L594

**Comment by aledbf** [comment]
@rochdev thank you. That works for me.
