### ISSUE TITLE
Feature request: ioredis

### ISSUE THREAD

**Issue by aledbf** [DataDog/dd-trace-js#259]
The redis module lacks support for sentinel, something that works OOTB in ioredis. Adding additional modules for redis to support the sentinel protocol breaks the instrumentation

**Comment by rochdev** [comment]
> Adding additional modules for redis to support the sentinel protocol breaks the instrumentation

Do you mean that it crashes in some way, or that it just stops instrumenting?

**Comment by aledbf** [comment]
>  or that it just stops instrumenting?

that

**Comment by rochdev** [comment]
Interesting. Which additional module caused this?

**Comment by rochdev** [comment]
I opened another issue to track the problem with `redis-sentinel` specifically.

Otherwise, we do plan to support ioredis in the future.

**Comment by aledbf** [comment]
@rochdev thanks!

**Comment by rochdev** [comment]
Released in v0.6.0
