### ISSUE TITLE
TypeError: activeSpan.context is not a function

### ISSUE THREAD

**Issue by demdh** [DataDog/dd-trace-js#2593]
```
/app/node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:269
    const spanContext = activeSpan && activeSpan.context()
                                                 ^
TypeError: activeSpan.context is not a function
    at Object.startChildSpan (/app/node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:269:50)
    at Object.startSpan (/app/node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:112:18)
    at /app/node_modules/dd-trace/packages/datadog-plugin-http/src/server.js:21:24
    at Subscription._handler (/app/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:14:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at Server.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/server.js:48:21)
    at parserOnIncoming (node:_http_server:1068:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)

Node.js v18.12.1
```

**Environment**

* **Node.js version:** 18.12.1
* **Tracer version:** 3.9.1

**Comment by tomhallam** [comment]
+1

This is stopping my application from starting properly. Need to pin previous version to resolve.

**Comment by richardsimko** [comment]
+1 Happening to us as well causing random crashes

**Comment by osher** [comment]
we got the same problem.
our work around is:
```
"dependencies": {
    "dd-trace": "^2.12.1 < 2.21.99 || 2.22.2 < 2.99",
```
hoping that 2.22.2 will fix that...

**Comment by osher** [comment]
uh - one question:
the big problem is that it did not "fail-fast" - i.e - the services launched and starting responding to health-check - so deployments completed successfully. 
HOWEVER - after ~30 sec - the first trace/apm/whatever fired - and the services crashed, where by that time - it is too late.

Is there something that can be done that will help it fail fast in such a future case?
I don't mind if it's a user-action - tell me what it is, I'll take it.
All our services get dd-trace through our logger package - so we can do it there.

Thanks

**Comment by MikeKoval** [comment]
Bumped into same issue on node v16.18.1

**Comment by pintojeremy** [comment]
Might be related to PR #2581

**Comment by marr** [comment]
+1 app down!

**Comment by tlhunter** [comment]
We're working on fixing this right now.

Please revert to v3.9.0 in the meantime. We should have a 3.9.2 released to fix this soon.

**Comment by akbar-myant** [comment]
bump

**Comment by tlhunter** [comment]
We're trying to figure out how this could happen. We could quickly revert the commit but we'd like to find the core issue.

Out of curiosity, what web frameworks are y'all using? Feel free to reply or email me at `{my github username} @ datadog.com`. If you send your package.json dependencies that could help too.

**Comment by richardsimko** [comment]
We're running Koa, I sent you the exact list of dependencies via email

**Comment by SterlingKelley** [comment]
We're encountering this issue with ` "@hapi/hapi": "^20.2.1",`

**Comment by donleistman** [comment]
Hi, we encountered this issue today when upgrading from v2.22.0 to v2.22.2. 

It looks like the bug introduced in v2.22.1 may not have been fixed in v2.22.2 as intended. We're rolling back to v2.22.0 for now.

**Comment by undees** [comment]
Just checking in—has anyone upgraded to one of the fixed versions and seen the problem go away?

**Comment by richardsimko** [comment]
Yeah I can confirm the fix worked for us with Koa. After all it was just a rollback of the change that caused the issue to begin with.
