### ISSUE TITLE
I cannot see data if I use a { Worker } = require('worker_threads');

### ISSUE THREAD

**Issue by royalcala** [DataDog/dd-trace-js#2616]
**Expected behaviour**

have data in datadog APM
**Actual behaviour**

I dont see any data in datadog APM
**Steps to reproduce**

**Environment**

* **Operation system:mac
* **Node.js version:16.13.2
* **Tracer version:3.9.3
* **Agent version:**
* **Relevant library versions:**

{
  "name": "taxi-admin-backend",
  "version": "1.0.0",
  "description": "Taxi backend",
  "main": "index.js",
  "scripts": {
    "lint": "eslint .",
    "lint:fix": "eslint . --fix",
    "pretest": "npm run lint",
    "test": "jest",
    "test:refactor": "jest /Users/mcronin/Projects/mktg/taxi/backend/gql-main/schema/gql.refactor.spec.js --no-coverage",
    "start": "node index.js",
    "start-debug": "node --inspect index.js",
    "restore-db": "./scripts/restore_local_db.sh"
  },
  "private": true,
  "dependencies": {
    "@graphql-tools/schema": "^9.0.2",
    "@slack/webhook": "^6.1.0",
    "analytics-node": "^6.0.0",
    "apollo-server-core": "^3.10.2",
    "apollo-server-express": "^3.10.2",
    "aws-sdk": "^2.10.0",
    "body-parser": "^1.20.1",
    "cookie-parser": "^1.4.3",
    "cors": "^2.8.1",
    "dd-trace": "^3.9.3",
    "express": "^4.18.2",
    "express-graphql": "^0.12.0",
    "graphql": "^15.8.0",
    "graphql-date": "^1.0.3",
    "graphql-type-json": "^0.2.0",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.19",
    "morgan": "^1.9.0",
    "node-fetch": "^2.6.7",
    "passport": "^0.6.0",
    "passport-saml": "^3.2.4",
    "pg": "^8.7.3",
    "pug": "^3.0.1",
    "sequelize": "^6.11.0",
    "winston": "^3.3.3"
  },
  "devDependencies": {
    "eslint": "^8.2.0",
    "frisby": "^2.0.16",
    "jest": "^27.3.1"
  }
}

**Comment by bengl** [comment]
Hi @royalcala. Currently, worker threads are treated the same as a separate Node.js process, so you'll have to initialize `dd-trace` in each worker thread.

**Comment by furstenheim-goodnotes** [comment]
Hi @bengl, could you point to a doc on how to connect the traces in the two different processes

**Comment by furstenheim-goodnotes** [comment]
Hi, I see this is closed but no direction to documentation
