### ISSUE TITLE
Question: mongodb child span

### ISSUE THREAD

**Issue by aledbf** [DataDog/dd-trace-js#262]
What's the correct way to create a child span with some mongodb operation?
Using something like the next snippet I get all the mongodb tracing information in the rootSpan.

```
    return new Promise((resolve) => {
      const processSpan = tracer.startSpan('crear-proceso', { childOf: rootSpan });

      setImmediate(async () => {
        const scope = tracer.scopeManager().activate(processSpan);
        const span = scope.span();

        let proceso = mongoose.models.Proceso();
        .....


        let [err, newproceso] = await wait(proceso.save());
        ....

        span.finish();
        scope.close();

        resolve();
      });
    });
```

**Comment by rochdev** [comment]
This seems to be correct. Is it possible that Mongoose uses an internal queue and executes `save()` in a different context? If this is the case then the library would need to be patched for this to work.

Is the code simple enough that you can try to replace all the `async/await` statements with promises? It should work the same, but it would at least eliminate the possibility that there is some incompatibility with `async/await`.

Also, what is `wait()` doing?

**Comment by aledbf** [comment]
@rochdev `wait` is this module https://www.npmjs.com/package/await-to-js
(just a wrapper to avoid `then` and `catch` with promises

**Comment by aledbf** [comment]
> Is it possible that Mongoose uses an internal queue and executes save() in a different context? 

Good question. I am going to enable debug in mongoose and the trace library to see if I can get this info

**Comment by rochdev** [comment]
I've been researching this recently and Mongoose definitely uses an internal task queue, but it looks to be only used while connecting. I will need to investigate further to make sure this is the case.

@aledbf Do you still have the issue with the new scope manager introduced in 0.9.0?

**Comment by andrewsouthard1** [comment]
@aledbf going to close this for now but please let us know if you still have any questions.
