### ISSUE TITLE
Mongo statement should not be part of the resource name

### ISSUE THREAD

**Issue by matehuszarik** [DataDog/dd-trace-js#2622]
**Expected behaviour**
Mongo span resource name should not include the statement.

**Actual behaviour**
Resource name is `find dbName.collectionName { ...query }` instead of `find dbName.collectionName` and the operations are not grouped in Datadog UI.

**Steps to reproduce**
```
tracer.use('mongodb-core', {
  service: 'mongo'
})
```

**Environment**

* **Operation system:** linux
* **Node.js version:** 16.18.1
* **Tracer version:** 3.9.3
* **Agent version:**
* **Relevant library versions:** mongoose 6.8.0

I'm happy to do a PR removing the query at this [this line](https://github.com/DataDog/dd-trace-js/blob/5dd23e7a60325a73c1445045f6ae76a7a814a7aa/packages/datadog-plugin-mongodb-core/src/index.js#L34).

**Comment by vanstinator** [comment]
Is the problem that the query shape is included in the resource name, or is the problem that the query _values_ are also included in `resource_name`. If you remove the query shape you lose the ability to granularly track database reads in both traces and the generated metrics. In the abstract the shape of the database query being included in the resource name is similar to including the http path on an `express.request` resource name for a `GET` operation.

My team has recently gone through some frustrations with the mongo tracing after https://github.com/DataDog/dd-trace-js/pull/2295 merged. When that PR landed `resource_name` became essentially useless out of the box for us (and lead to use blowing past the unique resource name limit enforced at datadog.com). I filed #2536 in response as I think the tracer should keep sanitizing queries, but we recently shipped a config change to our agents internally with some custom regex to quantize these values for our use case https://docs.datadoghq.com/tracing/troubleshooting/quantization/

I don't agree that the right answer is removing query details from `find` operations (and in fact I'd like to see them added to `update`) but I do think the current behavior is wrong and the out-of-the-box configuration should be sanitizing the queries so the default `resource_name` values are immediately useful without requiring consumers to manually write regex in the agent.

**Comment by matehuszarik** [comment]
Thanks for linking https://github.com/DataDog/dd-trace-js/issues/2536, I have not noticed that.

The real problem is the **values** are included in the statement. Keeping the query shape should be optional IMO.

I use [OpenTelemetry](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/database/) as a reference regarding resource naming which suggests:

> The span name SHOULD be set to a low cardinality value representing the statement executed on the database. It MAY be a stored procedure name (without arguments), DB statement without variable arguments, operation name, etc. Since SQL statements may have very high cardinality even without arguments, SQL spans SHOULD be named the following way, unless the statement is known to be of low cardinality: <db.operation> <db.name>.<db.sql.table>, provided that db.operation and db.sql.table are available. If db.sql.table is not available due to its semantics, the span SHOULD be named <db.operation> <db.name>. It is not recommended to attempt any client-side parsing of db.statement just to get these properties, they should only be used if the library being instrumented already provides them. When it’s otherwise impossible to get any meaningful span name, db.name or the tech-specific database name MAY be used.

We agree on the resource name is useless right now. My expectation for resource name would be `<db.operation> <db.name>.<db.sql.table>` but I see your point and would add query shapes optionally. The only thing we can debate here is whether having the query shape in the resource name should be the default behavior or not. I'm open to both solutions.

It would be great to solve this in the library rather than configuring the agent with custom regex, that's for sure. I'd love to hear back from the DataDog team on how we should handle the problem. Whether it's part of the library or we need to adjust our agent configuration too.

Some additional information, we use the GO [plugin](https://github.com/DataDog/dd-trace-go/blob/main/contrib/go.mongodb.org/mongo-driver/mongo/mongo.go#L45) too, where the resource name `mongo.operationName` is yet in another format which adds even less granularity and not quite usable as well.

**Comment by vanstinator** [comment]
> The only thing we can debate here is whether having the query shape in the resource name should be the default behavior or not. I'm open to both solutions.

I'd be open to both as well. I think, for tracing specifically, it's useful to have more knobs rather than fewer.

**Comment by Qard** [comment]
This has been a bit of a challenging behaviour as we've had users that specifically _want_ that data and others that specifically want it filtered out. Probably going to have to make the query sanitization configurable. 🤔

**Comment by Qard** [comment]
I've made https://github.com/DataDog/dd-trace-js/pull/2631 as a resolution to this. The query will be removed from the resource.name as that's what we've done with other languages so we should be consistent there. I've included a config to re-enable it for the few customers that actually _want_ that data included.

**Comment by cabrinoob** [comment]
Hi. I have a question regarding the fact that the mongo "statements" disapeared from the resource name : Is it possible to list the most frequently used query shapes ??

Because something very usefull that also disapeared is that it was very easy to have those most frequently used queries by sorting the resources directly.

We used to do so for instance to optimize the indexation of our mongo collections or to improve the schema design.

Now it seems impossible to list those query shapes anymore without clicking on each ressource individually
