### ISSUE TITLE
Postgres query tracing is failing to parse sql statements after 2.5.0 when queries are large

### ISSUE THREAD

**Issue by graysonarts** [DataDog/dd-trace-js#2630]
**Expected behaviour**

When sending the `pg.query` span for an `UPDATE` or `INSERT` sql statement with a large json payload, I would expect the resource and `sql.query` values to be obfuscated (e.g. `UPDATE repos SET install_status = ? workflow_history = ? WHERE id = ?`) as it did in dd-trace 2.5.0

**Actual behaviour**
With versions of dd-trace after 2.5.0 (we tried 3.9.3 and 2.22.3), resource is `"Non-parsable SQL query"` and the `sql.query` value is the actual values of the query, but it's truncated for being too large (because we are inserting/updating a json blob).

**Steps to reproduce**

Here is one of function call where we've see the issue, but it's happening in other place also. It seems like the cause is the large json blobs.

```
 db.none(
    `
    UPDATE repos
    SET install_status = $2,
        workflow_history = $3
    WHERE id = $1`,
    [repoId, installStatus, JSON.stringify(workflowHistory)]
  );
```

**Environment**

* **Operation system:** OSX Ventura (also happens on Amazon Linux 2 AMI)
* **Node.js version:** 16.14.2
* **Tracer version:** (see description)
* **Agent version:** 7.25.1
* **Relevant library versions:**

```
 "devDependencies": {
    "@types/node": "^16.11.26",
    "tslint": "^6.1.2",
    "typescript": "^4.5.5"
  },
  "dependencies": {
    "dd-trace": "2.5.0",
    "pg": "^8.3.0",
    "pg-promise": "10.5.8",
    "pg-query-stream": "3.1.2"
  },
```

**Comment by Qard** [comment]
The library doesn't do query obfuscation, that's handled by the agent. Also, there hasn't really been any changes to postgres since 2.5.0 so I don't think this actually has anything to do with the js library. Did you also change your agent version recently?

**Comment by graysonarts** [comment]
We didn't change the agent version in our testing when trying to upgrade dd-trace which is why I started with filing the issue here. The only thing that has changed between it working and not working is the dd-trace version.

**Comment by chasdevs** [comment]
We are hitting the same issue with our NestJs/GraphQL setup. The bulk of our graphql queries are showing up as "Non-parsable SQL query".

<img width="554" alt="Screenshot 2023-01-30 at 4 46 05 PM" src="https://user-images.githubusercontent.com/8482352/215602449-fa62c608-92a6-4ce6-a1d2-8714dc6a92c2.png">

**Comment by tlhunter** [comment]
Looks like this issue was solved in a previous version of the tracer. I'll close it for now but feel free to reopen if this is still a probelm.
