### ISSUE TITLE
http-client service lost after upgrading 1.7.0 -> 3.8.0

### ISSUE THREAD

**Issue by jastabilesandbox** [DataDog/dd-trace-js#2634]
**Expected behaviour**
After upgrading from 1.7.0 to 3.8.0 we lost the service ...-http-client. This one is very useful to monitor request sent to external services using `axios`

**Actual behaviour**
Production environment (v1.7.0)
![image](https://user-images.githubusercontent.com/109677938/208984076-2f8097d4-e14e-42ed-9efd-c43a267508c5.png)

Pre-production environment (v3.8.0)
![image](https://user-images.githubusercontent.com/109677938/208984479-f0298a07-e505-4f36-9e9b-7d0375a1d185.png)

Why is this happening? Is there a way to activate it again?

**Comment by Qard** [comment]
You should be able to restore that behaviour through manually configuring each plugin with the service name you'd like.

```js
tracer.use('http', {
  client: {
    service: 'web-backend-http-client'
  }
})
```
