### ISSUE TITLE
low latency after upgrading 0.32.0 -> 3.9.3

### ISSUE THREAD

**Issue by Avifrankel** [DataDog/dd-trace-js#2649]
After upgrading  from **0.32.0** to **3.9.3**  we noticed  some major latency issues with our HTTP service.
roll back to old version - fixed the issue

![Screen Shot 2023-01-01 at 16 21 38](https://user-images.githubusercontent.com/9639986/210173850-b4eeabba-a647-478b-bc2b-4a8483e235b4.png)

**Environment**

* **Operation system:node official docker**
* **Node.js version:14.16.1**
* **Tracer version:3.9.3**
* **Agent version:7.41.1**
* **Relevant library versions:**

**Comment by tlhunter** [comment]
Going to close this as stale since there hasn't been any additional information for about a year. Feel free to reopen if it's still a problem!
