### ISSUE TITLE
need to set serviceMapping in dd-trace.init()

### ISSUE THREAD

**Issue by umarkhan17** [DataDog/dd-trace-js#2653]
when java services call mysql and redis, In datadog APM it is shown correctly as `java-service -> mysql`, `java-service -> redis`, but when one nodeJS service is calling redis or mysql it gets named as `NodeJSservice -> NodeJSservice-mysql` and `NodeJSservice -> NodeJSservice-redis`, it gets prefixed with servicename. upon checking on it i came to know that we have to set `serviceMapping`.

We are using `ioredis` and `mysql2` libraries.

```
require('dd-trace').init({
    env: ENV
    service: 'SERVICE',
    version: VERSION,
    logInjection: true,
    serviceMapping: 'mysql2:abc-mysql,ioredis:abc-redis',
    profiling: true,
  });
```
It still shows as NodeJSservice-redis & NodeJSservice-mysql in datadog

what am i doing wrong?

dd-trace-js version 3.9.3

**Comment by devinsba** [comment]
@umarkhan17 I think you meant to file this in this repo. Please let me know if that wasn't the case

**Comment by umarkhan17** [comment]
@devinsba No, i am using dd-trace in nodeJS. So i believe that would be here.

dd-trace: 3.9.3

**Comment by umarkhan17** [comment]
Seems like it has to be plugin(library)-name:apm-service-name like this  `'mysql2:mysql, ioredis:redis'` but for some reason if i add it in code like 
```
require('dd-trace').init({
    env: ENV
    service: 'SERVICE',
    version: VERSION,
    logInjection: true,
    serviceMapping: 'mysql2:mysql, ioredis:redis',
    profiling: true,
  });
```
It does not work, but if i pass it as environment variable to the container, it works

```
- name: DD_SERVICE_MAPPING
   value: "mysql2:mysql,ioredis:redis"
```
is this a bug?

**Comment by Qard** [comment]
Service mapping currently only exists as the env var, there is no support for programmatic config. Seems to be a docs bug, though it may be worth exposing it as a programmatic config too. I'll discuss with the team and figure out what the correct thing to do is here.
