### ISSUE TITLE
Http request headers are NOT provided in spans when arrays are returned from ClientRequest.getHeader(string)

### ISSUE THREAD

**Issue by theJC** [DataDog/dd-trace-js#2660]
When using make-fetch-happen (minipass fetch), the tags for http client headers are not being populated.  Via step debugging, the biggest difference I see with these codepaths vs others is that when the request header value is retrieved, an array is returned rather than a string, even when there is just one value.

https://nodejs.org/api/http.html#requestgetheadername states:
Reads out a header on the request. The name is case-insensitive. The type of the return value depends on the arguments provided to [request.setHeader()](https://nodejs.org/api/http.html#requestsetheadername-value).

**Expected behaviour**
In http plugin's client.js, when the value returned from ClientRequest request.getHeader(string) is an array, client.js should be turning the array into a string and use that string value for the tag.  

**Actual behaviour**
header value used in http client.js addRequestHeaders does not consider the case when the return value is an array and effectively sets the value to the string array:

```
 const value = req.getHeader(key)
 span.setTag(`${HTTP_REQUEST_HEADERS}.${key}`, value)
```

setTag(string, [string]) doesnt result in headers being returned in the spans propagated to Datadog presumably because the opentracing spec behavior for this is undefined.

**Steps to reproduce**
In my case it appears that the headers are arrays (even when there is only one value) for https calls initiated with make-fetch-happen / minipass fetch

**Potential solve:**

This results in spans created with the headers properly populated for this particular use case:

```
function addRequestHeaders (req, span, config) {
  config.headers.forEach(key => {
    const value = req.getHeader(key)

    if (value) {
      span.setTag(`${HTTP_REQUEST_HEADERS}.${key}`, Array.isArray(value) ? value.toString() : value);
    }
  })
}
```

**Environment**

* **Operation system:** macos and linux
* **Node.js version:** 16
* **Tracer version:** 3.10.0
* **Agent version:**
* **Relevant library versions:**

**Comment by juan-fernandez** [comment]
fixed by https://github.com/DataDog/dd-trace-js/pull/2667
