### ISSUE TITLE
Feature request: Make sample rate configurable via environment variable

### ISSUE THREAD

**Issue by devillexio** [DataDog/dd-trace-js#269]
There are few options that can be set via environment variable. Unfortunately `sampleRate` is not one of them.

In our environment we have one service that hits rabbitmq and redis a lot more than any other application. For this particular application we'd like to be able to set `sampleRate` to 1% (0.01), but we cannot use the config option, and need to use an environment variable.

**Comment by rochdev** [comment]
@devillexio `sampleRate` is actually only meant as a safeguard for extremely high load, because it will drop the traces directly at the client level and not count any dropped trace in the metrics for that service.

Are you experiencing any performance issues related to the number of spans in the traces from this service?

Also note that it's possible to set this configuration (or any other configuration that doesn't have built-in env var support) in code by using `tracer.init({ sampleRate: process.env.DD_TRACE_SAMPLE_RATE })`

**Comment by devillexio** [comment]
Hi @rochdev. Thanks for the response.

We experienced rate limits and datadog agent crashes after rolling out dd-trace to the application in question. Although we don't log a lot to the system, it uses both redis and amqp, which is likely what caused the problem. Long term we will need to review this application, but for now I'd like to stop the datadog agent crashes and rate limits. For reference, the application hit redis 6 million times, as well as amqp about 1.2 million times in the span of 20 minutes.

Thanks. I'll take the advice of the environment variable. It's a good solution and will work for our needs. Please feel free to close this issue.

**Comment by rochdev** [comment]
If I calculate this properly, that would mean only 6000 spans per second total, which the agent should handle easily.

@devillexio What do you mean by "datadog agent crashes"? This should never happen. Do you have any kind of log entry or more details about the nature of the crash?

**Comment by devillexio** [comment]
Unfortunately I don't have access to the logs from the period we experienced the issue, but the symptoms were as follows:

- datadog agent pods hit rate limit errors when persisting data to datadog
- not sure if related, but we also noticed rabbitmq connection errors for the first time since rolling out agent v6; these are still happening now (see below)
- agent pods restarted several times during this period
- for a period of roughly 12 hours, no data was transmitted to datadog

This is the current view of the datadog agents in our cluster:

```
NAME                                               READY     STATUS      RESTARTS   AGE
datadog-agent-8xvgh                                1/1       Running     45         6d
datadog-agent-fh2sn                                1/1       Running     6          6d
datadog-agent-h6qj6                                1/1       Running     26         6d
datadog-agent-j7kb7                                1/1       Running     12         6d
datadog-agent-ldx57                                1/1       Running     6          6d
```

RabbitMQ connection error:
```
[ AGENT ] 2018-09-06 05:13:17 UTC | ERROR | (datadog_agent.go:133 in LogMessage) | (rabbitmq.py:254) | error while contacting rabbitmq (https://xxx.rmq.cloudamqp.com/api/), setting aliveness to CRITICAL for vhosts: {'https://xxx.rmq.cloudamqp.com/api/': [u'/', u'xxxl']}
```

We regained stability by rolling out the `sampleRate` change to the high volume application.

Is there any additional info I can provide to help? I have a support ticket (165904) open if it will be better to continue the discussion that way.

**Comment by rochdev** [comment]
From this it seems the problem is with the agent, so I'd say to continue the discussion in the ticket. Just make sure to update this issue with any update/resolution.

**Comment by andrewsouthard1** [comment]
Looks like this was handled outside issue, please let us know if you are having any additional issues.
