### ISSUE TITLE
[Mocha] TypeError: this.tracer._exporter.getItrConfiguration is not a function

### ISSUE THREAD

**Issue by JohnDaly** [DataDog/dd-trace-js#2709]
**Expected behaviour**
`dd-trace` should allow a Mocha test suite to run when using the standard `AgentExporter`

**Actual behaviour**
When trying to run a Mocha test suite, I get the following error:
```
TypeError: this.tracer._exporter.getItrConfiguration is not a function
    at /node_modules/dd-trace/packages/dd-trace/src/plugins/ci_plugin.js:19:29
    at Subscription._handler (/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:14:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at /node_modules/dd-trace/packages/datadog-instrumentations/src/mocha.js:351:26
    at exports.AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at Mocha.run (/node_modules/dd-trace/packages/datadog-instrumentations/src/mocha.js:350:27)
``` 

**Steps to reproduce**

As far as I can tell, here is what seems to be happening:

The Exporter for the `tracer` is being set to `AgentExporter` when `config.experimental.exporter` is not provided:
https://github.com/DataDog/dd-trace-js/blob/a96389bc5de239da74769f6fb8cfdfbcefb8e386/packages/dd-trace/src/opentracing/tracer.js#L23

https://github.com/DataDog/dd-trace-js/blob/a96389bc5de239da74769f6fb8cfdfbcefb8e386/packages/dd-trace/src/exporter.js#L25

ITR Configuration Channel is set up here:
https://github.com/DataDog/dd-trace-js/blob/a96389bc5de239da74769f6fb8cfdfbcefb8e386/packages/datadog-instrumentations/src/mocha.js#L20

Event is published to that channel here, when Mocha starts:
https://github.com/DataDog/dd-trace-js/blob/a96389bc5de239da74769f6fb8cfdfbcefb8e386/packages/datadog-instrumentations/src/mocha.js#L358

Published event is handled is called here:
https://github.com/DataDog/dd-trace-js/blob/a96389bc5de239da74769f6fb8cfdfbcefb8e386/packages/dd-trace/src/plugins/ci_plugin.js#L19

Handler fails because the `_exporter` (`AgentExporter`) on the tracer was never set up with a `getItrConfiguration` function.

**Environment**

* **Operation system:** Mac
* **Node.js version:** 16.17.0
* **Tracer version:** 3.11.0
* **Agent version:** N/A
* **Relevant library versions:** mocha@6.1.4

**Comment by JohnDaly** [comment]
After some more investigation, the problem seems to occur when Mocha is loaded after the tracer is initialized.

Here's a minimal repro:
```
// Initialize dd-trace
const { tracer } = require('dd-trace');
tracer.init();

// Simulate 'mocha' being loaded in another module
require('mocha');

// Tests
const assert = require('assert');

describe('Sample', function () {
  it('should pass', function () {
    assert.equal(1 + 1, 2);
  });
});
```

**Comment by juan-fernandez** [comment]
hi @JohnDaly ! Thanks for the detailed description and the reproducible case. 

As a note, keep in mind that the way to initialise `dd-trace` to use CI Visibility (where the `mocha` plugin reports) is through `dd-trace/ci/init`: https://docs.datadoghq.com/continuous_integration/tests/javascript/?tab=onpremisesciproviderdatadogagent#instrument-your-tests. The `ci` prefix in the `init` makes sure that the correct exporter is used.

Whatever the case, this error should _not_ happen with any exporter so I'll get to fixing this.

**Comment by juan-fernandez** [comment]
https://github.com/DataDog/dd-trace-js/pull/2711 should do the trick 😄
