### ISSUE TITLE
node-abort-controller@3.1.0 requires node < 14.7.0

### ISSUE THREAD

**Issue by guidev** [DataDog/dd-trace-js#2727]
**Expected behaviour**

Running `npm update` should work without issues.

**Actual behaviour**

```
$ npm update
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'node-abort-controller@3.1.0',
npm WARN EBADENGINE   required: { node: '<14.7.0' },
npm WARN EBADENGINE   current: { node: 'v19.5.0', npm: '9.3.1' }
npm WARN EBADENGINE }


```
**Environment**

* **Operation system:** macOS 13.2 (22D49)
* **Node.js version:** v19.5.0
* **Tracer version:**
* **Agent version:**
* **Relevant library versions:**

**Comment by giovanni-caiazzo** [comment]
I just got this surprise today too and a fix seems easy to implement luckily.
Looks like `node-abort-controller` has updated that engine requirement [here](https://github.com/southpolesteve/node-abort-controller/commit/0cec4269848de64e9661f2f4edc02cc53afb5350) very recently

**Comment by guidev** [comment]
fixed in https://github.com/southpolesteve/node-abort-controller/issues/39
