### ISSUE TITLE
Playwright test execution results are not reported to DataDog

### ISSUE THREAD

**Issue by AnatoliiHanziuk** [DataDog/dd-trace-js#2766]
**Expected behaviour**
Test execution results captured after execution tests in GitHub Workflow should be sent to DataDog and visible in CI tests

**Actual behaviour**
Test execution results are invisible in CI tests

**Steps to reproduce**
1. Install dd-trace of version 3.13.1: `pnpm install -D`
2. Add command to execute Playwright tests to `package.json`:
```
"scripts": {
    "test": "npx playwright test"
},
```
4. Create GH Workflow with following env variables being set:
```
DATADOG_SERVICE: my-service
DATADOG_SITE: datadoghq.eu
DD_ENV: ci
DD_CIVISIBILITY_AGENTLESS_ENABLED: true
```
5. Execute add execution command for tests as a part of GH Workflow:
```
- name: Execute tests
  run: NODE_OPTIONS="-r dd-trace/ci/init" pnpm test
```

**Environment**

* **Operation system: ubuntu-20.04**
* **Node.js version: 16.15.0**
* **Tracer version: 3.13.1**
* **Agent version: 2.3.1**
* **Relevant library versions:**

```json
"devDependencies": {
    "@datadog/datadog-ci": "^2.3.1",
    "dd-trace": "^3.13.1",
    "@playwright/test": "^1.30.0"
}
```

**Comment by juan-fernandez** [comment]
hi @AnatoliiHanziuk! Thanks for the report. 

I see an issue with your site configuration: it should be `DD_SITE: datadoghq.eu`. We could probably improve our docs around that. I'll see what I can do.

Additionally, is `DD_API_KEY` env var being set with the correct datadog API key?

**Comment by AnatoliiHanziuk** [comment]
Closing the issue. Not an issue - misconfiguration of the env variable name.
