### ISSUE TITLE
Allow sanitization of resource.name for MongoDB plugin

### ISSUE THREAD

**Issue by yunfeng-scale** [DataDog/dd-trace-js#2792]
Hi, [queryInResourceName](https://datadoghq.dev/dd-trace-js/interfaces/plugins.mongodb_core.html#queryinresourcename) can be specified to include query in resource.name. However this is not ideal from privacy and grouping perspective (too many resources). We currently use Datadog agent `apm_config.replace_tags` to scrub ObjectID. Is it possible to provide an option so we can go back to the behavior before https://github.com/DataDog/dd-trace-js/pull/2295?

For example, currently resource name looks like `find db.collection {"name":"some_name"}`, and this option will make it `find db.collection {"name":?}`

**Comment by vanstinator** [comment]
They've been moving this kind of thing over to the agent. I had to do this in a project too, and I found these agent docs helpful https://docs.datadoghq.com/tracing/troubleshooting/quantization/

At my company, we set the `DD_APM_REPLACE_TAGS` environment variable on the agent and used the following regex to clean up our queries. No guarantees this will catch everything, but it caught all of the weird edges in _our_ data.



```js
[
  // Quantize arrays of string-like values into {val}, but ignore empty arrays.
  // Handles broken arrays (the dd-trace-js mongo plugin truncates strings longer than 10k) of resource names that terminate unexpectedly
  {
    name: 'resource.name',
    pattern: ':\\[(?:"[^"]+(?:"|$)|,|null|"|\\[])+(?:]|$)',
    repl: ':["{val}"]',
  },
  // Quantize single string-like values into {val}
  {
    name: 'resource.name',
    pattern: ':"(?:[^"]+)"|:null',
    repl: ':"{val}"',
  },
  // Quantize single numbers that the agent doesn't handle
  {
    name: 'resource.name',
    pattern: ':\\d+',
    repl: ':{num}',
  },
  // Quantize arrays of numbers that the agent doesn't handle
  {
    name: 'resource.name',
    pattern: '\\[(?:[\\d]+|,)+]',
    repl: '[{num}]',
  },
]
```

You'll end up with resource names like the following, which render nicely in the web UI and matches the out-of-the-box quantization that DD is doing elsewhere:

```
find media.playqueues {"items._id":"{val}"}
```

**Comment by tlhunter** [comment]
It looks like a solution was given for this issue so I'll close it for now. Feel free to reopen if it didn't work out!
