### ISSUE TITLE
Datadog not tracing Google pubsub traces when message published with publisherClient

### ISSUE THREAD

**Issue by Kannndev** [DataDog/dd-trace-js#2835]
**Expected behaviour**

Datadog should trace when a message is published with publisherClient object.

**Actual behaviour**

We are not seeing the trace.

**Steps to reproduce**

Traces when message published like below in the custom service metric call "pubsub.request"
```
const pubsub = new PubSub();
pubsub.topic('abc').publish('hello');
```

Does not trace when 

```
const {v1} = require('@google-cloud/pubsub');

const pubsub = new v1.PublisherClient({});

const response = await pubsub.publish({topic: 'abc', messages: [{data: 'hello'}]}, {
    retry: PUB_SUB_RETRY_SETTINGS // retry config
});
```

**Environment**

* **Operation system: **
* **Node.js version: 16**
* **Tracer version:**
* **Agent version:**
* **Relevant library versions: dd-trace - 0.32.2**

**Comment by rochdev** [comment]
This was fixed in #2883 and will be in next release.
