### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by edwardfeng** [DataDog/dd-trace-js#2837]
We upgraded the DD tracing library from 1.7.x to 3.x.x and found a memory leak issue. Currently, it hasn't caused too much trouble because we have a mechanism for deploying services on a daily basis.

<img width="1949" alt="mem leak" src="https://user-images.githubusercontent.com/930294/220835115-1ee8fe0f-bbff-47c5-8f17-6d13183e7725.png">

Environment:

Operation system: docker image node:12.18.3-slim
Node.js version: 18.12.1
Tracer version: 3.13.2
Agent version: datadog/agent:7.39.2
Relevant library versions:
"express": "4.18.2",
"http-proxy": "1.18.1",
"http-proxy-rules": "1.1.3",

**Comment by ballercat** [comment]
Yeah the library leaks memory pretty aggressively see https://github.com/DataDog/dd-trace-js/issues/2713 for a related problem. After a lot of wasted time looking into the implementation for automated instrumentation I've come to a conclusion that it's basically not worth it. The automatic instrumentation leads to every `IncomingMessage` being held on to. 

It's a shame really, the automatic instrumentation could be valuable if it was executed better, but as it is a complete no-go unless you want to chew through your memory in a production App. We had to revert back to manual tracking, with all plugins disabled and that has resolved all memory problems.

**Comment by plus-** [comment]
He is already using node 18

**Comment by rochdev** [comment]
@edwardfeng Are you still seeing a memory leak with the latest version of Node 18 and of dd-trace? And if yes, can you provide a reproduction snippet? I tried to reproduce this and couldn't in the latest version.

**Comment by svrakitin** [comment]
There is still a memory leak causing OOM happening after `3.9.0` and still present in `4.4.0`. You can see on a screenshot exactly the time when the change with a library upgrade was deployed.

<img width="854" alt="Screenshot 2023-07-06 at 19 39 46" src="https://github.com/DataDog/dd-trace-js/assets/3988244/149d2b89-2fec-4251-a202-056ae5a878e6">
<img width="869" alt="Screenshot 2023-07-06 at 19 39 42" src="https://github.com/DataDog/dd-trace-js/assets/3988244/ce0d6756-e5fd-41a7-86aa-5817970154de">

**Comment by ocdrums3** [comment]
@svrakitin I'm experiencing the same issue. Were you able to find a version of dd-trace-js that doesn't have memory leak problem? I tried several and couldn't find anything that works.

**Comment by svrakitin** [comment]
@ocdrums3 We're currently using `v3.9.0`

**Comment by cakasuma** [comment]
node 18 issue ? https://github.com/nodejs/help/issues/4228

**Comment by khanayan123** [comment]
Hi @svrakitin as @cakasuma alluded to it, it might be a node 18 issue. Did you find similar memory issues in node 16 or node 20?

**Comment by lenfree** [comment]
It's been mentioned in https://github.com/DataDog/dd-trace-js/issues/2640#issuecomment-1654629873 that it could be related to GRPC, worth checking I guess?

**Comment by tlhunter** [comment]
We recently landed a feature that helps log any spans that have a lifetime exceeding 1 minute. This could be helpful to diagnose which integration might be causing the memory leak.

Can you run your app with `DD_TRACE_SPAN_LEAK_DEBUG=1` and let me know what the results are? I should print periodic messages with a list of span types and their counts. This could help diagnose if it's grpc, http, etc.

I'd recommend running it locally or in staging as there will be performance overhead.

**Comment by tlhunter** [comment]
I'll close this for now but we can reopen it if it's still an issue.
