### ISSUE TITLE
Support DD_TRACE_HEADER_TAGS to control headers in traces, similar to how dd-trace-java does

### ISSUE THREAD

**Issue by theJC** [DataDog/dd-trace-js#2866]
Our company heavily uses Datadog, and we are in the middle of adjusting how Node apps will get the dd-trace-js library automatically added to their Node app (following a pattern we've already had for JVM services for the past couple of years).

One feature that we have heavily used for JVM services that our Node teams are wanting is the capability of using environment variables to control which headers get logged as tags,  often used for just-in-time diagnostic purposes, but will be especially useful for services that get dd-trace-js automatically wired, where they wont have tracer config happening in their codebase.

We would like:
- dd.trace.header.tags
- dd.trace.request_header.tags
- dd.trace.response_header.tags environment variables to have the ability (https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) to control the same setting described here: https://datadoghq.dev/dd-trace-js/interfaces/plugins.koa.html#headers and work for both http and http2 traffic.

**Comment by umarkhan17** [comment]
I don't know why datadog does this, but they have one set of features available for library in one language that don't exist in another language, this makes it very difficult to have standardised mechanism for implementing something. for example we wanted some headers to be set as tags for all the services, it's easy in java as it has dd.trace.header.tags, but it does not exist in nodejs :(

**Comment by ferarnoled** [comment]
For other people looking into this I got a response from the datadog support team. I haven't tried but wanted to post this before I forget..

> I've heard back and was able to confirm there is indeed an existing FR to support this as an env var. However, it seems like NodeJS does support the feature already, just not in env var form. 
>  
> May I ask if you're aware of the headers option that some integrations provide:
> tracer.use('express', {
> headers: ['sample-header', 'sample-header2']
> })
> doc ref: https://datadoghq.dev/dd-trace-js/interfaces/plugins.express.html#headers

**Comment by Bdthomson** [comment]
Are you sure that this doesn't work already? I am using `"dd-trace": "^4.11.0"` and `"express": "^4.18.2"` and have the following environment variable set
```
DD_TRACE_HEADER_TAGS: my-header-one:tag-one,my-header-two:tag-two
```

And in my Datadog traces I can see those on the `express.request` spans. Maybe it's just undocumented?

**Comment by tlhunter** [comment]
It does look like support for this was added in v4.11.0. I'll close this issue for now but if the feature is not working as expected please reopen it and tag me.
