### ISSUE TITLE
Module plugin request: Fastify

### ISSUE THREAD

**Issue by bojand** [DataDog/dd-trace-js#287]
https://www.fastify.io

It would be nice to have this supported. While it is compatible with Express middleware in general, and similar implementation as Express could probably work... Fastify does offer its own [request / response hooks](https://www.fastify.io/docs/latest/Hooks/) that may be more appropriate to utilize at the top level scope.

**Comment by rochdev** [comment]
Thanks for the suggestion! There is work being done right now to extract helpers that will make it easier to implement more Web frameworks. Since this is a less used framework, it could take some time before we get to it, but these helpers will greatly help community contributions.

**Comment by fabong** [comment]
Since fastify is growing a lot lately, is it in your backlog now or is there some community contributions about it?

**Comment by rochdev** [comment]
Definitely in our backlog, but work is not scheduled yet to support it. I'll keep this issue up to date when we start working on it.

**Comment by rochdev** [comment]
What version of Fastify are you using?
