### ISSUE TITLE
Plugin.name clashes with Funciton.name and makes subsequent plugin registration to fail

### ISSUE THREAD

**Issue by svsool** [DataDog/dd-trace-js#2873]
Hi, I encountered a problem with dd-trace, ESM and [tsx](https://github.com/esbuild-kit/tsx) runtime. Node v18.14.2.

Here is an example of the Pino plugin from dd-trace library:

```
class PinoPlugin extends LogPlugin {
  static get name () {
    return 'pino'
  }
}
```

I debugged dd-trace internals for a bit and it seems that `PinoPlugin.name` returns `PinoPlugin` instead of `pino` which breaks plugin registration https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugin_manager.js#L27-L44, plugin gets registered under class name instead of the name returned from the static getter.

This is what TS compiler says about using static `name` property:

![image](https://user-images.githubusercontent.com/1452141/223485947-6d89e6e3-257f-44a0-b4b3-3b18c3c5d0e9.png)

To reproduce:

```
// create test.ts
class TestPlugin {
  static get name () {
    return 'test'
  }
}

console.log(TestPlugin.name); // will print TestPlugin instead of test

// run
npx tsx test.ts
```

Would it make sense to rename `name` to `id` for example to make dd-trace work?

Example of a similar issue: https://github.com/Netflix/pollyjs/issues/309.

**Comment by svsool** [comment]
thanks, @tlhunter! 🚀

**Comment by tlhunter** [comment]
Roch did all the work ;)
