### ISSUE TITLE
[test-visibility] mocha --parallel does not work

### ISSUE THREAD

**Issue by JavaScriptBach** [DataDog/dd-trace-js#2886]
**Expected behaviour**
Using dd-trace to instrument mocha should work when mocha is running in [parallel mode](https://mochajs.org/#parallel-tests).

**Actual behaviour**

dd-trace fails with: `TypeError: global.run is not a function`

**Steps to reproduce**

Write a mocha test file and run it with `--parallel`, with `NODE_OPTIONS="-r dd-trace/ci/init"` in the env. A test file as simple as this will suffice:

```javascript
import assert from "assert";

describe("blah", () => {
  it("blah2", () => {
    assert(true);
  });
});

```

**Environment**

* **Operation system:** Linux
* **Node.js version:** 18
* **Tracer version:** 2.27.1
* **Agent version:** N/A
* **Relevant library versions:**

I'm not sure if this is a bug or intended behavior. Since Mocha is mentioned as supported in https://docs.datadoghq.com/continuous_integration/tests/javascript/?tab=onpremisesciproviderdatadogagent, I assumed the former. If `parallel` is intentionally unsupported, it would be great to clarify this in the docs. Thanks!

**Comment by juan-fernandez** [comment]
hey @JavaScriptBach. Thanks for the report! That's indeed a limitation of the `mocha` plugin: `--parallel` can't be used. I'll make sure the docs reflect that. Also, failing with a `TypeError` is not helpful so I'll look into that too.

**Comment by juan-fernandez** [comment]
while looking at this I think I may have found a way to make the mocha plugin compatible with `--parallel` mode. I still have some edge cases to look at but it looks promising (https://github.com/DataDog/dd-trace-js/pull/2888)

**Comment by JavaScriptBach** [comment]
Thanks @juan-fernandez !! It'd be great to get this support added. Good luck with the PR.

**Comment by juan-fernandez** [comment]
hey @JavaScriptBach sadly supporting parallel mode is harder than expected. We still want to do it, but it'll be later on. In the meantime I fixed the `global.run` ugly error in https://github.com/DataDog/dd-trace-js/pull/2900
