### ISSUE TITLE
Lambda errors are always wrapped as `Runtime.UnhandledPromiseRejection`

### ISSUE THREAD

**Issue by koneru9999** [DataDog/dd-trace-js#2893]
It seems the latest 2.x versions of the dd-trace does not propagate the original error thrown by lambda function.

We observed this behaviour after upgrading to `2.27.1` from `2.24.0`. 

The error is preserved when running with `2.24.0`. We are not sure yet which version exactly broke this behaviour.

**Expected behaviour**
_(refer to the sample lambda below)_
```
ERROR	[dd.trace_id=** dd.span_id=**] Invoke Error 	
{
    "errorType": "CustomError",
    "errorMessage": "my error",
    "stack": [
        "CustomError: my error",
        "    at <stack trace redacted for clarity>..."
    ]
}
```

However, the following is observed.
**Actual behaviour**
_(refer to the sample lambda below)_
```
[dd.trace_id=** dd.span_id=**] Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "CustomError: my error",
    "reason": {
        "errorType": "CustomError",
        "errorMessage": "my error",
        "stack": [
            "CustomError: my error",
            "    at <stack trace redacted for clarity>..."
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: CustomError: my error",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1189:17)",
        "    at process.emit (node:events:513:28)",
        "    at process.emit (/var/task/node_modules/source-map-support/source-map-support.js:516:21)",
        "    at emit (node:internal/process/promises:140:20)",
        "    at processPromiseRejections (node:internal/process/promises:274:27)",
        "    at processTicksAndRejections (node:internal/process/task_queues:97:32)"
    ]
}
```

**Steps to reproduce**
Sample lambda handler code to reproduce the above scenario.
```ts
class CustomError extends Error {
  constructor(message?: string) {
    super(message)
    Object.defineProperty(this, 'name', { value: 'CustomError' })
  }
}

export function myHanlder() {
  throw new CustomError('my error')
}
```

**Environment**

* **Operation system:** amazon/aws-lambda-nodejs:16.2023.03.08.12
* **Node.js version:** 16.x
* **Tracer version:** 2.27.1
* **Agent version:** latest (`datadog/lambda-extension:latest`)
* **Relevant library versions:**
  * **datadog-lambda-js:** 6.87.0

**Comment by koneru9999** [comment]
Preserving the errorType is crucial especially when a lambda is used in a step function with `Retry` strategies based on the error type.

**Comment by mskarbe** [comment]
Checked again with `v3.20.0` of `dd-trace-js`: 

```
    "datadog-lambda-js": "6.89.0",
    "dd-trace": "3.20.0",
```

and image released from `datadog/lambda-extension:latest` (i.e. `v43`).  

**The issue still persist; errorType is replaced by `Runtime.UnhandledPromiseRejection`.**

**Comment by astuyve** [comment]
Hey folks, I'm trying to determine if this is an issue with `datadog-lambda-js` or `dd-trace-js` - it seems most folks here are manually packaging the tracer along with the `datadog-lambda-js` library, is that correct?

Is there a version where this was working in `datadog-lambda-js` which no longer works?

Thanks!

**Comment by arminrosu** [comment]
@astuyve I think it's an issue with dd-trace-js originally, because different version thereof have it, whereas all versions of `datadog-lambda-js` work.

@mskarbe pinned down the issue to only happen with `async` handlers. Here's a repro repo: https://github.com/AMN-DATA/eng-datadog-runtime-error

**Comment by astuyve** [comment]
Amazing, thank you so much for this repo and assistance. I'll make sure we get routed the ticket anyway.

Thank you!!

**Comment by astuyve** [comment]
This should be fixed in Datadog Lambda Layer [v93](https://github.com/DataDog/datadog-lambda-js/releases/tag/v7.93.0)

**Comment by arminrosu** [comment]
@astuyve thanks, we'll check and report back.

**Comment by arminrosu** [comment]
@astuyve seems to work. I updated the repro repo with it and tried it on our staging environment. Thanks so much!

**Comment by astuyve** [comment]
Glad to hear it @arminrosu!
