### ISSUE TITLE
Env var to share service name

### ISSUE THREAD

**Issue by jamiehodge** [DataDog/dd-trace-js#2896]
It would very nice if there was an environment variable that set all plug-in service names to the parent service name. Enumerating a potentially changing list of plugins in DD_SERVICE_MAPPING is less than ideal.

**Comment by rochdev** [comment]
There is a change coming soon that will allow doing just that. Basically there will be a configuration option available in every language to normalize some of the metadata that is currently reported with better defaults for our auto-instrumentation, including the service name and operation name. I don't have a specific timeline, but I'll update this issue when it's out or when I have more information.
