### ISSUE TITLE
grpc-js plugin

### ISSUE THREAD

**Issue by nhomble** [DataDog/dd-trace-js#2912]
Support was previously added for [grpc](https://www.npmjs.com/package/grpc) in https://github.com/DataDog/dd-trace-js/issues/311

but this package seems deprecated in favor of [grpc-js](https://www.npmjs.com/package/@grpc/grpc-js)

Could this tracer library support the new grpc library?

**Comment by rochdev** [comment]
Both libraries are currently supported by dd-trace. Is this not working for you? And if that's the case, can you describe what's not working?

**Comment by nhomble** [comment]
Sorry I misunderstood the docs. After adding `.use('grpc')` we see traces as expected.
