### ISSUE TITLE
Request hook no longer called from dd-trace v3.15.0 and NextJS >=13.2.x

### ISSUE THREAD

**Issue by tamarasaurus** [DataDog/dd-trace-js#2919]
**Expected behaviour**

If I'm using NextJS >=13.2 and dd-trace v3.15.0 I expect to have the `request` hook triggered on requests to my server when I set up the plugin like this: 

`tracing.js`
```js
const tracer = require('dd-trace').init();

tracer.use('next', {
  hooks: {
    request: (span, req, res) => {
      console.log('request hook called')
    }
  }
})
```

`package.json`
```json
 "scripts": {
    "dev": "node --require ./tracing.js ./node_modules/.bin/next dev",
  },
```

![Screenshot 2023-03-21 at 15 24 37](https://user-images.githubusercontent.com/1336344/226636650-78627594-ad74-4396-8510-4d914d9246a1.png)

**Actual behaviour**

If I'm using NextJS 13.2.4 and dd-trace v3.15.0 it looks like the next plugin is not being set up correctly because I don't have any output from the request hook

![Screenshot 2023-03-21 at 15 26 32](https://user-images.githubusercontent.com/1336344/226637312-e57154d4-1821-4eb8-ab18-b1ee3609b5df.png)

**Steps to reproduce**

I've created a repository to reproduce the issue in different versions of NextJS - https://github.com/tamarasaurus/dd-trace-reprod (instructions in the README) 

From what I understand it looks like the following change caused the plugin to not support v13.2 anymore:
https://github.com/DataDog/dd-trace-js/pull/2851/files#diff-2459f26b869c7f2688c130857769922a2b367bf5e9d39602c91e60c4584a4047R131

Because when I change this line it works as expected: 
```diff
- addHook({ name: 'next', versions: ['>=11.1 <13.2'], file: 'dist/server/next-server.js' }, nextServer => {
+ addHook({ name: 'next', versions: ['>=11.1 <=13.2'], file: 'dist/server/next-server.js' }, nextServer => {
```

Does this mean that the NextJS plugin in dd-trace v3.15.0 is not meant to be compatible with v13.2.x? If so I wouldn't expect this change to occur in a minor version as it's not mentioned in the release notes. 

**Environment**

* **Operation system:** Mac M1 Ventura 13.2.1
* **Node.js version:** 18.13.0 
* **Tracer version:** 3.15.0
* **Agent version:** N/A
* **Relevant library versions:** next@13.2.4

Thanks for your help!

**Comment by sylvaingi** [comment]
I've also noticed this with next@13.2.4 and dd-trace@3.15.0. Reverting to 3.14.1 fixed the issue.

**Comment by rochdev** [comment]
There was an issue with Next 13.2 and support for it was temporarily disabled in the last release. It's been re-enabled in #2905 and should work properly again in the next release.
