### ISSUE TITLE
The Datadog Playwright instrumentation should correctly handle and instrument tests when running compiled Playwright tests from another directory.

### ISSUE THREAD

**Issue by declancarrollcb** [DataDog/dd-trace-js#2924]
**Expected behaviour** The Datadog Playwright instrumentation should correctly handle and instrument tests when running compiled Playwright tests from another directory.

**Actual behaviour** When running compiled Playwright tests from another directory, the Datadog Playwright instrumentation throws an unhandled exception due to attempting to filter on an undefined object.

**Steps to reproduce**

1.  Set up a project with Playwright tests and Datadog Playwright instrumentation.
2.  Compile the tests to a different directory, for example 'C:\repo\tests-out\testname.test.js'.
3.  Run the compiled Playwright tests from the new directory.

**Error Details** The exception is caused by the following code on line 123:

```
`remainingTestsByFile[testSuiteAbsolutePath] = remainingTestsByFile[testSuiteAbsolutePath]
    .filter(currentTest => currentTest !== test)` 
```

This code attempts to filter on an undefined object because the test file could be named 'C:\repo\tests-out\testname.test.js', but the instrumentation will look for 'c:\repo\testname.test.ts'.

**Environment**

-   **Operating system:** (Please provide your operating system)
-   **Node.js version:** v18.15.0
-   **Tracer version:** 3.15.0
-   **Agent version:** (Please provide the agent version)
-   **Relevant library versions:** Playwright 1.31.2, Datadog Instrumentations

**Additional context** Stack trace of the error:

```
`'/runner/_work/cloudbeds-sdk/cloudbeds-sdk/node_modules/dd-trace/packages/datadog-instrumentations/src/playwright.js:123
    .filter(currentTest => currentTest !== test)
     ^

TypeError: Cannot read properties of undefined (reading 'filter')
    at testEndHandler (/runner/_work/cloudbeds-sdk/cloudbeds-sdk/node_modules/dd-trace/packages/datadog-instrumentations/src/playwright.js:123:6)
    at WorkerHost.<anonymous> (/runner/_work/cloudbeds-sdk/cloudbeds-sdk/node_modules/dd-trace/packages/datadog-instrumentations/src/playwright.js:194:7)
    at WorkerHost.emit (node:events:525:35)
    at ChildProcess.<anonymous> (/runner/_work/cloudbeds-sdk/cloudbeds-sdk/node_modules/@playwright/test/lib/runner/processHost.js:84:16)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Node.js v18.15.0'` 
```

Please provide any additional information or code snippets that could help diagnose the issue.

**Comment by declancarrollcb** [comment]
Hey Juan,

Of course. Playwright can be built with the "tsc" command and compiled into Javascript ( we are doing this due to some legacy decorators in the code that Playwright can't handle). So to run our tests first we do "tsc" then we run the tests from that directory with the javascript files.


```
    "pretest": "tsc --incremental -p tsconfig-playwright.json",
    "test": "npm run pretest && npx playwright test -c tests-out",
```

Our tests end up in a "tests-out" directory and then we run the tests from there. It means there is a test name mismatch when trying to filter them.

**Comment by declancarrollcb** [comment]
I was able to get around the issue with the following:


```
// Get the output directory for the test suite, if it's different from the root directory return the relative path.
// This means if your tests are running from "test" and your output directory is "test/output" it will return "output"
function getOutDir(playwrightRunner) {
  const config = getPlaywrightConfig(playwrightRunner)
  const globalOutputDir = config._internal && config._internal.globalOutputDir;
  const configDir = config._internal && config._internal.configDir;
  if (globalOutputDir !== configDir) {
    return path.relative(globalOutputDir, configDir);
  }
  return '';
}


```


And the "normalizing" the test suite path for checking.

```
  const normalizedTestSuiteAbsolutePath = path.normalize(testSuiteAbsolutePath).replace(/\.js$/, '.ts').replace(outputDir, '');

  if (!remainingTestsByFile[normalizedTestSuiteAbsolutePath]) {
    // Log the remaining tests by file
    remainingTestsByFile[normalizedTestSuiteAbsolutePath] = [];
    console.log(`Could not find remaining tests for ${normalizedTestSuiteAbsolutePath}`)
    console.log('remainingTestsByFile', remainingTestsByFile)
  }
```

**Comment by juan-fernandez** [comment]
> I was able to get around the issue with the following:
> 
> ```
> // Get the output directory for the test suite, if it's different from the root directory return the relative path.
> // This means if your tests are running from "test" and your output directory is "test/output" it will return "output"
> function getOutDir(playwrightRunner) {
>   const config = getPlaywrightConfig(playwrightRunner)
>   const globalOutputDir = config._internal && config._internal.globalOutputDir;
>   const configDir = config._internal && config._internal.configDir;
>   if (globalOutputDir !== configDir) {
>     return path.relative(globalOutputDir, configDir);
>   }
>   return '';
> }
> ```
> 
> And the "normalizing" the test suite path for checking.
> 
> ```
>   const normalizedTestSuiteAbsolutePath = path.normalize(testSuiteAbsolutePath).replace(/\.js$/, '.ts').replace(outputDir, '');
> 
>   if (!remainingTestsByFile[normalizedTestSuiteAbsolutePath]) {
>     // Log the remaining tests by file
>     remainingTestsByFile[normalizedTestSuiteAbsolutePath] = [];
>     console.log(`Could not find remaining tests for ${normalizedTestSuiteAbsolutePath}`)
>     console.log('remainingTestsByFile', remainingTestsByFile)
>   }
> ```

great catch! Thanks for the investigation and code! I'll try this as soon as possible. You're free to contribute this too if you want 😄

**Comment by declancarrollcb** [comment]
Hey Juan,

I added a PR, it does seem like a lot of extra steps to get this to work, there were also some path normalization issues that needed to be addressed to allow me to run it locally on Windows due to backslashes etc.

**Comment by juan-fernandez** [comment]
thanks for the contribution! We can continue the conversation in the PR 😄
