### ISSUE TITLE
What is intended to be reported as an "error" from the HTTP plugin?

### ISSUE THREAD

**Issue by timrogers** [DataDog/dd-trace-js#297]
What kinds of errors are we trying to report as "errors" from the HTTP(S) plugin?

https://github.com/DataDog/dd-trace-js/blob/34c168555f44a961a61ede95a39341d7c527701a/src/plugins/http.js#L59-L67

I've observed that 4XX and 5XX HTTP responses *don't* seem to lead to errors being recorded in Datadog APM. Perhaps this is the expected behaviour, but strikes me as a little counterintuitive and worth documenting if it is how it is meant to work.

I realise that this approach may align with the JavaScript ecosystem more generally (for example `fetch` doesn't natively treat HTTP error responses as errors.

**Comment by timrogers** [comment]
My gut feeling is that for most use cases, recording 4XXs and 5XXs as errors would be valuable.

Most of the time, an elevated rate of these would indicate a problem with the health of my application which I want to be able to see at a glance, receive alerts for, etc.

That said, there are cases where (at least for certain requests), some 4XX or 5XX errors are an expected part of the ordinary operation of the application and don't represent a problem, so having the flexibility to decide what is and isn't an error would be valuable. (On the other hand, it seems like you would *always* want to consider timeouts and network errors an "error").

A `validateStatus` function as part of the configuration could help with this. At the minimum, I'd expect it to be passed the status, but perhaps some other context (for example the request) would be useful as well to allow me to decide on a more fine-grained basis what is an "error" and what isn't (although obviously that level of configurability adds complexity).

Nevertheless, it feels like recording these as errors would be a reasonable default.

Can I suggest that we?:

* (a) document explicitly what is treated as an error and what isn't
* (b) add the simplest possible configuration, a `validateStatus` function which is passed the response code

**Comment by timrogers** [comment]
Thinking about it, you might well have logic to retry connection failures
too (if the request is idempotent), and despite having handled the error,
you’d still probably want it recorded as an error. I think the same goes
for 500s.

**Comment by timrogers** [comment]
I'm happy to write the code for this. How would you want the errors to be recorded? There seem to be three properties: `msg`, `type` and `stack`. `stack` is going to be challenging - we might have to omit it if that's permitted (or potentially we could generate a stack trace from the current line and remove entries that came from `dd-trace-js`).

**Comment by rochdev** [comment]
In this case, since there is no actual error, I would probably omit the error object and simply set the `error` tag. Then it will be possible to infer the reason of the error from the status code.

I wouldn't generate an actual error whenever it's possible not to do it because error generation is pretty heavy in JavaScript.

**Comment by timrogers** [comment]
I have an implementation for this locally. I’ll push it up tomorrow.

**Comment by johnnydimas** [comment]
Hey @timrogers, thanks for submitting this change. We were racking our brains trying to figure out why our 4xx errors weren't being reported in APM as errors. 

I have pointed our npm package to the latest in master as your branch was merged, but not yet published. 

I was curious if you could provide an example of how you implement this? Does it require any changes or does it work by default now that 4xx errors are treated as errors, since by definition they are errors?

Thanks!

**Comment by timrogers** [comment]
It should just work. I haven’t updated yet 🙈 What’s missing here is the
ability to customise what is considered an error based on how the specific
API you’re calling works, but if you’re not worried about that and can
configure globally, this should work for you.

**Comment by rochdev** [comment]
@johnnydimas Please note that the feature was merged in the `v0.7.0` branch and not `master`.

**Comment by johnnydimas** [comment]
@rochdev Is there a timeline on when this will be available in a release?

**Comment by rochdev** [comment]
@johnnydimas I don't have a specific timeline but it should be fairly soon. In the meantime, you can use one of the intermediary beta releases, such as `0.7.0-beta.2` which I've just released.

**Comment by timrogers** [comment]
I’m going to close this as my change was merged, if not released. In an idea world, you’d be able to customise on a per-request basis but it’s hard to imagine how you’d do that in a nice automatic way!
