### ISSUE TITLE
Koa plugin throws 500 error: "Cannot read property 'length' of undefined."

### ISSUE THREAD

**Issue by phyllisstein** [DataDog/dd-trace-js#300]
👋 Hey Datadogs! I wanted to flag an issue I'm having with the JS tracer's Koa plugin. It seems to run without complaint in dev, but running it in prod throws a `500` on every request:

```
172.20.55.142 - - [03/Oct/2018:20:50:15 +0000] "GET /ping HTTP/1.1" 500 21 "-" "kube-probe/1.12" "-"
App 567 output: 
App 567 output:   TypeError: Cannot read property 'length' of undefined
App 567 output:       at ctx.matched.filter.layer (/usr/lib/ignota/node_modules/dd-trace/src/plugins/koa.js:39:38)
App 567 output:       at Array.filter (<anonymous>)
App 567 output:       at extractRoute (/usr/lib/ignota/node_modules/dd-trace/src/plugins/koa.js:39:8)
App 567 output:       at next.then.catch.e (/usr/lib/ignota/node_modules/dd-trace/src/plugins/koa.js:16:9)
App 567 output:       at runCallback (timers.js:694:18)
App 567 output:       at tryOnImmediate (timers.js:665:5)
App 567 output:       at processImmediate (timers.js:647:5)
App 567 output:   From previous event:
App 567 output:       at ddTrace (/usr/lib/ignota/node_modules/dd-trace/src/plugins/koa.js:15:13)
App 567 output:       at dispatch (/usr/lib/ignota/node_modules/koa-compose/index.js:42:32)
App 567 output:       at /usr/lib/ignota/node_modules/koa-compose/index.js:34:12
App 567 output:       at Application.handleRequest (/usr/lib/ignota/node_modules/koa/lib/application.js:151:12)
App 567 output:       at Server.handleRequest (/usr/lib/ignota/node_modules/koa/lib/application.js:133:19)
App 567 output:       at Server.emit (events.js:187:15)
App 567 output:       at parserOnIncoming (_http_server.js:652:12)
App 567 output:       at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

I'm afraid I don't know the plugin architecture well enough to speculate on what the problem might be---or on why it only seems to show up in prod---but I'd be grateful for any thoughts you folks have. Thanks in advance for your help!

**Comment by rochdev** [comment]
I'll take a look. Are you using the same version of Koa in dev and prod? (the actual installed version, not version range).

**Comment by rochdev** [comment]
Also, what version of `koa-router` are you using?

**Comment by phyllisstein** [comment]
Thank you! `yarn.lock` should keep the versions in sync in both environments; `koa-router` is pinned to `8.0.0-alpha.1`, and since that's probably silly I could certainly try rolling it back.

**Comment by rochdev** [comment]
While `koa-router` 8.x is not officially supported at the moment, it should not result in an error, so there is definitely a bug. They probably changed the structure of Layer, so I'll add additional checks to ignore layers that are not matching what we expect.

However, even after solving the bug, the instrumentation would still be limited as it would not include the route in the resource name. I'd definitely recommend sticking to 7.x for now if it's possible for you.

**Comment by phyllisstein** [comment]
Thanks for the suggestion! I knocked `koa-router` back down to `^7.4.0` and the app started responding again. I think I have some additional work to do around exposing the APM ports on my nodes but that's a story for another ticket.
