### ISSUE TITLE
Links in documentation are not working

### ISSUE THREAD

**Issue by Enriquecava** [DataDog/dd-trace-js#3016]
Reviewing the documentation in https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md i was testing the links for tracer.scope() tracer.tracer() and tracer.wrap() and all of them are returning a 404 page 

**Expected behaviour**
should redirect to the correct page

**Actual behaviour**
redirecting to an incorrect page

**Steps to reproduce**
go to https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md and click on the links of tracer.tracer()

**Comment by tlhunter** [comment]
That markdown document represents the "API" link in the main README.

It's rendered over here where relative links should work: https://datadoghq.dev/dd-trace-js/

**Comment by Enriquecava** [comment]
> That markdown document represents the "API" link in the main README.
> 
> It's rendered over here where relative links should work: https://datadoghq.dev/dd-trace-js/

in the link you shared it is working but if you test it in https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md you will see that it is redirecting you to 404 page
