### ISSUE TITLE
I can't figure out what 'undefined' means

### ISSUE THREAD

**Issue by hwooo** [DataDog/dd-trace-js#3026]
**Environment**

* **Operation system:** macOS/Linux
* **Node.js version:** 16
* **Tracer version:** 3.10

<img width="450" alt="pic" src="https://user-images.githubusercontent.com/46282492/233560482-cbf90608-2256-452a-b2bd-9c0ad2542bc4.png">

```typescript
import tracer from 'dd-trace';

tracer.init({
  logInjection: true,
  service: process.env.DD_SERVICE,
  version: process.env.DD_VERSION,
});

export default tracer;
```

Every datadog log has `undefind` text after 'Info'.
How can I pass right value to this? I can't figure out which options is related to.

**Comment by tlhunter** [comment]
Are you using a logging package? The output kind of appears to be `console.log()` output, which by default has yellow numbers and green strings, which makes me think it's for local debugging instead of outputting well-formed, parseable data?

**Comment by tlhunter** [comment]
Looks like this is stale so you might have found the solution by now. I'll close it but feel free to reopen if it's still applicable!
