### ISSUE TITLE
Support for apollo gateway spans

### ISSUE THREAD

**Issue by jmvtrinidad** [DataDog/dd-trace-js#3058]
Please support the Gateway-specific spans for dd trace js.
After upgrading to the latest apollo gateway, the span is not emitted anymore.
https://www.apollographql.com/docs/federation/opentelemetry#gateway-specific-spans

**Comment by rochdev** [comment]
Do you know what is the last version of Apollo Gateway that worked with dd-trace?

**Comment by JamesAwesome** [comment]
Hey there, we're having this issue as well. It seems to have functioned with `"@apollo/gateway": "2.1.3"`

It would be super helpful to have these added back

**Comment by yuvekfp** [comment]
hey we are running into this issues as well while upgrading from @apollo/gateway 2.1.2 -> 2.5.6. We are currently running dd-trace version 1.5.0. Is this issue fixed now ? If yes what version of dd-trace do we need to upgrade to ?

**Comment by tlhunter** [comment]
I'm going to close this as a duplicate of #1057. Note that we are looking into Apollo Gateway as a candidate for instrumenting.
