### ISSUE TITLE
Tracing does not work with Apollo server schema merging

### ISSUE THREAD

**Issue by terryma** [DataDog/dd-trace-js#307]
What works:
- Apollo server 2 + apollo-server-express + graphql 0.13 + dd-trace 0.6 using a local schema. This works fine I see the following flame graph for both the express request and the graphql resolution:

![image](https://user-images.githubusercontent.com/567259/46843384-5da25980-cd87-11e8-8d8d-c0e003e3beda.png)

Once I start doing [schema stitching](https://www.apollographql.com/docs/graphql-tools/schema-stitching.html) using `mergeSchema`, I no longer see any traces being generated on the client. 

Any idea what might be causing this? How should I debug this?

Please see a basic hello world example below to repro. The example is copied straight from apollo-server 

package.json
```json
{
  "name": "hello-apollo-server",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "apollo-server": "^2.1.0",
    "apollo-server-express": "^2.1.0",
    "dd-trace": "^0.6.0",
    "graphql": "^0.13.2"
  }
}
```

index.js
```js
const tracer = require('dd-trace').init({
    hostname: 'localhost',
    debug: true,
    service: 'hello-apollo-server',
  },
)

const express = require('express');
const { ApolloServer, gql } = require('apollo-server-express');
const { makeExecutableSchema, mergeSchemas } = require('apollo-server');

const app = express();

const typeDefs = gql`
  type Query {
    hello: String
  }
`;

const resolvers = {
  Query: {
    hello: () => 'Hello world!'
  },
};

schema = makeExecutableSchema({typeDefs, resolvers});
// Uncommenting the line below causes tracing to fail
// schema = mergeSchemas({schemas: [schema]});
const server = new ApolloServer({schema});

server.applyMiddleware({ app });

app.listen({ port: 4000 }, () =>
  console.log(`🚀 Server ready at http://localhost:4000${server.graphqlPath}`)
)
```

**Comment by rochdev** [comment]
Related to https://github.com/DataDog/dd-trace-js/issues/235

**Comment by rochdev** [comment]
We instrument the schema directly, so it's possible that if an entirely new schema is created by Apollo our instrumentation is lost. I'm guessing we would probably need to explicitly support Apollo for this to work properly.

**Comment by terryma** [comment]
Thanks for fixing this! Do you have a planned release date for 0.6.1?

**Comment by rochdev** [comment]
I'm aiming for today, or Monday at the latest.

**Comment by terryma** [comment]
Thank you! 👍I'll test this out and let you know if it fixes the issue we were seeing.

**Comment by terryma** [comment]
Seems good so far, thank!
