### ISSUE TITLE
Cannot implement Node tracer in TypeScript - Property 'init' does not exist

### ISSUE THREAD

**Issue by andreydrozd** [DataDog/dd-trace-js#3070]
**Expected behaviour**

I'm following the TS instructions for [Node tracing](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/nodejs/?tab=containers#typescript-and-bundlers). The below should not cause TS compilation to fail, but TS says otherwise.

```js
import tracer from "dd-trace"
tracer.init() // initialized in a different file to avoid hoisting.
export default tracer
...
..
.
[11:45:33 AM] Found 0 errors. Watching for file changes.
```

**Actual behaviour**

```js
import tracer from "dd-trace"
tracer.init() // initialized in a different file to avoid hoisting.
export default tracer
...
..
.
[11:37:11 AM] Starting compilation in watch mode...

tracer.ts:2:8 - error TS2339: Property 'init' does not exist on type 'typeof import("/Users/andreydrozd/**/node_modules/dd-trace/index")'.
```

**Steps to reproduce**

**Environment**

* **Operation system:** macOS Monterey 12.6.3 (21G419)
* **Node.js version:** 18.12.0, TypeScript - 4.9.3
* **Tracer version:** 3.18.0
* **Agent version:** N/A yet.
* **Relevant library versions:**

**Comment by shinwonse** [comment]
You can write like this
```
import ddTrace from 'dd-trace';

const tracer = ddTrace.init({
  // Any setting
});

export default tracer;
```

**Comment by andreydrozd** [comment]
Still does not work.

```js
[11:53:41 AM] File change detected. Starting incremental compilation...

tracer.ts:3:24 - error TS2339: Property 'init' does not exist on type 'typeof import("/Users/andreydrozd/**/node_modules/dd-trace/index")'.

3 const tracer = ddTrace.init({
                         ~~~~

[11:53:41 AM] Found 1 error. Watching for file changes.
```

**Comment by andreydrozd** [comment]
Hi, any updates on this? I'm surprised the TS implementation on such a library would be broken for so long.

**Comment by andreydrozd** [comment]
I saw in the docs that it's also possible to import and initiate like this - `import "dd-trace/init"`. That worked on my project. Not sure why it didn't work the way I initially tried it, perhaps it's something with the tsconfig.

**Comment by andreydrozd** [comment]
Doing an import like `import "dd-trace/init"` worked locally, but upon deployment the import couldn't be resolved. Not sure if Linux is less forgiving regarding import names than Mac, as I've had similar bugs before on incorrectly capitalized imports before.

Anyway, what worked with the directions in the doc is a named import
```js
import { tracer } from "dd-trace"
tracer.init() // initialized in a different file to avoid hoisting.
export default tracer
```

My tsconfig `module` setting is set to `NodeNext`, and I think this is the root of the issue. When I set it to `CommonJS`, then I was able to do a default import. I noticed the library does not have a `type` property on its package.json, which affects how a module is resolved by Typescript, as explained [here](https://www.typescriptlang.org/tsconfig#node16nodenext-nightly-builds). When I set the `type` to `module`, then the import worked as well. Not sure if the functionality would've worked though 😆

**Comment by mschnee** [comment]
This might be due to your ES interop settings.  If you're using [any of these bases](https://github.com/tsconfig/bases), you might be importing the typed namespace but not the actual CommonJS module export.

```ts
// index.ts
import DDTrace from 'dd-trace';

const { init } = DDTrace.default;
```

```json
// tsconfig.json
{
    "extends": ["@tsconfig/strictest/tsconfig.json", "@tsconfig/node-lts/tsconfig.json", "@tsconfig/esm/tsconfig.json"],
    "compilerOptions": {
        "outDir": "dist",
        "declaration": true,
        "declarationMap": true,
        "sourceMap": true,
        "moduleResolution": "nodenext"
    },
    "include": ["src"]
}
```

**Comment by khanayan123** [comment]
Hi @andreydrozd is this still an issue?

**Comment by andreydrozd** [comment]
I didn't change my tsconfig. I ended up doing the below.

``` javascript
import tracer from "dd-trace"
const { init } = tracer.default
init()
export default tracer
```

**Comment by tlhunter** [comment]
Looks like this issue was solved so I'll close it. Please reopen if it's still an issue.
