### ISSUE TITLE
Hapi + GraphQL

### ISSUE THREAD

**Issue by willyyang** [DataDog/dd-trace-js#308]
Is there something wrong with my configuration if I want to use the [DD integrations](https://datadog.github.io/dd-trace-js/#Integrations) for Hapi and GraphQL? 

```
export const tracer = require('dd-trace').init({
  plugins: false
})
tracer.use('hapi')
tracer.use('graphql')
```

**Comment by rochdev** [comment]
The configuration looks correct. What is the issue?

**Comment by willyyang** [comment]
No traces showing up for the graphql requests

**Comment by rochdev** [comment]
Are you getting a trace for the Hapi request? What version of GraphQL are you using? Are you using a framework on top of the `graphql` module? (i.e. Apollo)

**Comment by willyyang** [comment]
no Hapi request traces. 
```
"graphql": "^0.13.0",
"apollo-server": "^2.0.7",
 "apollo-server-hapi": "^1.3.2",
```

**Comment by willyyang** [comment]
nvm solved my issue.

**Comment by rochdev** [comment]
For future reference, what was the issue?

**Comment by willyyang** [comment]
Initialization of code.
