### ISSUE TITLE
Playwright test.fixme() annotation is not counted as skipped test

### ISSUE THREAD

**Issue by unhir** [DataDog/dd-trace-js#3097]
**Expected behaviour**

When a Playwright test is marked with annotation `test.fixme()` it will be counted as skipped as the test is not run:

> - [test.fixme()](https://playwright.dev/docs/api/class-test#test-fixme-1) marks the test as failing. Playwright Test will not run this test, as opposed to the fail annotation. Use fixme when running the test is slow or crashes. - https://playwright.dev/docs/test-annotations

**Actual behaviour**

Tests with `fixme` annotation are not counted as skipped.

**Steps to reproduce**

Adding `fixme` annotation to a test and observe results.

```
import { test, expect } from '@playwright/test';

test.fixme('test to be fixed', async ({ page }) => {
  // ...
});
```
**Environment**

* **Operation system: MacOS 13**
* **Node.js version: 18**
* **Tracer version: 3.19.0**
* **Agent version: N/A**
* **Relevant library versions: Playwright 1.33.0**

**Comment by juan-fernandez** [comment]
hey @unhir, thanks for the report. 

> Tests with fixme annotation are not counted as skipped.

Would you expect this test to be reported as failed, as playwright reports it?

**Comment by unhir** [comment]
Hey @juan-fernandez and thanks for a swift reply!

I would expect this test to be reported as skipped rather than failed, as the test does not run at all and therefore does not fail. 

Here's an example spec from a Playwright `results.json` file contents:
```
    {
      "title": "/fixme.spec.ts",
      "file": "fixme.spec.ts",
      "column": 0,
      "line": 0,
      "specs": [
        {
          "title": "Fixme annotated test",
          "ok": true,
          "tags": [],
          "tests": [
            {
              "timeout": 30000,
              "annotations": [
                {
                  "type": "fixme"
                }
              ],
              "expectedStatus": "skipped",
              "results": [
                {
                  "workerIndex": -1,
                  "status": "skipped",
                  "duration": 0,
                  "errors": [],
                  "stdout": [],
                  "stderr": [],
                  "retry": 0,
                  "startTime": "2023-05-04T05:40:51.116Z",
                  "attachments": []
                }
              ],
              "status": "skipped"
            }
          ],
          "id": "<UUID>",
          "file": "fixme.spec.ts",
          "line": 19,
          "column": 6
        }
      ]
    },
```

**Comment by juan-fernandez** [comment]
https://github.com/DataDog/dd-trace-js/pull/3100 should fix this. 

This bug is a bit weird though, because `test.fixme` used to be reported correctly _sometimes_, depending on whether it was part of a `test.describe` or not. It seems to always work now, but I'd appreciate if you can test my branch with your project: 
```
yarn add --dev dd-trace@https://github.com/DataDog/dd-trace-js/tarball/juan-fernandez/fix-playwright-fixme
```

**Comment by unhir** [comment]
I did a quick check on this and it indeed seems to fix the issue!

Thanks @juan-fernandez 💯 

<img width="385" alt="Screenshot 2023-05-04 at 14 59 29" src="https://user-images.githubusercontent.com/33260886/236197494-3b4e41b7-deb1-4ba4-bdf3-540c40ffe2f2.png">

**Comment by juan-fernandez** [comment]
nice! Thanks for checking so quickly! 👏
