### ISSUE TITLE
Add support for gRPC

### ISSUE THREAD

**Issue by rochdev** [DataDog/dd-trace-js#311]
Related: https://github.com/DataDog/dd-trace-js/issues/312

**Comment by ebenoist** [comment]
I was able to create an interceptor for this!

https://gist.github.com/ebenoist/00c8695e8750138f76ef3f4b97b135a1

**Comment by rochdev** [comment]
Thanks for this @ebenoist! I'm not very familiar with gRPC, are interceptors documented somewhere? Also, are they available on the server as well?

**Comment by ebenoist** [comment]
It depends on the implementation. Client interceptors were added to grpc node core in [version 1.11](https://github.com/grpc/grpc-node/pull/59). Server interceptors in node are planned, but [not currently implemented](https://github.com/grpc/grpc-node/issues/419) AFAIK. I've used the [Proxy API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) in the past to fake this behavior, but its than ideal.
