### ISSUE TITLE
Crashes nodejs process with error `error Command failed with signal "SIGSEGV".` when running for second time in worker thread.

### ISSUE THREAD

**Issue by Mouri0** [DataDog/dd-trace-js#3112]
**Expected behaviour**
trace as normal

**Actual behaviour**
nodejs crashes with error `error Command failed with signal "SIGSEGV".`

**Steps to reproduce**
on a new nodejs project install bree, add a file with some db connection and a query, run that file using bree for the specified interval (cron), require dd-trace in that file, and now run bree. PS dd-trace is loaded in the main process as well.

**Environment**

* **Operation system:** Apple silicon mac os
* **Node.js version:** 18
* **Tracer version:** v3
* **Agent version:** 7.37
* **Relevant library versions:** bree  6.5

```json
  "dependencies": {
    "@aws-sdk/client-ses": "^3.72.0",
    "@ladjs/graceful": "^1.0.5",
    "app-root-path": "^3.0.0",
    "axios": "^0.24.0",
    "bree": "^6.5.0",
    "cors": "^2.8.5",
    "dd-trace": "^3.19.0",
    "express": "^4.17.2",
    "fast-xml-parser": "^4.0.3",
    "http-status": "^1.5.0",
    "joi": "^17.4.2",
    "moment": "^2.29.1",
    "mysql2": "^2.3.2",
    "nodemailer": "^6.7.2",
    "sequelize": "^6.9.0",
    "winston": "^3.3.3",
    "winston-daily-rotate-file": "^4.5.5"
  }
```

**Comment by tlhunter** [comment]
Does this appear to be the same as #2627?

**Comment by jpdsteno** [comment]
> Does this appear to be the same as #2627?

Yes. Our exact issue occurs with node threads. We are also using bree.js.
