### ISSUE TITLE
Set errors in span metadata

### ISSUE THREAD

**Issue by willyyang** [DataDog/dd-trace-js#315]
How do I see the errors set from the span tag?
```
const querySpan = tracer.startSpan('xx-query', {
    childOf: resolverSpan.context()
})
querySpan.setTag('traceID', JSON.stringify(querySpan.context().traceId))

querySpan.setTag('db', 'query')
querySpan.setTag('error', 'this should be my message')
tracer.scopeManager().activate(querySpan)
...
querySpan.finish()
```

![screen shot 2018-10-15 at 12 39 16 pm](https://user-images.githubusercontent.com/6396257/46964989-88d2c480-d077-11e8-9404-3c1e8750d35f.png)
![screen shot 2018-10-15 at 12 39 26 pm](https://user-images.githubusercontent.com/6396257/46964990-8a03f180-d077-11e8-9776-38e33843d24c.png)

**Comment by rochdev** [comment]
Not sure I understand the question. Are you trying to flag a custom span as an error? If that's the case, there are a few tags that you can set: `error.type`, `error.msg` and `error.stack`

**Comment by willyyang** [comment]
Yes trying to flag a custom span as an error. Can you give me a full example of how this should be done or point me to docs? thanks.

**Comment by rochdev** [comment]
Basically it should look something like this:

```js
try {
  // some operation that may fail
} catch (e) {
  span.addTags({
    'error.type': e.name,
    'error.msg': e.message,
    'error.stack': e.stack
  })
}
```

**Comment by rochdev** [comment]
I'm inferring from the above thumbs up that this fixed your issue. Please feel free to reopen if that's not the case.
