### ISSUE TITLE
Graphql 14.x.x

### ISSUE THREAD

**Issue by danhaller** [DataDog/dd-trace-js#324]
Hi,

I believe graphql instrumentation isn't working in our app because the latest version of graphql is now `14.x.x` whereas the plugin instruments `0.13.x`.

https://www.npmjs.com/package/graphql

Is supporting 14.x.x something that you want the library to do?

Thanks

**Comment by rochdev** [comment]
It's definitely something we want to do. We want to always support new versions, but cannot do so automatically for major versions in case there are breaking changes in how the library works.

**Comment by rochdev** [comment]
Released in 0.7.0
