### ISSUE TITLE
Distributed trace stops collecting downstream services metrics on v3 or v4

### ISSUE THREAD

**Issue by danielfigueiredo** [DataDog/dd-trace-js#3244]
I've updated the dd-trace library for Nodejs to v4.2.0, and I could not get distributed tracing and individual traces to work properly.
We have no special configs and none of the braking changes required code changes.

You can see in the image below that before 13.15h - the time when I deployed the new dd-trace version - our main gateway accounted for only a small portion of time spent; after the update took place, most of the time spent was incorrectly attributed to the gateway (big purple area). 

Before the upgrade, it averaged < 10% of the time since this gateway is just a Graphql gateway server where all other schemas are remote and stitched.

<img width="1559" alt="Screenshot 2023-06-14 at 2 47 43 PM" src="https://github.com/DataDog/dd-trace-js/assets/6464911/daf045b3-cc71-4d5c-99c5-b1440053adb5">

☝️ You can see at the end I've rollback the changes, and the time spent on downstream services was already returning to normal. 

**Expected behaviour**
No changes in how it calculates time spent on downstream services.
We are able to see downstream services spans created under proper parents for requests that hit downstream services.

**Actual behaviour**
Downstream service spans are not created properly for distributed tracing.

Before, I was able to see nested spans emitted from downstream services. For example:
![Screenshot 2023-06-14 at 2 58 14 PM](https://github.com/DataDog/dd-trace-js/assets/6464911/d68f52f7-e30f-4515-9471-806c6776bc64)

**Steps to reproduce**
The [migration guide](https://github.com/DataDog/dd-trace-js/blob/master/MIGRATING.md) has no breaking changes or required code changes that affect us. Our entire tracer config fits in one simple file:

```ts
import tracer from 'dd-trace';

import { shouldSetError, Result } from '../graphql-server';
import { k } from '../project-env';
import { logger } from '../services/logger';

interface TracerLogger {
  error: (err: Error | string) => void;
  warn: (message: string) => void;
  info: (message: string) => void;
  debug: (message: string) => void;
}

const createTracerLogger = (loggerInstance: typeof logger): TracerLogger => ({
  error: (err: Error | string) => loggerInstance.error(err),
  warn: (message: string) => loggerInstance.warn(message),
  info: (message: string) => loggerInstance.info(message),
  debug: (message: Error | string) => loggerInstance.debug(message),
});

tracer.init({
  service: `${k.DATADOG_APM_DEFAULT_SERVICE}-${k.APP_ROLE}`,
  tags: { env: process.env.APP_ENV },
  hostname: k.DATADOG_APM_HOST,
  port: k.DATADOG_APM_PORT,
  logInjection: true,
  logger: createTracerLogger(logger),
});

// configure plugins
tracer.use('dns', {
  service: `${k.DATADOG_APM_DEFAULT_SERVICE}-${k.APP_ROLE}`,
});

tracer.use('net', {
  service: `${k.DATADOG_APM_DEFAULT_SERVICE}-${k.APP_ROLE}`,
});

tracer.use('redis', {
  service: `${k.DATADOG_APM_DEFAULT_SERVICE}-redis`,
});

tracer.use('pg', {
  service: `${k.DATADOG_APM_DEFAULT_SERVICE}-postgres`,
});

tracer.use('graphql', {
  hooks: {
    execute(span, _args, res: Result) {
      span?.setTag('error', shouldSetError(res));
    },
  },
});

export { tracer } from 'dd-trace';
```
☝️This file is the first file imported on top-level `app.ts`. There is no other import line that comes before the line that imports our tracer configuration above.

There are no error logs emitted by the tracer, even though I verified logging statements are working perfectly fine.

**Environment**

* **Operation system:** Alphine (based on docker.io/library/node:18.16.0-bullseye-slim)
* **Node.js version:** 18.14.0
* **Tracer version:** v2.30 (prior to upgrade), then tried v3.23.0, and v4.2.0 both have the same errors mentioned above.
* **Agent version:** v7.43.0
* **Relevant library versions:** 
  apollo-server-koa@3.10.2
  koa@2.14.1
  graphql@16.6.0
  node-fetch@2.6.11

**Comment by mrkosima** [comment]
we had a similar issue with `4.2.0` and `3.23.0`. Rolling back to the previous one that we were using (`3.8.0`) resolved the issue. So my assumption that this bug was introduced after `3.8.0`.

**Comment by danielfigueiredo** [comment]
> we had a similar issue with `4.2.0` and `3.23.0`. Rolling back to the previous one that we were using (`3.8.0`) resolved the issue. So my assumption that this bug was introduced after `3.8.0`.

That's good to know. I have not tried 3.8.0 yet, so I'm going to give that a shot as well!

**Comment by khaong** [comment]
Hi all,

We've seen the same problem on our end as well:
- OS/Node: docker.io/library/node:18-alpine docker image
- Tracer versions: 3.7.1 -> 3.23.0 (also broken on v4.6.0)
- Agent version: 7.44.1

Observed behaviour is the same - on trying different dd-trace-js versions we see a marked change in the % of downstream timing
![image](https://github.com/DataDog/dd-trace-js/assets/351934/f32b3d34-eca7-4647-940b-fa0db0e09f79)

Our trace counts in APM/traces become really inconsistent as well (note our deployment version changes):
![image](https://github.com/DataDog/dd-trace-js/assets/351934/eb6e8976-3d99-4cd9-8d18-35945985fdbf)

Example trace before:
![image](https://github.com/DataDog/dd-trace-js/assets/351934/bf44b62b-da23-4efb-bc75-493a20625430)

Example trace after:
![image](https://github.com/DataDog/dd-trace-js/assets/351934/bdf47ca6-7290-4d64-87c6-76dba4c449dc)
Note both missing downstream traces, as well as an out of order trace....referenced [in this issue](https://github.com/DataDog/dd-trace-js/issues/3044) as well?

We've done a preliminary investigation, and this behavioural change seems to stem from https://github.com/DataDog/dd-trace-js/pull/2779 - specifically the change to how the [span_context sampling is propagated]([packages/dd-trace/src/opentracing/span_context.js](https://github.com/DataDog/dd-trace-js/pull/2779/files#diff-4a2bef898d7ce94551fddb81d20eece04006b54d8d142fec43b88460858684da)). I believe @Qard references this in his PR comments -> "`SpanContext` sampling object was being reference-copied which made descending span contexts mutate their parents".

Prior to v3.15.0, as is referenced in the PR it seems that the 'last changed' span's sampling selection would win for the entire trace (within the service) - with this change each span retains an independent sample selection, essentially applying the chosen sample rate _per_ outbound request from our server, as opposed to at the root span.

Is this the desired behaviour? We were expecting any root spans which originate at this service to have _full_ depth traces downstream for spans which have been selected for trace...but what we're seeing now is really gappy and not as useful :(

**Comment by khaong** [comment]
In my local testing to debug this, a change which calls `_prioritySampler.sample()` for root spans (spans without parent) in the [tracer](https://github.com/DataDog/dd-trace-js/blob/e33a4ef8ac6bb2a18ed86ddde8285b4fd9f9e1cb/packages/dd-trace/src/opentracing/tracer.js#L70) fixes this issue, but I'm unsure if this is the intended behaviour.

**Comment by khaong** [comment]
> @khaong thanks for providing details on the error you experienced!
> 
> I have another ticket open with the DD support team for our enterprise account, as it seems like they don't look at Github issues.
> 
> Verified on my company that rolling back to the latest change before the aforementioned PR (#2779) works as expected. Children spans are created as expected, and the % of time spent is also calculated fine 👍 .
> 
> This release [v3.15.0](https://github.com/DataDog/dd-trace-js/releases/tag/v3.15.0) is the one that includes the PR 2779, and apparently, it has been broken since then.

Cool thanks for confirming @danielfigueiredo - we too have a support ticket open, let's see how we go! 🤞
