### ISSUE TITLE
[mongodb-core] Filter with circular references throws

### ISSUE THREAD

**Issue by g-ongenae** [DataDog/dd-trace-js#3247]
**Expected behaviour**

No error is thrown / the error is logged.

**Actual behaviour**

The module throws an unhandled error:

```
/usr/src/app/node_modules/dd-trace/packages/datadog-plugin-mongodb-core/src/index.js:31
  if (cmd.filter) return JSON.stringify(limitDepth(cmd.filter))
                              ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Array'
    |     index 0 -> object with constructor 'NativeConnection'
    |     property 'base' -> object with constructor 'Mongoose'
    --- property 'connections' closes the circle
    at JSON.stringify (<anonymous>)
    at getQuery (/usr/src/app/node_modules/dd-trace/packages/datadog-plugin-mongodb-core/src/index.js:31:31)
    at MongodbCorePlugin.start (/usr/src/app/node_modules/dd-trace/packages/datadog-plugin-mongodb-core/src/index.js:10:19)
    at /usr/src/app/node_modules/dd-trace/packages/dd-trace/src/plugins/tracing.js:17:12
    at Subscription._handler (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:14:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at /usr/src/app/node_modules/dd-trace/packages/datadog-instrumentations/src/mongodb-core.js:159:13
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at instrument (/usr/src/app/node_modules/dd-trace/packages/datadog-instrumentations/src/mongodb-core.js:158:24)
    at Connection.wrapped (/usr/src/app/node_modules/dd-trace/packages/datadog-instrumentations/src/mongodb-core.js:104:12)

Node.js v18.16.0
```

**Steps to reproduce**

With an app using mongoose, do a find request with a filter `{ subModel: { subProperty: true } }`

In mongoose@7.1.1, it will get converted to a mongoose object (I'm also opening a ticket on their side) which will have circular references.

I will create a sample app later.

**Environment**

* **Operation system: docker node:18.16.0-alpine**
* **Node.js version: 18.16.0**
* **Tracer version: 3.19.0** (Also tested with 4.2.0 version)
* **Agent version: hot-shots@9.3.0**
* **Relevant library versions: mongodb@5.4.0 / mongoose@7.1.1** (Also tested with 7.3.0 version)

**Comment by ghost91-** [comment]
@g-ongenae We have also just run into this issue, have you already created an issue at mongoose?

**Comment by ghost91-** [comment]
We cannot reproduce the problem with mongoose 7.3.1, but with 7.3.3, it appears again :/

**Comment by g-ongenae** [comment]
> @g-ongenae We have also just run into this issue, have you already created an issue at mongoose?

Yes, I did: https://github.com/Automattic/mongoose/issues/13512

**Comment by ghost91-** [comment]
We also cannot reproduce the problem in the 7.4 branch (to which the fix to your issue has been merged, if I am not mistaken), but that branch does not have the most recent changes from 7.3.3, so not sure if the new fix actually addresses the problem...

**Comment by FlorianChristie** [comment]
mongoose v7.4 was released yesterday and unfortunately this problem still exists for us. :(

**Comment by ghost91-** [comment]
Considering https://github.com/advisories/GHSA-9m93-w8w6-76hh, this is now a big problem for us, since there is no non-vulnerable version of mongoose that we could upgrade to, that does not trigger this bug, causing our application to crash.
