### ISSUE TITLE
Exclude hosts/domains from http plugin

### ISSUE THREAD

**Issue by archerabi** [DataDog/dd-trace-js#325]
It would be nice to add the ability to ignore tracing certain domains in the http plugin. 
A lot of applications use third party libraries for monitoring, error reporting etc and it would be good to have the option to ignore these domains.

**Comment by rochdev** [comment]
Thanks for the suggestion! This shouldn't be too difficult to implement so I'll try to do it soon.

**Comment by rochdev** [comment]
Released in 0.7.0
