### ISSUE TITLE
TraceIds - hexadecimal vs decimal inconsistency

### ISSUE THREAD

**Issue by klassm** [DataDog/dd-trace-js#3262]
Hi,

We are currently investigating the behaviour of dd-trace. Our setup looks like:
- We have the [DataDog CloudFoundry buildpack](https://github.com/DataDog/datadog-cloudfoundry-buildpack)
- We use the Node.js [automatic tracing implementation](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/nodejs/?tab=containers)
- To do so `DD_LOGS_INJECTION` is set to `true`

What we are seeing as behavior:
- We always see one log message for the router before the application and multiple log messages of the application itself
- The log from the router in front of the application contains a nice hexadecimal tracingId with 16 digits
- The logs from the service contain a 19 digit decimal representation of the trace id
- DataDog contains the decimal traceId in the APM UI.
- Downstream services get the hexadecimal representation

The B3 functionality was introduced [here](https://github.com/DataDog/dd-trace-js/pull/607) by @rochdev.

Expected:
We should see the hexadecimal implementation everywhere.

From the specification ([source](https://github.com/openzipkin/b3-propagation)) it should always be a hex number - both for traceIds and spanIds.

```
The X-B3-TraceId header is encoded as 32 or 16 lower-hex characters. For example, a 128-bit TraceId header might look like: X-B3-TraceId: 463ac35c9f6413ad48485a3953bb6124. Unless propagating only the Sampling State, the X-B3-TraceId header is required.
```

To verify what dd-trace is doing we had a look at the source code - what we found is `DatadogSpanContext`, which is calling `toString(10)` on a buffer. When we played around with it we saw that the number was always decimal, always with 19 digits.

Do you maybe have an insight on why it is implemented like this?

Thanks
Matthias

**Expected behaviour**
TraceIds and SpanIds with 64 bit (16 digit) hex numbers.

**Actual behaviour**
TraceIds and SpanIds with 19 digit decimal numbers

What we can see in the logs (via DD_TRACE_DEBUG=true)

```
2023-06-21T11:51:15.46+0200 [APP/PROC/WEB/0] OUT Extract from carrier: {"x-b3-traceid":"75c90bb7a9dc42ce","x-b3-spanid":"75c90bb7a9dc42ce","b3":"75c90bb7a9dc42ce-75c90bb7a9dc42ce"}.
2023-06-21T11:51:15.51+0200 [APP/PROC/WEB/0] OUT {"level":"info","time":1687341075510,"pid":438,"hostname":"68d7b827-39ff-4648-7487-3ac0","dd":{"trace_id":"8487327856213115598","span_id":"3992510529360162655","service":"my-service","version":"2348497297fbe7c534bfbe99d6a62f8980a1dfcd","env":"prd"},"message":"some log message","context":{"userAgent":{"raw":"Apache-HttpClient/4.5.14 (Java/17.0.6)"},"route":"/some/route"}}
2023-06-21T11:51:15.51+0200 [APP/PROC/WEB/0] OUT Inject into carrier: {"x-b3-traceid":"75c90bb7a9dc42ce","x-b3-spanid":"7768fccee01b6b8c","x-b3-parentspanid":"37683f2c5884ef5f","x-b3-sampled":"1"}.
```

You can see that dd-trace-js is extracting the hex header, logging in decimal and adding hex again to the outgoing request.

**Steps to reproduce**

From the code we tried the following:
```
const DatadogSpanContext = require('../opentracing/span_context')
const id = require('../id')

function newContext () {
  const spanId = id()
  return new DatadogSpanContext({
    traceId: spanId,
    spanId
  })
}

// eslint-disable-next-line no-console
console.log(newContext().toTraceId().length)
```
However, it is difficult to reproduce locally due to the LOGS_INJECTION part.

**Environment**

* **Operation system:** MacOS
* **Node.js version:** 18
* **Tracer version:** Git Head (Source)
* **Agent version:** Git Head (source)
* **Relevant library versions:** -

**Comment by klassm** [comment]
Hey ho.

Turns out the issue is a tiny bit different. We are using the DataDog CloudFoundry buildpack. The interesting thing is now:
- The logs from the gorouter, in front of the actual service contain a hex traceId - which is correct and which is generated by the DataDog CloudFoundry buildpack
- Logs from the actual service contain decimal, 19 digit trace and spanIds - which is imho not correct
- Logs for external services are called with the correct traceId (via DD_LOGS_INJECTION).
So the issue is the same, a little bit of a different scope.

Matthias

**Comment by klassm** [comment]
We found that trace ids need to be decimal -> https://docs.datadoghq.com/tracing/guide/span_and_trace_id_format/

**Comment by jakub-nezasa** [comment]
@klassm Just run into this. The referenced url doesn't say anywhere that the displayed value has to be decimal. In fact, it should be hexadecimal and we would need that it is.
