### ISSUE TITLE
NextJS plugin request hook called twice for a single request

### ISSUE THREAD

**Issue by tamarasaurus** [DataDog/dd-trace-js#3272]
With version 13.3.0 of NextJS + dd-trace 4.2.0 I have set up a starter NextJS project from scratch and enabled the NextJS plugin: 

```js
// tracer.js
const tracer = require('dd-trace').init();

tracer.use('next', {
  service: 'my-blog',
  hooks: {
    /* Executed when the request is finished but before API handlers are called */
    request: (
      span,
      request,
      response,
    ) => {
      console.log('request', span.context()._tags, request.url)
    },
  },
});
```

I require the tracer and start the app like this: 
```bash
node --require ./tracer.js ./node_modules/.bin/next dev
```

When I make requests to the dev or production server I see multiple logs for a single requests. 

**Expected behaviour**
I expect the request hook to be called once when I make a single request to the server.

**Actual behaviour**
The `request` hook that I've passed to the NextJS plugin is called twice. 

**Steps to reproduce**
Clone this repository - https://github.com/tamarasaurus/dd-trace-duplicate

```bash
cd nextjs-blog
npm install
npm run dev
```

The server should start at localhost:3000, then make a request to the server using curl:
```bash
curl http://localhost:3000/test
```

The result is that the console log on this line https://github.com/tamarasaurus/dd-trace-duplicate/blob/main/nextjs-blog/tracer.js#L12 is called twice. In the first span, the `next.page` span tag is not included while it's there in the second call. E.g.

```
➜  nextjs-blog git:(main) ✗ npm run dev

> dev
> node --require ./tracer.js ./node_modules/.bin/next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 243 ms (154 modules)
wait  - compiling /test (client and server)...
event - compiled client and server successfully in 47 ms (166 modules)
request {
  'service.name': 'my-blog',
  service: 'node',
  env: undefined,
  version: undefined,
  'runtime-id': 'c22c1d1b-21c4-4c21-8a17-4bfe943e0eea',
  component: 'next',
  'resource.name': 'GET',
  'span.type': 'web',
  'span.kind': 'server',
  'http.method': 'GET',
  '_dd.measured': true,
  'http.status_code': 200
} /test
request {
  'service.name': 'my-blog',
  service: 'node',
  env: undefined,
  version: undefined,
  'runtime-id': 'f8be125f-eb13-47ee-877f-3290050e39eb',
  component: 'next',
  'resource.name': 'GET /test',
  'span.type': 'web',
  'span.kind': 'server',
  'http.method': 'GET',
  '_dd.measured': true,
  'next.page': '/test',
  'http.status_code': 200
} /test

```
This issue exists on both the the dev and production servers. 

To debug the issue I added some logs in the base server of NextJS and saw that `handleRequest` is indeed called twice - is this expected behaviour? Am I initialising the tracer incorrectly? 

**Environment**

* **Operation system:** MacOS Ventura 13.3.1 
* **Node.js version:** 18.16.0
* **Tracer version:** 4.2.0
* **Agent version:** N/A
* **Relevant library versions:** NextJS 13.3.0

**Comment by tamarasaurus** [comment]
Hey team, is there any plan to fix this? It currently makes the `request` hook unusable and blocks us from upgrading NextJS. 

I think this is a case which is not caught by your NextJS plugin tests if I understand correctly by the way they're written, as they run on a custom server.

**Comment by wtan-chwy** [comment]
Hello team, we are blocked by this as well.

The changes that are being discussed in this next js issue seem to correspond to why this is happening in dd-trace. We are noticing 4 web.requests, 3 next.requests and 3x http.requests for every incoming request to our service, I am assuming that the handoff between nextjs internal processes are being captured by dd-trace
https://github.com/vercel/next.js/issues/49929#issuecomment-1637185156

**Comment by wtan-chwy** [comment]
Is this PR intended to fix this issue? do we have a ETA for release?
https://github.com/DataDog/dd-trace-js/pull/3494

**Comment by srikarsams** [comment]
@wtan-chwy Looks like the code is now available in the `v4.11.1`

**Comment by apadiyar-chwy** [comment]
@srikarsams still seeing the issue 4.11.1

**Comment by tamarasaurus** [comment]
I can confirm that this is still broken in `dd-trace@4.13.1` using `next@13.4.19`

**Comment by tamarasaurus** [comment]
After digging into this a little further it doesn't look like this PR https://github.com/DataDog/dd-trace-js/pull/3494 fixes the problem in higher versions (next > 13.2).

From testing the instrumentation by making requests to the server on `next@13.4.19` I could see that requests are stored in a `WeakSet`
https://github.com/DataDog/dd-trace-js/blob/28d21b17f1ae6e1d5c271c68788194fea272cc85/packages/datadog-instrumentations/src/next.js#L14 but that when a request is instrumented twice it doesn't look like this check works correctly: https://github.com/DataDog/dd-trace-js/blob/28d21b17f1ae6e1d5c271c68788194fea272cc85/packages/datadog-instrumentations/src/next.js#L112-L114 

Maybe the request object differs depending on which function called `instrument` e.g. `initialize` vs `handleRequest` so the `requests.has(req)` fails and so when the message is published to the `apm:next:request:finish` channel twice the request hook is then called twice https://github.com/DataDog/dd-trace-js/blob/28d21b17f1ae6e1d5c271c68788194fea272cc85/packages/datadog-plugin-next/src/index.js#L65

**Comment by apadiyar-chwy** [comment]
@sabrenner 
i am still seeing the issue, tried 3.37.0 version which had your fix.
using next version 13.4.1
<img width="782" alt="ddog_duplicate_spans" src="https://github.com/DataDog/dd-trace-js/assets/93671052/dc255394-9571-4d32-b88b-253e5704e89b">

**Comment by sabrenner** [comment]
@apadiyar-chwy Thanks for pointing this out! I will take a look at this today and try and get some clarity on why this is happening still.

For anyone else on this thread who has updated to the most recent version of the tracer, are you still experiencing this issue? If so, with which version of Next.js?

**Comment by sabrenner** [comment]
@apadiyar-chwy After taking a look at the issue, it seems that versions 13.3.1 to 13.4.12 of Next.js, when starting the server using `next start`, have issues with handoff between the internals of Next.js and our integration in the tracer. However, from some testing I did, there seems to only be one `next.request` (and, by extension, the hook is only called once) when using versions above (or below) the range defined above. If possible, try and upgrade your Next.js version to at least 13.4.13, with the latest tracer version, and see if it resolves the issue.

**Comment by apadiyar-chwy** [comment]
thank you @sabrenner , seems to working with 13.4.13
we will continue monitoring it
