### ISSUE TITLE
Major upgrade problem

### ISSUE THREAD

**Issue by trajanoreuter** [DataDog/dd-trace-js#3274]
### Discussed in https://github.com/DataDog/dd-trace-js/discussions/2705

<div type='discussions-op-text'>

<sup>Originally posted by **trajanoreuter** January 18, 2023</sup>
Hi, how are you?
We have several services that communicate via http calls and use datadog/dd-trace. We are upgrading some to v.3.1.1.
Problem:
Service A
- node: 12.20.1
- dd trace: 0.31.0

Service B
- node: 16.15.0
- dd trace: 1.5.1

Service A makes requests to Service B and we get all the traces right.
When we made the change from service B to use dd-trace v.3.1.1, we stopped having trace links between the two services.
Is this expected behavior? Were there any interface breaks between the version headers or something like that? Or how are they interpreted and linked to each other?
Thanks</div>

**Comment by tlhunter** [comment]
Distributed tracing should still work between versions like this.

Do you know if there are other tracing headers present in these requests? I believe old versions of the tracer would treat other tracing headers as higher priority than the datadog headers which caused issues like these.

Also, are you sure it's version v.3.1.1 that you updated to? That version doesn't seem to exist.

**Comment by tlhunter** [comment]
Going to close this issue as stale. Feel free to reopen if it's still occuring.
