### ISSUE TITLE
Support runtime metrics over statsd unix domain socket

### ISSUE THREAD

**Issue by ryanartecona** [DataDog/dd-trace-js#3318]
I have an application that runs in an environment where outgoing connections to local network addresses are disallowed via iptables. This app has a [hot-shots](https://github.com/brightcove/hot-shots) client configured using a unix domain socket rather than localhost:8125. It appears the statsd client that dd-trace-js uses for runtime metric reporting expects a hostname and port, so I can't give it my `uds://...` URL, and since connections to local addresses are blocked I can't fall back to `127.0.0.1:8125`.

I'd love if the runtime metrics statsd config could accept a UDS address, so I could get those metrics in this restricted environment.

**Comment by tlhunter** [comment]
Is this a duplicate of #993?

**Comment by ryanartecona** [comment]
Looks like yes, I must have missed that one.
