### ISSUE TITLE
Add support for `pg` native client

### ISSUE THREAD

**Issue by terryma** [DataDog/dd-trace-js#334]
Is this intended to work with http://docs.sequelizejs.com/ over `pg`? Out of the box I'm not seeing any spans for `pg` recorded, although I do see the `pg` plugin getting initialized. If this doesn't work out of the box, do you have some instructions on how to make it work?

**Comment by rochdev** [comment]
It should work with Sequelize or any other ORM using the `pg` module. Which versions of `dd-trace` and `pg` are you using?

**Comment by terryma** [comment]
```
dd-trace: 0.6.0
pg: 6.1.2
```

In the same application if I use the `pg.Client` directly then tracing works, but with Sequelize I'm not seeing any traces (the `pg` plugin's `patch` logic is not invoked)

**Comment by rochdev** [comment]
I wonder if Sequelize uses `pg` in some way that would skip our instrumentation. I'll have to take a look.

**Comment by terryma** [comment]
Looks like we're using the `native` option for Sequelize, which uses the `pg.native` module here https://github.com/brianc/node-postgres/tree/master/lib/native. 

Wrapping the `pg.native` module in `pg.js` allows the monkeypatching to work, but fails inside `queryWrap` because the native query object is different. 

```js
  this.wrap(pg.Client.prototype, 'query', queryWrap)
  this.wrap(pg.native.Client.prototype, 'query', queryWrap)
```

Would it be possible to support this, we want to keep the `native` flag on for our existing applications.

**Comment by rochdev** [comment]
I'll have to check if it's possible, but given the API is the same, it should definitely be possible.

**Comment by rochdev** [comment]
Ok it's definitely possible. The difficulty lies in testing this since it requires that Postgres is installed when installing `pg-native`.

**Comment by terryma** [comment]
Would you be willing to take a PR for this? I can try to get a working version locally in the next few days

**Comment by rochdev** [comment]
Definitely, but we should probably discuss to test this first given the concern I have raised above.

**Comment by rochdev** [comment]
I've split the build with 1 job per plugin, which should make it easier to implement this. However, I'm still concerned about the ability to run tests locally if an installation of Postgres is required on the developer's machine.

@terryma Any ideas?

**Comment by terryma** [comment]
Sorry I haven't taken a look at this in depth yet. I didn't realize pg native would require a local postgres to be installed? If so, is it possible to run the tests in docker? (looks like it's done that way for the CircleCI build)

**Comment by rochdev** [comment]
It's possible but I'm not sure how to do that in watch mode.

**Comment by damianijr** [comment]
+1

**Comment by rochdev** [comment]
I added support for `pg-native` but the module fails to build in tests and I can't figure out why as I don't know this module. If you guys want to take a look it's in the [pg-native](https://github.com/DataDog/dd-trace-js/tree/pg-native) branch. Once the compilation succeeds, it should be good to go.

**Comment by rochdev** [comment]
Opened an issue on `pg-native`: https://github.com/brianc/node-pg-native/issues/79

**Comment by rochdev** [comment]
Ok I found the issue which was an incompatibility between how we run tests and native module.

**Comment by rochdev** [comment]
This was added in 0.10.0
