### ISSUE TITLE
Cannot read properties of null (reading 'dogstatsd')

### ISSUE THREAD

**Issue by GeoffreyPlitt** [DataDog/dd-trace-js#3411]
I'm seeing the exact same problem as in https://github.com/DataDog/dd-trace-js/issues/3357, but I am unable to re-open that bug. Can someone with permissions re-open it?

Seems to be a regression. Happens for me whether DD_APM_ENABLED is set or not.

dd-trace 4.7.0
node 18.16.1

**Comment by tlhunter** [comment]
Reopened #3357
