### ISSUE TITLE
npm package size in 0.6.1

### ISSUE THREAD

**Issue by jordanrogers** [DataDog/dd-trace-js#343]
I noticed that the size on disk of the dd-trace npm package increased significantly with version 0.6.1

//version 0.6.0
```
~/.../node_modules/dd-trace
>du -h -d 1 .
 32K	./benchmark
464K	./test
 20K	./ext
 24K	./docs
 32K	./scripts
4.0K		./lib
4.0K		./.circleci
260K	./src
892K	.
```

//version 0.6.1
```
~/.../node_modules/dd-trace
>du -h -d 1 .
 32K	./benchmark
2.6M	./test
 20K	./ext
 25M	./docs
 32K	./scripts
4.0K		./lib
4.0K		./.circleci
260K	./src
 28M	.
```

I suspect that ./docs and ./test could be excluded from the published npm package. Perhaps ./scripts and ./benchmark as well, I am not sure.

**Comment by rochdev** [comment]
It looks like for some reason files that are excluded from `.gitignore` are not actually ignored by npm. Definitely a bug.
