### ISSUE TITLE
Distributed tracing bug?

### ISSUE THREAD

**Issue by terryma** [DataDog/dd-trace-js#344]
I haven't dug into this yet, but I think there might be a bug with serializing/deserializing trace/span IDs across distributed traces?

On service A, I have dd-trace enabled, and I make an outbound request to service B. I see this logged in service A:
```
Inject into carrier: {"x-datadog-trace-id":"2921056843272994139","x-datadog-parent-id":"4616772057589969231","x-datadog-sampling-priority":"1"}.
```

On service B running `express`, I've injected some logging to log the request headers:

```
request headers =  { accept: '*/*',
  'user-agent': 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)',
  'accept-encoding': 'gzip,deflate',
  connection: 'close',
  'x-datadog-trace-id': '2921056843272994139',
  'x-datadog-parent-id': '4616772057589969231',
  'x-datadog-sampling-priority': '1',
  host: 'host.docker.internal:3000' }
```

So I correctly see the datadog headers in service B.

But here's the encoded trace on service B for the same request:

```
2018-10-30T22:52:48.241Z 1a5Cn92c8F1d2qh0L51ZXUoJ info: [request/REST] 1a5Cn92c8F1d2qh0L51ZXUoJ - GET /v0/_status
Encoding trace: [{"trace_id":2921056843272994300,"span_id":8505126487674155000,"parent_id":8736944094988820000,"name":"redis.command","resource":"del","service":"shipotle-api-redis","error":0,"meta":{"span.kind":"client","db.type":"redis","db.name":"0","out.host":"localhost","out.port":"6379"},"metrics":{"_sample_rate":1,"_sampling_priority_v1":1},"start":1540939968228825900,"duration":1001221,"type":"redis"},{"trace_id":2921056843272994300,"span_id":8736944094988820000,"parent_id":4616772057589969000,"name":"express.request","resource":"GET /v0/_status","service":"shipotle-api","error":0,"meta":{"http.url":"http://host.docker.internal:3000/v0/_status","http.method":"GET","span.kind":"server","http.status_code":"200"},"metrics":{"_sample_rate":1,"_sampling_priority_v1":1},"start":1540939968216968000,"duration":13055664,"type":"http"}]
```

Notice how the `trace_id` is `2921056843272994300` instead of `2921056843272994139`, and the `parent_id` is `4616772057589969000` instead of `4616772057589969231`. This obviously causes the traces from service A and B to not be combined as expected.

I'll dig a little more, but want to bring this up since I just observed this behavior, and I don't have any custom logic on service B to modify the datadog headers in any way.

**Comment by terryma** [comment]
Looks like the debug log is using `JSON.stringify()`, which is not logging the correct unsigned 64bit int, see test:

```

❯ cat test.js

const Uint64BE = require('int64-buffer').Uint64BE
test = new Uint64BE('2921056843272994139', 10)
console.log('toString():', test.toString())
console.log('JSON.stringify():', JSON.stringify(test))

~/code/playground
❯ node test.js
toString(): 2921056843272994139
JSON.stringify(): 2921056843272994300

```

Not sure if this only affects logging, or the actual encoding/decoding of the trace/span IDs using msgpack yet

**Comment by rochdev** [comment]
From what I can see, this should definitely end up in a single trace. Are you saying this ends up in 2 different traces?

**Comment by terryma** [comment]
No they did end up in a single trace, looks like this is only a logging bug. Although I'm seeing very inconsistent result where a lot of my traces are missing the spans from service B. Not sure if they're getting sampled or what, is there some debugging I can do locally to verify that all traces are sampled and therefore should appear in the datadog UI?

**Comment by rochdev** [comment]
Are both services on the latest version of the tracer? Priority sampling was only added in v0.6.0

If that's the case, you should be able to see the `x-datadog-trace-id`, `x-datadog-parent-id` and `x-datadog-sampling-priority` headers being propagated in our logs in both services. You will also be able to see from the log of the trace itself if the parent header is being used properly. This should provide enough information to figure out where the context is lost.

**Comment by terryma** [comment]
I haven't seen this issue today, but it was definitely happening yesterday. If I can repro again, I'll definitely let you know, thanks!

Regardless, the logging bug should be fixed?

**Comment by andrewsouthard1** [comment]
@terryma the logging should have been added here https://github.com/DataDog/dd-trace-js/issues/347 let us know if you have any other questions
