### ISSUE TITLE
AWS S3 service name

### ISSUE THREAD

**Issue by jamiehodge** [DataDog/dd-trace-js#3469]
The aws-s3 instrumentation is not honouring the top-level service name

**Expected behaviour**
the aws-s3 traces should be under my-service

**Actual behaviour**
they are under my-service-aws-s3

**Comment by rochdev** [comment]
You can achieve this with `tracer.use('aws-sdk', { service: 'my-service' })`.

**Comment by jamiehodge** [comment]
I really wish the inheritance behavior was consistent across all services. I guess I'll resort to populating DD_SERVICE_MAPPING for now.

**Comment by ZeroCho** [comment]
I found out that there is an option named `splitByAwsService`. Setting it to be `false` prevents datadog from splitting aws services out from main service.

**Comment by bhrutledge** [comment]
> I found out that there is an option named `splitByAwsService`. Setting it to be `false` prevents datadog from splitting aws services out from main service.

@ZeroCho How did you set it to `false`?
