### ISSUE TITLE
Opentelemetry and cross process traces

### ISSUE THREAD

**Issue by Riron** [DataDog/dd-trace-js#3496]
I've been using the new Opentelemetry API to [trace Prisma](https://www.prisma.io/docs/concepts/components/prisma-client/opentelemetry-tracing) spans successfully like so.

```
const { TracerProvider } = tracer.init();

const provider = new TracerProvider();
registerInstrumentations({
  tracerProvider: provider,
  instrumentations: [new PrismaInstrumentation({})]
});

provider.register();
```

However, Prisma is split into 2 parts:
- a prisma client, running in JS land as a normal node_modules
- a prisma engine, running as a N-API. The code is in Rust

The **prisma:client:*** spans are correctly collected by dd-trace. But the **prisma:engine:*** are not. It's annoying as most of the work Prisma is doing is happening on the engine (DB query, serialization, etc).

Several people have the same problem as [mentionned in this issue](https://github.com/DataDog/dd-trace-js/issues/1244#issuecomment-1652793489). Note that in this issue, there is [another solution](https://github.com/DataDog/dd-trace-js/issues/1244#issuecomment-1212462924) with a custom `AsyncLocalStorageContextManager ` and `BasicTracerProvider` that does get the `prisma:engine` spans. It's just not as well integrated to dd-trace.

I know next to nothing about the Opentelemetry spec but I peeked at the code and I noticed that the Datadog TracerProvider doesn't support any `Propagator`. Could the Propagator be needed to enable cross process traces / spans ?
Propagators are implemented for Opentracing, so enabling them for Opentelemetry should be doable.
Or maybe it's something entirely different !

**Comment by gingermusketeer** [comment]
@Riron were you able to find a solution to this?

**Comment by Riron** [comment]
Kind of. The problem occurs because of the way Prisma implemented opentelemetry.
I've created a PR to propose a fix, but I'm not sure it will be merged as it's a bit hacky: https://github.com/prisma/prisma/pull/21076
