### ISSUE TITLE
NodeJS dd-trace payload is discarded issue

### ISSUE THREAD

**Issue by valarpirai** [DataDog/dd-trace-js#3508]
I am trying to integrate dd-trace JS SDK with NodeJS application and getting the following error from the DD debug logs

**Expected behaviour**

DD trace is not pushed to Datadog

**Actual behaviour**

This message is printed when DD debug logs enabled
`Maximum number of active requests reached: payload is discarded.`

**Steps to reproduce**

**Environment**

* **Operation system:**  AWS Linux AMI
* **Node.js version:** v16
* **Tracer version:** 4.8.0
* **Agent version:**
* **Relevant library versions:**

**Comment by ferraris-ricardo** [comment]
Hey @valarpirai. I'm running into this same issue and i saw that you closed this one. How did you solve it? Thanks!

**Comment by julianobrasil** [comment]
Same here...

**Comment by ferraris-ricardo** [comment]
@julianobrasil This is what was happening to me:

Investigating the dd-trace source i found that API calls made by dd-trace do not timeout nor fail in case of not being able to resolve the host (at least in my case). In my case, the host were the agent was running was unreachable, therefore when 8 api calls concurrently were hit the error was thrown.

**Comment by julianobrasil** [comment]
Thanks for the answer, @ferraris-ricardo. It ended up being my VPN connection that got frozen. So basically, I couldn't connect to the agent :)

**Comment by ccarse** [comment]
Has anyone solved this? We're getting some traces from this service so it doesn't seem to be a network issue.

**Comment by PauloRenato98** [comment]
I'm also having this problem with the node, some traces arrive but then they stop collecting, does anyone have any updates on the problem?
