### ISSUE TITLE
We are observing that service names as <servicename>-fs/sqs/dns/tcp but those are not specifically mentioned in that service

### ISSUE THREAD

**Issue by jvwoundtech** [DataDog/dd-trace-js#3525]
We are planning to reduce the number of logs/traces ingested to datadog as part of this initiative we are planning to reduce/remove traces for <servicename>-fs/sqs like that services. We are unable to find the exact implementation code snippet in our repository and those are being ingested directly from the sdks. Could you please suggest me on how to remove these kind of services from the datadog and stop ingestions to those in future.

**Comment by tlhunter** [comment]
What version of the tracer are you using? I think the dynamic service name generation stuff isn't the default in current versions of the tracer.

**Comment by tlhunter** [comment]
I'll close this for now but we can reopen it if it's still an issue.
