### ISSUE TITLE
Uncaught exception when closing a PubSub Subscription with active message

### ISSUE THREAD

**Issue by ndresselhaus** [DataDog/dd-trace-js#3527]
**Expected behaviour**

Subscription should close cleanly to allow graceful shutdown, even if message is currently processing.

**Actual behaviour**

Uncaught exception thrown.

**Steps to reproduce**

It's important to note that this error does not occur when there isn't a message being actively processed from a topic. 

I'm able to reproduce this on recent pubsub libraries and all major tracer versions.  The issue only occurs when there's a leased message from a PubSub subscription actively processing when calling `close()` (during a graceful shutdown).

I was able to make a quick setup using a pubsub-emulator container to minimally reproduce.

The stack trace after calling `subscription.close()`.  This test was run with dd-trace 3.32.1 and @google-cloud/pubsub 4.0.0, but it's the same error for other versions (just maybe some different line numbers).

```
~/node_modules/dd-trace/packages/dd-trace/src/plugins/tracing.js:58
    this.activeSpan.finish()
                    ^

TypeError: Cannot read properties of undefined (reading 'finish')
    at GoogleCloudPubsubConsumerPlugin.finish (~/node_modules/dd-trace/packages/dd-trace/src/plugins/tracing.js:58:21)
    at GoogleCloudPubsubConsumerPlugin.finish (~/node_modules/dd-trace/packages/datadog-plugin-google-cloud-pubsub/src/consumer.js:35:11)
    at ~/node_modules/dd-trace/packages/dd-trace/src/plugins/tracing.js:73:22
    at Subscription._handler (~/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:14:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at LeaseManager.clear (~/node_modules/dd-trace/packages/datadog-instrumentations/src/google-cloud-pubsub.js:154:23)
    at Subscriber.close (~/node_modules/@google-cloud/pubsub/build/src/subscriber.js:492:25)
    at Subscription.close (~/node_modules/@google-cloud/pubsub/build/src/subscription.js:248:26)
    at Subscription.wrapper (~/node_modules/@google-cloud/promisify/build/src/index.js:30:35)
    at process.<anonymous> (~/index.js:21:16)
```

The code:

<details><summary>Consumer</summary>

```
const tracer = require('dd-trace');
tracer.init();

process.env.PUBSUB_EMULATOR_HOST = 'localhost:8682';

const { PubSub } = require('@google-cloud/pubsub');

const client = new PubSub({ projectId: 'test-project' });

const subscription = client.subscription('test-subscription');

subscription.on('message', async (msg) => {
  console.log('message received', msg.data.toString());
  await new Promise(r => setTimeout(r, 10_000));
  msg.ack();
  console.log('acked');
});

process.on('SIGINT', () => {
  console.log('sigint received');
  subscription.close(cb => {
    console.log('after close')
  });
});

process.on('uncaughtExceptionMonitor', (...args) => {
  console.log('uncaught error', args);
});
```
</details>

<details><summary>Publisher</summary>

```const { PubSub } = require('@google-cloud/pubsub');
process.env.PUBSUB_EMULATOR_HOST = 'localhost:8682';

const client = new PubSub({ projectId: 'test-project' });

const topic = client.topic('test-topic');

void (async () => {
  await topic.publishMessage({ json: {} });
})()
  .catch(console.error)
  .then(() => process.exit());
```
</details>

<details><summary>Emulator container, for completeness</summary>

```
version: '3'
name: pubsub-test
services:
  pubsub-emulator:
    image: 'messagebird/gcloud-pubsub-emulator:latest'
    ports:
      - '8682:8681'
    environment:
      PUBSUB_PROJECT1: test-project,test-topic:test-subscription
```

</details>

**Environment**

* **Operation system:** MacOS, alpine
* **Node.js version:** 16.20.0, 18.15.0,
* **Tracer version:** 2.40.0, 3.32.1, 4.11.1
* **Agent version:** N/A
* **Relevant library versions:** `"@google-cloud/pubsub": "3.7.1 || 4.0.0"`

```
{
  "name": "pubsub-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "@google-cloud/pubsub": "^4.0.0",
    "dd-trace": "3"
  }
}
```

**Comment by ndresselhaus** [comment]
Just realized this PR was an attempt to fix this problem: https://github.com/DataDog/dd-trace-js/pull/2716

[This comment](https://github.com/DataDog/dd-trace-js/pull/2716#discussion_r1084657872) indicates that this won't be a simple fix regardless, and that PR might be a better source of discussion.  Not sure if this issue should be closed in favor of that PR.  Let me know.

**Comment by philwhln** [comment]
We hitting this as well. We've hit several issues with `dd-trace/packages/datadog-plugin-*` packages recently that I'm wondering if Datadog is doing a wise thing here by trying to auto-integrate with arbitrary versions of packages. Would be better if this was explicit installs of these plugins specific to the versions installed.

**Comment by rochdev** [comment]
Closing as the fix from the above PR was released a few weeks ago.
