### ISSUE TITLE
MariaDB database monitoring

### ISSUE THREAD

**Issue by jamiehodge** [DataDog/dd-trace-js#3528]
Looking at the source, the mariadb plugin inherits from the mysql plugin, so I would expect it to produce [database monitoring](https://docs.datadoghq.com/database_monitoring/connect_dbm_and_apm) data, but I'm not seeing it. Beyond setting `DD_DBM_PROPAGATION_MODE` to `full`, are there additional steps?

**Comment by tlhunter** [comment]
My guess is that the tracer does insert the DBM comments for the query but that there's no MariaDB backend integration so the comments are just ignored. This is based on the document you linked to not mentioning "Maria" anywhere. So I suspect this is a feature request for another team.

Can you fill out a feature request on this form? They'll be able to route it to the right team and prioritize correctly.
https://help.datadoghq.com/hc/en-us/requests/new
