### ISSUE TITLE
`dd-trace/esbuild` doesn't resolve Typescript and aliased imports

### ISSUE THREAD

**Issue by zemlanin** [DataDog/dd-trace-js#3547]
**Expected behaviour**
Typescript projects bundled by esbuild with `dd-trace/esbuild` plugin enabled should build without any warnings when importing `.ts`/`.tsx` files or using [`compilerOptions.baseUrl` TS option](https://www.typescriptlang.org/tsconfig#baseUrl) for shorter import paths

**Actual behaviour**
Getting `MISSING: Unable to find "{imported path}". Is the package dead code?` warnings build build

**Steps to reproduce**
Example repo: https://github.com/zemlanin/dd-trace-esbuild-ts

Examples of problematic imports:

```ts
 // importing `./module/index.ts`
import * from "./module";
import * from "./module/index.ts";

// importing `src/module/index.js` with `compilerOptions.baseUrl: "src"` in `tsconfig`
import * from "module";
```

**Environment**

* **Operation system:** macOS Ventura 13.4
* **Node.js version:** 18.16.0
* **Tracer version:** `dd-trace@4.12.0`
* **Agent version:** n/a
* **Relevant library versions:** `esbuild@0.17.16` and higher

```json
{
  "dependencies": {
    "dd-trace": "^4.12.0",
    "esbuild": "^0.19.2"
  }
}

```

**Comment by tlhunter** [comment]
You're finding that `import * from "./module/index.ts";` fails? I was trying variants of this locally where the .ts extension was provided and it seemed to work.

I'm building out a solution to this in #3545. Do you know all of the permutations of importing that are possible? Is it common for TS projects to have a foo.js file sitting next to a foo.ts file?

**Comment by zemlanin** [comment]
> You're finding that `import * from "./module/index.ts";` fails? I was trying variants of this locally where the .ts extension was provided and it seemed to work.

TS checker doesn’t like it when you import paths with `.ts` extension

> Do you know all of the permutations of importing that are possible? Is it common for TS projects to have a foo.js file sitting next to a foo.ts file?

In seven years of using TS, I don’t remember ever seeing that in live projects

**Comment by g3tr1ght** [comment]
".ts" file extension in the import statements is invalid, see: https://www.typescriptlang.org/docs/handbook/esm-node.html

**Comment by zemlanin** [comment]
For completeness's sake, `.jsx` and `.tsx` files cause the same problem

**Comment by tlhunter** [comment]
Do any of you use this feature?

```js
// importing `src/module/index.js` with `compilerOptions.baseUrl: "src"` in `tsconfig`
import * from "module";
```

**Comment by zemlanin** [comment]
Yes

And, while we’re not using Next.js at the company, it seems to be somewhat popular and it does [suggest](https://nextjs.org/docs/pages/building-your-application/configuring/absolute-imports-and-module-aliases) this approach for imports

**Comment by tlhunter** [comment]
I'll need some sort of marker to know if a package is "local" or not. It looks like Next suggests prefixing paths with `@`. Do you do something similar, @zemlanin?

**Comment by zemlanin** [comment]
We’re using `@/` prefix in some of the projects, but not in the one with `dd-trace`, where top-level import are unprefixed, just like in the example repo (just haven’t gotten to updating `import`s everywhere). But might be an okay compromise/solution

It’s late where I am, so I’ll check tomorrow if other tooling in that “un-prefixed” project work fine with `@/` imports

**Comment by zemlanin** [comment]
[`eslint-import-plugin`](https://github.com/import-js/eslint-plugin-import) doesn't resolve aliased paths at the moment 😕

https://github.com/import-js/eslint-plugin-import/issues/2765

**Comment by zemlanin** [comment]
Yup, all other build/lint tooling supports `@/` imports
