### ISSUE TITLE
Esbuild plugin throws a lot of warnings

### ISSUE THREAD

**Issue by hkroger** [DataDog/dd-trace-js#3567]
**Expected behaviour**

No warnings

**Actual behaviour**

Dozens of warnings like this with different referenced files:

    MISSING: Unable to find "./pagination". Is the package dead code?

The bundled file seems to work though.

**Steps to reproduce**

**Environment**

* **Operation system:** MacOS 13.5.1
* **Node.js version:** 18.17.1
* **Tracer version:** 4.12.0 
* **Agent version:**
* **Relevant library versions:**

Esbuild config:

```
import ddPlugin from 'dd-trace/esbuild.js';
import * as esbuild from 'esbuild';

await esbuild.build({
  entryPoints: ['src/index.ts'],
  outfile: 'js/index.js',
  bundle: true,
  platform: 'node',
  target: 'node18',
  plugins: [ddPlugin],
}).catch((err) => {
  console.error(err)
  process.exit(1)
})
```

**Comment by tlhunter** [comment]
That output is useful for debugging an application that builds properly but behaves in a manner that is different than its unbundled equivalent. The MISSING logs mean that a "./pagination" file was required or imported but doesn't exist on disk. If the app behaves correctly then the output can be ignored. It's just like any compiler warning.

Is this negatively affecting your application?

**Comment by hkroger** [comment]
> That output is useful for debugging an application that builds properly but behaves in a manner that is different than its unbundled equivalent. The MISSING logs mean that a "./pagination" file was required or imported but doesn't exist on disk. If the app behaves correctly then the output can be ignored. It's just like any compiler warning.
> 
> Is this negatively affecting your application?

It doesn't seem to be affecting the execution of the program. Only thing it causes is just stress to me and other developers :)

**Comment by tlhunter** [comment]
Would the experience be better if all of those logs were prefixed with `Warning: `?

**Comment by dearmondk** [comment]
This error still exists. I see this for ~lines. If I remove the "dd-trace/esbuild" plugin, the issue goes away. Currently on `dd-trace": "^5.9.0`

**Comment by mlh758** [comment]
Just chiming in to respond to that last question - I personally think that yes, the experience would be better if the logs were prefixed with `Warning:` since at first glance I was worried it was failing completely.
