### ISSUE TITLE
Cypress Hooks Failure Marking Tests as Skipped Instead of Failed in DataDog

### ISSUE THREAD

**Issue by OlgaShchekina** [DataDog/dd-trace-js#3578]
**Expected behaviour**
Cypress hooks should be traced along with the **IT** block. If requests fail in hooks, tests should be marked as failed, and errors should be shown in DataDog.

**Actual behaviour**
If requests fail in **before** or **beforeEach** hooks, tests are marked as skipped in DataDog, despite the status in CI being failed. 

**Steps to reproduce**
Any Cypress test with before hook - the request in before hook should fail.

Ex: Create a user token: We create the token in the **before** hook and use it in the **it** block. If the request in the hook fails, DataDog marks the test as skipped.

```
describe('User Management', () => {

let userToken;
const username = 'testuser'
const password = 'testpass'

  before(() => {
    cy.request('POST', '/api/create-user', { **username1**, password }) // wrong username on purpose to fail the hook
      .then(response => {
        expect(response.status).to.eq(201); 
        userToken = response.body.token;
      });
  });

  it('should retrieve user token', () => {
    cy.log('User Token:', userToken);
  });

  after(() => {
    if (userToken) {
      cy.request({
        method: 'DELETE',
        url: '/api/delete-user/username',
        headers: {
          Authorization: `Bearer ${userToken}`
        }
      }).its('status')
        .should('eq', 200)
    }
  });
});
```

Output: the test skipped in DD:
<img width="721" alt="Screen Shot 2023-08-24 at 5 48 13 PM" src="https://github.com/DataDog/dd-trace-js/assets/57824176/384ad897-b720-4dbf-94a0-4f4d8e42916b">

**Environment**

* **Operation system: Linux**
* **Node.js version: 16.20.1**
* **Tracer version: 4.12.0**
* **Agent version:**
* **Relevant library versions: Cypress v12.17.2**

**Comment by juan-fernandez** [comment]
hey @OlgaShchekina ! Thanks for the report. `before` is a _suite_ level hook, so it it fails, no tests are actually run. `before` is not attached to any specific test. 

This said, I agree it's confusing if datadog is not reporting any error, but _it should_. With test suite level visibility, the test suite and the test session should be failing. 

So my question is the following: can you see test levels other than _test_? If not, are you using agentless mode? More info about how to activate it in https://docs.datadoghq.com/continuous_integration/tests/javascript/?tab=cloudciprovideragentless. If you're using a datadog agent, what version is it? This is important, because older versions might not be compatible with test suite level visibility.

**Comment by juan-fernandez** [comment]
that's weird. Don't you see a **Level** selector at the top left corner of the "Test Runs" section? 
<img width="412" alt="Screenshot 2023-08-28 at 23 11 51" src="https://github.com/DataDog/dd-trace-js/assets/22798219/9fabdb44-9eb6-48cf-bdfb-3879a284fea4">

see more in https://docs.datadoghq.com/continuous_integration/explorer/?tab=testruns#overview

**Comment by juan-fernandez** [comment]
let me confirm but I'm pretty sure I found no way to extract this from cypress 😞. I did this work in https://github.com/DataDog/dd-trace-js/pull/3214/files#diff-3ffc2a62ff13d8fae43be401b0db00fa504cc23dbe9fe36911577780243c98f1R18-R27, but as I can see, errors in `before` hooks (suite level) are a special case where the error is not reported

**Comment by OlgaShchekina** [comment]
Same for me, I tried to add assertions and throw an error but didn't see it in DD, only in Gihtub Actions

**Comment by juan-fernandez** [comment]
> Same for me, I tried to add assertions and throw an error but didn't see it in DD, only in Gihtub Actions

I'll have a look to confirm, but for the moment I'm pretty sure this will be a known limitation of the cypress integration.

**Comment by OlgaShchekina** [comment]
thank you @juan-fernandez !

**Comment by juan-fernandez** [comment]
hey @OlgaShchekina is this still happening to you? The latest changes to the cypress plugin should fix this. I'm closing the issue but feel free to reopen if you keep seeing it
