### ISSUE TITLE
Distributed Tracing bug (Inject)

### ISSUE THREAD

**Issue by willyyang** [DataDog/dd-trace-js#363]
I think there's an issue with the injection of traceIds which makes figuring out which distributed spans are linked via traceIDs in Trace Search impossible.

```
import { FORMAT_HTTP_HEADERS } from 'opentracing'

const tracer = require('dd-trace').init({..})
const span = tracer.startSpan("span")
const headersObj = {}
// do work...
tracer.inject(span, FORMAT_HTTP_HEADERS, headersObj)

console.log(headersObj['x-datadog-trace-id']) //5662658751323240948

// Now lets see what the traceID is of our span
const Uint64BE = require('int64-buffer').Uint64BE
const test = new Uint64BE(span.traceId, 10)
console.log('test')
console.log(test.toString()) //15915993762011021322
console.log(JSON.stringify(test)) // 15915993762011021000
console.log(JSON.stringify(span.traceId)) // 5662658751323240000
```

So the traceId from the span I created .. and the traceId that gets created by using `inject` .. is not the same ?

Any guidance on how I can fix this issue would be great.  

"dd-trace": "^0.6.0",

**Comment by willyyang** [comment]
similar to https://github.com/DataDog/dd-trace-js/issues/344

**Comment by rochdev** [comment]
Your test is not working because `span.traceId` doesn't exist. I updated the code and I am seeing the correct behavior where both IDs are the same.

```js
const { FORMAT_HTTP_HEADERS } = require('opentracing')

const tracer = require('dd-trace').init()
const span = tracer.startSpan('span')
const headersObj = {}
// do work...
tracer.inject(span, FORMAT_HTTP_HEADERS, headersObj)

console.log(headersObj['x-datadog-trace-id'])

// Now lets see what the traceID is of our span
console.log('test')
console.log(span.context().traceId.toString())
```

Are you experiencing a problem that you were trying to debug using this?

**Comment by willyyang** [comment]
Sorry I was trying to get rid of private code, I was testing using `console.log(JSON.stringify(span.context().traceId))` to generate that number.
Looks like `JSON.stringify(` and `.toString()` give different numbers. `toString()` gives the correct value as you mentioned.

And yes, I'm trying to use the Trace Search Feature in DD to filter my services by traceIDs but I noticed that each of my traceIDs are only associated with one service. Though I'm able to see distributed traces formed by spans linking from 3 services in Trace List ..

**Comment by rochdev** [comment]
It sounds like this is out of scope of Node APM. I would recommend either asking for help on our public Slack or open a support ticket. It's possible the difference is expected and there may be another way to do what you want, or maybe it's a bug.

**Comment by rochdev** [comment]
Closing this for now. Please feel free to reopen if needed.
