### ISSUE TITLE
Can we disable injection of DD tracing headers for some requests?

### ISSUE THREAD

**Issue by azjgard** [DataDog/dd-trace-js#3662]
My question / request is actually identical to a corresponding issue in the dd-trace-java repository: https://github.com/DataDog/dd-trace-java/issues/3685

We're implementing support for a webhook system, wherein users can furnish 3rd party URLs to which we will send requests. 

Currently, all of these requests include DataDog-injected headers (`x-datadog-origin`, `x-datadog-trace-id`, etc). Our strong preference would be to omit these headers when sending requests to 3rd party systems.

Is this something that is currently possible? As mentioned in the other issue, we'd be super happy with a list of allowed hosts to constrain the header injection to requests internal to our system.

**Comment by manvydasu** [comment]
Thinking again, it looks like for webhooks use case instead of having`propagationBlocklist`, there should be `propagationWhitelist` - as it's going to be impractical to list all of the possible urls during startup with the `propagationBlocklist`

**Comment by azjgard** [comment]
> Thinking again, it looks like for webhooks use case instead of havingpropagationBlocklist, there should be propagationWhitelist - as it's going to be impractical to list all of the possible urls during startup with the propagationBlocklist

We may be able to make `propagationBlocklist` work by inverting the regex and matching against all URLs that are not internal (unless there's something I'm missing about the implementation of the added field), but agreed that it would be a little more ergonomic for our use-case if there were a `propagationWhitelist` instead.

I'll report back after testing this out to see if our needs are met by the linked PR. Thanks!
