### ISSUE TITLE
Allow Datadog trace headers when using AWS IAM authentication

### ISSUE THREAD

**Issue by ryan-breidenbach** [DataDog/dd-trace-js#3719]
Currently, dd-trace [explicitly omits trace HTTP headers](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-http/src/client.js#L61-L63) if a request uses AWS IAM authentication. This behavior was introduced by [this change](https://github.com/DataDog/dd-trace-js/pull/205) that was made in 2018.

The comments in the change suggest that adding Datadog headers will break the authentication of the signature and cause `403` errors. However, this is not the case. When the [signature is created](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html), the headers used to calculate the signature are captured in the `SignedHeaders` component of the `Authorization` header. Any additional headers that are added after the signature is generated will be ignored.

We work with many applications that use IAM authentication for service-to-service communication. Not being able to see traces span all of our applications is hindering our ability to support and troubleshoot these applications.  I would like the ability to at least "opt-in" for allowing headers when using IAM authentication.

**Comment by tlhunter** [comment]
I'm reverting the commit that I made to re-enable these headers on AWS requests:
https://github.com/DataDog/dd-trace-js/pull/3799

Both @rochdev and @astuyve believe the change will cause a lot of failures. Will need to build out better tests to figure this out.

**Comment by astuyve** [comment]
Hey I'm sorry there was some confusion here on my end, unless the headers are explicitly part of the signature (present in `SignedHeaders`), it should be possible to add additional headers after signing without causing issues. I think #3796 would be okay, and we can test this in an integration test in something like Lambda to verify. But it seems like we had some reported issues, so I'd be curious to see what those are before making any further changes.

**Comment by rochdev** [comment]
> But it seems like we had some reported issues

That's the main concern, we used to not handle this at all and we received several reports that applications were starting to error. Since there hasn't been any changes to the signature version, I would expect a regression of any cases that were not working before we introduced the check.

**Comment by janos-kasa** [comment]
We were able to use this version and all requests correctly went through the IAM Authentication between our services, and DD was able to connect the trace.
I also support the configuration flag idea.
