### ISSUE TITLE
Support data streams monitoring for AWS SQS

### ISSUE THREAD

**Issue by nikhilgupta345** [DataDog/dd-trace-js#3732]
https://docs.datadoghq.com/data_streams/#explore-data-streams-monitoring

This feature is not supported for SQS within the NodeJS SDK, but is supported by Java and Python. Would love to see this functionality added to the NodeJS project!

**Comment by mipearson** [comment]
Alternatively, provide instructions on manual instrumentation, similar to what's there for Go.
