### ISSUE TITLE
Restify route mangled/duplicated when using Restify v9 async middlewares.

### ISSUE THREAD

**Issue by pinko-fowle** [DataDog/dd-trace-js#3775]
(This is likely related to other Restify v9 issue in #3774)

**Expected behaviour**

`dd-trace` server sdk should report the service's entry spans with the `http.route` and span resource used by Restify. If I request `/echo/:name`, I should see `/echo:name` as the entry span's resource and `http.route`.

**Actual behaviour**

Currently the route reported by the service's entry span is mangled if async middlewares/handlers are used (introduced in Restify v9).

For example, in the screenshot snippet below I am actually hitting a `/async/:name` route, but it shows up as `/async/:name/async/:name`.

<details>
<summary>example detailed trace view</summary>

![Screenshot 2023-11-07 at 5 24 20 PM](https://github.com/DataDog/dd-trace-js/assets/60750759/772b3425-acb6-4a2e-b5d3-7b1b9bf99681)
</details>

This shows the route duplicated twice. Also, in some cases, we have seen the route repeated >2 times. I don't have an easy reproduction, but we have seen in prod `/health-check/health-check/health-check` and some routes duplicating the route 4+ times.

**Steps to reproduce**

The `/async/:name` route in https://github.com/pinko-fowle/repro-dd reproduce this behavior. (This is derived from the example Restify app at https://github.com/restify/node-restify#server . For reference, I have copy-pasted the code below:

<details>
<summary>server.js</summary>

```js
var trace = require('dd-trace');
trace.init();

var restify = require('restify');

const server = restify.createServer({
  name: 'repro-dd',
  version: '0.1.0'
});

server.use(restify.plugins.acceptParser(server.acceptable));
server.use(restify.plugins.queryParser());
server.use(restify.plugins.bodyParser());

function logSomething(req, res, next) {
  console.log({something: 42})
  return next();
}
function echoName(req, res, next) {
  res.send(req.params);
  return next();
}
// legacy restify syntax
server.get('/echo/:name', logSomething, echoName);

async function logSomethingAsync(req, res) {
  console.log({something: "someday"})
}
async function echoNameAsync(req, res) {
  res.send(req.params);
}
// restify v9+ can accept async functions
server.get('/async/:name', logSomethingAsync, echoNameAsync);

server.listen(8080, function () {
  console.log('%s listening at %s', server.name, server.url);
});
```

</details>

Technical notes: this is likely related to how Restify v9 has changed. The best guide I've found is [8to9guide.md](https://github.com/restify/node-restify/blob/master/docs/guides/8to9guide.md). In short, anything with 3 arguments is treated as "legacy" middleware, and anything (warning: async or not!!) with only two arguments is regarded as "new" middleware that is awaited. Note that _testing for function asyncness is not how Restify checks what mode to run a middleware/handler in_.

There are currently no async middleware/handler tests in https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-restify/test/index.spec.js#L40 .

This is likely related to another Restify v9 issue in #3774 (I have made this callout at the beginning of this bug report as well). It is a very different symptom, & only affects some of our routes, but occurred around the same time, as we upgraded Restify.

**Environment**

* **Operation system:** MacOS 13.6
* **Node.js version:** 20.81
* **Tracer version:** 4.18.0
* **Agent version:** 7.40.1
* **Relevant library versions:** Restify 11.1.0
* **Relevant `package.json`:**

```json
{
  "name": "repro-dd-restify",
  "version": "0.1.0",
  "dependencies": {
    "dd-trace": "^4.18.0",
    "restify": "^11.1.0"
  }
}
```

**Comment by AndrewCsontos** [comment]
This issue can now be closed.

It was resolved by https://github.com/DataDog/dd-trace-js/pull/3782 and https://github.com/DataDog/dd-trace-js/pull/3818 and fixed in release: https://github.com/DataDog/dd-trace-js/releases/tag/v4.21.0

Thanks for the fix @tlhunter!
