### ISSUE TITLE
express  web xhr 》router》node xhr》res

### ISSUE THREAD

**Issue by wanglong167** [DataDog/dd-trace-js#382]
node xhr Will the new generation trace_id

**Comment by wanglong167** [comment]
node xhr  Will the new generation trace_id

**Comment by wanglong167** [comment]
`
  function makeRequestTrace (request) {
    return function requestTrace () {
      const args = normalizeArgs.apply(null, arguments)
      const uri = args.uri
      const options = args.options
      const callback = args.callback

      if (!config.filter(uri)) {
        return request.call(this, options, callback)
      }

      const method = (options.method || 'GET').toUpperCase()

 
      const parentScope = tracer.scopeManager().active()

    parentScope  null
`

**Comment by wanglong167** [comment]
express-rate-limit   cause

**Comment by rochdev** [comment]
@wanglong167 Can you add more details about what the issue was? Is there some sort of incompatibility between `dd-trace` and `express-rate-limit`?
