### ISSUE TITLE
trace grouping not working when used with router

### ISSUE THREAD

**Issue by saidmasoud** [DataDog/dd-trace-js#385]
We have multiple instances of `koa-router`, and we inject the tracer agent as a middleware into each router so that `ctx._matchedRoute` will work properly. However, when we inject the tracer into the Router object, it does not properly associate database (postgres and mysql) and other traces with the HTTP request. This functionality worked when we were injecting the tracer directly into the Koa object, but doing that breaks the `ctx._matchedRoute` attribute that we need to group HTTP requests together with their matched route.

**Comment by rochdev** [comment]
What do you mean when you say "inject the tracer"? The tracer should be initialized only once before all other modules are required. If you are not getting the correct resource name when using `koa-router` this is a bug.

Which version of `dd-trace`, `koa` and `koa-router` are you using? Also, could you provide a snippet of how the tracer is used?

**Comment by saidmasoud** [comment]
dd-trace: 0.6.2
koa: 2.5.1
koa-router: 7.4.0

We have the tracer initialized in a separate code base (which serves as a dependency to our main app), and is initialized as so:

```typescript
export const tagRequest = (opts: TracerOptions): (ctx: Context, next: () => Promise<{}>) => Promise<void> => async (ctx: Context, next: () => Promise<{}>): Promise<void> => {
    const appName = opts.name || process.env.APP_NAME;
    .............................

    const tracer = Tracer.init({
        name: appName,
        env: process.env.NODE_ENV,
        port: opts.port || process.env.DD_AGENT_SERVICE_PORT,
        hostname: opts.hostname || process.env.DD_AGENT_SERVICE_HOST,
    });

    const span = await tracer.startSpan(appName, {
        service: appName,
        tags: {
            "http.matchedRoute": ctx._matchedRoute,
            "http.url": ctx.url,
            "http.method": ctx.method,
        },
    });
.................
}
```

We then import that project into our main app and use it as a router middleware:

```typescript
import * as Router from "koa-router";
import { middleware } from "dependency-repo";

const tagRequest  = middleware.datadog.tagRequest({
    name: "main-app",
    env: process.env.NODE_ENV,
    port: process.env.DD_AGENT_SERVICE_PORT,
    hostname: process.env.DD_AGENT_SERVICE_HOST,
});

const authRouterv2 = new Router();

authRouterv2.use(tagRequest);
..................

securedRoutes.forEach((route: Router) => route.use(...authMiddleware, tagRequest));
```

What we USED to do (which broke `ctx._matchedRoute` because we `app.use()` multiple router instances) is the following:

```typescript
const tracer = require("dd-trace").init({
    name: "main-app",
    env: process.env.ENVT,
    port: process.env.DD_AGENT_SERVICE_PORT,
    hostname: process.env.DD_AGENT_SERVICE_HOST,
});

app.use(async (ctx:Context, next: () => Promise<{}>) => {
    const span = await tracer.startSpan("relax", {
        service: "main-app",
        tags: {
            "http.url": ctx.url,
            "http.method": ctx.method,
        },
    });
.................
}
```

**Comment by rochdev** [comment]
Thanks for the snippets. A few things:

Using the tracer as mentioned in the first 2 snippets is not supported. If it works it's luck but it could eventually break.

Using multiple instances of `koa-router` is however supported, so if this is not working for you there is definitely a bug there. Can you provide a minimal runnable snippet that reproduces the issue?

As a side note, why are you creating an additional span at the beginning of every handler? Are you missing any information when using the out of the box integration?

**Comment by saidmasoud** [comment]
We figured out the root cause: we were referencing `ctx._matchedRoute` before calling `await next();`. Switching the code around fixed the issue!

**Comment by rochdev** [comment]
Thanks for the update @saidmasoud ! One thing I'm still wondering is why not use our out of the box integration for Koa? Anything missing?
