### ISSUE TITLE
How to set a user_id tag with graphql plugin?

### ISSUE THREAD

**Issue by idris** [DataDog/dd-trace-js#386]
I'm setting up Trace Search, and have my graphql queries and mutations set in `analyzed_spans`.  That's all working great, but now I want to add a `user.id` tag to all of those spans so that I can filter by user ID in Trace Search & Analytics.

What's the best way to do this?  I tried adding the following in a schema-level resolver (using [`addSchemaLevelResolveFunction` from graphql-tools](https://www.apollographql.com/docs/graphql-tools/resolvers.html#addSchemaLevelResolveFunction)):
```js
addSchemaLevelResolver(Schema, (user, args, ctx, info) => {
  if (user) {
    const scope = tracer.scopeManager().active();
    if (scope) {
      const span = scope.span();
      if (span) {
        span.setTag('user.id', user.id);
      }
    }
  }
});
```

That did not work.. didn't add a tag to anything.  Ideas?

**Comment by rochdev** [comment]
Is the user ID already available when the GraphQL query executes, or does it become available from one of the resolvers?

**Comment by rochdev** [comment]
On which level are you trying to do the search? If the user ID is available on the root span, can you do the search on the top-level service?

**Comment by idris** [comment]
The problem is that Trace Search shows the Resource name, which for GraphQL hits are all `POST /graphql`.  That makes that column useless, and there's no way to get the GraphQL query info (query name, for example) without using GraphQL as the span that's analyzed.

**Comment by rochdev** [comment]
Do you have any way to explicitly pass an initial `contextValue` to the operation with the library you are using? If this is the case, I can offer a workaround since attaching a tag to every span of a specific trace is not currently possible.

**Comment by rochdev** [comment]
Actually never mind my previous comment, I think you could simply attach the query name to the request itself in order to be able to search on it since the user ID is already available on the request. This of course has the assumption that the request only does a single operation.

**Comment by idris** [comment]
Great idea.. thanks!
