### ISSUE TITLE
Playwright: Adding custom tags is not working.

### ISSUE THREAD

**Issue by jllopez** [DataDog/dd-trace-js#3861]
Hello,

I stumbled upon this PR https://github.com/DataDog/dd-trace-js/pull/3741 and tried adding custom tags to my Playwright tests but sadly it didn't work. I added the following lines to my tests:

```test('my first test', async ({ page }) => {
    test.info().annotations.push({
      type: 'DD_TAGS[tag.team]',
      description: '@uiTeam',
    });
    ...
    ...
  });
  ```

**Expected behaviour**
The user should be able to see custom tags added to tests displayed under the DataDog CI -> Tests -> "your branch" section.

**Actual behaviour**
The annotation push did not produce any custom tags. I am not able to see them in the DataDog UI when navigating to my tests executions under the CI -> Tests section.

**Steps to reproduce**

1. Create a PW test
2. Add a custom annotation as described in the following example:

```
test('user profile', async ({ page }) => {
  test.info().annotations.push({ type: 'DD_TAGS[tag.team]', description: '@uiTeam' })
  // ...
});
```

3. Push your changes and let them run in the CICD Pipeline
4. Navigate to the CI -> Tests -> "branch name" section in DataDog
5. Navigate the UI and locate your test
6. Click on your test and scroll down to the "Other tags" section
7. Click on the "Other tags" section and search for your custom tag
8. The custom tag should be visible. In this case "tag.team"

**Environment**

* **Operation system: Linux (Gitlab Docker container)**
* **Node.js version: v20.9.0**
* **Tracer version: ^4.20.0**
* **Agent version:**

**Comment by juan-fernandez** [comment]
hey @jllopez ! Thanks for the report. This is unexpected, because we're testing exactly that in our e2e tests: https://github.com/DataDog/dd-trace-js/blob/master/integration-tests/playwright/playwright.spec.js#L112-L113 and https://github.com/DataDog/dd-trace-js/blob/master/integration-tests/ci-visibility/playwright-tests/landing-page-test.js#L24-L25. 

I also run a manual test and the tag seems to be reported: 

<img width="240" alt="Screenshot 2023-12-12 at 15 46 39" src="https://github.com/DataDog/dd-trace-js/assets/22798219/276e8c5c-9861-457d-b950-9f4453d83731">

What version of playwright are you using? Are you using agentless? A small reproducible case would be extra useful in this case 😄

**Comment by jllopez** [comment]
Hello Juan,

Thanks for  the response. 

Yes, we are Agentless.

Playwright info:

"playwright": "^1.39.0",
"@playwright/test": "^1.39.0"

Will this work as a small reproducible case? 

```
test('assert a value', async ({ page }) => {
 test.info().annotations.push({ type: 'DD_TAGS[tag.team]', description: '@uiTeam' })
  const value = 2;
  expect(value).toBe(2);
});
```

This simple tests runs successfully but DataDog tags are never reported.

**Comment by juan-fernandez** [comment]
sadly that's exactly what I tested and the tags are reported correctly 🤔. I just tested those versions too. Do you think you can create a small public repository where the issue is reproduced?

**Comment by jllopez** [comment]
Will try to reproduce on a small repo and update this issue accordingly. Thanks for the feedback.

**Comment by jarydpeloton** [comment]
I'm also experiencing a similar issue trying to set this up. Should these annotations show up in the `Encoding payload` step when executing the tests with `DD_TRACE_DEBUG` as true? I don't see them there, or in the DD UI either

**Comment by jarydpeloton** [comment]
Actually, I just upgraded playwright and dd trace and now its working as expected 👍 
dd trace @ 4.20.0 
playwright @ 1.40.1

**Comment by jllopez** [comment]
I just noticed that the team uses @nx/playwright and @playwright/tests packages.

Those were also outdated. I updated them to:

"@nx/playwright": "^17.2.4",
"@playwright/test": "^1.40.1",

but still no luck.

I am still trying to figure out how to create the small public repo w/o impacting the organization's cicd infrastructure and security (which we depend on)

**Comment by juan-fernandez** [comment]
> I'm also experiencing a similar issue trying to set this up. Should these annotations show up in the `Encoding payload` step when executing the tests with `DD_TRACE_DEBUG` as true? I don't see them there, or in the DD UI either

yeah, it should show up there

**Comment by jllopez** [comment]
A package clean up and rebuilt helped. Now tagging is working as expected with the following versions:

"@playwright/test": "^1.40.1"
"dd-trace": "^4.21.0",

Closing this issue. Thank you @juan-fernandez for your input.
