### ISSUE TITLE
express req._datadog.config.headers null

### ISSUE THREAD

**Issue by wanglong167** [DataDog/dd-trace-js#395]
- "dd-trace": "0.7.2";
-  "express": "^4.13.3",

``` 


const tracer = require('dd-trace').init();
tracer.use("express",{
  headers:['user-agent','host'],
  validateStatus:function (item) {
    console.log("item",item);
    
  }
})

const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => res.send('Hello World!'))
app.listen(port, () => console.log(`Example app listening on port port!`))

```

```
console.log('req._datadog.config.headers',req._datadog.config.headers);
```

**Comment by rochdev** [comment]
The issue is that the `express` plugin does not correctly update the existing configuration for the request that comes from the `http` plugins. As a temporary workaround, you can set the headers on `http` instead.

For example:

```js
tracer.use('http', {
  headers: ['user-agent', 'host']
})

tracer.use('express', {
  validateStatus: function (item) {
    console.log('item', item)
  }
})
```

**Comment by rochdev** [comment]
This should no longer be an issue as these integrations have been reworked since this issue was opened. Please feel free to re-open if you are still having the issue.

**Comment by dhay** [comment]
I'm still seeing this issue.  I've configured both the `express` and the `http` plugin with the headers I want attached to my spans, but they're not showing up.  When I debug into the `web.js` method `addHeaders`, the `req._datadog.config.headers` array is empty.

```
tracer.init({ logger, enabled: true });
tracer.use('http', {
  headers: ['user-agent', 'x-forwarded-for']
});
tracer.use('express', {
  headers: ['user-agent', 'x-forwarded-for']
});
```

**Comment by rochdev** [comment]
@dhay Usually this would be caused when the tracer is not initialized before any other module is imported. Can you validate if that is the case? When using some tools the result in transpilation such as TypeScript, hoisting may also happen in which case you would have to make sure that the tracer is also initialized in its own file which is explained in the [setup docs](https://docs.datadoghq.com/tracing/setup_overview/setup/nodejs/?tab=containers#typescript-and-bundlers).
