### ISSUE TITLE
Mapping request headers to baggage keys

### ISSUE THREAD

**Issue by yonatanhakatan** [DataDog/dd-trace-js#4019]
Hi,

In the [Java](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) DD tracing library there is a `DD_TRACE_HEADER_BAGGAGE` environment variable that does the following:
```
Accepts a map of case-insensitive header keys to baggage keys and automatically applies matching request header values as baggage on traces. On propagation the reverse mapping is applied: Baggage is mapped to headers.
```

But I dont see an equivalent in the node.js tracing library. Is there no way to do this currently with the node library? What is the recommended approach if the tracing library does not offer this?

Thanks

**Comment by tlhunter** [comment]
There is no way to automate this with an env variable. But it could be achieved using Span Hooks:
https://datadoghq.dev/dd-trace-js/#span-hooks

I think something like this:

```js
const tracer = require('dd-trace').init()

tracer.use('express', { // assuming using Express
  hooks: {
    request: (span, req, res) => {
      span.setBaggageItem('keyName', req.header.foo)
    }
  }
})
```

We've noted the feature request and I'll close this for now but feel free to reopen if you have more concerns!
