### ISSUE TITLE
Support Mocha parallel tests

### ISSUE THREAD

**Issue by AM1988** [DataDog/dd-trace-js#4046]
Please support parallel test executions using mocha.

![image](https://github.com/DataDog/dd-trace-js/assets/19313323/1e66f5d6-cad7-4dfb-8ff9-c0abe4753f80)

**Comment by juan-fernandez** [comment]
hey @AM1988 ! Thanks for the feedback. Sadly this is not a straightforward feature so it needs a bit of planning. We'll take this feedback into account when taking decisions though 😄

**Comment by juan-fernandez** [comment]
> > hey @AM1988 ! Thanks for the feedback. Sadly this is not a straightforward feature so it needs a bit of planning. We'll take this feedback into account when taking decisions though 😄
> 
> Some background info. In my project we use data dog a lot, but our e2e tests are executed in parallel mode by mocha and execution in a single thread is not an option because we will lose a lot of time. So we rather would find/use another tool for tests history. From my point of view it is a key feature and I would love to see it your library.

thanks for the extra context 👍

**Comment by juan-fernandez** [comment]
hey @AM1988 ! We're currently working in supporting parallel mode for mocha in https://github.com/DataDog/dd-trace-js/pull/4314. It'll still take a bit to be released but things are looking good 😄

**Comment by AM1988** [comment]
> hey @AM1988 ! We're currently working in supporting parallel mode for mocha in #4314. It'll still take a bit to be released but things are looking good 😄

That's a very good news. Fingers crossed.

**Comment by AM1988** [comment]
Hi @juan-fernandez . I hope you are doing well.

I'm sorry for pinging you directly but I haven't found any information about the next planned release. Documentation on https://docs.datadoghq.com/tests/setup/javascript/?tab=cloudciprovideragentless is not updated. When will we get a new lib version with support of mocha parallel mode?

**Comment by juan-fernandez** [comment]
hey @AM1988 ! We'll try to get a release out this week. We were waiting for the release to update the docs 😄. I'll let you know here when the release happens

**Comment by juan-fernandez** [comment]
hey @AM1988 , new releases are out 🎉 :

* [v5.15.0](https://github.com/DataDog/dd-trace-js/releases/tag/v5.15.0)
* [v4.39.0](https://github.com/DataDog/dd-trace-js/releases/tag/v4.39.0)

The doc updates are also about to go out: https://github.com/DataDog/documentation/pull/23512

Let me know if you encounter any issues 😄 .
