### ISSUE TITLE
Segmentation for monorepos

### ISSUE THREAD

**Issue by abejfehr** [DataDog/dd-trace-js#4121]
Sorry for not using the "bug report" or "feature request" form, but this is more a question than anything else.

We have a big monorepo with many packages, and when running tests we run many instances of Jest. Each package has a name, but in the "CI Tests" section in Datadog we only get the repo name or the suite name, there's seemingly no layer in between.

There's filters in the top left for Session > Module > Suite > Test, and I _feel_ like this would be very appropriate for module, since, by elimination:
- a session is a CI run
- a suite is a filename
- a test is an test block in the file

Is there any way that I can send a custom name for "module" that encompasses each package? It would be nice to see how long monorepo -> package-a takes vs monorepo -> package-b

**Edit:** 
It looks like module is set [here](https://github.com/DataDog/dd-trace-js/blob/b6fe67e2855d57f92357cd791a0e3218d0e3034b/packages/datadog-plugin-jest/src/index.js#L138), but I don't know where `this.testModuleSpan` is assigned, and it doesn't seem configurable on the surface, maybe this is turning into a feature request

**Edit edit:** the [`displayName`](https://jestjs.io/docs/configuration#displayname-string-object) field in the jest config would be great to use for this if it's set

**Comment by juan-fernandez** [comment]
hey @abejfehr ! Thanks for posting this, it's a great piece of feedback. 

In your example, as far as I understand, `jest` will **not** run the all the tests in `package-a` before starting with `package-b`: this makes it hard to group tests in each package in any meaningful way, as tests for every package will be scattered across the whole test session (=test command). 

This said, I think adding the `displayName` as metadata in the test and test suites is low hanging fruit and it's something we should definitely do. 

> It would be nice to see how long monorepo -> package-a takes vs monorepo -> package-b

Given how `jest` runs tests in different packages (as I explain above), can you think of a way we could do this? I might be missing something (or wrong about something) and this is a feature that I think would be valuable.

**Comment by abejfehr** [comment]
If a "test session" is a single invocation of jest, then it might be trickier to do in a hierarchical way 🤔

In any case, having `displayName` as a custom field would be kind of nice for grouping runs by packages that ran

**Comment by juan-fernandez** [comment]
I've pushed #4128 to grab the `displayName` config and attach it to a tag that you can use to group by / filter 😄. 

> If a "test session" is a single invocation of jest, then it might be trickier to do in a hierarchical way 🤔

Can you think of a different way to do it? I'm interested in hearing your feedback

**Comment by juan-fernandez** [comment]
@abejfehr after the next release you'll be able to use `test.jest.display_name` tag to grab whatever you have configured in `displayName` 😄

**Comment by abejfehr** [comment]
Sorry that I didn't get a chance to test yet 😅 thank you so much for the PR, I appreciate your responsiveness
