### ISSUE TITLE
Document how to wrap a promise

### ISSUE THREAD

**Issue by kevinburkenotion** [DataDog/dd-trace-js#418]
I'm trying to do this to activate a span and trace a function that returns a Promise. It doesn't work.

```typescript
	startSpan(name: string, parentSpan?: Span, activate: boolean = true): Span {
		let span: Span;
		if (typeof parentSpan === "undefined") {
			span = this.tracer.startSpan(name)
		} else {
			const ps = parentSpan as Span
			span = this.tracer.startSpan(name, {
				childOf: ps.context(),
			})
		}
		if (activate === true) {
			this.tracer.scopeManager().activate(span)
		}
		return span
	}

	async timeFn(
		name: string,
		parentSpan: Span,
		fn: () => Promise<void>
	): Promise<void> {
		const childSpan = this.startSpan(name, parentSpan)
		try {
			await fn()
		} catch (e) {
			childSpan.log({ error: e.message })
			childSpan.finish()
			throw e
		}
		childSpan.finish()
	}
```

I'm pretty sure we're activating too quickly - we call `activate` and then some more stuff happens before `fn()` gets called and we need to call it right before `fn`.

Can you add some docs on how I can activate the span right before calling `fn`?

**Comment by ionutale** [comment]
Hi Kevin,
Do you still need help with this?

**Comment by rochdev** [comment]
This is now documented in the [API docs](https://datadoghq.dev/dd-trace-js/#promise).
