### ISSUE TITLE
Dogstatsd is undefined during jest tests

### ISSUE THREAD

**Issue by QuentinLemCode** [DataDog/dd-trace-js#4213]
Hello

We recently tried to add a metric using `dd-trace` by doing : 
```typescript
dogstatsd.increment('service.call');
```

However it's undefined during jest (even after `init` was called).
`TypeError: Cannot read properties of undefined (reading 'increment')`

The `DD_TRACE_ENABLED` is set to `false` during tests

The error can be reproduced on this repo : https://github.com/QuentinLemCode/dogstatsd-jest-bug

This only happen with dogstatsd, other function works fine.

Can you take a look at it please

**Comment by juan-fernandez** [comment]
hey @QuentinLemCode ! Thanks for the report. 

> The DD_TRACE_ENABLED is set to false during tests

Why do you set this to false? If tracing is disabled, `dogstatsd` is not defined, by design. 

To run your `jest` suite with test visibility you need to follow these instructions: https://docs.datadoghq.com/tests/setup/javascript/?tab=cloudciprovideragentless#instrument-your-tests.

**Comment by QuentinLemCode** [comment]
> hey @QuentinLemCode ! Thanks for the report.
> 
> > The DD_TRACE_ENABLED is set to false during tests
> 
> Why do you set this to false? If tracing is disabled, `dogstatsd` is not defined, by design.
> 
> To run your `jest` suite with test visibility you need to follow these instructions: https://docs.datadoghq.com/tests/setup/javascript/?tab=cloudciprovideragentless#instrument-your-tests.

Hello @juan-fernandez ! Thanks for the fast reply :) 

We don't want to activate test visibility, for now, we want to make tests pass ;) 

For now, we have found a solution by mocking `dogstatsd` but it would be great to have the same behavior for metrics than for traces : noop ;)

**Comment by juan-fernandez** [comment]
ah I see, thanks for the clarification! Yeah I think this makes sense. 

@rochdev is this something we could do?

**Comment by rochdev** [comment]
> @rochdev is this something we could do?

Yes definitely, actually this is a bug as the entire public API should be no-op when the library is disabled.

**Comment by rochdev** [comment]
> @rochdev would https://github.com/DataDog/dd-trace-js/pull/4225 be a fix?

Kind of, but using the noop version shouldn't also import the real version if not needed. There also needs to be a test for this.

**Comment by juan-fernandez** [comment]
this should be fixed in the new releases 😄 : 

* [v3.56.0](https://github.com/DataDog/dd-trace-js/releases/tag/v3.56.0)
* [v4.35.0](https://github.com/DataDog/dd-trace-js/releases/tag/v4.35.0)
* [v5.11.0](https://github.com/DataDog/dd-trace-js/releases/tag/v5.11.0)
