### ISSUE TITLE
Bug with selenium instrumentation

### ISSUE THREAD

**Issue by garrettheel** [DataDog/dd-trace-js#4329]
There is a bug [here](https://github.com/DataDog/dd-trace-js/blob/c69cd644a4134f996f8795a3c7b7e5089b9c64f6/packages/datadog-instrumentations/src/selenium.js#L43-L45) introduced by #4241

When the plugin is disabled or there is no span available, we end up calling `addCookie({value: undefined})` which causes the following error in chromedriver: `invalid argument: missing 'value'`

We should guard the `addCookie` in an undefined check.

I'm observing this error on `5.14.0` but it should be present on all versions since `5.11.0` and pretty easy to reproduce if you use selenium.

I can't find any way to workaround this. `DD_TRACE_SELENIUM_ENABLED=false` doesn't work because the instrumentation still tries to call `addCookie`.

cc @juan-fernandez

**Comment by juan-fernandez** [comment]
hey @garrettheel ! Thanks for reporting the issue. Under what circumstances does this happen? How are you running your selenium tests? Would you mind providing a small reproducible case?

**Comment by juan-fernandez** [comment]
I think your issue should be fixed with https://github.com/DataDog/dd-trace-js/pull/4330

**Comment by garrettheel** [comment]
That looks like it should fix it, thank you @juan-fernandez!
