### ISSUE TITLE
Playwright CI Error: Cannot read properties of undefined (reading 'steps')

### ISSUE THREAD

**Issue by johnkrzywanek** [DataDog/dd-trace-js#4466]
Hi, looks like something is broken with latest Playwright version:

```
TypeError: Cannot read properties of undefined (reading 'steps')
    at /path/to/tests/node_modules/dd-trace/packages/datadog-instrumentations/src/playwright.js:252:25
```
Seems like dd-trace is unable to get the test results from testEndHandler

**Comment by juan-fernandez** [comment]
hey @johnkrzywanek ! Thanks for the report. I can't seem to reproduce the issue with the latest version of playwright. Also, the e2e tests we have are passing. Could you provide a small reproducible case? 

Any information around the test that's failing would also be useful

**Comment by juan-fernandez** [comment]
I've pushed #4471 so that we don't unsafely access the property, which should fix the problem, but I'd like to be able to reproduce this to add a e2e test 😄

**Comment by johnkrzywanek** [comment]
Thanks so much @juan-fernandez! It seems that the error is only triggered on test failures, I've pushed a sample repo where you can see this: https://github.com/johnkrzywanek/playwright-ddtrace

And running with `NODE_OPTIONS="-r dd-trace/ci/init" DD_ENV=local DD_SERVICE=automated-tests npm run test` results in the error I've originally posted.

Can confirm that it no longer errors out after your fix 🙌

**Comment by juan-fernandez** [comment]
thanks @johnkrzywanek , that was very helpful. The specific combination that was buggy is:
* passing `maxFailures: 1`
* one test failing
* another test after the one that fails

I've pushed a test case in https://github.com/DataDog/dd-trace-js/pull/4471/commits/5a92b231bf1b47e4b143497033928d6dbace8059 for this specific case 😄 . This fix should be released soon!
