### ISSUE TITLE
init missing from new TS types

### ISSUE THREAD

**Issue by stephenh** [DataDog/dd-trace-js#462]
Using the new `0.9.2`, our existing code that did:

```typescript
import * as ddtrace from 'dd-trace';
...
  return ddtrace.init({
    service,
    hostname: 'statsd',
    plugins: false,
  });
```

Is failing with:

```
Error:(156, 18) TS2339: Property 'init' does not exist on type 'typeof import("/home/.../node_modules/dd-trace/docs/index")'.
```

I see that `index.d.ts` has an `init` method but its within the `Tracer` instance and AFAICT from the docs, the expectation is to call the module `init`.

FWIW after seeing `module.exports.tracer = module.exports` I changed the code to:

```typescript
import { tracer } from 'dd-trace';
...
function createTracer(): Tracer {
  return tracer.init({ ... });
}
```

Where `Tracer` is the opentracer type and am now getting a pretty fun error:

```
Error:(156, 3) TS2322: Type 'import("/home/stephen/.../ts-pkg/node_modules/dd-trace/docs/index").Tracer' is not assignable to type 'import("/home/stephen/.../ts-pkg/node_modules/opentracing/lib/tracer").Tracer'.
  Types of property 'startSpan' are incompatible.
    Type '(name: string, options?: import("/home/stephen/.../ts-pkg/node_modules/dd-trace/node_modules/opentracing/lib/tracer").SpanOptions | undefined) => import("/home/stephen/.../ts-pkg/node_modules/dd-trace/docs/index").Span' is not assignable to type '(name: string, options?: import("/home/stephen/.../ts-pkg/node_modules/opentracing/lib/tracer").SpanOptions | undefined) => import("/home/stephen/.../ts-pkg/node_modules/opentracing/lib/span").Span'.
      Types of parameters 'options' and 'options' are incompatible.
        Type 'import("/home/stephen/.../ts-pkg/node_modules/opentracing/lib/tracer").SpanOptions | undefined' is not assignable to type 'import("/home/stephen/.../ts-pkg/node_modules/dd-trace/node_modules/opentracing/lib/tracer").SpanOptions | undefined'.
          Type 'import("/home/stephen/.../ts-pkg/node_modules/opentracing/lib/tracer").SpanOptions' is not assignable to type 'import("/home/stephen/.../ts-pkg/node_modules/dd-trace/node_modules/opentracing/lib/tracer").SpanOptions'.
            Types of property 'references' are incompatible.
              Type 'import("/home/stephen/.../ts-pkg/node_modules/opentracing/lib/reference").default[] | undefined' is not assignable to type 'import("/home/stephen/.../ts-pkg/node_modules/dd-trace/node_modules/opentracing/lib/reference").default[] | undefined'.
                Type 'import("/home/stephen/.../ts-pkg/node_modules/opentracing/lib/reference").default[]' is not assignable to type 'import("/home/stephen/.../ts-pkg/node_modules/dd-trace/node_modules/opentracing/lib/reference").default[]'.
                  Type 'import("/home/stephen/.../ts-pkg/node_modules/opentracing/lib/reference").default' is not assignable to type 'import("/home/stephen/.../ts-pkg/node_modules/dd-trace/node_modules/opentracing/lib/reference").default'.
                    Property '_type' is protected but type 'Reference' is not a class derived from 'Reference'.
```

So I guess just a) an FYI about the (typescript) "breaking" change (just a compiler thing, so not an actual breaking change), an ES6/TS-style example in the docs would be nice and then also b) the "can't return the ddtrace Tracer as an opentracing Tracer" compile error. Which should probably be a separate issue.

**Comment by rochdev** [comment]
a) Technically, TypeScript was not supported before 0.9.0 so this is not really a breaking change. I agree however that this should be documented, especially since what's worse is that currently it's documented with the wrong syntax.

b) I will take a look at the interoperability issue with OpenTracing.

**Comment by rochdev** [comment]
@stephenh I can't seem to be able to reproduce. What versions of `dd-trace`, `opentracing` and TypeScript are you using?

**Comment by stephenh** [comment]
@rochdev ah hrm, I'll check:s dd-trace 0.9.2, TS 3.2.2, and opentracing 0.14.3.

**Comment by rochdev** [comment]
@stephenh I've just tried with the snippet you provided and these exact versions and cannot reproduce. Could you provide the entire snippet? Also, are you extending `dd-trace` or `opentracing` in any way?

**Comment by rochdev** [comment]
Can you also share your `tsconfig.json`? Maybe there is a specific rule causing this.

**Comment by rochdev** [comment]
This seems to happen when the version of OpenTracing used in the project is not exactly the same as the one pulled by `dd-trace`. I'll do some more testing as it seems it may cause even other issues outside of TypeScript. In the meantime, a possible workaround would be to use `opentracing-javascript` with a version fixed at `0.14.1`. Please let me know if that works.

**Comment by amckibben** [comment]
Question: Is it deliberate that `dd-trace`'s `opentracing` dependency is using a fixed version rather than `^` or `~` ranges?

**Comment by rochdev** [comment]
This was because of a bug introduced in `0.14.2` which we were trying to avoid. It should no longer be an issue in `0.14.3` and thus no longer needed, but still, we shouldn't enforce using the same version as the project.

**Comment by amckibben** [comment]
I agree. Was just trying to get insight on that since the vast majority of your dependencies are `^`.

**Comment by amckibben** [comment]
I don't have experience using them with any package I've authored, but is this what https://docs.npmjs.com/files/package.json#peerdependencies are for?

**Comment by rochdev** [comment]
The problem with a peer dependency is the user has to know about OpenTracing. Since many users don't care about OT and simply wants to use our tracer, this knowledge should not be necessary. It also doesn't necessarily address the issue since we still need to depend on specific versions. Although I don't like it for long-term, for now making the semver less strict will at least fix the issue.

**Comment by amckibben** [comment]
🤷‍♂️ Yeah, I thought there may have been more magic with peer dependencies. But reading the documentation tells otherwise. It's a bit uncomfortable, but I suppose interfacing with any 0.x.x dependency runs the risk of interfaces breaking at the patch level.

**Comment by rochdev** [comment]
Definitely, but when actively using OT then this is already an issue (i.e. they change an API that they start calling and we don't have).

**Comment by rochdev** [comment]
Fix released in `0.9.3`. If it's not working right away, please try to reinstall dependencies and/or refresh your `package-lock.json` or `yarn.lock`.

**Comment by stephenh** [comment]
@rochdev yep, that worked great! Thanks for the quick fix.

**Comment by jpblair** [comment]
I'm seeing what I think is a related issue in `"dd-trace": "^4.17.0"`. Using the Typescript instructions provided on [this page](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/nodejs/), calling the `init()` function fails:

```
Property 'init' does not exist on type 'typeof import("{project root}/node_modules/dd-trace/index")'.
```

Interestingly, the following does work:
```
import ddTrace from 'dd-trace'
const { tracer } = ddTrace
tracer.init(config)
```

Let me know if I can provide additional info, or if this merits a separate issue.
