### ISSUE TITLE
The `debug` option in `tracer.init` doesn't work

### ISSUE THREAD

**Issue by stanislav-halyn** [DataDog/dd-trace-js#4719]
The docs [here](https://datadoghq.dev/dd-trace-js/interfaces/export_.TracerOptions.html#logger) say that in order to enable custom logging, you need to pass `debug: true` to the `tracer.init`, but it's not working. Is this intentional functionality?

I guess the reason is because it's ignored when initializing the `Config` class.
[[this.debug = logConfig.enabled](https://github.com/DataDog/dd-trace-js/blob/b079c6f93f567e9e464fffd8fe2624d6760fc4f2/packages/dd-trace/src/config.js#L247)](https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/config.js#L247)

When I change this line to `this.debug = coalesce(options.debug, logConfig.enabled)` it starts working.

**Comment by simon-id** [comment]
@stanislav-halyn I can't see the place in the link you sent where it mention `debug: true` ?

**Comment by stanislav-halyn** [comment]
Since it's not a bug, I'm closing the issue.

**Comment by simon-id** [comment]
Ah indeed I found it now. I'll try to find how to update it. Thank you for reporting this!
