### ISSUE TITLE
dd-trace: package with critical vulnerability

### ISSUE THREAD

**Issue by sfgoncalvesm** [DataDog/dd-trace-js#4795]
The new version of the dd-trace package has critical vulnerabilities.
![Image](https://github.com/user-attachments/assets/e9b68d1f-d803-4f31-be41-abe92984aaac)

**Comment by wizseek** [comment]
Think this will be [fixed in 5.24.0](https://github.com/DataDog/dd-trace-js/pull/4782). The fix is already merged into master but pending release.

**Comment by adrsimon** [comment]
there's a closed issue about this matter, #4770
the update to jsonpath-plus@10.0.0 did nothing as the issue still exists on jsonpath-plus side 
you can have a look at https://snyk.io/vuln/SNYK-JS-JSONPATHPLUS-7945884

**Comment by bengl** [comment]
5.24.0 and 4.48.0 have both been released, and fix this issue.
