### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by stephen** [DataDog/dd-trace-js#48]
What parts are missing for this package to work in the browser? Is there a plan overall for traces from frontends?

Our datadog agents aren't exposed to the public internet, so we're thinking of having a small ingestion proxy that forwards spans. I think that means we'd want to plug in a custom [write](https://github.com/DataDog/dd-trace-js/blob/bb8a6f35d8f586ea2f2d87c94cf5716a4f8233a7/src/writer.js#L34-L58) method or similar.

**Comment by Paskalouis** [comment]
Hi,

Is there any update regarding this feature request ?
Now I stumbled upon working on integrating datadog into the frontend.
In this case, I am using Vue. I see another similar issue (#233) about integrating to React/ReactNative .

Thanks !

**Comment by rochdev** [comment]
I don't have any updates at the moment unfortunately.

However, we have recently released our [RUM](https://www.datadoghq.com/blog/dash-2019-new-feature-roundup/#real-user-monitoring) product in private beta.

@Paskalouis Would that fit your use case?

**Comment by timiyay** [comment]
What is the status of browser support for this package?

We've just started assessing the Real User Monitoring (RUM) Traces feature, which uses this library to correlate RUM requests with APM requests. This implies that `dd-trace` will be deployed to a browser.

**Comment by rochdev** [comment]
@timiyay While `dd-trace` has beta support for the browser with limited functionality, it is indeed currently required to correlate RUM and APM. We are however working on a change that should remove this requirement in the next few weeks. Once the change lands, you will only need to add `dd-trace` in the browser if you want to do actual tracing, but not for simply correlating RUM and APM.

**Comment by rochdev** [comment]
Closing as browser support has been moved from APM to RUM. Tracing can be enabled with the [allowedTracingOrigins](https://docs.datadoghq.com/real_user_monitoring/browser/#initialization-parameters) configuration options.
