### ISSUE TITLE
Feature: Plugin for async package

### ISSUE THREAD

**Issue by tekmaven** [DataDog/dd-trace-js#488]
It would be awesome for there to be tracing integration with the [`async` npm package](https://www.npmjs.com/package/async) (>23m weekly downloads).   GH Repo: https://github.com/caolan/async.

**Comment by rochdev** [comment]
Is there a particulat use case or would you want to be able to trace every asynchronous executions in general?

**Comment by tekmaven** [comment]
Yes.  I've seen a lot of node/express apps using this package.  In the current app I am working with, it is used extensively, and it would really light up a lot more information in our traces.

**Comment by rochdev** [comment]
What I meant is that the `async` package is just one of the several ways to do work asynchronously. Do you expect to see any asynchronous operation as a span, or only operation using the `async` package specifically? Just trying to get a better grasp of the actual use case.

**Comment by tekmaven** [comment]
Yes, I would want to see every async operation as a span.  The codebase I'm referring to uses `async.parallel` (http://caolan.github.io/async/docs.html#parallel) and `async.each` (http://caolan.github.io/async/docs.html#each) quite often.

**Comment by rochdev** [comment]
What makes these asynchronous operations more interesting than any other asynchronous operations using timers, promises, etc?

**Comment by tekmaven** [comment]
Nothing.  Ideally we could have spans for all of those operations.

**Comment by rochdev** [comment]
Ok, I will look into it. What would you expect the metadata of such span to look like? For example, what would be the operation name and resource name?

**Comment by tekmaven** [comment]
The resource should be the app that is running and the name should be Async, possibly including the function name (if it's named).  There are some async methods that optionally can give more visibility with names, for example, async.parallel - see the second example: https://caolan.github.io/async/docs.html#parallel.

**Comment by rochdev** [comment]
Closing as the `async` module simply handles asynchronous workflows similar to built-in constructs like timers and promises, and is thus out of scope for tracing. We do have profiling in private alpha right now which would make more sense for this use case. If this is something that would be interesting to you, I'd recommend reaching out to support to get that enabled.
