### ISSUE TITLE
Changelog would be extremely helpful

### ISSUE THREAD

**Issue by kylealwyn** [DataDog/dd-trace-js#489]
Would be great to get a changelog added to see what's changed between your releases, particularly while in the 0.x stage.

Thanks for any consideration!

**Comment by rochdev** [comment]
Thanks for the suggestion! We did consider a `CHANGELOG.md` but chose instead to go with GitHub Releases. You can find the release notes for every version here: https://github.com/DataDog/dd-trace-js/releases
