### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by stephen** [DataDog/dd-trace-js#49]
Typescript definitions (or using ts in the project 😄) would be helpful when interacting with this library.

**Comment by jamiehodge** [comment]
I would also really like a Flow declaration or a Typescript one that I can translate.

**Comment by rochdev** [comment]
Great idea! Actual API documentation will also be done at a later time but this will definitely be a quick win.

**Comment by rochdev** [comment]
I've opened another issue for Flow to track those definitions separately

**Comment by ColinBradley** [comment]
I've written a basic definition on definitely typed: https://www.npmjs.com/package/@types/dd-trace
Hopefully that's good enough for now.

**Comment by jlujan-omg** [comment]
@ColinBradley 

Seeing type conflicts when using these definitions.

```
error TS2345: Argument of type 'TraceProxy' is not assignable to parameter of type 'Tracer'.
  Types of property 'startSpan' are incompatible.
```

Changing imports in the definitions and removing the copy of opentracing definitions in `./src` fixes this.

`import {Tracer, Span, SpanContext} from "opentracing"`

**Comment by aleccool213** [comment]
👍

**Comment by ColinBradley** [comment]
@jlujan-omg I have submitted a PR for compatibility with `opentracing`: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28118

Should be merged soon and hopefully helps you out! : )

**Comment by Nysosis** [comment]
@ColinBradley
Getting an issue using those typings:

`Return type of exported function has or is using name 'TraceProxy' from external module "[ROOT]/node_modules/@types/dd-trace/index" but cannot be named.`

**Comment by stephenh** [comment]
@rochdev this can be closed now :-)

**Comment by rochdev** [comment]
TypeScript definitions are now in this repo and officially supported. Thanks to everyone who contributed!
