### ISSUE TITLE
Playwright test names do not include titles from test.describe() groups

### ISSUE THREAD

**Issue by cmecklenborg** [DataDog/dd-trace-js#4976]
**Expected Behavior**

In Datadog Test Optimization, tests should be fingerprinted based on their full names, and distinct tests should not be grouped together

**Actual Behavior**

The Playwright plugin names tests based only only the text in `test('Test Name')`, so parametrized tests (or identically named tests in different `test.describe()` groups) are erroneously merged together.

**Example**

```
import { expect, test } from '@playwright/test';

['foo', 'bar'].forEach((x) => {
    test.describe(`Parametrized Test - ${x}`, () => {
        test('Test simple assert', () => {
            expect(true);
        });
    });
});

test.describe('Simple Test A', () => {
    test('Test simple assert', () => {
        expect(true);
    });
});

test.describe('Simple Test B', () => {
    test('Test simple assert', () => {
        expect(true);
    });
});

```

Playwright correctly identifies these as 4 different tests:
```
Running 4 tests using 1 worker

  ✓  1 [Desktop Chrome] › sample.spec.ts:5:13 › Parametrized Test - foo › Test simple assert (3ms)
  ✓  2 [Desktop Chrome] › sample.spec.ts:5:13 › Parametrized Test - bar › Test simple assert (0ms)
  ✓  3 [Desktop Chrome] › sample.spec.ts:12:9 › Simple Test A › Test simple assert (0ms)
  ✓  4 [Desktop Chrome] › sample.spec.ts:18:9 › Simple Test B › Test simple assert (0ms)
```

But the DD Playwright plugin would see them as 1 test that ran 4 times. If one or more is flaky/failing, this makes digging into the results confusing.

**Comment by juan-fernandez** [comment]
hey @cmecklenborg ! Thanks for the report. This should be simple to fix. I'll keep you updated 😄

**Comment by juan-fernandez** [comment]
ℹ I just pushed #4981 to fix this
