### ISSUE TITLE
RetireJS warning from docs folder

### ISSUE THREAD

**Issue by SethDavenport** [DataDog/dd-trace-js#513]
I'm getting the following error from retirejs when upgrading from 0.7.2 to 0.10.3:

```
$ retire
retire.js v2.0.2
Downloading https://raw.githubusercontent.com/RetireJS/retire.js/master/repository/jsrepository.json ...
Downloading https://raw.githubusercontent.com/RetireJS/retire.js/master/repository/npmrepository.json ...
/home/circleci/wealthsimple/node_modules/dd-trace/docs/node_modules/typedoc-default-themes/bin/default/assets/js/main.js
 ↳ jquery 2.1.1
```

Looks like you're including an old version of jquery in your `docs` folder in npm. I'm seeing an [entry in `.npmignore`](https://github.com/DataDog/dd-trace-js/blob/master/.npmignore#L5) which probably is intended to prevent this, but it seems to be including the whole `docs` folder and not just `.d.ts` files:

```sh
ls -la node_modules/dd-trace/docs/                                                                            Mon  1 Apr 23:54:11 2019
total 56
drwxr-xr-x   6 sdavenport  1930983314    192  1 Apr 23:52 .
drwxr-xr-x  13 sdavenport  1930983314    416  1 Apr 23:52 ..
-rw-r--r--   1 sdavenport  1930983314  19400  1 Apr 23:51 index.d.ts
drwxr-xr-x  38 sdavenport  1930983314   1216  1 Apr 23:51 node_modules
-rw-r--r--   1 sdavenport  1930983314    276  1 Apr 23:51 package.json
-rw-r--r--   1 sdavenport  1930983314    209  1 Apr 23:51 typedoc.js
```

**Comment by rochdev** [comment]
This has been fixed in the upcoming minor release. If this is something that is blocking you I can backport it. Otherwise it will land whenever 0.11.0 is released. Just me know :)

**Comment by SethDavenport** [comment]
cool
yeah I can wait for 0.11.0. Thanks!
