### ISSUE TITLE
mongodb-core plugin doesn't work with official MongoDB

### ISSUE THREAD

**Issue by jessedobbelaere** [DataDog/dd-trace-js#518]
Similar to #221, we are using [the `mongodb` package in our NodeJS app](https://www.npmjs.com/package/mongodb). The description of the package explains that it's built on top of mongodb-core, and it's an *official* driver. 

> The official MongoDB driver for Node.js. Provides a high-level API on top of mongodb-core that is meant for end users. 
> https://www.npmjs.com/package/mongodb

We added Datadog tracing to our Node app, and we see Koa http and MySQL traces in Datadog right now, but no MongoDB tracing. We suppose it's because the dd-trace-js only supports mongodb-core. Would there be a workaround besides refactoring the code to use mongodb-core instead of mongodb?

**Comment by perryh** [comment]
Did you import and init the tracer before your mongo client? There is a warning at the top of the quickstart section: https://docs.datadoghq.com/tracing/languages/nodejs/

The mongodb-core plugin should work with the mongodb package.

**Comment by rochdev** [comment]
Correct. `mongodb` uses `mongodb-core` so it's transitively supported.

Usually when an integration is not working at all the most likely causes are:

* The tracer is imported after the library.
* The version is not supported

Both are documented in the aforementioned link. Also keep in mind that for TypeScript the tracer should be imported from its own file to avoid hoisting as described in the docs.

**Comment by jessedobbelaere** [comment]
Thanks for the quick reply! 

* The Datadog tracing setup is indeed imported from it's own file on the very first line of app.js (currently no typescript in this project), so before any other package. Similar like I did in another project where tracing is working perfectly for mysql & elasticsearch. 
* Mongodb `2.1.18` is used in this project, will look into upgrading but should be supported according to the docs (>=2). We also use mysql, which does appear in datadog traces at the moment. 

Good to know that the `mongodb` package should work! I'll do some more investigation on my side. 
Possible issue: the `mongodb` package is imported not in app.js where the tracing is set up, but deeper in the application logic. We have a refactor planned anyway to include the mongodb package in app.js (below the datadog tracing) so we'll know soon enough if that was the issue.

**Comment by rochdev** [comment]
It looks like `mongodb` 2.1.18 uses `mongodb-core` 1.3.18 which is indeed not supported. The first version of `mongodb` that supports `mongodb-core` >=2 is 2.2.0.

**Comment by jessedobbelaere** [comment]
Yeah indeed, did not look at the actual mongodb-core version used, thought it followed the core versioning. Facepalm :) Will upgrade soon! Thanks for the help!
