### ISSUE TITLE
Promise-based `scope.activate`

### ISSUE THREAD

**Issue by icebob** [DataDog/dd-trace-js#558]
Hi,

I'm working on adding `dd-trace` to the [Moleculer framework](https://github.com/moleculerjs/moleculer) as a trace exporter. My big problem is that the framework is promise-based so every important process is async thus I can't use the `scope.activate` because it is sync.

I've created a `scope.activatePromise (span, promise)` method which solves my issues.
Can I send it as a PR? I think it can be useful for other users, too. Maybe it can solve #437, as well.

Here is the relevant code:
```js
 _activatePromise (span, promise) {
    const asyncId = executionAsyncId()
    const oldSpan = this._spans[asyncId]

    this._spans[asyncId] = span

    return promise.then(res => {
        if (oldSpan) {
            this._spans[asyncId] = oldSpan
        } else {
            this._destroy(asyncId)
        }
        return res;
    }).catch(err => {
      if (span && typeof span.addTags === 'function') {
        span.addTags({
          'error.type': e.name,
          'error.msg': e.message,
          'error.stack': e.stack
        })
      }

      if (oldSpan) {
        this._spans[asyncId] = oldSpan
      } else {
        this._destroy(asyncId)
      }

      throw e;
    });
  }
```

**Comment by rochdev** [comment]
Definitely feel free to open a PR, it's the best way to contribute to the tracer :)

Could you show a snippet of how this would be used?

**Comment by icebob** [comment]
Great, I will make an example because it doesn't work with the normal `startSpan`. In Moleculer I've created a custom startSpan & finish methods which uses `activatePromise` and the result is that simple writing mode:
```js
async handler(ctx) {
async handler(ctx) {
	const span1 = ctx.startSpan("something async", { tags: {/*...*/}});
	const something = await this.broker.cacher.get("something");

	const span2 = ctx.startSpan("nested span");
	const res = await Promise.all(/*...*/);

	span2.finish();

	span1.finish();
}
}
```

**Comment by rochdev** [comment]
How does the above code work to propagate the scope?

**Comment by rochdev** [comment]
@icebob Are you still planning to open a PR for this? I'm still not 100% sure I understand how it works, but it should be more obvious when I see the tests.

**Comment by icebob** [comment]
@rochdev ohh, sorry for late, just I wasn't sure how it would be good and I could implement it on my side without dd-trace modification. So I close it.
