### ISSUE TITLE
Decouple enablement of error and debug logs

### ISSUE THREAD

**Issue by perryh** [DataDog/dd-trace-js#559]
In my use case, I want to forward errors to my logger but ignore debug messages.

According to log.js, both `debug` and `error` of the `logger` object for TracerOptions need to be instances of functions in order for me to use custom loggers for either of them. And even if I pass a noop function for `debug`, my application will waste cycles computing the debug messages.

**Comment by rochdev** [comment]
The logger is not very flexible on that front currently. We are working on improving it with more options, but in the meantime this is unfortunately not possible.

**Comment by rochdev** [comment]
Closing as this was addressed with #727 and released in [0.16.0](https://github.com/DataDog/dd-trace-js/releases/tag/v0.16.0).
