### ISSUE TITLE
Broken under jest

### ISSUE THREAD

**Issue by terryma** [DataDog/dd-trace-js#585]
When initializing the tracer inside a jest test, it runs into the following problem:

```
  node_modules/dd-trace/src/proxy.js:54
   TypeError: asyncHooks.createHook is not a function
```

This is due to the following line: https://github.com/DataDog/dd-trace-js/blob/8274544480ffc4e2ddf25d6ab1e84095c2b32edf/src/scope/async_hooks.js#L3

Somehow jest's require cannot resolve `require('./async_hooks/')`. This works if you do `require('./async_hooks/index')` or rename the `async_hooks` directory to avoid the name collision with `async_hooks.js` in the same directory.

This is impacting my ability to write integration tests for our wrapper library on top of this library. This is also a regression after bumping to the latest version (previously we were on 0.9^, this was probably introduced when the scope manager was rewritten).

**Comment by rochdev** [comment]
We're actually in the process of changing the structure of the project, which will resolve this issue at the same time.

It this something you need very quickly? The new structure will probably only be ready in a few days.

**Comment by rochdev** [comment]
FWIW I think an issue should also be opened in Jest since this is a valid CommonJS syntax.

**Comment by terryma** [comment]
Thanks for the quick update! Ready in a few days is certainly fine. I'll disable the test for now.

**Comment by rochdev** [comment]
This should be fixed in 0.12.1 which includes the new project structure.

**Comment by terryma** [comment]
Looks like the same require that was tripping jest is still there: https://github.com/DataDog/dd-trace-js/blob/b999b45a8fb8e1779ef3f44ea19ae8da48995eae/packages/dd-trace/src/scope/async_hooks.js#L3

**Comment by rochdev** [comment]
Sorry about that, I thought I had fixed that. Will be fixed in next release.

**Comment by terryma** [comment]
No worries, thanks for the update!
