### ISSUE TITLE
Errors being emitted and traces incomplete with APM

### ISSUE THREAD

**Issue by songawee** [DataDog/dd-trace-js#640]
**Description**
We're seeing a number of errors being emitted from the `dd-trace` JS library.

Here is the stack we're seeing:

![Screen Shot 2019-07-30 at 1 57 11 PM](https://user-images.githubusercontent.com/434885/62162474-950dd280-b2d5-11e9-9c23-c065e141c47a.png)

The application is a Node.js express server that is responding to a GET request. Our tracer configuration is very minimal (just enabling http, express, etc. plugins). It is `require`d at the entrypoint of the application. We are not using the `opentracing` lib.

The problem seems to be from `fields.tags` - https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/opentracing/tracer.js#L81 being undefined and I'm not sure what the source of that issue is. Missing parent? Sampling?

**In the UI**
Additionally, we are seeing in the DataDog UI a ton of incomplete traces for these requests. I've only seen 1 complete trace out of like 100 or so requests. Not sure if it is related, but could be related given the amount of errors we're seeing emitted. There is a separate `/healthcheck` resource and these traces do show up fairly regularly, but is quite limited compared to the endpoint we'd really like traces on.

Any thoughts or ideas?

**Environment**

* **Operation system:** Linux (AWS AMI)
* **Node version:** 10.15.3
* **Tracer version:** 0.13.1
* **Agent version:** 6.13.0

**Comment by songawee** [comment]
cc @paul-salmon-ib

**Comment by rochdev** [comment]
The error has been fixed in 0.14.0.

About the incomplete traces, do you mean within the same process or with multiple distributed services? If the later, are all services using the Node tracer, or some of them are in other languages?

**Comment by songawee** [comment]
Thanks for the bug fix!

It is a node process that calls out to elasticsearch, DynamoDB, etc, but does not call out to other instrumented microservices

**Comment by rochdev** [comment]
Are the missing parts available as their own traces in the individual services? Usually incomplete traces within a single process are caused by the scope that was lost, and the different parts end up in different traces. If that's the case, I can explain how to find where exactly the scope was lost.

**Comment by songawee** [comment]
Once we updated to 0.14, our traces are showing up now. Looks like we just had a naming change. Thanks for your help @rochdev!!!

Will close 👍
