### ISSUE TITLE
Disable plugins feature (DD_INTEGRATIONS_DISABLED)

### ISSUE THREAD

**Issue by tot-ra** [DataDog/dd-trace-js#663]
php extension can accept env var `DD_INTEGRATIONS_DISABLED` to disable certain (unstable?) plugins. Seems that dd-trace-js doesn't have this feature (http for example seems to always intercept requests). Would be nice to have black list of disabled plugins

**Comment by tot-ra** [comment]
And how do I do it in typescript, if tracer wants specific type? :suspect:

**Comment by andrewsouthard1** [comment]
Was merged in https://github.com/DataDog/dd-trace-js/pull/733
