### ISSUE TITLE
[datadog-plugin-graphql] - Missing loc object breaks query

### ISSUE THREAD

**Issue by rdhaliwal** [DataDog/dd-trace-js#672]
Hello! I've come across an interesting scenario that's resulting in some of my GraphQL requests breaking. 

Essentially, on [L295 of datadog-plugin-graphql/src/index.js](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-graphql/src/index.js#L295), the `fieldNode` doesn't have `loc` object, resulting in the error `"Cannot read property 'start' of undefined"`. 

If I change L294 to the following, then the request still works:
```js
if (document && fieldNode && fieldNode.loc) {
```

I'm still in the process of debugging exactly how this happens, the only common part about reproducing it is that this only happens for _some_ schema stitched queries and mutations.

My question/s:

 - I'm not overly familiar with the GraphQL AST, but how reasonable is it to assume that a fieldNode _always_ has a `loc` object? 
   - When looking at the [graphql-tag library](https://github.com/apollographql/graphql-tag/blob/master/src/index.js#L77), there is a method that strips this object out sometimes. This to me suggests that it's not something that can be assumed to be there. 
 - Does it make sense to update the tracer so that it has to do a check `loc` exists before accessing it?

**Environment**

* **Operation system:** MacOS 10.14.6
* **Node version:** 8.15.0
* **Tracer version:**  0.15.0

**Comment by rochdev** [comment]
What is the value of `document` for that field?

**Comment by rdhaliwal** [comment]
@rochdev I've updated the gist with the document. The key difference seems to be the alias is missing in the fieldNode? 

If I remove the alias, the query works. However, there are other queries & mutations with aliases that work perfectly fine, and other queries that don't have aliases that also break in a similar manner.

Something else I tried was seeing if there was another field object (maybe the alias created two?). But [`startResolveSpan`](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-graphql/src/index.js#L281) is only called by [`assertField`](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-graphql/src/index.js#L348), and when I log the [`fields`](https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-graphql/src/index.js#L350) array, there's only 1 entry in it.

**Comment by rochdev** [comment]
From the document, it looks like the field is not actually the entire document. This means that without the `loc` it's not possible to know what is the source of the field. I'll have to add a check to the `fieldNode` but this will have the side-effect to lose some information for that field on the span.

I consider this a bug in Apollo since a field that is part of a document should always include a `loc`, so I'll have to also investigate this further after I release a fix to at least prevent a crash when the bug is present.

**Comment by rdhaliwal** [comment]
Awesome, thanks for that @rochdev ! Any idea of a rough timeline on when to expect #676 to be merged?

And yes, I agree, I have a feeling there's a bug in Apollo or something else that's messing up the fieldNode. I'm trying to trace it down, but it's slow going >_>

**Comment by rochdev** [comment]
As soon as it's merged I'll publish a release. It should happen by tomorrow.

**Comment by rdhaliwal** [comment]
Beautiful, thanks!
