### ISSUE TITLE
datadog-plugin-http server no HTTP_ROUTE fallback (v0.13.1)

### ISSUE THREAD

**Issue by dm03514** [DataDog/dd-trace-js#703]
Greetings, I noticed that some http.requests only showed the `request.method` as the resource instead of the path:

<img width="1107" alt="Screen Shot 2019-10-02 at 1 28 38 PM" src="https://user-images.githubusercontent.com/321963/66066977-9eefc400-e518-11e9-9a59-21f07c40f719.png">

With traces that look like:
```
{"tenant_id":"0.8362000324042156"
,"http.url":"http://api2:3000/api/v2/test","http.method":"GET","span.kind":"server","http.status_code":"200","language":"javascript"},"metrics":{"_sample_rate":1,"_sampling_priority_v1"
:1,"_dd1.sr.eausr":1},"start":1570030884600427800,"duration":9102783,"service":"api2","type":"web"}]
```

For whatever reason (unknown) it looks like [`req._data.paths` aren't being set](https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/util/web.js#L347) so `HTTP_ROUTE` is never set when `addResourceTag` is [being called](https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/util/web.js#L363).

I was thinking two things:
- figure out why `paths` aren't being set for this
   - Looking a little closer it seems like `enterRoute` is a helper method for other packages to use and is not used by the http server package.
   - **Now I wonder should the datadog-plugin-http package be updated to hook into the correct call/event and call `enterRoute`?**
- add a fallback to use the http request

I added code:

```
  const url = require('url')

...

  if (req._datadog.paths.length > 0) {
    span.setTag(HTTP_ROUTE, req._datadog.paths.join(''))
  } else {
    span.setTag(HTTP_ROUTE, url.parse(req.url).pathname)
  }
```
And the resource is now being calculated as expected:

<img width="805" alt="Screen Shot 2019-10-02 at 1 36 08 PM" src="https://user-images.githubusercontent.com/321963/66067511-ba0f0380-e519-11e9-8dd1-014fd1e52b15.png">

```
encoding trace: [{"trace_id":"5678549602621792600","span_id":"5678549602621792600","parent_id":null,"name":"http.request","resource":"GET /api/v2/test","error":0,"meta":{"tenant_id":"0.17716810322087206","http.url":"http://api2:3000/api/v2/test","http.method":"GET","span.kind":"server","http.route":"/api/v2/test","http.status_code":"200","language":"javascript"},"metrics":{"_sample_rate":1,"_sampling_priority_v1":1,"_dd1.sr.eausr":1},"start":1570037669490207500,"duration":5474365,"service":"api2","type":"web"}]
```

Is this something you'd be willing to accept in order to address this issue? 

Thank you

**Comment by rochdev** [comment]
Unfortunately this is not something we can support out of the box at the moment because the cardinality of the path can be very high. However, we have 2 options depending on the use case:

1. If you are using a web framework, we can patch the router of the framework to add the route automatically. This is what we do to support for example Express out of the box. If possible this would definitely be the easiest approach as we can add support and you will need no code change on your end.

2. If you use a custom router, then you can take control over the route tag by using [hooks](https://datadog.github.io/dd-trace-js/interfaces/plugins.http.html#hooks) to modify the route directly on the request span. For example:

```js
// right after tracer.init()
tracer.use('http', {
  server: {
    hooks: {
      request: (span, req, res) => {
        // pathname should be low cardinality (i.e. not /user/:id with millions of IDs)
        span.setTag('http.route', url.parse(req.url).pathname)
      }
    }
  }
})
```

Let me know if that helps!

**Comment by dm03514** [comment]
Awesome, yes this is super helpful.  The second approach works great.  Thank you
