### ISSUE TITLE
Graphql apm tracing not visible

### ISSUE THREAD

**Issue by shavo007** [DataDog/dd-trace-js#706]
**Describe the bug**

Enable ddtrace for graphql api. When we deploy via fargate with sidecar container datadog, we get a logging error but error is null

```
{"level":"error","timestamp":"2019-10-08T04:19:31.898Z","pid":1,"hostname":"ip-xxx-ap-southeast-2.compute.internal","name":"cm-graphql-api","err":null,"v":1}
```

**Environment**
Typescript, Apollo graphql with koa

* **Operation system:**
Docker
* **Node version:**
node:12.10.0-alpine
* **Tracer version:**
  "dd-trace": "0.15.3",
* **Agent version:**
datadog/agent:6.12.1

The config is 

```

const tracer: Tracer = ddTrace.init({
  debug: true,
  enabled: true,
  env: config.env,
  hostname: config.ddMetricsServer,
  logger: {
    debug: message => logger.debug(message),
    error: err => logger.error({ err }),
  },
  plugins: true,
  service: config.appName,
  sampleRate: config.ddApmSampleRate,
});
```

this config is imported at the top of our app.ts file

We use `apollo-server-koa`

The RestDatasource under the hood uses http for resolving to our upstream APIs.

We do not see any traces on APM.

**Comment by rochdev** [comment]
In general, this kind of issue would happen when we log an error that was passed to an error handler. In this case, it means either the error handler didn't pass the error object properly, or we have a bug where we grab the wrong value. In both cases, this should be fixed since we should always provide the stack trace regardless, especially when the error is missing.

In the meantime, is there a way for you to quickly add the stack trace to all error logs? This will add a bit of overhead but will allow us to know exactly where this error is coming from. If you use for example winston/bunyan/pino it should be possible by adding a [serializer](https://github.com/trentm/node-bunyan#serializers).

**Comment by rochdev** [comment]
Also worth noting is that in general you should still be getting traces even if one integration is broken, unless a span in never finished because of the issue. Can you try to disable the `graphql` plugin using `tracer.use('graphql', false)` right after the call to `tracer.init()` to see if you start getting traces?

**Comment by rochdev** [comment]
I've just released 0.15.4 which should at least give you a stack trace on this error. Please let me know if that works and post the stack trace here if possible.

**Comment by shavo007** [comment]
hi @rochdev  thanks for prompt response. 

we use pino logger under the hood.

i will update the version today and get back to you.

**Comment by shavo007** [comment]
we are actually noticing problems with plugins true, the tracing does not work.

 "dd-trace": "0.15.4"

config is 

```
const tracer: Tracer = ddTrace.init({
  debug: true,
  enabled: true,
  env: 'dev',
  hostname: 'localhost',
  logger: {
    debug: message => logger.debug(message),
    error: err => logger.error({ err }),
  },
  plugins: true,
  service: config.appName,
  sampleRate: 1,
});
```

it actually breaks our microservice into multiple datadog services (see scnshot attached)

i did get the stacktrace now for you!

```
{"level":"error","timestamp":"2019-10-08T23:39:43.616Z","pid":1,"hostname":"ip-xxx-ap-southeast-2.compute.internal","name":"cm-graphql-api","err":{"message":"null","stack":"Error: null\n    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log.js:61:15)\n    at /app/node_modules/dd-trace/packages/dd-trace/src/exporters/agent/writer.js:79:13\n    at IncomingMessage.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/platform/node/request.js:33:9)\n    at /app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:66:19\n    at Scope._activate (/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:40:14)\n    at Scope.activate (/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:11:17)\n    at IncomingMessage.bound (/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:65:20)\n    at IncomingMessage.emit (events.js:214:15)\n    at endReadableNT (_stream_readable.js:1178:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","name":"Error"},"v":1}
```



if we set plugins to false and only enable graphql its back to normal but we dont see our span that calls our upstream rest API then


```
const tracer: Tracer = ddTrace.init({
  debug: true,
  enabled: true,
  env: 'dev',
  hostname: 'localhost',
  logger: {
    debug: message => logger.debug(message),
    error: err => logger.error({ err }),
  },
  plugins: false,
  service: config.appName,
  sampleRate: 1,
});

tracer.use('graphql', {
  depth: -1,
});

```

**Comment by shavo007** [comment]
![Screenshot 2019-10-09 at 10 40 54](https://user-images.githubusercontent.com/5466825/66442676-6e170e00-ea87-11e9-8489-a1afc521c938.png)

**Comment by shavo007** [comment]
![Screenshot 2019-10-09 at 11 26 31](https://user-images.githubusercontent.com/5466825/66442727-ad455f00-ea87-11e9-9ab6-9b3ea15e4c68.png)

only graphql enabled

**Comment by shavo007** [comment]
![Screenshot 2019-10-09 at 11 30 01](https://user-images.githubusercontent.com/5466825/66442821-2cd32e00-ea88-11e9-9f5b-d2fe09e4d017.png)

you can see the trace does not include the span (http call) to our upstream rest API that resolves the query

**Comment by rochdev** [comment]
Thanks for the detailed information! I will look into what could be causing the error.

For the microservice broken into multiple service names, this is the expected behavior. We split services by component so that stats can be aggregated more granularly. This behavior can be changed depending on your specific needs. However, all spans for the same request should still always be displayed in the same trace regardless of the service name. Is this the case or do you get multiple different traces for the same request?

Also note that it's possible the error prevents some spans from finishing, which could cause all sorts of issues. In general I would say fixing the error should fix any other issue you are currently having.

**Comment by shavo007** [comment]
thanks @rochdev  be good to see if you get any issues on your side trying to replicate.

For example, running a graphql API example using apollo koa and RestDataSource to an underlying rest API resolver.

**Comment by rochdev** [comment]
After looking more into this, I think the error is most probably caused by another issue that is unrelated. I will release a new version in the next few days with a potential fix that should fix the error, but not the original issue. This will confirm if the error is related or not.

In the meantime, would you be able to create a minimal reproduction snippet that I can run locally? This would help me expedite the investigation, especially if the error is indeed unrelated.

**Comment by rochdev** [comment]
The error should now be fixed.

@shavo007 Can you try with 0.15.5 and see if you still have the error, and if you are getting traces? This should tell us if the problem was the error or not.

**Comment by shavo007** [comment]
hi @rochdev , thanks for reply.

i will look to upgrade to that version next week 

i dont have time to create a quick demo, but pretty much can fork my graphql-api repo and change to koa instead of express, add in dd-trace and see how you go.

https://github.com/shavo007/graphql-playground/tree/master/api

this graphql-api resolves to two upstreams:
- db 
- rest API

hope that helps

**Comment by rochdev** [comment]
I tried to setup the playground, but I'm getting traces without any issue.

These are the steps I took:

```bash
git clone git@github.com:shavo007/graphql-playground.git
docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 -d postgres
docker exec -it some-postgres bash
psql -d postgres -U postgres
CREATE DATABASE mytestdatabase;
exit
exit
cd api
nvm use 10
yarn
yarn add dd-trace
cp .env.example .env
```

Then I updated the code to include `dd-trace` like so:

##### api/src/index.js
```js
import './tracer'; // at the very top of the file
```

##### api/src/tracer.js
```js
import { tracer } from 'dd-trace'

tracer.init()
```

Then I have started the server using:

```bash
 yarn start
```

Then I visited `http://localhost:8000/graphql` and sent the following query:

```graphql
{
  user(id: 1) {
    username
  }
}
```

This resulted in traces being generated and sent properly.

Do you have more details of how I can replicate the issue with this setup? Is there any difference between what I did and what would generally cause the issue?

**Comment by rochdev** [comment]
Just tried with Koa instead of Express and it worked as well.

**Comment by shavo007** [comment]
hi @rochdev , can you post a sample trace from datadog? and the services that are created?

**Comment by shavo007** [comment]
and the trace config?

**Comment by rochdev** [comment]
> can you post a sample trace from datadog? and the services that are created?

Created a [gist](https://gist.github.com/rochdev/936331c18f2fd58458fd8b892fb3404f) for the sample trace.

> and the trace config?

I didn't configure the tracer and simply called `tracer.init()` without any options.

**Comment by rochdev** [comment]
I reverted to Express because I was getting errors with Koa (but was still getting traces).

**Comment by shavo007** [comment]
hi @rochdev , that part of the schema calls the db

what i wanted to see was calling out to the rest API ticketmaster
https://github.com/shavo007/graphql-playground/blob/master/api/src/schema/artist.js

**Comment by shavo007** [comment]
i have updated to the latest version now: dd-trace@0.15.5

but now, when i deploy to dev, my services have changed and i dont see any graphql calls anymore!

**Comment by shavo007** [comment]
![Screenshot 2019-11-06 at 14 12 31](https://user-images.githubusercontent.com/5466825/68265323-d0bbf380-009f-11ea-8d6e-994f09f6d369.png)

**Comment by shavo007** [comment]
![Screenshot 2019-11-06 at 14 15 27](https://user-images.githubusercontent.com/5466825/68265363-e8937780-009f-11ea-850f-88c8c9cf2a4b.png)

**Comment by shavo007** [comment]
i only see koa requests now, no requests to graphql endpoint anymore

**Comment by shavo007** [comment]
![Screenshot 2019-11-06 at 14 59 00](https://user-images.githubusercontent.com/5466825/68267649-3e1f5280-00a7-11ea-8d79-b6dd1836e4c1.png)

**Comment by shavo007** [comment]
![Screenshot 2019-11-06 at 15 06 31](https://user-images.githubusercontent.com/5466825/68267662-45def700-00a7-11ea-90da-567c79d22d0b.png)

**Comment by rochdev** [comment]
You would have to change the primary operation to be `graphql.execute` which encompasses queries and mutations. The link in the error message should help with that.

For the original issue, can you give more precise instructions of how to replicate the issue? I feel like I'm close to replicate it with the GraphQL playground, but I need to know exactly what query to send and any missing steps I have to do for the issue to occur. If you can replicate the issue with that project and provide any missing steps, that would help me a lot.

**Comment by shavo007** [comment]
hi @rochdev  this is an example query

```
# Write your query or mutation here
query{
  myFavoriteArtist(id: "K8vZ9175BhV") {
    name
    image
    twitterUrl
    events {
      name
      startDateTime
    }
  }
}
```

readme explains the setup

```
### Running queries locally

You’ll need to get one API key:

- [Ticketmaster API key](https://developer.ticketmaster.com/products-and-docs/apis/getting-started/)
- copy api key to .env file
```

**Comment by shavo007** [comment]
TBH, i want to see an  actual prod like replication; which means testing this demo on fargate and reviewing the services created on  datadog and the distributed traces/flame graphs.

But at this stage, this is probably out of scope for this issue.

So Im happy to close it, i will follow up with datadog support.

thanks,
shane
