### ISSUE TITLE
Default service name defaults to potentially incorrect value

### ISSUE THREAD

**Issue by alexrhogue** [DataDog/dd-trace-js#710]
Ran into a potential bug with the default value of 'service' in the tracer init.  I am setting up my team's project to have a shared npm module that contains something like this:

shared-dd-config:
```js
const tracer = require('dd-trace');

tracer.init({
    analytics: true
});
```

The idea is to install this package and require it across our node apps.  This would allow me to make changes to our init/plugins in one place. 

This issue I ran into (after much head banging) is that the default 'service' value of the tracer was being initialized to 'shared-dd-config' not the name of the root node project.  

I was able to get around this by just adding the following line to my init.  But I am curious if this is intended behavior or a bug

```js
service: process.env.npm_package_name
```

**Environment**
* **Operation system:**
OSX 10.14.3
* **Node version:**
v11.15.0
* **Tracer version:**
dd-trace@0.15.4
* **Agent version:**
6.14.1

**Comment by rochdev** [comment]
This is the intended behavior, but this use case was not considered. It should be straightforward to find the root module instead of the parent one and update the tracer accordingly. In the meantime, you can use the `DD_SERVICE_NAME` environment variable which is supported out of the box.
