### ISSUE TITLE
Blacklist passed in Hapi plugin options has no effect

### ISSUE THREAD

**Issue by i-hardy** [DataDog/dd-trace-js#711]
Based on the documentation, I expected the following to result in no instrumentation of the `/healthcheck` route:

```
tracer.use('hapi', {
  blacklist: ['/healthcheck'],
});
```

However this appeared to have no effect. Passing a function that should exclude _all_ routes (`() => false`) also had no effect. I could only successfully exclude the route when the option was passed to the http plugin:

```
tracer.use('http', {
  blacklist: ['/healthcheck'],
});
```
This excluded the route from instrumentation whether I passed the same option to the Hapi plugin or not.

**Environment**

* Docker (Linux Alpine)
* Node 10
* dd-trace@0.15.3
* @hapi/hapi@18.3.2
* Agent: latest image

**Comment by ericmustin** [comment]
hey there @i-hardy , hope all is well, i tried to reproduce this as it seemed interesting to me but was unable to. [Here is a little gist of the steps i took to do so](https://gist.github.com/ericmustin/a83c4799ca6f134fcc9fa09a9f37e384),  to be fair it's a very minimal hapi implementation so it's possible there's a more complex interaction that i am missing in my approach.

One common hiccup tho that folks get tripped up on is ensuring that both the `tracer.init` and the `tracer.use('hapi', {blacklist: ['/healthcheck']});` block gets invoked _before_ importing/requiring in the `hapi` package. Is it possible this is the case with your issue? No worries if not just wanted to knock out the low hanging fruit if so.

To diagnose this better though, it might be a good idea to share your account so we can look at it. To do so you'd want to [open a support ticket via the website](https://docs.datadoghq.com/help/) (to protect any sensitive information about your account) and describe more or less the problem as you did here. Be sure to share any links you have for the traces in question along with a code snippet of how you're approaching this, so we can look at the same data you're seeing. You can mention me by name, and the team should relay it to me so I can investigate further.

Cheers,
Eric

**Comment by i-hardy** [comment]
Massive facepalm moment- that was it, once I require Hapi after setting up the tracer everything works perfectly. We have to initialise the tracer asynchronously due to our setup of the agent on AWS, and it was throwing me off. Thanks so much for the help!
