### ISSUE TITLE
Error message logged for every emitted trace

### ISSUE THREAD

**Issue by rdacquisto** [DataDog/dd-trace-js#712]
**Describe the bug**
Every time a trace is emitted, I am seeing a `null` error in the logs. The cause of this log message is https://github.com/DataDog/dd-trace-js/blob/d830ae6f58480089e37bbe8f1a4cd14898bf1db6/packages/dd-trace/src/exporters/agent/writer.js#L78

`this._prioritySampler` is undefined. The `e` from the catch block is 
```
TypeError: Cannot read property 'update' of undefined.
```
The variable `e` isn't exposed, and the `null` `err` variable is returned. `err` Cannot have a value and reach https://github.com/DataDog/dd-trace-js/blob/d830ae6f58480089e37bbe8f1a4cd14898bf1db6/packages/dd-trace/src/exporters/agent/writer.js#L80.

**Environment**

* **Operation system:** Linux
* **Node version:** 10.15.3
* **Tracer version:** 0.15.4 (seen since at least 0.15.1. The stack only recently was made visible.)
* **Agent version:** Latest (Installed today)

**Comment by rochdev** [comment]
The `null` part was fixed in #716. The actual error will also be fixed soon.
