### ISSUE TITLE
Add the ability to safely get the root span from the tracer  

### ISSUE THREAD

**Issue by alexrhogue** [DataDog/dd-trace-js#725]
It would be very helpful to be able to get the root span of a request safely from the tracer object via a public function/getter.  Currently to do this I need to use a private property (code provided by @rochdev):

```js
// anywhere during the request lifecycle
const span = tracer.scope().active()

if (span) {
  const rootSpan = span.context()._trace.started[0];
}
```

I propose something like the following:
```js
tracer.scope().rootSpan();
//or
tracer.scope().active().rootSpan();
```

This would make it much easier to add tags and information to the root of a request without having to communicating via the req object and/or plugin hooks.

**Comment by rochdev** [comment]
This is unfortunately not something we can support since it would break for asynchronous workflows. I will close this for now, but please feel free to re-open if you have a use case where using span hooks doesn't work.

**Comment by mintuhouse** [comment]
I want to addTags to localRootSpan (similar to https://docs.datadoghq.com/tracing/setup_overview/custom_instrumentation/java/#set-tags--errors-on-a-root-span-from-a-child-span in java)

I don't have access to express `req` at the point where I am adding these tags. Is there a way to addTags on localRootSpan?

**Comment by rochdev** [comment]
@mintuhouse Unfortunately there is no official way right now. You can grab the root on the span context of any span within a trace with `span.context()._trace.started[0]` but that is a private API that might change.

**Comment by rkrv** [comment]
Hi folks, just chiming in about our use case. We are using Next.js and adding an `owner` tag on the entry span to route errors to appropriate teams that maintain those pages. Hooks are not enough in this case, as the owner metadata lives together with the source code for the Next.js page. Any suggestions for implementation besides using the `span.context()._trace.started[0]` snippet?

**Comment by TREFZ** [comment]
> if you have a use case where using span hooks doesn't work

I'm trying to do the same as the OP, add tags to the root span. But I'm unfamiliar with span hooks, so it's possible that would work for my use case. Can someone direct me to docs on span hooks, or an example of how that would work?

**Comment by caldempsey** [comment]
> [@mintuhouse](https://github.com/mintuhouse) Unfortunately there is no official way right now. You can grab the root on the span context of any span within a trace with `span.context()._trace.started[0]` but that is a private API that might change.

This is kind of backwards, on one hand we're claiming this isn't supportable and on the other we are proposing the fix in a Github issue. Which is it? Is it safe or not? 

<img width="1029" height="444" alt="Image" src="https://github.com/user-attachments/assets/b7f882b8-076f-4397-97a2-a595518501d5" />

Adding tags to the root span does not work with Nest/Express JS. Should be documented to save others time. Plugins link doesn't return a valid Url at time of writing.

**Comment by BridgeAR** [comment]
I will reopen this as feature request due to the many requests. At the same time, I can not promise this to be implemented.

Issues on github can not be escalated, thus, I kindly ask to reach out to our support https://www.datadoghq.com/support. They are able to either find a way for you to set things up in the way that would resolve the need for it from ground up or would be able to escalate a feature request best.

**Comment by BridgeAR** [comment]
I had a brief look into it and we expose some kind of top level root access in `Go` (span.Root()), `Python` (tracer.current_root_span()), `Java` (span.getLocalRootSpan()), `PHP` (\DDTrace\root_span()), and `CPP` (span.trace_segment().local_root()). I did not check Rust and Ruby.

@rochdev I think we should have a look how we can have a unified handling across tracers and start an initiative for that.

**Comment by caldempsey** [comment]
Honestly if its safe just expose the private API method if it is safe to do so, this is what everyone seems to have do anyway, regardless of whether it is safe to do so. No real choice other than to do what was suggested or wrangle a manual way to grab the same reference to that object.
