### ISSUE TITLE
Unexpected jump in reported metrics when upgrading 

### ISSUE THREAD

**Issue by jasperlin451** [DataDog/dd-trace-js#729]
**Describe the bug**
We're trying to upgrade the tracer version from 0.6.2 to 0.15.4. 

![Screen Shot 2019-10-29 at 1 38 07 PM](https://user-images.githubusercontent.com/6192397/67807093-624cb500-fa51-11e9-9a75-4eb39f1b631a.png)

We're noticing a huge jump (> 10x) in the number of express request hits when we deploy the change and once we rollback, the numbers return back to normal. Based on the ALB numbers, we're pretty confident in the non-inflated numbers. 

We're running a very vanilla Tracer. 

**Environment**

* **Node version:** v10.15.0
* **Tracer version:** dd-trace@0.15.4
* **Agent version:** 6.14.1

**Comment by rochdev** [comment]
There was a bug in how sampling priority was calculated in 0.15.4 which may cause issues related to metrics upscaling. Can you try with 0.15.5? Also, can you confirm whether you've set a sample rate on the tracer?

If updating to 0.15.5 doesn't resolve the issue and you are not using client sampling, I would recommend opening a [support](https://docs.datadoghq.com/help/) ticket for this as it can be caused by many factors, and metrics are calculated outside of the tracer in the agent and backend.

**Comment by jasperlin451** [comment]
We're were trying to set the sample rate to 0.01. But we actually weren't using sampling before (on 0.6.2). We were trying to give sampling a shot of because of latency issues we were seeing.

**Comment by rochdev** [comment]
Do you get the correct numbers if you set the sample rate to 1.0? Also, were you able to try 0.15.5 to see if it fixes the issue?

**Comment by jasperlin451** [comment]
Haven't had a chance to try it. We're trying to come up with a safer way to experiment with this upgrade since it caused some outages last time.

**Comment by rochdev** [comment]
@jasperlin451 Were you able to resolve the issue?

**Comment by jasperlin451** [comment]
Don't think the update helped. Working with support team.

**Comment by jasperlin451** [comment]
I dug into this a bit more and I found that the sampling was working correctly. Out of 400 traces tracked, 4 were sampled and available in datadog. 

The main question is then why `trace.express.requests.hits` is showing so many more hits than reality. We also cannot recreate the problem on our personal laptops but it's consistent in our staging/production environments.

**Comment by rochdev** [comment]
Is the affected service the first service for this request (so the root of the distributed trace) or a downstream service?

**Comment by jasperlin451** [comment]
It's at the root. But mostly resolved within this single service. The tracing was to help dig into graphql resolvers

**Comment by andrewsouthard1** [comment]
Hey @jasperlin451 - if you are still experiencing this issue with the latest tracer please reach out to support@datadoghq.com and we can address from there.
