### ISSUE TITLE
tracer.use not working for setting service name for some plugins

### ISSUE THREAD

**Issue by JesperLorentzenDK** [DataDog/dd-trace-js#742]
**Describe the bug**
The tracer.use does not work for all plugins for changing service names.
We have used this code, for test:
(tracer has been initialized with debug:true)
tracer.use('mysql2', { service: `xxxxxx-mariadb2` });
tracer.use('amqplib', { service: `xxxxxx-rabbitmq` }); 
tracer.use('amqp10', { service: `xxxxxx-rabbitmq` });
Replaced both amqp libraries to make sure the logs does not contain any "-amqp".
**The debug output:**
,"service":"xxxxxx-mariadb2","type":"sql"}]
,"service":"[<**project name**>]-amqp","type":"worker"}]
**expected output:**
,"service":"xxxxxx-mariadb2","type":"sql"}]
,"service":"xxxxxx-rabbitmq","type":"worker"}]

**Environment**
Node version 10.15.3
dd-tracer 0.15.5

**Comment by rochdev** [comment]
Can you provide a snippet of the file where you call `tracer.init` and `tracer.use`? We have tests validating that the service name works as expected, so I wonder if there is some ordering issue since these have to be called at the very top of the application entrypoint.

**Comment by JesperLorentzenDK** [comment]
I rewrote the tracer for the snippet and then out of nowhere it was renamed.
So it was the order and because I wanted the to use names from my configuration service. 
It was because I didn't want the service name written in text in different places.
Sorry about that...
