### ISSUE TITLE
Tracing-application-metrics for `http` does not work with `express` if set same service name

### ISSUE THREAD

**Issue by rugamaga** [DataDog/dd-trace-js#793]
**Describe the bug**

Tracing-application-metrics(https://docs.datadoghq.com/ja/tracing/guide/metrics_namespace/) from http integration is disappered if set same service name as express integration.

for example:

```javascript
// set trace options as following...
const service = 'test-application';
const tracer = require('dd-trace').init();
tracer.use('net', {service: service});
tracer.use('http', {service: service});
tracer.use('express', {service: service});

// after, in some express's route, use http client.
```

After, we can see tracing about this route in datadog APM.
Also, In this tracing, we can see http.request span.

But, tracing-application-metrics are not.
`trace.http.*` are not generated, regardless `trace.express.*` is ok.

**Environment**

* **Operation system:**
Docker container: `node:12.4.0-alpine` ( https://hub.docker.com/_/node )

* **Node version:**
12.4.0

* **Tracer version:**
0.16.3

* **Agent version:**
6.15.1-jmx

**Comment by rochdev** [comment]
Metrics are only collected for the root span of a service. If every plugin is configured to use the same service name, then only the root one (in this case `express.request`) will have metrics. This is why we default to use a different service name by plugin.

**Comment by rugamaga** [comment]
Ah... Is this spec? Thank you for telling me that. 
By the way, I can see metrics for redis.command in same situation.
datadog shows me following:

<img width="244" alt="Screenshot for additional span names" src="https://user-images.githubusercontent.com/43959381/70841007-21223000-1e5a-11ea-9a62-e87b27e36f79.png">

<img width="799" alt="Screenshot for a sample of tracing" src="https://user-images.githubusercontent.com/43959381/70841034-5d559080-1e5a-11ea-8caf-4a566b7c07fb.png">

Maybe, It is collected the most right redis.command span as root span?

**Comment by rochdev** [comment]
It's possible for Redis to do commands outside of an Express context, which would cause it to be considered a root operation and thus have metrics. From this trace specifically it doesn't seem to be the case, but it's a common behavior for data stores and caches like Redis.

In general I would recommend to not change the service name for the various plugins to avoid this issue. While it may be a bit verbose for the service map, this is what will give you the most granular visibility over the different components that are included in your services.

What was your original use case for changing the service name?

**Comment by rugamaga** [comment]
I get it. Thank you.

my original usecase:
Our organization have a standard for `service` tag.
It defines `service` tag for any metrics as means as that "does this metrics what microservice from?".
Our many dashboards (especially if the dashboard is specific to a microservice) have `service` template-variable 
 to avoid metrics mixed from other microservices by filter all metrics.
When difference name for `service` tag, we cannot do this.
So I just changed the names for all integration service name.

**Comment by rochdev** [comment]
Makes sense. In general the way we think about this is to use the service that the span represent, instead of the service from which it originates. For example, if server A calls an external endpoint or a database, and there is a the delay in the call, the delay is generally caused by the external service and not service A, so we set the service name to that of the remote service.

This could definitely be more flexible, and we are actively working to improve how to define this relationship.

**Comment by rugamaga** [comment]
I will share change our service tag policy to our organization.
Thank you for your answers.
