### ISSUE TITLE
Unable to override service name for graphql plugin

### ISSUE THREAD

**Issue by SethDavenport** [DataDog/dd-trace-js#794]
We're trying to clean up our traces and our APM service map by merging services associated with plugins under the main service name.  For example, we have an `apollo-server-koa` based graphql API server that shows up  in the service map like this:

![image](https://user-images.githubusercontent.com/4614141/70819802-178ac080-1da5-11ea-84fe-017438ba8792.png)

From our point of view, it doesn't make sense for things which are ddtrace plugins to be separate services unless they're talking to an external resource like postgres or redis. So we've adjusted our config to rename things that should be considered part of the 'top-level' service (in this case `invest-graphql-api-web`:

```ts
// @flow
import ddTrace from 'dd-trace';
import { k, PROJECT_ENV } from '../project-env';

export const tracer = ddTrace.init({
  service: `${k.DATADOG_APM_DEFAULT_SERVICE}-web`,
  enabled: k.DATADOG_APM_ENABLED,
  hostname: k.DATADOG_APM_HOST,
  port: k.DATADOG_APM_PORT,
  debug: k.DATADOG_APM_PORT,
  tags: { env: PROJECT_ENV },
  logInjection: true,
});

// Tuning things for APM service map:

// Adjust the default naming of tracer plugins that are 'part of the code'
// (i.e. not across network boundaries). We want their data to be included
// in the service/worker itself.
tracer.use('dns', {
  service: `invest-graphql-api-web`,
});

tracer.use('http', {
  service: `invest-graphql-api-web`,
});

tracer.use('net', {
  service: `invest-graphql-api-web`,
});

tracer.use('graphql', {
  service: `invest-graphql-api-web`,
});

// Adjust naming for tracer plugins that go across a network boundary -
// supporting systems like postgres, redis, etc. In this case, these
// things are shared between worker and web containers, so we don't want
// to disambiguate the traces by app role origin.
tracer.use('redis', {
  service: `invest-graphql-api-redis`,
});
```

Ideally our graph will now have only:
* `invest-graphql-api-web` (consolidated spans for -http, -net, -dns, and -graphql)
* `invest-graphql-api-redis`

As it stands, this is working for _everthing except the graphql plugin_ which still shows up as a separate `invest-graphql-api-web-graphql` service in APM.

We're on dd-trace-js 0.16.4, node 12.

**Comment by rochdev** [comment]
This should definitely work. Is it possible that somehow `graphql` is imported before the tracer? I've seen cases in the past where this would still enable the plugin but cause weird issues similar to this one.

**Comment by SethDavenport** [comment]
Sorry for the delay getting back to you. Yeah graphql is definitely imported before the tracer.

```js
import Koa from 'koa';
import KoaRouter from 'koa-router';
import KoaBody from 'koa-body';
import { ApolloServer } from 'apollo-server-koa'; // graphql probably imported as a result of this.
import uuid from 'uuid';

// tracers imported and set up as a result of this (nodeway is our shared setup lib.
import {
  logger,
  applyDefaultMiddleware,
  authenticator,
  extractPropagatableRequestHeaders,
} from '@companyname/nodeway';
```

Since our lint setting make us import 3rd party packages before internal packages, this is the most common use case for us.

I'll try swapping the order around and let you know if that changes the behaviour.

**Comment by SethDavenport** [comment]
Ok just tested it out - swapping the import order fixes the issue. I'll use that as a workaround for now; thanks.

**Comment by SethDavenport** [comment]
I mean - it's still fairly unexpected behaviour that this would be sensitive to import ordering though?

**Comment by rochdev** [comment]
Unfortunately this is a limitation of how the module system for Node has to be instrumented. This is why we [recommend](https://docs.datadoghq.com/tracing/setup/nodejs/#javascript) to always import the tracer first. While it's possible to still instrument from the require cache in some cases, it can still cause missing functionalities or weird issues, so it's always best to import and initialize the tracer first.

Is this something that would be problematic for you to keep as a permanent fix?

**Comment by SethDavenport** [comment]
ok thanks - no it's just a footgun we have to remember to avoid.
