### ISSUE TITLE
ssh2 integration

### ISSUE THREAD

**Issue by amitgilad3** [DataDog/dd-trace-js#806]
Hi, 
i have a microservice which is an ssh server, when i use this library i don't see any data in datadog because i doesn't have any integrations for ssh2.
how hard would it be to create some kind of integration and is it even possible.
any help would be appreciated

**Comment by rochdev** [comment]
In general it should be feasible to have an integration for ssh2, but also to manually instrument it while an integration is not available. Could you describe how the SSH server is used, and what kind of corresponding traces you would like to see?

**Comment by bengl** [comment]
Closing this since without a use case, it's unclear that an `ssh2` instrumentation could be done automatically. Please feel free to reopen or comment.
