### ISSUE TITLE
`.init` options not working

### ISSUE THREAD

**Issue by eavestn** [DataDog/dd-trace-js#82]
Same reproduction steps as listed in Issue #77 and same output; however, the only difference is that I am using the call to `.init` to provide the configuration values (not `ENV` values). My modified version of the default, test code provided in the doc.s looks like:

```
const tracer = require('dd-trace').init({
  service: 'bobs-burges',
  hostname: 'localhost',
  port: 8126
});
```
Even with the above default values specified, no connectivity is established.

**Comment by rochdev** [comment]
There is a bug at the moment that may prevent traces from being sent in some cases. Not sure if this is related but it most likely is. I will release a fix tomorrow.

**Comment by rochdev** [comment]
@eavestn Can you try again with `v0.1.6`?

**Comment by rochdev** [comment]
Other users have confirmed that it works with `v0.1.6` so I'm closing this.

@eavestn Please feel free to reopen if you are still experiencing the issue!
