### ISSUE TITLE
Support OpenTelemetry

### ISSUE THREAD

**Issue by pauldraper** [DataDog/dd-trace-js#820]
I read the Sep 2019 blog post https://www.datadoghq.com/blog/opentelemetry-instrumentation/ , but as far as I can tell Datadog does not support OpenTelemetry, at least for JavaScript?

**Comment by irabinovitch** [comment]
@pauldraper As of September Datadog has donated the tracing and auto-instrumentation code for several languages to the upstream OpenTelemetry project. Given the size of the donation many of the language teams are still working through ingesting these contributions upstream, including support to forward traces to Datadog.

**Comment by pauldraper** [comment]
For Datadog users, a Datadog exporter is the higher priority, as compared to porting instrumentations.

OpenTelemetry already had over a dozen instrumentations of common Node.js APIs, but not a one can be used with Datadog until there is an exporter.

**Comment by pauldraper** [comment]
Any update on this effort?

@rochdev ?

OpenTelemetry has requested that commerical implementations should live in their own repos... https://github.com/open-telemetry/opentelemetry-js/issues/890

I could submit some code, but it's not going to do much good without being published.

And there are some undocumented black-magic things going in the current code like messagepack.

**Comment by rochdev** [comment]
I don't have a timeline for when it will land, but we're actively working on OpenTelemetry support. Short-term it will just be an exporter, but eventually we will also support the OpenTelemetry API directly on the tracer as well.

**Comment by ericmustin** [comment]
hey @pauldraper , hey @rochdev , just checking in here. We actually just put an early PR for an otel exporter a few hours ago in Otel-js repo for the folks there to review, https://github.com/open-telemetry/opentelemetry-js/pull/1316 . The plan is to get some feedback from them and then host this within a Datadog org repo as a standalone package, like @rochdev said no firm timeline right now but hopefully should have something to share in the coming weeks. Will make a point to keep things updated here as well, apologies I had missed this issue.

**Comment by ericmustin** [comment]
Apologies on the delay in followup here @pauldraper. For OpenTelemetry, we had chosen to focus on opentelemetry-collector first, where you can export OpenTelemetry traces to datadog via [our exporter package found in the `contrib` distribution flavor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter).  It is currently in a public beta.

Adding a link to our documentation for OpenTelemetry support  

- https://docs.datadoghq.com/tracing/setup_overview/open_standards/#opentelemetry-collector-datadog-exporter

That being said we're working to continue adding support for OpenTelemetry across tracing, metrics, and logs signals as they reach stability. Would like to close this issue if there's nothing else, but feel free to reach out to our support team with any questions or open an issue on the [contrib repo](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter) if you have any issues or questions with the opentelemetry-collector setup.
