### ISSUE TITLE
Better support for setting and generating trace IDs

### ISSUE THREAD

**Issue by benjdezi** [DataDog/dd-trace-js#846]
I'm in a situation where I have two services that are connected via a queueing system (SQS). The first one pushes events to the queue and the second one reads those events from the queue. I wanted to propagate the trace ID from the first service onto the second one so I can see the whole trace across services in datadog.

However, I have found that there isn't a plugin to help attach trace IDs onto queue messages, so I ended up having to retrieve the trace ID, attach it to the message payload, retrieve it on the other side and then set it on the current context. In some cases, I also generate a trace ID on my own.

I've found it harder than expected to do that due to the lack of documentation around trace ID. For example, I discovered that they can't contain non-numerical characters, otherwise they would end up being truncated at some point in the pipeline.

Here's my current implementation to get/set the trace ID:
```typescript
export function setTraceId(traceId: string): void {
  if (traceId) {
    const activeScope = tracer.scope().active();
    if (activeScope) {
      const ctx: any = activeScope.context();
      Object.assign(ctx, { _traceId: traceId });
    }
  }
}

export function getTraceId(): string | undefined {
  const activeScope = tracer.scope().active();
  if (!activeScope) {
    return undefined;
  }
  return activeScope.context().toTraceId();
}
```

The implementation for `setTraceId` feels very hacky and brittle to me as it relies on knowledge of dd-trace internals, I wish there were a `setTraceId` on the context object, that would help a lot in this case.

Also, is there documentation or specs relating to generating trace IDs somewhere? I haven't found anything.

Thanks.

**Comment by rochdev** [comment]
The trace ID is not meant to be altered after the span has been started since it could cause issues. However, for your use case it shouldn't be necessary to alter it after the fact. You should be able to inject the trace ID using [tracer.inject()](https://datadog.github.io/dd-trace-js/interfaces/tracer.html#inject) and extract it using [tracer.extract()](https://datadog.github.io/dd-trace-js/interfaces/tracer.html#inject).

For example:

##### Producer
```js
const span = tracer.startSpan('sqs.send')
const attributes = {}

// Injects the trace ID and span ID
tracer.inject(spanContext, 'text_map', attributes)

sqs.sendMessage('some payload', {
  MessageAttributes: attributes
})
```

##### Consumer
```js
sqs.receiveMessage((err, data) => {
  data.Messages.forEach(message => {
    // Extract the trace ID and the producer span ID
    const childOf = tracer.extract('text_map', message.Attributes)

    // Use the producer span as the parent of the consumer
    const span = tracer.startSpan('sqs.receive', { childOf })
  })
})
```

Please let me know if I misunderstood your use case. We also plan to support AWS soon at which point you should no longer need to handle this manually.

**Comment by bengl** [comment]
We now support automatic propagation through SQS when using `aws-sdk@2.x`. Please give that a try using the latest `dd-trace`. I'll close this, but please feel free to comment, reopen, or open a new issue if it's not working for you.

**Comment by jacekzlowocki** [comment]
Hi, @bengl Is there any documentation regarding automatic SQS support? I'm wondering if I can make use of it for Producer -> EventBridge -> SQS -> Consumer use case. And I cannot find any docs regarding tracing in such implementation

**Comment by jorgebo10** [comment]
Hi @bengl , i'm using `aws-sdk@2.15, dd-agent-java 0.85.0` and the following libraries in my build.gradle.

```
implementation 'io.opentracing.contrib:opentracing-reactor:0.2.0'
    implementation 'io.opentracing:opentracing-api:0.33.0'
    implementation 'io.opentracing:opentracing-util:0.33.0'
    testImplementation 'io.opentracing:opentracing-mock:0.33.0'
    implementation 'com.datadoghq:dd-trace-api:0.85.0'
```
however i am not able to propagate traces automatically. Is this working?

**Comment by SuvabBaral** [comment]
Hi @bengl, is there a way we can disable this feature?
What I mean is that , is there any way, we can stop the tracer to append these trace details to the SQS queue messageAttributes?

**Comment by rochdev** [comment]
@SuvabBaral What is your use case? Disabling propagation would mean distributed tracing wouldn't work, making the traces mostly useless. Right now the only way to disable propagation completely would be to disable either the plugin or the tracer itself.

**Comment by SuvabBaral** [comment]
@rochdev I see that for every SQS message, an extra attribute **_datadog** is added. Since this message is consumed by someone else, I am a bit concerned about the effects. Is there a way I can prevent sending such extra attribute?

**Comment by rochdev** [comment]
@SuvabBaral Right now this is not possible. We recently introduced the concept of a propagation blocklist for HTTP that allows you to filter propagation based on the URL. Would something similar work for you for SQS? If yes, what would be the best property to filter on?
