### ISSUE TITLE
graphql plugin preventing traces being sent to datadog

### ISSUE THREAD

**Issue by baptistemarchand** [DataDog/dd-trace-js#852]
**Describe the bug**
We have an express app which makes calls to a GraphQL API using Prisma client.
APM traces are not sent to datadog whenever we make a call to the GraphQL API.
In the debug logs there are lines like `Inject into carrier: ...` but it looks like the spans never finish so they are never sent.
At the start of my code, when I initialize Prisma:
```
const db = new Prisma({
  endpoint: GRAPHQL_PRISMA_ENDPOINT,
  secret: PRISMA_API_SECRET,
  //debug: true
})
```
I get the following error in dd-trace debug output:
```
Error: Expected object [object Object] to contain method then.
    at /***/node_modules/dd-trace/packages/dd-trace/src/instrumenter.js:79:17
    at Array.forEach (<anonymous>)
    at /***/node_modules/dd-trace/packages/dd-trace/src/instrumenter.js:77:13
    at Array.forEach (<anonymous>)
    at Instrumenter.wrap (/***/node_modules/dd-trace/packages/dd-trace/src/instrumenter.js:76:13)
    at Instrumenter.patch (/***/node_modules/dd-trace/packages/datadog-plugin-q/src/index.js:10:12)
    at Instrumenter.patch (/***/node_modules/dd-trace/packages/dd-trace/src/instrumenter.js:152:36)
    at /***/node_modules/dd-trace/packages/dd-trace/src/platform/node/loader.js:101:52
    at Array.forEach (<anonymous>)
    at /***/node_modules/dd-trace/packages/dd-trace/src/platform/node/loader.js:97:14
Error while trying to patch q. The plugin has been disabled.
```
As a workaround I disabled the graphql plugin and now the traces are being sent.

**Environment**
* **Operation system:**
Debian GNU/Linux 9.11 (stretch) on Google Compute Engine
* **Node version:**
v12.15.0
* **Tracer version:**
0.17.1
* **Agent version:**
v7.17.0

**Comment by rochdev** [comment]
This error should cause the plugin to be disabled. This means there are actually 2 issues here:

1) An expected method couldn't be found on the module, meaning the plugin might be broken for the version of `graphql` used by `prisma`.
2) The plugin should disable itself when there is an error while instrumenting, and this is not happening since you are still getting spans for `graphql`.

What versions of `prisma` and `graphql` are you using?

**Comment by baptistemarchand** [comment]
Thank you for your response. Here are the versions we use:
```
"prisma": "1.17.1",
"graphql": "14.5.3",
```

**Comment by rochdev** [comment]
This is definitely a version that should be supported. Does the above code result in the error without any other code? Meaning do you get the error just by instantiating Prisma?

**Comment by andrewsouthard1** [comment]
Hey @baptistemarchand - if you are still having any issues here please let us know!
