### ISSUE TITLE
DD_INTEGRATIONS_DISABLED not working

### ISSUE THREAD

**Issue by orgito** [DataDog/dd-trace-js#857]
**Describe the bug**

Disabling plugins using DD_INTEGRATIONS_DISABLED env var is not working.
setting integrationsDisabled on init() also does not work.

**Environment**

* **Operation system:** Linux
* **Node version:** 12
* **Tracer version:** 0.17.1
* **Agent version:** 7.16

**Comment by rochdev** [comment]
The correct environment variable for this is `DD_TRACE_DISABLED_PLUGINS`. You can find the complete list of options in the [API docs](https://datadoghq.dev/dd-trace-js/#tracer-settings).

It's also possible to disable a plugin programmatically using `tracer.use('plugin-name', false)`.

Please let me know if that works!
