### ISSUE TITLE
Headers tracing

### ISSUE THREAD

**Issue by tatianafrank** [DataDog/dd-trace-js#872]
How can I add a header from the http request as a tag to the tracer? I see in the python api there is a `trace_headers` method but I can't find the equivalent in the JS ddtrace library.. Here is a link to the python method I'm referring to: http://pypi.datadoghq.com/trace/docs/advanced_usage.html#headers-tracing

**Comment by rochdev** [comment]
You can add headers as tags for both client and server using the `headers` configuration on the corresponding plugin.

Examples:

```js
// Express server
tracer.use('express', {
  headers: ['x-some-data']
})

// HTTP clients
tracer.use('http', {
  client: {
    headers: ['x-some-data']
  }
})
```

In all cases, `tracer.use()` should be called right after `tracer.init()`.

See the [API docs](https://datadoghq.dev/dd-trace-js/interfaces/plugins.http.html#headers) for more information.

Please let me know if that helps!

**Comment by tatianafrank** [comment]
Thanks for the reply. So 'x-some-data' should be the name of the header field? and the value will be dynamic right?

**Comment by rochdev** [comment]
Yes, so for example, say you have a header `x-request-id`, and for a specific server request the value is `1234` then you would get a `http.request.headers.x-request-id` tag with the value `1234` for the corresponding span.

**Comment by tatianafrank** [comment]
Thanks so much, that worked!
