### ISSUE TITLE
Jest crashes when newrelic library is imported along with dd-trace: Assertion `(argc) >= (3)' failed. Aborted (core dumped)

### ISSUE THREAD

**Issue by gornostal** [DataDog/dd-trace-js#887]
**Describe the bug**

* Add the following packages: `jest`, `newrelic`, `dd-trace`
* Create file `my.test.js` with the content below
* run `jest`

Result:
```
node[19]: ../src/node_file.cc:1441:void node::fs::RealPath(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `(argc) >= (3)' failed.
Aborted (core dumped)
```
I've created a simple project with instructions on how to reproduce this issue locally: https://github.com/gornostal/debug-dd-trace-js

**Environment**

* **Operation system:**  Linux host. `node:10-alpine` in Docker
* **Node version:**  12.16.1
* **Tracer version:**  0.19.0
* **Agent version:**  Doesn't matter. I'm not running the agent.

**Comment by rochdev** [comment]
This looks very similar to #868. Does it only happen with newrelic in your case? Or does the issue disappear if you remove newrelic?

**Comment by gornostal** [comment]
@rochdev it disappears if I remove newrelic

**Comment by rochdev** [comment]
Just for completeness, does it also go away it you remove `dd-trace` and not newrelic? If that's the case I'm thinking there must be some incompatibility with how we both patch the `fs` module. This is difficult to avoid since there are cases where double-patching can cause issues.

**Comment by gornostal** [comment]
I discovered this issue as I was adding DD support to the app, so yes the
issue goes away if I remove it.

As we are migrating from NR to DD we wanted to first add DD and after some
time to remove NR. Seems like it's not possible

**Comment by rochdev** [comment]
We try to patch in the safest way possible, but in some cases conflicts with other vendors are unavoidable.

If this only happens with Jest, I would say one option would be to keep only the target vendor in the tests, and keep both enabled in production as you transition. But in general this is discouraged because the way instrumentation works in Node is by monkey-patching which can lead to unexpected behavior when done multiple times on the same functions/objects, especially native ones.

**Comment by gornostal** [comment]
I see.
Thanks for the clarifications!

**Comment by andrewsouthard1** [comment]
Hey @gornostal - wanted to confirm are you unblocked with this issue?

**Comment by gornostal** [comment]
@andrewsouthard1 yes. I'm going to close it now.
