### ISSUE TITLE
Pino v6 changes

### ISSUE THREAD

**Issue by jsumners** [DataDog/dd-trace-js#893]
This issue is to let you know that Pino will be releasing a v6 release soon. This release has some significant changes:

https://github.com/pinojs/pino/milestone/2?closed=1

I'm not sure if you need to do anything here or not. Just giving you a heads up.

**Comment by rochdev** [comment]
Thanks for the heads up! I'll do some testing to make sure it still works and release a new version if necessary.

**Comment by jsumners** [comment]
https://github.com/DataDog/dd-trace-js/blob/704c8e07cd67a41903cf6bc28bee7e7b28280365/packages/dd-trace/src/platform/node/loader.js#L138

^ that is preventing me from testing against an rc release (`6.0.0-rc.2`) of Pino. Is there any way around this?

**Comment by rochdev** [comment]
Right now there is no way around this, but it came up a few times. I wonder if it would make sense to drop the prerelease part of the version number when doing the comparison. I'll do some testing a bit later tonight.

**Comment by jsumners** [comment]
Maybe a toggle in some way to say you accept pre-releases?

**Comment by rochdev** [comment]
Is there a use case for not accepting them? Technically we don't officially support prereleases, but there should be no harm in trying to patch them anyway. At worst the plugin will fail to patch and will be automatically disabled.

**Comment by jsumners** [comment]
🤷‍♂ 

I'm open to whatever you decide as long as I can complete my testing 😀

**Comment by rochdev** [comment]
I opened #896 with the change. When it lands I'll publish a release to unblock your tests.

**Comment by jsumners** [comment]
🎉

**Comment by jsumners** [comment]
💥 I installed `dd-trace` from your commit and everything is working:

```json
{"level":"debug","time":"2020-03-25T12:10:40.916Z","logger":"foo","trace_id":"9347cb6d-08a9-4f71-b0c8-c0d5fc1683c9","data":{"dd":{"trace_id":"4089385671770256770","span_id":"4089385671770256770"}},"message":"looking up deals"}
```

**Comment by rochdev** [comment]
Perfect! Thanks for testing this!

I'll leave this open until #896 is merged and Pino v6 is officially released.

**Comment by jsumners** [comment]
v6 has been released -- https://github.com/pinojs/pino/releases/tag/v6.0.0

**Comment by rochdev** [comment]
Tests passing with v6: https://circleci.com/gh/DataDog/dd-trace-js/105172.

Closing this now, thanks for making sure Datadog continues to work with Pino!
