### ISSUE TITLE
Upgrade minimist because of vulnerability in dependency

### ISSUE THREAD

**Issue by catchin** [DataDog/dd-trace-js#894]
dd-trace uses an old version of tar, depending on mkdirp depending on minimist 0.0.8.
And a vulnerability has been found in minimist 0.0.8: https://www.npmjs.com/advisories/1179

Please consider upgrading your version of tar to get rid of the minimist dependency (mkdirp is dependency-less in later versions). This would fix alerts when running "npm audit".

**Comment by rochdev** [comment]
Would it be enough to move it to the dev dependencies? `tar` is not longer used outside of dev.

**Comment by catchin** [comment]
Sounds good to me.

**Comment by catchin** [comment]
Thanks for the fast response.
