### ISSUE TITLE
Unable to access trace_id from winston integration.

### ISSUE THREAD

**Issue by KempfCreative** [DataDog/dd-trace-js#926]
**Describe the bug**
I want to use the generated `trace_id` and `span_id` to implement custom APM traces inside a SPA. I don't know how to retrieve the value of these with the dd-trace logInjection:true configuration while using `winston`.

Example:
```
const winstonOptions = {
  transports: [new winston.transports.Console({ level: 'info' })],
  format: winston.format.json()
};
const logger = winston.createLogger(winstonOptions);

require('dd-trace').init({
  logInjection: true
});
...
const logTrace = logger.info(body);
const traceId = logTrace.dd.trace_id;
// traceId is undefined, even logTrace.dd is undefined.
```

**Environment**

* **Operation system:** MacOS
* **Node version:** 10.19
* **Tracer version:** 0.17.0
* **Agent version:**

**Comment by rochdev** [comment]
The trace ID and span ID are only defined in the context of a trace that is currently active on the current scope. In your example that is not the case.

An example that should work:

```js
const tracer = require('dd-trace').init({
  logInjection: true
});

const winstonOptions = {
  transports: [new winston.transports.Console({ level: 'info' })],
  format: winston.format.json()
};
const logger = winston.createLogger(winstonOptions);

tracer.trace('web.request', () => {
  const logTrace = logger.info(body);
  const traceId = logTrace.dd.trace_id;
  // here we are in the context for a trace that has been activated on the scope by tracer.trace
})
```

**Comment by KempfCreative** [comment]
Oh, sorry I should have been more clear. Im not concerned with the implementation of tracing. The issue is in the logInjection. If I try and console.log `logTrace` in this example, I get back a winston stream, which is expected. However, since my application is built on top of NextJS, the default APM integration does not work. I would like to associate these logs I am sending to Cloudwatch with the manual APM traces I will be sending, and I want that generated `{ dd: { trace_id: xxxx, span_id: xxxx } }` value to send with it. 

If this isn't the right place to ask about logInjection issues, please point me in the right direction.

**Comment by rochdev** [comment]
Gotcha. Support for this kind of environment is something we want to improve, but in the meantime you should be able to manually inject the tracing context.

For example:

```js
const logTrace = logger.info(body);

tracer.inject(span, 'log', logTrace);
```

More information can be found in the [documentaton](https://docs.datadoghq.com/tracing/connect_logs_and_traces/nodejs/#manual-trace-id-injection).

**Comment by rochdev** [comment]
Please reopen if the above snippet didn't resolve the issue.
