### ISSUE TITLE
Angular Universal Issue

### ISSUE THREAD

**Issue by emanuelr93** [DataDog/dd-trace-js#942]
**Describe the bug**
I have a NodeJS Application based on Angular Universal Framework (Server Side Rendering for Angular App) (https://angular.io/guide/universal). The framework is based on Express middleware but the DataDog APM dashboard doesn't report information about Endpoints. 
This is a screenshot with an example : https://ibb.co/P4V9tbb

The Express Route is exposed by Wildcard. This is an example of code in TypeScript:

```typescript
app.get('*', (req, res) => {
  // mock navigator from req.
  global['navigator'] = req['headers']['user-agent'];
  const http =
    req.headers['x-forwarded-proto'] === undefined ? 'http' : req.headers['x-forwarded-proto'];
  res.render(
    'index.html',
    {
      req: req,
      res: res,
      // provers from server
      providers: [
        // for http and cookies
        {
          provide: REQUEST,
          useValue: req,
        },
        {
          provide: RESPONSE,
          useValue: res,
        },
        // for absolute path
        {
          provide: 'ORIGIN_URL',
          useValue: `${http}://${req.headers.host}`,
        },
      ],
    },
    (err, html) => {
      if (err) {
        throw err;
      }
      res.send(html);
    },
  );
````
The code is instumented in automatically way. The app is builded with WebPack and the main file (server.js) contain only the init of tracer and the import of server-base.js. The reported span is ok, missing only the information about Endpoints.

`**Environment**

* Operation system: RedHat 7
* Node version: Node 10.6
* Tracer version: 0.20.2
* Agent version: 7.19.0

**Comment by emanuelr93** [comment]
I don't know if it is related to [https://github.com/DataDog/dd-trace-js/issues/477](url)

**Comment by rochdev** [comment]
This is expected since there is only a single route which is a match-all. Do you have any way to know the actual route that was matched from the server side?

**Comment by emanuelr93** [comment]
> This is expected since there is only a single route which is a match-all. Do you have any way to know the actual route that was matched from the server side?

Yes, because the application intercepts all requests and renders pages as if it were a browser. I see that all reported span have the attribute http.url with right value.

**Comment by rochdev** [comment]
The `http.url` tag is the actual URL and not the route. Do you have any way to map the URL to an actual route of your application?

**Comment by andrewsouthard1** [comment]
Hey @emanuelr93 - if you are still having issues here please open up a support ticket at support@datadoghq.com

**Comment by villanuevadani** [comment]
Do you know whether this issue has been resolved in v4?

**Comment by marcmarcet** [comment]
I have something that seems to work more or less fine in Angular 17 SSR.

First add dd-trace as external dependency in **angular.json**:
```
...
"builder": "@angular-devkit/build-angular:application",
"options": {
  ...
  "externalDependencies": [
    "dd-trace"
  ]
}
```

Then define an injection token for the span:

```
export const SPAN = new InjectionToken<Span>('SPAN');
```

Then get the reference to the current span in server.ts and pass it to the app using the injection token:

**server.ts**
```
server.get('*', (req, res, next) => {
    const { protocol, originalUrl, baseUrl, headers } = req;

    const span = trace.scope().active();

    commonEngine
      .render({
        bootstrap,
        documentFilePath: indexHtml,
        url: `${protocol}://${headers.host}${originalUrl}`,
        publicPath: browserDistFolder,
        providers: [
          {
            provide: APP_BASE_HREF,
            useValue: baseUrl,
          },
          {
            provide: SPAN,
            useValue: span
          }
        ],
      })
      .then((html) => res.send(html))
      .catch((err) => next(err));
  });
```

Finally, subscribe to router events and set the 'resource.name' tag manually:

**app.component.ts**
```
constructor(
    private router: Router,
    @Inject(PLATFORM_ID) private platformId: object,
    @Inject(SPAN) @Optional() private span: Span,
  ) {
    if (isPlatformServer(this.platformId)) {
      router.events.subscribe((event: unknown) => {
        if (event instanceof ActivationEnd) {
          span.setTag('resource.name', this.getRoute(event));
        }
      });
    }
  }

  private getRoute(event: ActivationEnd) {
    const path = event.snapshot.pathFromRoot
      .map((activatedRouteSnapshot) => activatedRouteSnapshot.routeConfig)
      .filter((routeConfig) => Boolean(routeConfig))
      .map((routeConfig) => routeConfig?.path)
      .join('/');

    return `GET /${path}`;
  }
```
