### ISSUE TITLE
bump to 1.x for semver

### ISSUE THREAD

**Issue by ungoldman** [DataDog/dd-trace-js#946]
It would be nice to start incrementing updates from 1.x for this library so that module consumers can rely on semver update ranges more easily.

For example, right now I'm trying to determine if it's safe to update `dd-trace` from `0.15.5` to `0.20.3`. Some maintainers use the minor position `0.X.0` to indicate breaking changes in zero ranges, some don't. Reading through all of the releases, it appears only [v0.16.0](https://github.com/DataDog/dd-trace-js/releases/tag/v0.16.0) introduced a breaking change (reading the release notes closely and looking at the related code, it appears to not be a breaking change at all, but a change in performance with a new option). So it looks like in one case the minor position was meant to indicate a breaking change, and in all other cases since it was not.

Various folks ([including npm](https://docs.npmjs.com/about-semantic-versioning)) recommend starting with `1.0.0` so module consumers can more reliably update below major version ranges, and know what to do when.

`0.x.x` updates are problematic for a lot of reasons. `0.x` updates may or may not indicate breaking changes and are hard to rely on. Zero ranges were used to indicate alpha/beta modules in the early days but are largely avoided now because they behave differently than 1+ ranges in terms of semver resolution and can cause lots of upstream issues.

Some people find incrementing to 1.x daunting because it means it's out of beta or something like that. I would recommend not worrying about the semantics of that and focus on what it means for the people using your software. Plenty of people are using `dd-trace` in production right now, so it should probably go past the 1.x threshold.

**Comment by andrewsouthard1** [comment]
Hey @ungoldman - thanks for bringing this up. This has been an ongoing internal conversation for us, and eventually we do want to do a 1.x release. We don't necessarily have any short term plans to make this update, but we can leave this open and when we get closer to shipping this.

**Comment by rochdev** [comment]
Closing this as we have just landed 1.0.0 🎉
