### ISSUE TITLE
Lack of documentation to add custom span when using default integration

### ISSUE THREAD

**Issue by nicolasgere** [DataDog/dd-trace-js#953]
**Describe the bug**
Hello, I'm using dd-trace with default integration for Hapi, is it possible to add a custom trace in a route handler? to get the root trace_id for each request? 

There is nothing about that in the documentation. Thank you

**Comment by rochdev** [comment]
This is handled for you out of box when using [tracer.trace](https://datadoghq.dev/dd-trace-js/#tracer-trace) or [tracer.wrap](https://datadoghq.dev/dd-trace-js/#tracer-wrap). These methods will automatically handle the relationship to the current active span.
