### ISSUE TITLE
tracer.wrap not sending traces or logs

### ISSUE THREAD

**Issue by dhaniboy09** [DataDog/dd-trace-js#958]
**Describe the bug**
I'm using `tracer.wrap` on my nextjs application to trace calls to my nextjs API. I'm not using express. I'm using the default nextjs server. Here's how I'm using it:

`pages/api/endpoint.js.` (called from the client application)

```javascript
export default async (req, res) => {
tracer.wrap('web.request', async () => {
    res.setHeader('Content-Type', 'application/json');
    try {
      const response = await fetch('http://www.example.com/', { method: 'GET' } );
      const responseJson = await response.json();
      logger.debug('Fetched Data successfully', { data: responseJson });
    } catch (e) {
      logger.error('Error while creating user');
    }
  })();
};
```
In a separate file I have the `tracer` object exported:`
```javascript
import { tracer } from 'dd-trace';
import logger from './logger';

tracer.init({
  logger: {
    debug: message => logger.trace(message),
    error: err => logger.error(err),
  },
  debug: true,
});

export default tracer;
```
In another file I have the logger:
```javascript
import bunyan from 'bunyan';

const logger = bunyan.createLogger({
  name: 'dd-trace',
  level: 'trace',
});

export default logger;
```
I can't see any traces or logs. 
Thanks for the support.

* **Tracer version:**
0.20.3

**Comment by rochdev** [comment]
Are you sure the code that is wrapped is running? From your snippet, it looks like the function is not being wrapped and should be traced directly, in which case `tracer.trace` should be used and not `tracer.wrap`.

What's odd though is that you should at least get some tracing from our out of the box integrations as well. Can you share the file where the tracer file is imported?

**Comment by dhaniboy09** [comment]
Yes, I can confirm that the code running. 
`endpoint.js` is where the tracer file is imported and what I have above is the entire content of that file. So with tracer imported it looks like:
```javascript
import tracer from '../ddtracer'

export default async (req, res) => {
tracer.wrap('web.request', async () => {
    res.setHeader('Content-Type', 'application/json');
    try {
      const response = await fetch('http://www.example.com/', { method: 'GET' } );
      const responseJson = await response.json();
      logger.debug('Fetched Data successfully', { data: responseJson });
    } catch (e) {
      logger.error('Error while creating user');
    }
  })();
};
```
The code is being run because when I hit the endpoint (i.e. /api/endpoint), I get a response back. Are you suggesting I use `tracer.trace` instead? 
Could that potentially fix the logging issue as well?

Thanks

**Comment by rochdev** [comment]
I would definitely say to try `tracer.trace` first and see what happens. The above usage seems slightly incorrect in a way that could cause the tracer to not work properly.

Does it work with something like this:

```js
import tracer from '../ddtracer'
import logger from '../logger'

export default async (req, res) => {
tracer.trace('web.request', async () => {
    res.setHeader('Content-Type', 'application/json');
    try {
      const response = await fetch('http://www.example.com/', { method: 'GET' } );
      const responseJson = await response.json();
      logger.debug('Fetched Data successfully', { data: responseJson });
    } catch (e) {
      logger.error('Error while creating user');
    }
  });
};
```

I would also recommend moving the try/catch outside of the wrapped function. This is because the tracer will add that error to the span, but only if it bubbles through it.

**Comment by dhaniboy09** [comment]
No, with that implementation, I'm unable to hit the endpoint from the client.
I'll try `tracer.trace` and report my findings.
Thanks for the support.

**Comment by dhaniboy09** [comment]
Great! @rochdev  I'm seeing the logs now. But I can't see the traces. I'm expecting to see the app show up under APM > Services in the Datadog UI, just like other services. Is this assumption correct?

**Comment by rochdev** [comment]
It is correct, sorry for the delay. Do you know if the traces are at least received by the agent? This can be validated by checking the agent logs, or by enabling debug logs on the tracer with `DD_TRACE_DEBUG=true` which would show you traces being sent to the agent and the agent response. This results in verbose logging, so make sure to enable only in an environment where you can either quickly disable it or accept a large influx of logs.

**Comment by andrewsouthard1** [comment]
Hey @dhaniboy09 - closing this out but feel free to reopen if you'd like to investigate further.
