### ISSUE TITLE
Terrible memory leak in dd-trace (present in older and latest version)

### ISSUE THREAD

**Issue by Throckmortra** [DataDog/dd-trace-js#959]
**Describe the bug**

Use dd-trace in your javascript application and check back after a day or so 

We have tested this out with 8 servers behind the same load balancer running different dd-trace configurations and versions except for 1 with dd-trace off. The one without dd-trace is the only one without a memory leak. The others have managed to consume 64~ GB of memory in 48 hours.

**Environment**

* **Operation system:**
node:carbon-jessie container running on Amazon Linux 1
* **Node version:**
v12.13.1
* **Tracer version:**
0.17.1 and 0.20.3
* **Agent version:**
7.16.0

how we add it to the application: 
```
if (/^true$/i.test(process.env.DD_APM_ENABLED)) {
  require('dd-trace').init({
    analytics: true,
    // do not enable this until resolution of https://github.com/DataDog/dd-trace-js/issues/931
    logInjection: false,
    service: 'redacted',
    hostname: '172.17.0.1'
  })
}
```

We thought it could be mongo trace related like #815 but we tested it with mongo core off as well. Our case id is 342127, just letting the community know. Thanks!

**Comment by bengl** [comment]
@Throckmortra thanks for reporting this!

Can you provide a small reproduction case? If not, maybe heapdumps?

Are you doing any manual tracing?

Enabling [runtime metrics](https://docs.datadoghq.com/tracing/advanced/runtime_metrics/?tab=nodejs#automatic-configuration) may provide additional insight into what's going on.

**Comment by Throckmortra** [comment]
hi @bengl 

unfortunately our heapdumps may contain sensitive data. For reproduction case, perhaps i can make a simple nodejs server and hit it with autocannon for 24 hours 

We are not doing any manual tracing and we were unaware of the runtime metrics. What would we be looking for in runtime metrics that could benefit us here? We are already getting most of this data from a different monitoring service and I don't find it helpful for finding the memory leak

**Comment by bengl** [comment]
> unfortunately our heapdumps may contain sensitive data.

In that case, maybe you can try looking at them yourself? What we'd want to look at is the number of Spans in the heap. If this is increasing over time and taking up a lot of memory, that could pinpoint the issue to Spans not finishing.

> What would we be looking for in runtime metrics that could benefit us here?

As with heapdumps, what we're looking for is the number of Span objects in the heap. This should be visible in heapdumps though, so if you'd rather not enable runtime metrics, heapdumps are likely the best approach in diagnosing this.

**Comment by bengl** [comment]
Also: Can you shared which of the libraries [listed here under "Available Plugins"](https://datadoghq.dev/dd-trace-js/#integrations) you're using?

**Comment by Throckmortra** [comment]
plugins used:

> express
> winston
> mongodb-core
> bluebird

I will check our heapdumps now

**Comment by Throckmortra** [comment]
<img width="1432" alt="Screen Shot 2020-05-18 at 1 52 35 PM" src="https://user-images.githubusercontent.com/9791760/82244287-05dab580-990f-11ea-9287-f06ea8c070ed.png">
result from filtering by "span"

**Comment by bengl** [comment]
That doesn't seem to be a terribly large amount of spans.

Could you try disabling the other plugins one-by-one to see if we can narrow it down to one of those?

Also, enabling runtime metrics would enable seeing the amount of memory specific to the JavaScript heap, and how much of the allocated space for the JavaScript heap is actually being used.

For more real-time communication on this issue, you can also reach out to me on our [public Slack](https://chat.datadoghq.com/).

**Comment by Throckmortra** [comment]
we will attempt disabling other plugins this evening

and thanks! I'll try reaching you there

**Comment by rochdev** [comment]
Just wanted to mention that the runtime metrics would definitely be useful to see if the number of spans increases over time and can be correlated with the memory usage. There are also a few other numbers like the number of asynchronous resources that can tell us many things, especially with this kind of issue. These are metrics that are extremely useful for debugging memory leaks and are not metrics you would normally get in other monitoring systems.

**Comment by Throckmortra** [comment]
hey @bengl @rochdev 

we did some testing last night and observed strange behavior. When using autocannon on our server WITHOUT dd-trace enabled, memory never rose above 300MB per nodejs process 

With dd-trace enabled, memory quickly rose to 1.5GB per process and then stabilized, regardless of plugins being enabled or not. 

```
require('dd-trace').init({
  analytics: false,
  plugins: false,
  logInjection: false,
  service: 'redacted',
  hostname: '172.17.0.1'
})
```

Does this mean dd-trace is just a really huge resource hog and the leak isn't so much a leak as it is just dd-trace requiring over a GB per nodejs process to run? (still pretty disappointing if so, we would have to rearchitect a bit)

**Comment by Throckmortra** [comment]
Hello all, 

At @bengl suggestion, we tried disabling `async_hooks` and we noticed no memory leak. I guess this indeed points to something leaky with `async_hooks`

To be clear, we reenabled all plugins and just disabled async with `scope: 'noop'`

```
// after autocannon and garbage collection
DD totally disabled:
{
  "rss": 254836736,
  "heapTotal": 184807424,
  "heapUsed": 161588000,
  "external": 23236673
}
DD fully enabled:
{
  "rss": 1242316800,
  "heapTotal": 179040256,
  "heapUsed": 168544912,
  "external": 23302657
}
DD enabled with `plugins: false`:
{
  "rss": 1303625728,
  "heapTotal": 175370240,
  "heapUsed": 164701104,
  "external": 23230799
}
DD enabled with `plugins: false` and `scope: 'noop'`:
{
  "rss": 237182976,
  "heapTotal": 170127360,
  "heapUsed": 161337696,
  "external": 23230711
}
```

**Comment by Throckmortra** [comment]
Hi all, we isolated the issue to just `async_hooks` playing not nice with our application - so not a dd-trace issue! my apologies. Thank you @bengl for all your help and advice. Closing this issue

**Comment by rochdev** [comment]
@Throckmortra Is the root cause in `async-hooks` or in the application? If it's in `async_hooks` then we should still make sure to fix the issue in the tracer since it depends on `async_hooks`.

**Comment by Throckmortra** [comment]
@rochdev we don't know exactly. So far the only thing we know is that async_hooks does not play nicely with our application. We will continue to debug and I will report our findings here

**Comment by Throckmortra** [comment]
at @bengl suggestion, we tried node v14 and found that it fixed our problems with async. We aren't ready to upgrade to v14 though so we're trying other options.
