### ISSUE TITLE
Span not appearing in express service

### ISSUE THREAD

**Issue by nishant-cf** [DataDog/dd-trace-js#991]
**Span not appearing in express service**

```
export interface Operation<T> {

    name(): string
    evaluate(...params: any): Promise<T>
}

export abstract class TracedOperation<T> implements Operation<T> {

    abstract name(): string

    abstract tracedEvaluate(...params: any): Promise<T>

    evaluate(...params: any): Promise<T> {
        return tracer.trace(this.name(), async () => {
            return this.tracedEvaluate(...params)
        })
    }
}

export class Addition<number> extends TracedOperation<number> {

    name(): string {
      return "additionspan"
    }

    async tracedEvaluate(...params: any): Promise<number> {
        return _.sum(params)
    }
}
```

Testing this operation within an express controller like so:

```
@httpGet("/trace1")
public async trace1() {
    const operation = new Addition<number>()
    return {answer: operation.evaluate(1, 2, 3)}
}
```

In the header of the APM product for this service, I don't see other spans in the dropdown. I only see

Services > myservicename > express.request 

I was expecting a dropdown with two values - express.request and additionspan. What am I doing wrong? Datadog otherwise is integrated correctly and I'm able to see spans, custom metrics etc.

**Environment: Node**

* **Operation system: ubuntu**
* **Node version: 12.14**
* **Tracer version: dd-trace version 0.22.0**
* **Agent version: 6.13.0-jmx**

**Comment by nishant-cf** [comment]
After setting DD_TRACE_DEBUG= true. I'm seeing logs such as 

```runtime.node.spans.finished.by.name:0|g|#env:prod,service:myservicename,span_name: additionspan
runtime.node.spans.unfinished.by.name:0|g|#env:prod,service:myservicename,span_name: additionspan
runtime.node.spans.finished.by.name:0|g|#env:prod,service:myservicename,span_name: additionspan
runtime.node.spans.unfinished.by.name:0|g|#env:prod,service:myservicename,span_name: additionspan
runtime.node.spans.finished.by.name:0|g|#env:prod,service:myservicename,span_name: additionspan
runtime.node.spans.unfinished.by.name:0|g|#env:prod,service:myservicename,span_name: additionspan ```

and a large json object which contains

```....{"trace_id":"0c3a0f8b02862745","span_id":"28f04e6398af1451","parent_id":"71adde31216c92c2","name":"additionspan","resource":"additionspan","error":0...```

**Comment by rochdev** [comment]
Only root operations of a service will appear in the dropdown in the `Services` page. Other operations will still appear in the trace and in App Analytics, but not on the service page.

In order to view this span as a dropdown item, you would have to change its service name so that it becomes the root of its own service. For example:

```js
const tags = {
  'service.name': `{service}-addition`
}

return tracer.trace(this.name(), { tags }, async () => {
  return this.tracedEvaluate(...params)
})
```

Alternatively, we also have a new functionality to generate stats for non-root spans without needing to add a new service:

```js
const { MEASURED } = require('dd-trace/ext/tags')

const tags = {
  [MEASURED]: true
}

return tracer.trace(this.name(), { tags }, async () => {
  return this.tracedEvaluate(...params)
})
```

I'm not sure if this will also add an item to the dropdown, but I think it's worth a shot since if it works it will resolve your issue without requiring adding a new service.

**Comment by andrewsouthard1** [comment]
Feel free to reach out @nishant-cf if you have any other questions.
