### ISSUE TITLE
How to set tag to all spans in Lambda during runtime?

### ISSUE THREAD

**Issue by bayarmanlai** [DataDog/dd-trace-js#996]
**set tag to active span (lambda handler)**
```
const span = tracer.scope().active()
span.setTag('<TAG_KEY>', '<TAG_VALUE>')

```
**set to globally**
```
const tracer = require('dd-trace').init({
  tags: {
    env: 'dev',
    '<TAG_KEY>': '<TAG_VALUE>'
  }
})
```
There is already two ways to apply tags, But I need to set tag to all spans which is created inside lambda function.

Thank you

**Comment by rochdev** [comment]
Could you describe your use case? There is no way to directly do what you're asking but it's possible we have an alternative way for you to achieve you use case.

**Comment by bayarmanlai** [comment]
@rochdev thanks for your quick reply, I want to tag all my spans with Execution.Name which is passed from Step function to lambda. I see that you set tags from StepFunctionContext which is nice, but it's only applied to lambda span not to other spans. Do you have suggestion?

**Comment by bayarmanlai** [comment]
Or is there anyway to loop through all spans which are created inside lambda handler?

**Comment by rochdev** [comment]
Why do you need the tag to be on every span? Why is it not enough to have it on the function span?

**Comment by andrewsouthard1** [comment]
Hey @bayarmanlai - going to close this for now but please feel free to reopen if you want to dig in further.

**Comment by tamanjoku** [comment]
Hey, @andrewsouthard1 and @rochdev I would love to piggyback on this. So we are logging in some of our functions, and we want to be able to set the same tags initialized from the first span all across the logs within the same trace. Here is an example:

Endpoint A
- Calls function B
- Calls function C
  - Writes a log.

We have a hook applied to endpoint A that sets the tags on that span and so I want those tags to show up in the log that is written by function C, which essentially is a part of the same trace, so I can build specific alerts based on the outputs of the log as opposed to the trace from endpoint A.

Does this make sense? Is there a way we can achieve this right now?

**Comment by rochdev** [comment]
@tamanjoku The tracer doesn't really have something built-in to propagate tags from spans to logs, but you could use [AsyncLocalStorage](https://nodejs.org/api/async_context.html#class-asynclocalstorage) to keep track of the tag value across the entire request and add it to any log from anywhere.
